### ISSUE TITLE
Make all UI sources completely bindable

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1003]
We need to fix `ContextMenu` (also combine with `Menu`?), `DropdownMenu`, `MenuBar` (not yet merged), `TabControl` to have completely bindable sources.

**Comment by smoogipooo** [comment]
[ ] ContextMenu
[ ] Menu
[ ] DropdownMenu
[ ] TabControl
[ ] MenuBar

**Comment by peppy** [comment]
All done!
