### ISSUE TITLE
Currently many classes are not mockable

### ISSUE THREAD

**Issue by miterosan** [ppy/osu-framework#1031]
Good day!

I am currently writing unit tests for everything inside osu-framework where possible.

While writing unit tests I faced a big problem: Most classes are not mockable.

Therefore I like to ask if could change not API related code in a way to make it mockable.

Example: class RNG

14: - private static readonly Random random = new Random();
14: +public IRandomProvider RandomProvider { set; private get; } = new RandomProvider(new Random());

**Comment by peppy** [comment]
You're welcome to make changes where required (please open one PR per class) and we can discuss there. I doubt there will be much contention, especially in cases such as above.
