### ISSUE TITLE
Targetting .NET Standard 2.0

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1098]
For cross-platformness, we need to target .NET Standard 2.0. This allows us to compile/run using .NET Core on Linux/OSX, Xamarin on Android/iOS, and .NET Core/Framework on Windows.

The following branches/repos track incremental changes towards the completion of this issue:
1. https://github.com/smoogipoo/osu-framework/tree/net-standard
2. https://github.com/ppy/opentk (yes, I've re-purposed the 'develop' branch).

The following items are required to be fulfilled before the transition to .NET Standard 2.0 is complete:
- [x] Retarget all projects in osu!framework and opentk.
- [ ] Fix crashing when entering fullscreen.
- [x] Re-implement drag/drop platform-agnostic. (Fulfilled by OpenTK)
- [ ] Look into the dll.config files that were removed, making sure all platforms run as expected.
  - [ ] Compiles + runs on Windows.
  - [ ] Compiles + runs on Linux.
  - [x] Compiles + runs on macOS.
- [ ] Fix mouse cursor not being hidden.
- [ ] Add back application icons somehow.

**Comment by swoolcock** [comment]
As part of this change (or soon after) we will need to look at refactoring `GameWindow` to not extend `OpenTK.GameWindow`.  The latter class is only used for desktop targets, as Android and iOS's game windows extend their corresponding UI classes ('SurfaceView` for Android, `UIView` for iOS).

My proposal is to add a `protected abstract IGameWindow CreateGameWindow();` to `GameWindow` and have each platform instantiate the corresponding OpenTK class.  Our `GameWindow` class could then be essentially a wrapper.

**Comment by smoogipoo** [comment]
@swoolcock That should be done on top of origin/master and merged into this branch. I intend this branch only to serve as far as achieving feature-parity with origin/master while targetting netstandard - I'm PRing all features/changes that I can back to origin/master to keep the changes minimal.

**Comment by swoolcock** [comment]
I see.  I might make a separate issue for it then to keep track.

**Comment by smoogipoo** [comment]
Tracked as milestone: https://github.com/ppy/osu-framework/milestone/3
