### ISSUE TITLE
Improve invalidation semantics to avoid unintuitive workarounds.

### ISSUE THREAD

**Issue by Tom94** [ppy/osu-framework#110]
I am talking about `public virtual Quad ScreenSpaceInputQuad => screenSpaceDrawQuadBacking.Value;` in particular.

I believe we should re-think and constrain where and how invalidations happen, and how the rest of the `Update` code interacts with changes that happened within the very same frame.
One possible way to attack is to make changes be a transaction that is only applied after all `Update` code has been executed, and before `DrawNode`s are generated. This way all `Update` code would see one consistent state of the scene graph.

**Comment by peppy** [comment]
completely agree with it being applied in a single transaction. I'd rather read from an outdated (but non-corrupt) state than have to deal with all these edge-cases.

**Comment by Tom94** [comment]
This got addressed.
