### ISSUE TITLE
Refactor GameWindow to not extend OpenTK.GameWindow

### ISSUE THREAD

**Issue by swoolcock** [ppy/osu-framework#1102]
As part of the upcoming iOS/Android builds, we will need to look at refactoring our `GameWindow` class.  It currently extends `OpenTK.GameWindow`, which is primarily for desktop platforms.  Attempting to use it on iOS or Android throws a `NotImplementedException`.

Proposal is to decouple our `GameWindow` class from `OpenTK.GameWindow` and instead use an `OpenTK.IGameWindow` property that's assigned the correct implementation for the platform.  OpenTK will assist us with most of this on the desktop side, but iOS/Android will need to manually instantiate and assign the window (not a big deal).

**Comment by FreezyLemon** [comment]
For reference:

#1420 crashed on Windows with the following exception:
`OpenTK.Graphics.GraphicsContextException: Failed to make context 65537 current. Error: 170`
65537 is the `GraphicsContext`'s handle (a pointer).
Error 170 in Windows translates to `ERROR_BUSY: The requested resource is in use.` ([source](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx))

Note that there were also two calls to `MakeCurrent` in the constructor, `MakeCurrent()` and `Implementation.MakeCurrent()` (which are the same, so one of those is most likely redundant).
