### ISSUE TITLE
Better name for "OS" namespace

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#112]
Contains low-level entities like GameHost and GameForm.

![image](https://cloud.githubusercontent.com/assets/191335/19142226/de473960-8bd6-11e6-858d-0dfa0df03b7f.png)

Open to suggestion.

**Comment by huoyaoyuan** [comment]
`Interop` can be a choice, like `System.Windows.Interop`.

**Comment by peppy** [comment]
it's not just interop though. it's also the basic host for games which includes stuff like threading logic.

**Comment by RemieRichards** [comment]
```GameManagement```?

**Comment by omkelderman** [comment]
from the discord channel, i feel that it deserves a place here:
![](https://omk.pics/1/WeS8v.png)

**Comment by RemieRichards** [comment]
```Platforms``` is nice.

**Comment by huoyaoyuan** [comment]
I think `Platform` is better than `Platforms`, because there are platform-neutral base classes.

**Comment by peppy** [comment]
👍
