### ISSUE TITLE
osu.Framework.Tests.exe crashes in SearchContainer tests

### ISSUE THREAD

**Issue by MKimiSH** [ppy/osu-framework#1137]
When I run `osu.Framework.Tests.exe` (compiled with the latest code) to the `SearchContainer` test, the program crashes when I click on an orange button (the ones with text `Visible end-children: <num>`) and the last click was not on its corresponding purple button (with text `Search term : <string>`). 

For example, it crashes when I click the 2nd purple button (followed by the 2nd orange button whose `<num>=2`) and then the 3rd orange button whose `<num>=1`, or when I click the 3rd purple button, 3rd orange button and then 2nd orange button. 

**However, if the orange buttons have the same `<num>`, it will not crash.** Thus I think the test does not fail.

My current observation: 
In `TestCaseSearchContainers.cs`, line 122, there seems to be an assert for each orange button, checking whether the number of children of `search` (which is a `SearchContainer`) as `<num>` (which is the number specified in corresponding orange button). These assertions fail (as supposed) and crash the program. In my opinion, maybe it can just prompt a message saying 'the numbers do not match' instead of crashing the whole program. Passing a test with a crash seems a little wierd?

**Comment by peppy** [comment]
These steps are mostly made for automated runs via nUnit. It's not really expected that users click them out of order.

**Comment by MKimiSH** [comment]
Oh I see. Thanks for the quick explanation! Tom showed me these tests one day and I just played with them :p
