### ISSUE TITLE
checkComponentsValid can't run in release builds

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1153]
While #1152 reduces the burden by a magnitude, the overhead of this is non-zero.

![untitled](https://user-images.githubusercontent.com/191335/32697610-b0e5b15c-c7d7-11e7-83f3-d86c8c5c8aa4.png)

It is as expensive to run these checks as the matrix transformation itself.

**Comment by peppy** [comment]
In a longer benchmark the burden becomes even more noticeable:

![image](https://user-images.githubusercontent.com/191335/32698905-1d8f91d4-c7f0-11e7-81b5-02d9b2d86b21.png)

**Comment by FreezyLemon** [comment]
So.. is what's meant here that `checkComponentsValid` has to be less CPU-intensive? Or should it not run at all? The title is a bit confusing.. 
If it shouldn't run at all, is the validity of the floats guaranteed elsewhere?

**Comment by peppy** [comment]
Going to do some profiling on this today to figure if we still need to keep this issue open. Likely has been resolved by the applied changes.

**Comment by peppy** [comment]
Overhead is no longer visible even over a five minute run in debug (and release) modes. Looks great 💯 .

**Comment by peppy** [comment]
Under very taxing circumstances (with as much movement on screen as I can create) the overall overhead looks to be around 0.2%, for what it's worth.

![screen shot 2017-11-29 at 18 03 19](https://user-images.githubusercontent.com/191335/33366758-9d1c2786-d52f-11e7-85af-d95f1338fdd2.png)

Comparing to the OP of this issue, the overhead in `ApplyTransform` has dropped to zero, only remaining as a very minor overhead of `computeDrawInfo` (for the single remaining non-set usage):

![screen shot 2017-11-29 at 18 06 12](https://user-images.githubusercontent.com/191335/33366928-1f7c45bc-d530-11e7-8831-9c728c6750b7.png)
