### ISSUE TITLE
Sounds still active when window is unfocused

### ISSUE THREAD

**Issue by PsYcHo96** [ppy/osu-framework#1162]
All sounds should be muted when the osu! window is unfocused/minimised. I assume this has something to do with AdjustableAudioComponent but I'm not familiar with the framework enough to propose a solution. Some direction would be appreciated

**Comment by UselessToucan** [comment]
Since this issue was not closed, I guess osu! should handle audio differently while minimized/unfocused/etc.
@peppy Could you please describe desired behaviour here?

**Comment by peppy** [comment]
I think the best solution is to not trigger hover events when the window doesn't have focus. This should probably be the default, but overridable at an `InputManager` level.

**Comment by UselessToucan** [comment]
> the best solution is to not trigger hover events when the window doesn't have focus. This should probably be the default, but overridable at an InputManager level.

It is already implemented. Hover events are handled if `HandleHoverEvents` is set to `true`. This property is overriden in `UserInputManager`(`true` if the cursor is inside of the game window) and it is always true in `OsuInputManager`(which is, as far as I understand, used during osu! gameplay).

**Comment by peppy** [comment]
I think this is fine for now then. Let's close this issue.
