### ISSUE TITLE
Async loading orchestration

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#117]
Need a way to do something like this:

```
    Texture : ILoadable
    AudioTrack : ILoadable

    ...

    class OsuLogo
    {
        override Load() {
            Texture t1, t2, t3;
            AudioTrack sfx1;
            Game.Async.Load(delegate
            {
                t1 = Game.Textures.Load(@"Menu/osu");
                t2 = Game.Textures.Load(@"Menu/osuRipple");
                t3 = Game.Textures.Load(@"Menu/osuOverlay");
                sfx = Game.Audio.Track.Load(@"Menu/heartbeat");
            }, delegate {
                //On load completion...
                OsuLogo.Texture = t1;
                OsuLogoRipple.Texture = t2;
                OsuLogoOverlay.Texture = t3;

                startBeat(sfx1);
                FadeIn(500);
            });
        }
    }
```

Open to feedback on the semantics in this sample.

**Comment by huoyaoyuan** [comment]
Considering:
- async/await pattern
- design of `ILoadable`

Will comment later if idea got.

**Comment by peppy** [comment]
async/await will be hard to use in the scenario i believe. but you're welcome to try.

**Comment by huoyaoyuan** [comment]
```C#
class Loadable<T>
{
    Loadable(Task<T> loadTask) { ... }
    Loadable(Func<T> loadDelegate) { ... }
    bool IsCompleted { get { ... } }
    static implicit operator T(Loadable<T> value) { ... }
}

...

Loadable<Texture> t1 = new Loadable<Texture>(Game.Textures.LoadAsync(@"Menu/osu"));
Loadable<Texture> t2 = new Loadable<Texture>(() => Game.Textures.Load(@"Menu/osuRipple"));
```
This pattern needs no change of the resource class, but some changes of consumer class.
Considering another pattern.

**Comment by huoyaoyuan** [comment]
```C#
public override async void Load()
{
    Task<Texture> t1, t2, t3;
    Task<AudioTrack> sfx1;
    t1 = Game.Textures.LoadAsync(@"Menu/osu");
    t2 = Game.Textures.LoadAsync(@"Menu/osuRipple");
    t3 = Game.Textures.LoadAsync(@"Menu/osuRipple");
    sfx1 = Game.Textures.LoadAsync(@"Menu/heartbeat");

    //if no same-time requirement
    OsuLogo.Texture = await t1;
    OsuLogoRipple.Texture = await t2;
    OsuLogoOverlay.Texture = await t3;
    startBeat(await sfx1);

    //if same-time required
    Task loadTask = Task.WhenAll(t1, t2, t3, sfx1);//pass if need to trace
    await loadTask;
    OsuLogo.Texture = t1.Result;
    OsuLogoRipple.Texture = t2.Result;
    OsuLogoOverlay.Texture = t3.Result;
    startBeat(sfx1.Result);
}
```
if there are several group of things to do, can make each into separated `LoadXXX()`.

**Comment by peppy** [comment]
yeah don't see that usage of async/await being beneficial at all. we need to be able to background schedule, not just delay stuff inside Load

**Comment by huoyaoyuan** [comment]
so difficult to make changes to current Scheduler model
maybe `ILoadable` is a better choice

**Comment by SirCmpwn** [comment]
:+1: to @huoyaoyuan's proposal

**Comment by SirCmpwn** [comment]
Could be simplified though

```C#
public override async void Load()
{
    Texture t1 = await Game.Textures.LoadAsync(@"Menu/osu");
    Texture t2 = await Game.Textures.LoadAsync(@"Menu/osu");
    Texture t3 = await Game.Textures.LoadAsync(@"Menu/osu");
    AudioTrack sfx1 = await Game.Textures.LoadAsync(@"Menu/heartbeat");
    startBeat(sfx1);
}
```

**Comment by peppy** [comment]
that code is pointless. the idea is that the completion action happens at a much later time (possibly seconds); not in that load method itself

**Comment by SirCmpwn** [comment]
Well, by using the Task<> we can still get a simliar result to what you're looking for, but we have the flexibility to also do something like this.

**Comment by huoyaoyuan** [comment]
As ppy said, what we need is not just delay loading, but custom scheduling. async/await uses the default ThreadPool, but we are using our custom task scheduler.
To integrate with current scheduler model, my idea is make a "task with preconditions" class.

**Comment by huoyaoyuan** [comment]
A new semantic idea:
##### Usage:
```C#
override Load()
{
    ScheduledDelegate<Texture> t1, t2, t3;
    ScheduledDelegate<AudioTrack> sfx1;
    t1 = Game.Textures.LoadBackground(@"Menu/osu");
    t2 = Game.Textures.LoadBackground(@"Menu/osuRipple");
    t3 = Game.Textures.LoadBackground(@"Menu/osuOverlay");
    sfx1 = Game.Audio.Track.LoadBackground(@"Menu/heartbeat");
    Game.BackgroundWorker.Work(() => //may be another name
    {
        OsuLogo.Texture = t1.Result;
        OsuLogoRipple.Texture = t2.Result;
        OsuLogoOverlay.Texture = t3.Result;
        startBeat(sfx1.Result);
        this.FadeIn(500);
        //and other works
    },//other options
    , t1, t2, t3, sfx1);
}
```

##### Prototypes:
`ScheduledDelegate<TResult> : ScheduledDelegate`
`LoadBackground`: returns a __not started, not scheduled__ `ScheduledDelegate<TResult>`
`BackgroundWorker.Work(Action completion, /*other options*/, params ScheduledDelegate[] preconditions)`
The `Work` will receive parameters and tasks, and schedule itself.

**Comment by UselessToucan** [comment]
peppy's code is not bad, but from my point of view, it can be improved:

    //On load completion...
    OsuLogo.Texture = t1;
    OsuLogoRipple.Texture = t2;
    OsuLogoOverlay.Texture = t3;

As a consumer, I don't want to write continuation code just for variables assignment. I think it should be done inside of TextureStore or elsewhere.

    t1 = Game.Textures.Load(@"Menu/osu");
    t2 = Game.Textures.Load(@"Menu/osuRipple");
    t3 = Game.Textures.Load(@"Menu/osuOverlay");
    sfx = Game.Audio.Track.Load(@"Menu/heartbeat");

As far as I understand, these resources are loaded sequentially using 1 thread. I think we should at least try to load them in parallel.

**Comment by peppy** [comment]
psoposed solution @ https://github.com/ppy/osu-framework/pull/253

**Comment by Tom94** [comment]
Got async loading now.
