### ISSUE TITLE
Fix cursor not hiding in .NET Standard

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1177]
Cursor is not hiding correctly on macOS under a `netcoreapp2.0` target. This requires some changes to our OpenTK branch at https://github.com/ppy/opentk/tree/netstandard.

**Comment by peppy** [comment]
I've posted a bounty on this one. Hoping someone with native macOS knowledge can jump in an help with this as it's the only remaining issues blocking us from packaging macOS releases of lazer.

**Comment by smoogipoo** [comment]
Likely needs more testing, but I've tested up to but not including [this line](https://github.com/ppy/opentk/blob/netstandard/src/OpenTK/Platform/MacOS/CocoaNativeWindow.cs#L1218) by saving the NSImage, and everything seems to be okay. So not sure if something weird is happening elsewhere or if this is the line that's failing, but no errors seem to be emitted...
