### ISSUE TITLE
Warnings and refactor points in code

### ISSUE THREAD

**Issue by huoyaoyuan** [ppy/osu-framework#12]
### Warnings

- Using obsolete methods in OpenTK.

- Hiding methods in base class not using keyword `new` or `override`.

- Redundant generic for nested types.

- A disposable should dispose its disposable members.

- Safer P/Invokes.

### Refactoring

- As some of the code uses C# 6 feature, it won't break compatibility to move all the code to C# 6, for example:
  - The properties of `osu.Framework.RuntimeInfo` are init only, so we can remove their setters now.

**Comment by peppy** [comment]
You're welcome to go ahead and tidy these things up.

**Comment by huoyaoyuan** [comment]
As there's no warning now, this issue can be closed.

**Comment by peppy** [comment]
We still need to fix the remaining rehsarper/mono warnings though (the ones stopping travis from building).
