### ISSUE TITLE
Unify how we construct drawables

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#120]
We really need to standardise how drawables should be initialized in a way that makes sense and drives conformity. My current thoughts are:

```
class MyDrawable : Drawable
{
    ctor()
    {
        //initialise children using Add or Children = new [] { ... };
        //should be simple operations as to not incur a performance overhead.
        //drawables can be constructed on any thread and in a disconnected tree.

        //any defaults for size/relativity/etc should be set here such that the consumer can override in object initialiser.
    }

    override Load()
    {
        //we now have Game available for loading textures and other heavy resources.
        //this should only be called on the update thread.
        //this should be able to start async loading and use this to strive to not incur a performance overhead.

        //avoid setting any defaults here.
    }
}
```

**Comment by Tom94** [comment]
What we discussed today:

- No usage of `Add` allowed in constructor, `Children = ...` is encouraged (including things like linq List comprehension).
- `AddInternal` to be used if Content should be bypassed and children need to be added to self.
- `InternalChildren = ...` should _only_ be used if the intention is to discard existing children (which could have been added by the base constructor.)

**Comment by Tom94** [comment]
We reached a good solution for now. We use `Add` and `Children = ` in constructors whereever possible. `load()` is run potentially on another thread to load resources, and any post-load tasks that need to happen on the main thread are done by overriding `LoadComplete()`. `AddInternal` and `InternalChildren = ` is used for bypassing overridden `Content`.
