### ISSUE TITLE
Make AutoSizeAxes virtual

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1203]
`RelativeSizeAxes` is already virtual, so I propose `AutoSizeAxes` should also be so we can handle state changes and pass on to a content container in the case we are a "wrapper" style drawable.

Example:

![screen shot 2017-11-27 at 18 35 52](https://user-images.githubusercontent.com/191335/33259960-d0f47d04-d3a1-11e7-81f5-78340cfc1e98.png)

We want to handle potential changes in AutoSizeAxes and RelativeSizeAxes to pass it on to our content.

@Tom94 feedback welcome

**Comment by Tom94** [comment]
I think this is fine. `ScrollContainer` and some other framework drawables sorely need adaptive support for their wrapped children, too, and I was not able to come up with a better solution than one like this.
