### ISSUE TITLE
Use locks/interlocked with _all_ cross-thread variables

### ISSUE THREAD

**Issue by Tom94** [ppy/osu-framework#121]
On x86 this is not necessary, but on other platforms changes in one thread may only become visible at a later point on other threads.

**Comment by Tom94** [comment]
After some discussion we concluded it's best to conservatively place locks on thread-shared variables (or use other standard methods for cross-thread communication) rather than going with the minimum necessary path of volatile variables.

**Comment by peppy** [comment]
@Tom94 has pledged to keep this under control
