### ISSUE TITLE
Consider adding NET461 target to projects

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1234]
It's possible to make `dotnet build` compile net461 by adding the following to the net461 projects:

```
  <PropertyGroup Label="NET461 Target" Condition="'$(TargetFramework)' == 'net461'">
    <FrameworkPathOverride>$(NuGetPackageRoot)microsoft.targetingpack.netframework.v4.6.1\1.0.1\lib\net461\</FrameworkPathOverride>
  </PropertyGroup>

  <ItemGroup Label="NET461 Target Packages" Condition="'$(TargetFramework)' == 'net461'">
    <PackageReference Include="Microsoft.TargetingPack.NETFramework.v4.6.1" Version="1.0.1" ExcludeAssets="All" PrivateAssets="All" />
  </ItemGroup>
```

This will require changes to the appveyor config, and we may also choose not to go down this path because unix systems shouldn't be building with net461 in the first place (dotnet build for net461 targets will still work on windows).

**Comment by peppy** [comment]
This has since been implemented.
