### ISSUE TITLE
TextBox selection between words

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#124]
Right now when double clicking then dragging, selection will completely ignore spaces (and only include them in selection when selecting the next word in the direction of the drag).

Instead, all non-words (special characters/symbols/spaces) should be individually added to the selection.

selectable ranges currently:

`this` `is` `a` `sentence`

corrected:

`this` ` ` `is` ` ` `a` ` ` `sentence`

**Comment by Tom94** [comment]
Just to clarify what should happen when there are no simple separators (e.g. a URL):

`https``://``github``.``com``/``ppy`
