### ISSUE TITLE
Set a minimum height for ScrollContainer scroll bars

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1264]
![image](https://user-images.githubusercontent.com/191335/34072353-2e08b07e-e2c9-11e7-9b07-6fadf1c35e5a.png)

**Comment by UselessToucan** [comment]
Whenever the ScrollContainer becomes too large(for example, there is a huge playlist inside of it) the scrollbar becomes literally invisible. Do I understand the problem correctly?

**Comment by peppy** [comment]
Yep, It should not get smaller after a certain number of pixels.

**Comment by smoogipoo** [comment]
Resolved.
