### ISSUE TITLE
ProxyDrawable doesn't respect the original drawable's parent's IsPresent state

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1283]
If a drawable's parent becomes `IsPresent = false`, its proxied version will still be drawn to the screen.

Resolves ppy/osu#1591.

**Comment by peppy** [comment]
Moving to January (low priority as we have a local workaround in osu!)

**Comment by peppy** [comment]
Removing milestone for now.

**Comment by peppy** [comment]
Adding back to milestone (still causing issues with approach circles in latest master).
