### ISSUE TITLE
TestBrowser should not crash when in interactive mode

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1284]
Our dynamic compilation workflow is pretty good, until you make a mistake and cause the game to hard-crash.

TestBrowser should gracefully catch exceptions so it itself does not crash when a coding error is made.

**Comment by smoogipoo** [comment]
The issue is for it to not crash while coding, not in asserts. I think it's possible in a broader way by overriding important methods (Updates) and catching all exceptions there while doing `base.UpdateX()`

**Comment by peppy** [comment]
Sounds like a slippery slope (and would only apply to the main `TestCase` class).

**Comment by smoogipoo** [comment]
It would apply from the testcase class downwards if you override `UpdateSubTree`.

A slippery slope in what way?

**Comment by peppy** [comment]
Hmm, could work. Should probably only be applied after a dynamic recompile though.
