### ISSUE TITLE
Occasionally freezes at startup on mono

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1290]
I believe this is a mono-only issue.

The game draws a few frames and then the Update thread freezes. From what I can tell it spinlocks internally to mono through `Dictionary.TryGetValue` -> `Dictionary.FindEntry()`, with the call from https://github.com/ppy/osu-framework/blob/08f85f9bf9a7376aec8dfcde8c7c96d267d8c295/osu.Framework/Graphics/Transforms/TransformCustom.cs#L128

Unfortunately mono's debugger is crap so I lost the callstack at one point and don't have a more complete stack :(.

**Comment by TemTemmie** [comment]
semicolon missing?

**Comment by ticotaco72** [comment]
Sorry, but it's probably issue to delete.
I didn't want to be annoying.
