### ISSUE TITLE
Allow GameHost to contain multiple Games

### ISSUE THREAD

**Issue by Tom94** [ppy/osu-framework#130]
Or even better: Containers which contain games at some point.

Alternatively: If only one Game should be allowed, then this game should be passed in not via the standard Drawable.Add interface which might mislead readers, and also requires a cast from Drawable to Game.

**Comment by peppy** [comment]
This used to be possible, for what it's worth. Haven't tested recently.

**Comment by Tom94** [comment]
This works now again.

!(image)[http://i.imgur.com/C1K9Zkd.png]
