### ISSUE TITLE
Window doesn't focus at startup on macOS

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1333]
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/MacOS/CocoaNativeWindow.cs#L268 This call in OpenTK's CocoaNativeWindow instantiation seems to be failing since the window is not getting focused (Window.Focused == false).

When this happens, the following call to `setActive` doesn't result in the expected state:

<img width="830" alt="screen shot 2018-01-17 at 5 04 50 pm" src="https://user-images.githubusercontent.com/1329837/35032674-04a4ee5a-fbab-11e7-9d50-4468c32c709d.png">

**Comment by swoolcock** [comment]
Fixed in https://github.com/opentk/opentk/pull/732
