### ISSUE TITLE
After exiting dynamically compiled test there's no way to test it again

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu-framework#1347]
When you switch to another test you can't switch back to dynamically compiled test.

**Comment by FreezyLemon** [comment]
To be more precise (we had a small misunderstanding regarding this):
1. Recompile a testcase (e.g. AllPlayers)
2. Said testcase is gone from its previous assembly (e.g. osu.Game.Tests)
3. If you switch from the dynamically compiled testcase to a different assembly (e.g. back to osu.Game.Tests), the "dynamic" assembly disappears too
  -> the test case can't be accessed in either assembly
