### ISSUE TITLE
Make ConfineMouseMode option a toggle

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu-framework#1372]
Currently `ConfineMouseMode` has three options:  
(quote and picture by ppy)
>never: the cursor will always leave the window, even when borderless and fullscreen (allowing moving to other displays)
fullscreen: the cursor will only leave the window in windowed mode, not fullscreen (debatable whether borderless should be included)
always: the cursor will never leave the window
![unknown](https://user-images.githubusercontent.com/27222621/35794161-eff78540-0a54-11e8-8202-fb0a7c80a5a4.png)

So I got really confused for this having actually three options. The default behaviour of literally every game I ever played (listed by `WindowMode`) so far is:
- FullScreen: You can't leave the game with your cursor unless you tab out
- Borderless: Depending on the game you may need to pause or something but usually you can freely leave the window
- Windowed: Same as Borderless

Of course anything for FullScreen and Borderless only really applies if you have multiple monitors.

So if we want more customization for mouse confinement independent of the `WindowMode` the `ConfineMouseMode` is actually really a toggle.  
If we want to leave the window in FullScreen we disable mouse confinement.  
If we don't want to leave the window in Windowed/Borderless we enable mouse confinement.

Thus my proposal is to make this option just a toggle.

**Comment by yyny** [comment]
The current "Confine mouse cursor to window" options are "Never"/"During Gameplay"/"Always", and confinement applies regardless of window mode. It's not quite a toggle, but the issue appears to be resolved.
