### ISSUE TITLE
Saving bindable values on every change causes massive performace drops for SettingsSliders

### ISSUE THREAD

**Issue by jai-sharma** [ppy/osu-framework#1387]
It appears that this code:
https://github.com/ppy/osu-framework/blob/eba12eb4a0fa6238873dd266deb35bfdece21a6a/osu.Framework/Configuration/ConfigManager.cs#L122
Indicates that bindable values are saved to file every time they are changed. This causes very heavy performance drops when adjusting setting sliders in game. This is most noticeable and reproducible when rapidly adjusting the Background Dim or Background Blur in gameplay settings.
Video example:
https://streamable.com/efpyv

**Comment by smoogipoo** [comment]
Discussed this briefly with @peppy , and we came to the conclusion that we should debounce the saves.

**Comment by peppy** [comment]
I'll tackle this as it's high prio
