### ISSUE TITLE
Dragging is discontinued upon leaving the window with raw input enabled

### ISSUE THREAD

**Issue by MrTheMake** [ppy/osu-framework#1397]
When dragging an element (e.g. a slider bar), the dragging is canceled upon leaving the game window while raw input is enabled. It then starts to drag the first element the cursor hits when reentering the game window. This behavior differentiates from disabled raw input as the dragging lasts as long as the mouse button is being hold (independently from the current mouse position).

A video showing this behavior: https://streamable.com/s9gcw

**Comment by peppy** [comment]
We probably don't want to allow exiting the window (forcing confined mode) when a mouse button is held down.
