### ISSUE TITLE
Level of Documentation

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#141]
Interested in hearing people's opinions on what level of documentation we should use when developing this framework. Full XMLDoc? Public methods/properties/classes only? Unnecessary altogether?

**Comment by SirCmpwn** [comment]
I don't see XML documentation as particularly useful. APIs that you can't understand without them are poorly designed APIs imo.

**Comment by NeoAdonis** [comment]
They help understanding how things work easier, though. I would go for XMLDoc for all reusable components, on anything public or protected expected to be used by subclasses.

**Comment by peppy** [comment]
We have since decided that anything public (or protected) will have full XMLDoc in the framework.
