### ISSUE TITLE
Strategy for linter errors

### ISSUE THREAD

**Issue by SirCmpwn** [ppy/osu-framework#143]
Parameter '...' hides field '...' - we use this pattern a lot: `public ...(Foobar foobar) { this.foobar = foobar }`

Delegate subtraction has unpredictable result - I mean how else are you supposed to do it

Use collection initializer - before: https://sr.ht/AqF8.txt after: https://sr.ht/pw7R.txt (breaks the test, too)

Redundant case label

``` c#
            switch (type)
            {
                default:
                case PerformanceCollectionType.Update:
                    return Color4.YellowGreen;
                case PerformanceCollectionType.Draw:
                    return Color4.BlueViolet;
```

Non-readonly field referenced in GetHashCode() in RectangleF merits some discussion. Fixing it involves changing a lot about how RectangleF works and causes breaking changes all over the codebase, but the linter rule is there for a good reason.

Lots of "Virtual member call in constructor" warnings also merit discussion, since I'm not really sure what the best approach is to solving them.

**Comment by peppy** [comment]
I believe we've already addressed this issue via our updated CI rules (resharper/inspectcode).
