### ISSUE TITLE
Resolution setting for fullscreen and borderless window

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu-framework#1455]
A toggle for letterboxing vs. stretching to screen should also exist, like it currently does in stable.

**Comment by peppy** [comment]
`WidthFullscreen` and `HeightFullscreen` already exist, for what it's worth. Also I'm not sure if we want to implement letterboxing at a framework level.

**Comment by FreezyLemon** [comment]
Note that the `FrameworkSetting` enum already contains values for letterboxing.

**Comment by FreezyLemon** [comment]
So.. a problem arises when we want to figure out what display the game window is currently on.
At the moment, all resolution changes only apply to the primary display (`DisplayDevice.Default`), which is not enough in multi-monitor setups.
The issue at hand is that OpenTK does not have a method to figure out what display a window would be on. It's not impossible to implement this manually, but should prob. be done at an OpenTK level since it might need direct access to the Win API (OpenTK currently does not even allow public access to the list of available devices, we can only get singular devices by index)

**Comment by peppy** [comment]
I remember reading a discussion on multi-displays in the OpenTK discord recently. Might be worth reading back.

**Comment by FreezyLemon** [comment]
#1588, #1688, and ppy/osu#2715 on the osu-side implemented this.

The letterboxing stuff should be tracked in another issue.
