### ISSUE TITLE
HandleMouseInput/HandleKeyboardInput should consider children

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1456]
Currently, there are two issues:
1. If a component derives `SpriteText`, it will not be able to handle any input events and be unable to have a tooltip due to the `HandleMouseInput => false` override of `SpriteText`.
2. If a component is in a `TextFlowContainer`, but wants to handle some sort of input (maybe a link that changes colour on hover, maybe a part of text that displays tooltip, etc), it will not be able to do so due to the `HandleMouseInput => false` override of `TextFlowContainer`.

Essentially, I believe we want to track how many children want to handle input, and propagate that up the hierarchy when drawables are added/removed. Then we should be able to completely remove these static `=> false` overrides.

**Comment by peppy** [comment]
We'll probably want to consider the case where disabling is intentional, too. ie. there may be a case you create a container with interactive elements inside it that we want to blanket disable.

**Comment by smoogipoo** [comment]
Yeah it should still be overridable as it currently is. This should be just a default.

**Comment by UselessToucan** [comment]
I may misunderstand someting, but you can just do something like `public override bool HandleKeyboardInput => true;` inside of the component

**Comment by smoogipoo** [comment]
The problem is we're explicitly setting `HandleMouseInput => false` at a higher level for performance reasons (e.g. TextFlowContainer), where individual components within the `TextFlowContainer` may want to handle input.

**Comment by UselessToucan** [comment]
I guess we may want to have something like [this](https://github.com/UselessToucan/osu-framework/commit/cc5735fcb725f1c92f3ec54954c4a4bb9a67cbf1), but I don't understand how to consume it.

**Comment by smoogipoo** [comment]
Just to iterate a little bit more on this: I would rather that this wasn't implemented as a recursive call for every call to `Handle*Input`, or if it needs to then it must be DP'd (caching + invalidation), or must be done greedily (i.e. bottom-up, done only once ever, and only when `Handle*Input` changes to `true`).

I believe we'll also need to make sure that the following scenario isn't possible:
1. Object A sets `HandleInput` to false.
2. InputManager's update traverses the scene graph, finds `HandleInput` = true for some reason.

**Comment by smoogipoo** [comment]
Resolved.
