### ISSUE TITLE
Tracks having negative length

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu-framework#1465]
If tracks can't be loaded Bass returns a negative value which is not allowed with the most recent changes.

Doc provided by smoogi:
>Bass.ChannelBytes2Seconds
If successful, then the translated length in seconds is returned, else a negative value is returned. Use BASS_ErrorGetCode() to get the error code.

In case of an error (in Bass) these tracks should have a length of 0 instead.

**Comment by smoogipoo** [comment]
Reposting here and closing:

Given http://www.bass.radio42.com/help/html/63fd986c-70cc-62e1-5287-205f3cadd47d.htm, it looks like the only two errors are invalid handle and notavail.
* invalid handle should fail, and should be handled gracefully elsewhere (related to #1165).
* notavail is the cause of attempting to ChannelGetLength on a streaming track, which will need separate handling altogether if we ever intend to do that.

We need to ensure that cases with no audio device are correctly handled, which is a game-wide thing (trackbass/samplebass/and audiomanager itself), not just `Length`.
