### ISSUE TITLE
Unnatural audio glow and very pixelated containers on CircularProgress

### ISSUE THREAD

**Issue by Frontear** [ppy/osu-framework#1478]
Best method to reproduce:

- Scroll mouse wheel to show audio meter(s)
- Take a look at the ring, very pixelated + The glow effect gets cut off at certain areas, most commonly above and to the sides at perfect 90 degrees

Video: https://streamable.com/1gecy

**Comment by jorolf** [comment]
I meant that you should create an issue for the underlying bug...

**Comment by Frontear** [comment]
I'm not **that** good at c#. Plus, I barely scratched the surface of the osu.Game code, let alone the framework.
