### ISSUE TITLE
IniConfigManager doesn't support non-basic types

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu-framework#1511]
Just encountered this when trying to introduce a `FrameworkSetting` of the type `Size`..
The `IniConfigManager` relies on `string.Format` to store and on an `IBindable.Parse` implementation to load the values to and from the .ini file..

This results in something like `Size = {Width=9999, Height=9999}` (in the .ini file) for non-basic types and can't really be properly parsed without custom parsing logic.

This particular case could be fixed by a `BindableSize` class with custom parsing logic, but I thought a more general solution might make more sense

**Comment by peppy** [comment]
You're going to have to implement the bindable anyway, thought?

**Comment by FreezyLemon** [comment]
You're right. The Bindable has to be implemented either way, and with that said, I just found out that with `ToString` and `Parse` method overrides, this is possible in a pretty neat way. Closing as probably not necessary.
