### ISSUE TITLE
Unicode text rendering

### ISSUE THREAD

**Issue by SirCmpwn** [ppy/osu-framework#156]
We need to sort out some solution for rendering characters that aren't in our font pages. We could probably make a working texture page that dynamically renders and rasterizes characters on-demand.

**Comment by peppy** [comment]
It's just a matter of adding the resources in. I've already tested and it works as expected.

As such I'd call this an osu! project-level issue, as I don't intend on adding full unicode ranges at a framework level.

**Comment by peppy** [comment]
Working at intended.
