### ISSUE TITLE
PassThroughInputManager blocks events from PlatformActionContainer

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1569]
`PlatformActionContainer` events are blocked by `PassThroughInputManager` and will not reach children that may be expecting them. This is because `PassThroughInputManager` is unaware of the incoming actions and therefore cannot pass them on.

Not sure what the best way to fix this is.

**Comment by UselessToucan** [comment]
Are there any concrete steps to reproduce the problem?

**Comment by peppy** [comment]
- Place a textbox inside a `PassThroughInputManager`
- Try to backspace

This can be seen on the `Lounge` VisualTest (osu)
