### ISSUE TITLE
Can't launch osu! client with audio devices disabled

### ISSUE THREAD

**Issue by UselessToucan** [ppy/osu-framework#157]
**Brief:**
If output audio devices are disabled, osu! crashes on launch.

**osu! version:**
https://github.com/ppy/osu/commit/4fc681a8b895980eb482a41029604df1313ee5f0

**Steps to reproduce:**
1. Disable audio devices.
![disable_audio](https://cloud.githubusercontent.com/assets/22450664/19403459/2fc3dac4-9270-11e6-867a-163cadd2b47c.jpg)
2. Launch osu!.

**Actual result:**
Crash.
System.StackOverflowException in AudioTrackBass.CurrentTime (did not investigate in detail yet).

**Expected result:**
1. I can launch osu! even if my audio devices are disabled.
2. I can't enter PlayMode.

**Additional info:**
Current osu! stable client does not have this problem.

**Comment by ZLima12** [comment]
I got this too on Linux, I solved it by installing the package "pulseaudio-alsa" from the Arch repositories in case it helps someone.

**Comment by peppy** [comment]
Adding this to #464.
