### ISSUE TITLE
TransformSequence.Loop() is broken for instantaneous transforms

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1577]
Currently, instantaneous transforms are updated instantly when they're added to the target `Drawable`. This occurs before `IsLooping` is set, and results in the transform being immediately removed from the target.

This is not intended for some transforms, e.g. `Spin()` which rely on the instantaneous transform being looped.

The following is an easily replicable case:

```
box.MoveToX(100)
      .Then().Delay(1000).MoveToX(0)
      .Then().MoveToX(200, 1000).Loop();
```

Which result in the following:

Time | Expected-X | Actual-X | Comment
--- | --- | --- | ---
**0** | 100 | 100 |
999 | 100 | 100 |
1000 | 0 | 0 |
1999 | ~200 | ~200 |
2000 | 100 | 200 | New loop starts
2999 | 100 | 200
3000 | 0 | 0
3999 | ~200 | ~200 |
4000 | 100 | 200 | New loop starts

[expected](https://streamable.com/ys2fx) vs [actual](https://streamable.com/yje5v)

Haven't been able to completely resolve this issue yet.

**Comment by peppy** [comment]
It indeed was!
