### ISSUE TITLE
A Drawable should be able to receive input when it IsMaskedAway

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu-framework#1608]
This affects for osu!catch catcher with a currently present bug which puts the catcher off-screen for some reason.

**Comment by peppy** [comment]
This is an optimisation that we have decided on ages ago.

Can you provide a screenshot or something? Not sure what you mean here, but it likely requires a local fix, not a framework logic change.

**Comment by ekrctb** [comment]
I know the catch bug is a bug and it needs to be fixed in there but I'm concerned about in general. If that was intended, maybe it is fine.

**Comment by ekrctb** [comment]
Maybe add a documentation for this behavior then?
