### ISSUE TITLE
Drop 32 bit support?

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1619]
The framework's graphical requirements basically mean that 32 bit hardware is *almost* ruled out as being an option (you'd need to have a modern gpu but very old CPU), but there's still the chance that users have a 32-bit operating system installed.

We need to decide whether we want to support this method of operation or not.

**Comment by smoogipoo** [comment]
![screen shot 2018-06-11 at 2 49 02 pm](https://user-images.githubusercontent.com/1329837/41214482-9b3a8d46-6d86-11e8-8c29-5a0c9180ebe9.png)

(Steam hardware survey)

I fully support dropping 32 bit.

**Comment by peppy** [comment]
Keep in mind that's 2.4% on 32 bit.

**Comment by Aergwyn** [comment]
The question is what is the threshold where you'd say that you'd comfortably drop 32 bit?
Is it < 1% of the players? Is it < 1000 players?

While steam has a wide range of users the numbers may be a bit different specifically for osu!.  
Also. By the time osu!lazer goes "live" or is at a point where it can be majorly used the amount of 32 bit users could be even lower.

**Comment by peppy** [comment]
I'd say we need analytics of lazer users specifically to make a decision here. Also this is open for other users of the framework to provide their opinion. I was just opening this issue as a future consideration (see ppy/osu-framework#1617).

**Comment by Tom94** [comment]
I actually wouldn't mind keeping 32 bit on Windows unless there is a specific issue that makes it annoying to keep around. As far as I can tell we can keep it basically for free.

**Comment by Psypherical** [comment]
@Tom94 while I do agree that keeping 32-bit support would be an inclusive decision for the niche audience that does possess 32-bit machines, the architecture itself is rapidly becoming obsolete. [Nvidia has ended support for 32-bit machines](https://www.extremetech.com/computing/267180-nvidia-ends-support-for-32-bit-operating-systems) and Apple, if we do ultimately decide to support macOS, is also [ending support for 32-bit applications](https://www.theverge.com/2018/4/12/17228374/apple-macos-32-bit-app-alert). Moreover, the additional overhead ending 32-bit support would likely be substantial as we wouldn't have to take into account the limitations of the architecture during development.

**Comment by swoolcock** [comment]
@Psypherical macOS is a primary target for the osu!framework, not an optional extra.

**Comment by Psypherical** [comment]
@swoolcock Thanks for the clarification. I'm admittedly not as knowledgeable regarding the framework repo as I am the primary one.

**Comment by Tom94** [comment]
> Moreover, the additional overhead ending 32-bit support would likely be substantial as we wouldn't have to take into account the limitations of the architecture during development

That's the thing, I don't see _how_ we need to take into account _any_ of the limitations. The language already abstracts away almost all of them.

In the cases where it became annoying (i.e. Linux and macOS, where the smallest portion of 32-bit users resides anyway) we already support only 64-bit.

**Comment by ard1998** [comment]
by keep supporting obsolete hardware / software interfaces there will be less reason for people to replace it. together with the fact that x86_32 processors haven't been made for over 10 years i think we can use the same idea as for software. no new versions for a long time so it's support can be dropped.

**Comment by Kyuunex** [comment]
Just wanna point out that osu's popularity in poorer countries is a thing because you can run the game on a "potato". While 32 bit x86 only processors have not been manufactured for over a decade, some people still use 32 bit operating system when they only have like 2 GB of ram because 32 bit apps take less ram (and windows it self won't consume too much) AFAIK. 

also i think you guys should use actual osu player stats instead of steam stats. (because many people in poorer countries don't bother creating steam accounts at all)

just putting this out there

**Comment by Drax47** [comment]
Even if the majority is using 64 bit systems, I still don't think it's fair to just kill the smaller audience that are still using older systems (including myself referring to the "Can't Install" thread)

Although the needed framework puts 32 bit off the table, I can't really do anything about it, other than saying do what you want to do.

**Comment by peppy** [comment]
What hardware are you running out of curiosity?

**Comment by Drax47** [comment]
> What hardware are you running out of curiosity?

A 2GB RAM Asus Laptop with 1GHz AMD C-60 APU with Radeon HD Graphics from like 2011

Got it a long time ago with the purpose of school work

**Comment by peppy** [comment]
Closing this for now. Framework can continue to support 32-bit for the time being (it looks like there are still quite a few users stuck on 32 bit hardware, even recently released).
