### ISSUE TITLE
Packaging improvement

### ISSUE THREAD

**Issue by VPeruS** [ppy/osu-framework#1638]
Can someone create separate repo for native deps in ppy/ root? Then all .dll/.so/.dylibs can be moved in there and packed/deployed to nuget. With correct structure it will solve "missing bass" problem on linux while bulding.

**Comment by Tom94** [comment]
I haven't encountered a problem with "missing bass" on both my linux installs and on macOS. Can you post more details on what is happening (or reference another issue that has more details)?

**Comment by VPeruS** [comment]
There are log.
```
% dotnet run -f netcoreapp2.1

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'bass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbass: cannot open shared object file: No such file or directory
```

Reference to docs for fix https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders

Dir structure:
```
vperus@arch-test ~/.nuget/packages % tree ppy.osu.framework 
ppy.osu.framework
└── 2018.619.0
    └── runtimes
        ├── linux-x64
        │   └── native
        │       ├── bass_fx.so
        │       └── bass.so
        ├── osx-x64
        │   └── native
        │       ├── libbass.dylib
        │       └── libbass_fx.dylib
        ├── win-x64
        │   └── native
        │       ├── bass.dll
        │       └── bass_fx.dll
        └── win-x86
            └── native
                ├── bass.dll
                └── bass_fx.dll
```
Pay attention that lib prefix was removed.

**Comment by jai-sharma** [comment]
There is currently a workaround for this where you have to manually set the `LD_LIBRARY_PATH` to the directory containing the library files:

```
$ cd osu-framework
$ dotnet build osu.Framework.Tests -f netcoreapp2.1
$ cd osu.Framework.Tests/bin/Debug/netcoreapp2.1/
$ export LD_LIBRARY_PATH=$(pwd)
$ dotnet osu.Framework.Tests.dll
```

This works for the main `osu.Desktop` project too, although there are other bugs which may occasionally crash the game.

**Comment by VPeruS** [comment]
@jai-sharma  it's how it's works now, this will move native libs out of this repo, so make it more "clean"

**Comment by Tom94** [comment]
If it works without `LD_LIBRARY_PATH` then by all means, that'd be a far better solution. I'm all for it, not just to fix consumers of the framework, but also to avoid all the other shortcomings of having to use `LD_LIBRARY_PATH`.

**Comment by VPeruS** [comment]
Send url here when ready

**Comment by morguldir** [comment]
Did you test this? It should be possible to test it out locally right? 

Also we shouldn't need to remove the lib part, DllImport should try to load bass, bass.so and then libbass.so

**Comment by VPeruS** [comment]
coreclr didn't look for libbass.so in runtimes dir. In order to test locally you need to inject dir structure in some deps package, clean obj/bin and recompile.

**Comment by morguldir** [comment]
It's not working for me, might have something to do with the arch package being completely broken now though (RID is set to arch-x64)

**Comment by morguldir** [comment]
`2018.619.0/
├── content
│   ├── libbass.dylib
│   ├── libbass_fx.dylib
│   ├── libbass_fx.so
│   ├── libbass.so
│   ├── x64
│   │   ├── bass.dll
│   │   └── bass_fx.dll
│   └── x86
│       ├── bass.dll
│       └── bass_fx.dll
├── contentFiles
│   └── any
│       └── netstandard2.0
│           ├── libbass.dylib
│           ├── libbass_fx.dylib
│           ├── libbass_fx.so
│           ├── libbass.so
│           ├── x64
│           │   ├── bass.dll
│           │   └── bass_fx.dll
│           └── x86
│               ├── bass.dll
│               └── bass_fx.dll
├── lib
│   └── netstandard2.0
│       ├── osu.Framework.dll
│       └── osu.Framework.xml
├── ppy.osu.framework.2018.619.0.nupkg
├── ppy.osu.framework.2018.619.0.nupkg.sha512
├── ppy.osu.framework.nuspec
└── runtimes
    ├── arch-x64
    │   └── native
    │       ├── bass_fx.so
    │       └── bass.so
    ├── linux-x64
    │   └── native
    │       ├── bass_fx.so
    │       └── bass.so
    ├── osx-x64
    │   └── native
    │       ├── libbass.dylib
    │       └── libbass_fx.dylib
    ├── win-x64
    │   └── native
    │       ├── bass.dll
    │       └── bass_fx.dll
    └── win-x86
        └── native
            ├── bass.dll
            └── bass_fx.dll
`

**Comment by VPeruS** [comment]
Did you remove obj/bin dirs in project dir?

**Comment by morguldir** [comment]
I just ran dotnet clean which removed everything inside the directories, i did indeed have to actually remove them, thanks.

**Comment by VPeruS** [comment]
all purpose of this is to remove .json file created by compiler, it contain all deps of dll(it's includes runtime dirs), clr use it when it loads library

**Comment by morguldir** [comment]
This doesn't work with dlopen() though, because ld.so resolves the path, we need to find something out for that.

**Comment by VPeruS** [comment]
Very unfortunate, we can try to put libs into `netcoredeps/` near main executable(I didn't test this). https://github.com/dotnet/core/blob/master/Documentation/self-contained-linux-apps.md . Or we can add multipath try-load for dlopen()

**Comment by Tom94** [comment]
We already tried `netcoredeps`. That one only works when actually publishing the app as a single executable---not when running the `.dll` via `dotnet`. Publishing on every compile would be too slow.

**Comment by VPeruS** [comment]
Using `./libbass.so` for libname to force it to search in current dir(near executable) instead of general ld.so resolve rules and pack .so correctly with msbuild

**Comment by morguldir** [comment]
I tried looking at how coreclr finds the libraries in the runtimes folder, but i didn't find out anything, i think that using the same method as coreclr or telling coreclr to find it for us would be a good idea.

If we use current directory won't we need the same directory structure that we have now as well?

**Comment by VPeruS** [comment]
Here is [loading](https://github.com/dotnet/coreclr/blob/da0a05431913dd5e3d65c5d3c74d7f12cf3f9ebb/src/vm/dllimport.cpp#L6013) which basically is iteration over some dirs list, here is list [setter](https://github.com/dotnet/coreclr/blob/60ba4751a4bab0651db356af1b269bc5d96822c5/src/vm/appdomainnative.cpp#L526), will lead you [here](https://github.com/dotnet/coreclr/blob/85374ceaed177f71472cc4c23c69daf7402e5048/src/System.Private.CoreLib/src/System/AppDomain.cs#L573), pay attention we need to find who set `NATIVE_DLL_SEARCH_DIRECTORIES`, unfortunately it's continues in another [repo](https://github.com/dotnet/core-setup/blob/4b628f43fc5989c8a3923cb074b905dbc458f11c/src/corehost/cli/hostpolicy.cpp#L19), where you can find
```
// NATIVE_DLL_SEARCH_DIRECTORIES
native_dirs_cstr.data(),
```
which [loaded](https://github.com/dotnet/core-setup/blob/f6bf0a83c66883fd1380fe0c3ce9b6d1e112f564/src/corehost/cli/deps_resolver.cpp#L847.) from `deps` file.

**Comment by morguldir** [comment]
Some reasons why we have to do a seperate nuget package:

The runtimes/{rid}/native/ location is part of nuget https://github.com/NuGet/NuGet.Client/blob/a72834eb86d790e43abd0e2db8ac52a20b5ebce5/src/NuGet.Core/NuGet.Packaging/ContentModel/ManagedCodeConventions.cs#L452

project.assets.json, which is what is showing the library location with a field called runtimeTargets, automatically looks in the nuget package path


Also looks like RID's are only used for nuget packages

> [RID values are used to identify target platforms where the application runs. They're used by .NET packages to represent platform-specific assets in NuGet packages](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)

**Comment by VPeruS** [comment]
But you can extend build/publishing/packaging processes and have libs in nativeDirs/ dir

**Comment by morguldir** [comment]
What do you mean?

**Comment by VPeruS** [comment]
You can try to inject your files into *.deps.json

**Comment by peppy** [comment]
We likely need to revisit this due to the size of native includes right now. Each framework build is currently a whopping 85mb..

**Comment by nyquillerium** [comment]
Not sure if this resolved any issues mentioned in the issue regarding linux libraries. Otherwise this can probably be closed.

**Comment by ticotaco72** [comment]
Mostly resolved?

**Comment by peppy** [comment]
It's still an ongoing effort, but probably doesn't need this issue to remain open.
