### ISSUE TITLE
Possible null mouse down position in OnMouseMove

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1646]
Perhaps still related to the cause of https://github.com/ppy/osu-framework/issues/1612 . Easily replicable in osu!'s `TestCaseKeyCounter`, if two keys are pressed simultaneously while moving the mouse.

Occurs prior to and after https://github.com/ppy/osu-framework/pull/1644

**Comment by ekrctb** [comment]
This is not framework's issue and MenuCursor's issue.
Reproduction can be done in a following way: (with MenuCursor showing e.g. on start screen) right button down -> left button down -> move -> left button up.
