### ISSUE TITLE
Contents of a Container flickers and become invisible when it changes its size

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu-framework#1661]
https://streamable.com/j19si.
1. Open TestCaseInputManager.
2. Change window height.
3. Texts flickers and become invisible.

I'm not sure this title is correct. I don't have any idea currently.
- Not only with a `FillFlowContainer` but with a `Container` the same happens.
- Not only with `SpriteText`s but with `Box`es the same happens.
  - But with one `Box` this doesn't happen.

**Comment by ekrctb** [comment]
It turned out my use of container was incorrect. Closed by #1698

**Comment by peppy** [comment]
Somehow completely missed this issue, wow.
