### ISSUE TITLE
Figure out why debug is slow under netcore

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1664]

**Comment by peppy** [comment]
Isolated to netcore2.1 + macOS + `TaskCreationOptions.LongRunning` usage.

Reported https://github.com/dotnet/coreclr/issues/18705

**Comment by peppy** [comment]
This is out of our hands and (slowly) being investigated at the aforementioned coreclr issue thread.

**Comment by tzachshabtay** [comment]
> and (slowly) being investigated

Seems appropriate...
