### ISSUE TITLE
Figure out an approach to resolving Update ordering

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1665]
At the moment we move code arbitrarily between `Update` and `UpdateAfterChildren` in an effort to fix various ordering issues where we depend on child states or child states depend on our states.

One such issue occurs with `CircularContainer`, for which the size of the container can change beyond the point where its `CornerRadius` is updated. The resulting effect is that for the rest of the frame (including draw), the container will have the incorrect `CornerRadius` but the correct `DrawSize`.

I've thought about two ways to resolve this:

1. Add inter-`Cached` dependencies. When a `Cached` value is updated, it will signal all other `Cached` values that are linked to it.
2. Add a `ValidateSubTree` method that runs post-`UpdateSubTree`. This would essentially be something like 
`while (!validated) { validate() /* re-validates cached values for our subtree */ }`.

**Comment by ekrctb** [comment]
An vague idea (not sure it is possible/reasonable) there is no need of single Update per a Drawable. Like a Drawable can contain size Update, info Update, etc. separately. And each Updatable make a dependency graph (should be a DAG and topologically sortable implicitly).

**Comment by jorolf** [comment]
What about somewhat redoing the whole update stuff and introduce private update or validate methods.
This could also allow marking specific update methods with depedencies or _maybe_ run them in parallel
It would probably look something like this:

```csharp
public class BaseDrawable : Drawable
{
  public int Counter { private set; get; }
  
  [Update(nameof(Counter))]
  private boolean updateCounter() 
  {
    if(??) 
    {
      Counter++;
      return true;
    }
    return false;
  }
}

public class DerivedDrawable : BaseDrawable
{
  public string Text;

  [Update]
  [Before(nameof(BaseDrawable.Counter))]
  private void beforeCounting()
  {
    ??
  }

  [Update(nameof(Text))]
  [Depedency(nameof(BaseDrawable.Counter))] //Only executed if updateCounter returns true
  private void updateText()
  {
    Text = "Counter: " + Counter;
  }
}
```

**Comment by smoogipoo** [comment]
So how would you define the dependency relationship between flow layout and autosize? (autosize depends on flow)

**Comment by smoogipoo** [comment]
This might work out okay... Certainly a path I'm willing to explore.

<img width="565" alt="screen shot 2018-07-01 at 1 06 34 pm" src="https://user-images.githubusercontent.com/1329837/42130945-a874158c-7d2f-11e8-9520-27386ad507bd.png">

With:

<img width="854" alt="screen shot 2018-07-01 at 1 07 14 pm" src="https://user-images.githubusercontent.com/1329837/42130948-b4eae8ae-7d2f-11e8-817e-7c773a6048d7.png">

**Comment by smoogipoo** [comment]
Initial implementation of the `[DependsOn]` and `[Updates]` attributes has been done in https://github.com/ppy/osu-framework/compare/master...smoogipoo:update-dag , however it will need a lot more work and I'm not sure if it's even feasible yet.

Moving this to backlog - we should attempt the revalidation technique described in the OP as an interim fix.
