### ISSUE TITLE
Platform actions don't work when joystick connected

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1702]
If a joystick is connected and has twitching axes or pressed buttons, platform actions will not work correctly. This should not be the case.

Reported [here](https://twitter.com/ez198/status/1016920391095279616) and [here](https://github.com/ppy/osu/issues/2982)

**Comment by swoolcock** [comment]
Stepping through `KeyBindingContainer.handleNewPressed`, it looks like it's trying to match key combinations that include any active joystick events.  Should we ignore joystick input when checking key combos?  I see limited use for things like "ctrl + shift + axis up", and it looks like it'll just cause more problems than it's worth.
