### ISSUE TITLE
Update wiki page for the loading process of a Drawable

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1709]
The loading process was adjusted in #1670. The following connection doesn't exist anymore:

![screen shot 2018-07-12 at 5 02 28 pm](https://user-images.githubusercontent.com/1329837/42620347-aeba3272-85f5-11e8-8b38-ec2d65d6e2c1.png)

**Comment by iiSaLMaN** [comment]
@smoogipoo Would appreciate a review for this diagram before putting it in the wiki. (added extra stuff and updated to latest `CompositeDrawable.cs`)
![image](https://user-images.githubusercontent.com/22781491/74533273-3db61380-4f42-11ea-8787-17cf486fd891.png)

**Comment by smoogipoo** [comment]
@iiSaLMaN I still very much dislike that diagram in general but it looks better. Remember to update the source!

**Comment by iiSaLMaN** [comment]
Will replace it with a text-explaining wiki later on. Closing as resolved.
