### ISSUE TITLE
Give the framework a better name

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1726]
As the framework approaches a relatively stable and usable state (and after internal discussion) I believe that the name `osu-framework` may begin to hold this project back. This framework is pretty useful for games in general, but also for developing high performance UI applications.

We have been looking at creating a logo for the framework, but at the same time I think renaming it to something more unique may be a good move forward.

Opening this thread for serious suggestions on this matter. Please make single replies with your suggestion for the framework name (and any attached logo ideas that build off that name). It should be something short and concise and hopefully build on the concepts which this framework tries to achieve (fast prototyping of UIs, bindable components etc.).

Preferably no `Sharp` suffix, single world and maybe related to light (weakly associating with lazer).

**Comment by swoolcock** [comment]
I hesitate to say... Lazer.

**Comment by AlFasGD** [comment]
How about "Infrared"?

**Comment by RemieRichards** [comment]
Photon.
Quanta.
Lumen.

**Comment by jorolf** [comment]
Crystals can be used to create lasers so we could just name the framework after some kind of crystal that produces a purple one.

**Comment by swoolcock** [comment]
Noble gases are used to make excimer lasers, so you could possibly name it after a noble gas.
Argon gives a nice purple glow, according to: https://en.wikipedia.org/wiki/Noble_gas#Discharge_color

**Comment by ca1ek** [comment]
If we are going into noble gases I propose "Neon".
[Lazer falls out cause there's already a game framework called that way](https://github.com/photonstorm/lazer),

**Comment by arflyte** [comment]
LightShow
LightCraft
LightBox
LightDraw
LightFold
LightSomethingSomething
Lyte
BryteLyte

**Comment by UnknownSoldier1** [comment]
Krypton sounds awesome.

**Comment by miterosan** [comment]
AbstractCrystal
![image](https://drive.google.com/uc?id=14si6KkkvmZc0sDyFM1owtHP_A1kGzSiC)

**Comment by WGCCoastguard** [comment]
I like Yttrium, it's used for a common type of laser and i just really like the sound of it.

**Comment by TPGPL** [comment]
Tourmaline, Rhodonite, Fuschia

**Comment by Kashouryo** [comment]
I think PhotonActive can be a cool name. I changed the word radioactive and replaced radio with photon(light partical, represents laser).

**Comment by default0** [comment]
How about.... "OpenGL UI Framework"? I know, I know, revolutionary. A framework that has a name that actually explains what kind of framework it is instead of using a name that is effectively arbitrary and needlessly difficult to memorize and has 0 communicative value for people who don't know what the framework is.

Guess that isn't happening with the premise of this issue thread though. Oh well.

**Comment by andy840119** [comment]
\Namico/

**Comment by KredkaOfficial** [comment]
Maybe **iroiro**? It means "various" in Japanese. Because it is in Japanese it will be related to osu. This name is short and can mean a lot of things if you add context to it. It also sounds great (imo).

**Comment by mwkjim** [comment]
Focus

**Comment by HoLLy-HaCKeR** [comment]
Photon sounds really nice. It's short (so easy to remember) and implies speed. A [GitHub search](https://github.com/search?p=1&q=photon&type=Repositories) reveals that there are a few projects using the name already, but none of them are game or graphics frameworks. If it's still an issue, perhaps something can be appended to the name, like PhotonFramework?

A logo could be similar to lazer's laser beam, but with lines parallel to the photon trajectory instead of emanating from it (again emphasizing speed), and perhaps a different color scheme (blue?).

**Comment by peppy** [comment]
We would have to differentiate ourselves from 

http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4809:ner6og.2.45 (https://www.photonengine.com/)
http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4809:ner6og.2.35 (https://vmware.github.io/photon/)

I do not think that is feasible, especially the first of the two.

**Comment by miterosan** [comment]
The renaming allows to reset the version of the framework.

This should be used to introduce semantic versioning of the framework.
See [https://semver.org/](SemVer)

**Comment by EVAST9919** [comment]
Nobel

**Comment by KredkaOfficial** [comment]
Maybe use "Maiman" after the last name of laser creator?
https://en.m.wikipedia.org/wiki/Theodore_Harold_Maiman

**Comment by peppy** [comment]
Thanks for all the suggestions. Unfortunately personally nothing (that was still available) really hit the spot I was looking for. We're going to be going forward with osu!framework for now, shortened to o!f in classic osu! style.

Going to close this one for now, but if anyone comes up with something they think is an amazing option feel free to post in this thread.
