### ISSUE TITLE
Setting trackers have hard-coded shortcut and not actual binding

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu-framework#1730]
In osu!, this overlay [NO KEY BOUND]: ![osu_2018-07-9_16-45-57](https://user-images.githubusercontent.com/32995012/42928792-3a3ffa20-8b73-11e8-8e7a-41b2a6b09e9e.jpg)
`SettingDescription.Shortcut` is `string` and hard-coded. Should show actual key binding somehow.

**Comment by ekrctb** [comment]
I think setting tracker thing should be all moved to osu! side and not on framework.

**Comment by smoogipoo** [comment]
Yup, sounds like a fair assertion. Am also completely fine with removing tracked settings as they are if there's a better implementation for them.

**Comment by ekrctb** [comment]
This is fixed by #10787.
