### ISSUE TITLE
Compose key not working on linux

### ISSUE THREAD

**Issue by WebFreak001** [ppy/osu-framework#1737]
The [compose key](https://en.wikipedia.org/wiki/Compose_key) is just ignored and the letters are being typed as is. Usually when you would input for example `<compose> t m` it would insert `™` but in osu it just types `t` and then `m` without composing.

**Comment by peppy** [comment]
Is this thing actually used by anyone?

**Comment by morguldir** [comment]
Could you test with the latest osu version?

**Comment by WebFreak001** [comment]
ah thanks for the reminder. Works now, nice
