### ISSUE TITLE
Implement a file / directory choose dialog

### ISSUE THREAD

**Issue by miterosan** [ppy/osu-framework#1739]
I'd like to implement this file / directory choose dialog.

The only design I could find is the one from next.ppy.sh. Is this the newest design so far?
![](https://78.media.tumblr.com/502586d396d6d84bd7b86a8ff704c5fd/tumblr_ojplpf2PSL1tleiqgo6_1280.jpg)

Should this be implemented in osu-framework first? This feels like nice thing to have.  (following the pattern that in osu-framework there is an really basic version and in osu there is one customized)
Please note that there is an implementation for breadcrumbs already that is only in osu and not in osu-framework. I would create a basic breadcrumb implementation in osu-framework and adjust the osu one to use the framework one in that case.

I'll submit a PR in osu! with the provided design from next.ppy.sh or from flyte if flyte posts a newer one.

Icons I could see in the pic above:

- hardrive: fa_database (sure about this one? there is an fa_hdd_o)
- file: fa_file_o
- parent directory: fa_folder_o
- directory: fa_folder
- textfile: fa_file_text_o
- audio file: fa_file_audio_o
- image file: fa_file_image_o

**Comment by peppy** [comment]
Please ensure when implementing to keep individual pull requests below 500 lines of code changed.

![skin editor](https://user-images.githubusercontent.com/191335/43375624-2c8df284-93f1-11e8-82c9-d60e7c7cce47.png)

Note that the design is a pretty early one, so changes may occur.

**Comment by miterosan** [comment]
My plan on implementing this:

1. Implement a breadcrumb naviagtion in osu-framework.
2. Apply the framework breadcrumb navigation on the existing one in osu
3. Implement a directory navigator in osu-framework.
4. Create a styled breadcrumb navigator in osu. (The one in the pic above)
5. Create a styled directory navigator in osu.
6. Submit the pr for the file choose dialog.

**Comment by jai-x** [comment]
Closed by https://github.com/ppy/osu-framework/pull/3920 I think?
