### ISSUE TITLE
TextBox regression/unintended behavior? Double click-drag doesn't work as expected.

### ISSUE THREAD

**Issue by columna1** [ppy/osu-framework#1827]
https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/UserInterface/TextBox.cs
Due to the way double click logic is implemented. (Double click callback is called after the second click's release) double-click to select can act odd in some situations.

When you click twice but don't let go of your second click OnDoubleClick is never called so doubleClickWord is never set and thus when you drag, it selects as if you clicked once. This leads to tripple clicking+dragging seeming to work how you would expect double click+drag to work for the reason explained below.

When you double-click a word doubleClickWord is set to the bounds of the word clicked. This works as expected. However when you click and drag again the drag function checks for doubleClickWord and uses it to select by word. So if you double click on a word then click-drag elsewhere it selects all words in between the starting position of the original word clicked on and your dragging position instead of starting a new selection like you might expect.

**Comment by UselessToucan** [comment]
@columna1 could you please provide some visual explanation? For example, video or gif animation.
