### ISSUE TITLE
The state of async

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1828]
Taken from #475.

Where things stand:

With the thread pool minimum size specification and concurrency limiting, I can no longer reproduce a deadlock. This isn't to say one can't happen, but I'm 99% sure the `LoadComponentAsync` flow can no longer be responsible for it. This is achieved by ensuring the maximum `Wait`ing threads (on the `loadChild` call) is three - two `LoadComponentAsync`s plus potentially the `Update` thread, resulting in a maximum of five worker threads.

I also had to revert the concurrency increasing change as that was causing single `LoadComponentAsync`s to result in potentially many tasks, all potentially blocking on the `.Wait()` call. I'm also dubious whether we want to allow a single drawable load that much concurrency in the first place, so not a big deal.

Obviously not an optimal or permanent solution. For anyone following along, [this](https://medium.com/rubrikkgroup/understanding-async-avoiding-deadlocks-e41f8f2c6f5d) is about the best write-up I can find on the subject (@smoogipoo I recommend you read as it may explain better than I've been able to).

Short term, I think the state this PR leaves things is OK to merge. It should not remain this way though.

The path forward as I see it:

- Stores and many other places we have `Get`/`GetAsync` are incorrect. We cannot allow the `Get` implementations to use `.Result`. We cannot use `.Result` or `.Wait` anywhere, ever.
- `AsyncLazy` in `WorkingBeatmap` is implemented in a way that it breaks `async` flow. Fixing this is possible, but special attention will be required for `Recycle`.
- We either need a complete async pathway through `Children_Set` / `AddInternal` or we should remove the async path altogether. If we were to remove it, we should disallow `async load()` altogether as there is no way to make it play nice.
- There is still the option of moving child load to the end of the load process, rather than having it run inside `AddInternal`. It is a sound solution as far as fixing the previous point, but will require documentation and paradigm updates which I'm not sure I agree with:

Previously

```csharp
[BackgroundDepenencyLoader]
private void load()
{
    var test = new TestDrawable();
    Child = test;

    // test is loaded
    
    // will work
    test.Text = "hi";
}

class TestDrawable : CompositeDrawable
{
    private SpriteText text;

	public string Text { set => text.Text = value; }

    [BackgroundDepenencyLoader]
    private void load()
    {
        Child = (text = new SpriteText());
    }
}
```

After

```csharp
[BackgroundDepenencyLoader]
private void load()
{
    var test = new TestDrawable();
    Child = test;

    // test is *not* loaded
    
    // will fail;
    // needs to be moved to LoadComplete (or SpriteText needs to be initialised in the ctor of TestDrawable).
    test.Text = "hi";
}

class TestDrawable : CompositeDrawable
{
    private SpriteText text;

	public string Text { set => text.Text = value; }

    [BackgroundDepenencyLoader]
    private void load()
    {
        Child = (text = new SpriteText());
    }
}
```

**Comment by peppy** [comment]
As the linked PR has been merged, we will hold off while the current framework release is tested for performance, usability and regressions. We may decide to drop the async behaviour (or move child load to complete the chain) after assessment.

**Comment by smoogipoo** [comment]
Async 🙅‍♂️
