### ISSUE TITLE
Incorrect window placement in borderless fullscreen

### ISSUE THREAD

**Issue by AtomCrafty** [ppy/osu-framework#1833]
If a user has their Windows taskbar position set to the top or left edge of the screen, entering borderless fullscreen won't set the window position correctly. It will instead be positioned below or to the right of the taskbar and therefore moved partially off screen.

From [DesktopGameWindow.cs](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Platform/DesktopGameWindow.cs):
```c#
WindowState = WindowState.Maximized;
WindowBorder = WindowBorder.Hidden;

// must add 1 to enter borderless
ClientSize = new Size(currentDisplay.Bounds.Width + 1, currentDisplay.Bounds.Height + 1);
```
When a window is maximized, Windows will try to not obstruct the taskbar by moving the it down or to the right, so in addition to manually overriding the client size it may be necessary to set the window location as well.

I haven't tested whether this is an issue on any platform other than Windows 10.

![borderless](https://user-images.githubusercontent.com/4553050/44852049-856bb100-ac62-11e8-92f5-a7348a4c6f29.PNG)
![borderless2](https://user-images.githubusercontent.com/4553050/44852656-1e4efc00-ac64-11e8-9c3c-2effc5ad74b3.PNG)

**Comment by LastExceed** [comment]
Also happens on [windows 7](http://puu.sh/Bq8mV/24409f815d.png) and [linux](https://cdn.discordapp.com/attachments/452044675902341122/486925339243577355/Screenshot_from_2018-09-05_17-45-49.png), idk about mac

**Comment by peppy** [comment]
There is a similar issue with maximising the window. After a restart it will be at an incorrect position (Windows 10)
