### ISSUE TITLE
Switch bitmap fonts to binary format

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#1858]
Will avoid hundreds of megabytes of string allocations during startup (and greatly reduce cpu overhead).

We can likely use this library: https://www.nuget.org/packages/SharpFNT/

Can use [this utility](https://www.npmjs.com/package/convert-bmfont) to convert our existing ascii formatted `.fnt` files to binary.

**Comment by FreezyLemon** [comment]
I just tried to get an example working, and it seems that the NPM package/tool there does not work with SharpFNT. 

It looks like this is intended on SharpFNT's behalf, as it [requires some "magic bytes"](https://github.com/ToddBertaOldham/SharpFNT/blob/master/SharpFNT/BitmapFont.cs#L324-L331) when reading from binary format, and also [adds these manually](https://github.com/ToddBertaOldham/SharpFNT/blob/master/SharpFNT/BitmapFont.cs#L85-L87) when writing a font to file in binary format.

It's easy to work around this (by using SharpFNT itself to convert the fonts), but I'm not sure whether we want to use this almost "proprietary" binary format that only works with SharpFNT...

(Note: The binary file from that NPM tool is almost double the size of the SharpFNT binary format)
