### ISSUE TITLE
Maximising breaks stuff

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#187]
Not sure if framework or osu! level, but stuff doesn't resize correctly post-maximise.

**Comment by Tom94** [comment]
Did you check with `StaticCached.AlwaysStale = true`?

**Comment by peppy** [comment]
seems to fix..

**Comment by Tom94** [comment]
Which means we're not invalidating something correctly.

**Comment by Tom94** [comment]
Is this still broken after today's fixes?

**Comment by Tom94** [comment]
I don't recall what the original issue was. Do you? This might no longer be relevant.

**Comment by peppy** [comment]
This is indeed fixed.
