### ISSUE TITLE
Updating osu!lazer makes the game  "uninstall" itself

### ISSUE THREAD

**Issue by knuxfanwin8** [ppy/osu-framework#1873]
When I use the "Update is ready, click to restart" notification, the game turns off and deletes all of its shortcuts, it's no longer seen in the start menu or while searching. Interestingly enough, the game's files are still in their right place, even the updated ones.

Specs:
- Processor: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, 2701 Mhz, 2 Core(s), 4 Logical Processor(s)
- RAM: 8GB DDR3 SODIMM
- Drive: 128gb SSD
- Laptop model: Dell Latitude E7240
- OS: Windows 10 Home x64 English, Version 10.0.17134 Build 17134

[Here are the logs.](https://1drv.ms/u/s!AiBiGzZBnITMjgQOmiGm8eFSfrhR)

**Comment by peppy** [comment]
Please run the installer once.

**Comment by knuxfanwin8** [comment]
Whoops, just realized I accidentally posted this in the osu-framework issues 😛  Sorry for the confusion!

I tried re-running the old installer and allowed it to update, and after clicking the notification about the update being ready to be installed, it did it again. The same issue happened previously, so I had to download the newest installer at the time and install the newest version manually.

Guess I'll just stick to that for the time being.

**Comment by peppy** [comment]
Please try by using the second most recent installer, so you can test one update process.

**Comment by knuxfanwin8** [comment]
Like, the previous installer release? I tried that, and it did the same thing.

**Comment by knuxfanwin8** [comment]
Moved to ppy/osu#3377.
