### ISSUE TITLE
Pressing Ctrl+F11 twice with debugger attached hangs the game

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1893]
Really weird scenario: start up visual tests with a debugger attached and press Ctrl+F11 twice in quick succession.

The game will lock up, and will continue to be locked up while the window has focus. As soon as another window is focused the game will continue, but will lock up again when focus is regained.

Likely related to the `Image` changes, as the debugger shows that Update thread is locked up on creating `FrameTimeDisplay` imaesg and Draw thread is locked up on uploading a texture.

**Comment by peppy** [comment]
Will be 100% related to this: https://github.com/SixLabors/ImageSharp/issues/700.

I'll make a fix locally for the time being.
