### ISSUE TITLE
Restoring window position does not work on multi-monitor set up

### ISSUE THREAD

**Issue by UselessToucan** [ppy/osu-framework#1901]
Environment:
Windows 10 computer with 2 displays.

Steps to reproduce:
1. Launch visual-tests in windowed mode.
2. Move it to the secondary display.
3. Switch to fullscreen/borderless.
4. Switch back to windowed.

Expected results:
Window position is the same as before
![before](https://user-images.githubusercontent.com/22450664/45419330-b6e77200-b68f-11e8-975b-abe1424b349d.jpg)

Actual results:
Window position was changed. The window is on the primary display.
![after](https://user-images.githubusercontent.com/22450664/45419386-d7173100-b68f-11e8-9976-77a000ed46dc.jpg)

Additional info:
This code is the culprit, but it can't be just removed without testing.
![culprit](https://user-images.githubusercontent.com/22450664/45419439-ff069480-b68f-11e8-9209-d01775d0a198.PNG)

**Comment by AtomCrafty** [comment]
Cause: #1908
Fix: #1909
