### ISSUE TITLE
Proposal: Add FrameworkSetting.LastDisplayDevice

### ISSUE THREAD

**Issue by AtomCrafty** [ppy/osu-framework#1914]
I'd like to ask for feedback here before implementing it:

Currently the last window mode, size and relative position are saved across restarts, but not the display the window was last on.
For example: If I position my window in the top right corner of my right screen and then close and reopen the program, I will end up with a window in the top right corner of my the center (primary) screen.
This also affects fullscreen, which is even worse because you can't just drag a fullscreen window to another screen.

I am not entirely sure how to identify the display. Should it be via the numeric DisplayDevice ID, the screen bounds or maybe just the window center location?
I'll open this to discussion, please let me know what you think :)

See also: #1909

**Comment by smoogipoo** [comment]
Resolved by the referencing PR.
