### ISSUE TITLE
Don't use global shader properties (and add vertex batching)

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#194]
Every time we need to change a global shader property, a batch much be split up.

Right now we are incurring *insane* performance overheads from zero batching. This needs to be addressed as a priority, in my opinion.

with batching: 1480fps
without batching: 98fps

**Comment by Tom94** [comment]
Are you sure the global shader properties are the issue? We also need to flush batches if we are just setting GL.Scissor without any property changes.

**Comment by peppy** [comment]
yeah, i already changed the code to flush on glscissor *or * global shader changes for now.

i think this alone is enough for the time being, until we have performance metrics to know when we are un-batching too much.

closing this issus as it will be resolved by my upcoming PR.
