### ISSUE TITLE
Precise scroll no longer works

### ISSUE THREAD

**Issue by Tom94** [ppy/osu-framework#1940]
Precise scrolling seems to have regressed and no longer works. A quick bisection shows that the offending commit is https://github.com/ppy/osu-framework/commit/61c3f1cbf58f5dacfe101d5866e5f91ebbcf50d6 @ekrctb

**Comment by peppy** [comment]
It works but the rate has been adjusted, as we discovered.

**Comment by Tom94** [comment]
Are you sure? The boolean is set to `false` when I check in `OnScroll`.

**Comment by peppy** [comment]
I believe this is the relevant change: https://github.com/ppy/osu-framework/pull/1922/commits/076a427dbc926d43433cc08222ea1aa0d0e7baab#diff-eb3162fc695252e644a7b378a6269486R484

It may have regressed further since, haven't checked in the last week or so.

**Comment by Tom94** [comment]
In any case, `HasPreciseScroll` seems to have an incorrect value within `ScrollContainer.cs:353`, which should get fixed.

**Comment by ekrctb** [comment]
Try #1922?

**Comment by Tom94** [comment]
Seems to fix it, awesome! I added a reference to its description. :)
