### ISSUE TITLE
Allow dropdown to handle invalid values

### ISSUE THREAD

**Issue by AtomCrafty** [ppy/osu-framework#1945]
A `Dropdown` will currently fault when the underlying `Bindable` is updated to a value not present in the dropdown.

Here are two ideas to circumvent this:
- Add the "invalid" value as a temporary `DropdownMenuItem` and delete it once the selection is changed.
This would allow to display the selected value temporarily and allow the user to keep it (which may or may not be desirable depending on the situation)
- Restore the "default" value and update the `Bindable` accordingly.
Could be either a fallback to the first item in the list or an optional delegate to retrieve a valid value from an invalid one (more flexible).
This might result in an infinite feedback loop of `Bindable` updates if used improperly.

Causes ppy/osu#3474

**Comment by smoogipoo** [comment]
I like the first idea, not a fan of the revert-to-default option.

**Comment by peppy** [comment]
I'm fine with the first plan, but rather than saying "invalid" it should probably just go blank. More friendly to the end-user in this case.

**Comment by peppy** [comment]
Proposal

- `AddDropdownItem(string text, T value)` becomes `AddDropdownItem(T value)`
- Move string converstion to `Dropdown` itself via:

```csharp
protected virtual string GetDisplayString(T item)
{
	if (item is MenuItem m)
		return m.Text;
    if (item is Enum e)
		return e.GetDescription();

	return item.ToString()
}```

Override as necessary, but should not need overriding in all existing usages.

**Comment by AtomCrafty** [comment]
Wouldn't that require changing every existing use of `Dropdown<T>` to `Dropdown<DropdownMenuItem<T>>`?

**Comment by peppy** [comment]
I don't think this would be required. Is there a particular scenario you see that being required?

**Comment by AtomCrafty** [comment]
Nevermind, I accidentally skipped the last line when reading your snippet. I'm a bit tired atm, so please excuse if I'm somewhat slow ^^"

**Comment by AtomCrafty** [comment]
Yeah that could work. Simplifies the use of dropdowns in many cases, but still allows you to specify text manually by creating a `Dropdown<DropdownMenuItem<T>>`.

**Comment by AtomCrafty** [comment]
@peppy
About the `AddDropdownItem(T)` proposal:
What do you think about keeping both methods, with something like
```
AddDropdownItem(T item) => AddDropdownItem(GetDisplayString(item), item);
```
and ditching the `if (item is MenuItem m)` part?

After thinking a bit I found that `Dropdown<MenuItem<T>>` isn't exactly elegant, since we'd then be dealing with a `Dictionary<T, DropdownMenuItem<MenuItem<T>>>` internally and the actual selected values would be `MenuItem`s as well, instead of their contained value.

**Comment by AtomCrafty** [comment]
It might be worth mentioning that in most cases, `AddDropdownItem` isn't used at all, since the dropdown is populated by setting the `Items` property. So I'm not sure whether the change is that useful to begin with. Unless of course, your primary goal with GetDisplayString was to just generate the "invalid item" label.

**Comment by peppy** [comment]
Give it a shot

**Comment by AtomCrafty** [comment]
Another point to keep in mind:
I don't like the idea of the label being directly generated from the value of a DropdownMenuItem.
There will likely be situations where you want multiple entries with the same value, but different labels (like a "default" option at the very top).

**Comment by peppy** [comment]
i'm not sure why we're keeping "both methods". i don't see the issue with my proposal.

**Comment by peppy** [comment]
code up what you think is right and we'll discuss.

**Comment by AtomCrafty** [comment]
The issue I have with your proposal --unless I'm completely missing your point-- is that it would make it impossible to manually specify the item text without creating either a new subclass of `Dropdown` or a class wrapping the actual values, which overrides `ToString`.
*(Could you explain what your goal with the `MenuItem` logic is? It seems like it is supposed to work around this by allowing you to specify a `Text`, but imho that would get very ugly fast.)*

I think there should remain a way to manually set the label for each dropdown entry, hence keeping the `Add(string, T)` method.
There should also be an option to set a fixed text for every value not present in the dropdown (like "Current resolution" or "Default"). Only in case this `FallbackText` is not set (`null`), the `GenerateItemText` method should be used to create the label.

To be honest, I personally don't believe the addition of `Add(T)` is that useful in the first place, as it wouldn't be used anywhere, since nearly all usages of `Dropdown` [set the `Items` property directly](https://github.com/ppy/osu-framework/issues/1945#issuecomment-426270840).

Please have a look at 0a5d8b98501f3b2366b3fc55eb6db9e2607f26bb if you're free.

**Comment by peppy** [comment]
This is completely correct – you would subclass the dropdown or you would give the item a description.

**Comment by AtomCrafty** [comment]
But what exactly is the point in making it *more* difficult than it is right now? I don't see the benefit.

**Comment by peppy** [comment]
This is how we design components in the whole game. Subclassing is not to be considered "difficulty" (it's a few extra lines at most) and keeps implementation detail where they should be – local to the UI element.

We want to avoid parents defining behaviour of unique children wherever possible.

**Comment by AtomCrafty** [comment]
I'm sure you're aware that this is a major breaking change to both the framework and the main repository, just to *remove* functionality.

>We want to avoid parents defining behaviour of unique children wherever possible.

It also goes against your own philosophy since it takes liberty *away* from the user by forcing *specific behavior* on them instead of allowing them to specify item labels freely.

If you're fine with that I'm happy to implement it, but I'm far from convinced this is the right way forward.

**Comment by peppy** [comment]
i am confident in this direction, but could @smoogipoo @ekrctb (or anyone else) please weigh in on this decision.

for what it's worth we make breaking changes on a regular basis and have no guarantee of API stability yet. One of my main goals is to make a framework that guides people into good coding practices while ensuring flexibility. The dropdown class was designed in an ugly way from the start, and I see no harm in fixing it.

**Comment by smoogipoo** [comment]
Chiming in that I agree with the direction proposed by @peppy . So long as you can only add items via plain `T` values, and let all the text be controlled by base/subclasses of dropdowns.

**Comment by AtomCrafty** [comment]
So... am I supposed to hide the `Add(string, T)` version and create a new subclass for every place that currently uses it, which does nothing but expose said method as public?
Or should I delete everything and have every subclass implement the entire adding logic from scratch?

Also, how would you handle duplicate values by subclassing? The `GenerateItemText` method can't distinguish between them.

**Comment by AtomCrafty** [comment]
You may want multiple entries with different labels, that correspond to the same value when selected.
