### ISSUE TITLE
Unhandled exception when changing to "valid" display resolution

### ISSUE THREAD

**Issue by AtomCrafty** [ppy/osu-framework#1953]
`OpenTK.DisplayDevice.ChangeResolution` fails whenever I select the display resolution 1768x992, even though it is listed as valid for every display.

[Demo video](https://www.youtube.com/watch?v=G_VbhifjaJs)
[Stack trace](https://pastebin.com/i0c91Apq)
[List of OpenTK display modes](https://pastebin.com/Yp22XasR) (generated by [this](https://github.com/AtomCrafty/list-display-modes/releases) tool)

I haven't investigated this in-depth, but I noticed that the 1768x992 resolution can't be used with a refresh rate of 60 Hz (see the attached list)

**Comment by AtomCrafty** [comment]
Could potentially be solved by including the refresh rate in the resolution dropdown as proposed [here](https://github.com/ppy/osu-framework/pull/1946#issuecomment-429009249).

**Comment by FreezyLemon** [comment]
This seems to be fixed. The desktop window now uses [SDL_GetClosestDisplayMode](https://github.com/ppy/osu-framework/blob/1a191f8becfb800d8b6d158d6e7a999f33ee1ece/osu.Framework/Platform/SDL2DesktopWindow.cs#L1481) to find a valid display mode, even if the current refresh rate is not supported in other resolutions.

I tested it on my machine to be sure and no problems.
