### ISSUE TITLE
PassThroughInputManager syncs key presses even if they were handled

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1966]
In `PassThroughInputManager.Update()` it syncs the state from the parenting input manager.

For mouse input, only released buttons are handled.
For keyboard input, pressed and released buttons are handled.

This has the effect that if a `Drawable` handles `KeyDown()` at a higher point in the hierarchy, the button press will _also_ be handled by every `PassThroughInputManager` in the draw hierarchy when they sync.

Test case:
```csharp
public class TestCaseScratch : TestCase
{
    public TestCaseScratch()
    {
        Children = new Drawable[]
        {
            new PassThroughInputManager
            {
                RelativeSizeAxes = Axes.Both,
                UseParentInput = true,
                Child = new InputBox { RelativeSizeAxes = Axes.Both }
            },
            new HiddenInputHandler { RelativeSizeAxes = Axes.Both }
        };
    }

    private class InputBox : Box
    {
        protected override bool OnKeyDown(KeyDownEvent e)
        {
            Colour = Color4.Red;
            return true;
        }

        protected override bool OnKeyUp(KeyUpEvent e)
        {
            Colour = Color4.White;
            return true;
        }
    }

    private class HiddenInputHandler : Box
    {
        public HiddenInputHandler()
        {
            Alpha = 0;
            AlwaysPresent = true;
        }

        protected override bool Handle(UIEvent e) => true;
    }
}
```

**Comment by UselessToucan** [comment]
I have a couple of questions.
Lets say we have the scene graph.
![image](https://user-images.githubusercontent.com/22450664/48051763-0a210100-e1b7-11e8-9797-f5e6bbad4060.png)

1. Do I understand correctly that `PassThroughInputManager` should sync input state changes related to `Container B` and `Container C`(including their children)?
2. Do I understand correctly that `PassThroughInputManager` should ignore input state changes out of its scope? For example, input state changes related to `Container A`.
3. Do I understand correctly that the relationship between `PassThroughInputManager` and parent `InputManager` is many to one? I mean, we can have multiple `PassThroughInputManager` which will sync with one parent `InputManager`.

**Comment by smoogipoo** [comment]
1. Not sure what you mean by this. Syncing input state changes related to its own children?
2. Container B/C should probably still see that key A is down even if Container A handled it.
3. Yes
