### ISSUE TITLE
BindableDouble throws exception when propagating precision

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#1976]
```
var number = new BindableDouble(1000);
var bindable = new Bindable<double>();

bindable.BindTo(number);

number.Precision = 0.5f;
```

In the above code, `bindable` does not support precision, so the line will crash. The same will likely happen with min/max values, that only `BindableNumber` (and by extension, `BindableDouble`) support.
Likewise, this is also going to be an issue with `BindableInt` and `BindableLong`.

I believe this is pretty unexpected behaviour, thoughts?

**Comment by peppy** [comment]
If there's a way to work around this then we should. If not, at very least it should probably not crash.
