### ISSUE TITLE
Support for "frost" blur effect

### ISSUE THREAD

**Issue by Altenhh** [ppy/osu-framework#1987]
in this, there is two things, a background (everything behind the object) and the main object (box/circle).

The main object will blur everything behind itself, but wont blur the content inside of the object, thus making a "frosted glass effect"

**Example:**
![Background (pretty much everything behind the object), Main object (blurring everything behind it)](https://cdn.discordapp.com/attachments/188630652340404224/512838264173101067/unknown.png)

**Comment by peppy** [comment]
This likely requires the main scene (in the screenshot "Background") to be rendered inside a `BufferedContainer`, then a new container type (acting as a base type for `BufferedContainer` too?) which allows for consumption of that buffered container in a way that blur can be applied.

**Comment by AltenGD** [comment]
ok so im back on this again, but just one question: how will i be able to allow consumption of the buffered container in a way that blur can be applied? im currently trying to make this as of now and i dont have any ideas on how i can implement this.
