### ISSUE TITLE
FontName should be replaced

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2003]
Rather than throwing around font name strings to `SpriteText`, there should be a class/interface.

```csharp
struct FontUsage
{
    string Name { get; }
    string Weight { set; }
	bool Italics { get; }

    // also potentially moving the following from SpriteText
	float Size { get; }
    bool FixedWidth { get; }
    ...
}

new OsuSpriteText
{
    Font { Size = 24 }
}
```

`SpriteText`'s `Font` would be non-null and set by the `ctor`s to sane values. This will help handling of bold/italics/weight changes where it is currently impossible due to no explicit font being set.

Discussion that brought this up: https://github.com/ppy/osu-framework/pull/2002#discussion_r238919255

**Comment by UselessToucan** [comment]
I suggest to create class hierarchy with abstract `FontInfo` class and concrete implementations like `NotoHangul`, `NotoCjkCompatibility` and so on.
