### ISSUE TITLE
Proposal: GenericTransformFloat<T>

### ISSUE THREAD

**Issue by SirCmpwn** [ppy/osu-framework#203]
``` c#
Transforms.Add(new GenericTransformFloat<MyComponent>(c,
    c => c.SomeProperty, // get
    (c, v) => c.SomeProperty = v); // set
```

**Comment by peppy** [comment]
We now have `void TransformTo<TValue>` which can be fed a custom Transform in the constructor. While it's not as flexible as providing the get/set directly as above, so far I think it's enough for our use-cases.

We can revisit this if providing custom one-use transforms becomes a more common thing.
