### ISSUE TITLE
Markdown containing [elements] hard crashes

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2059]
As seen [failing ci](https://ci.appveyor.com/project/peppy/osu-framework/builds/21327169).

Due to the way `CustomizableTextContainer` handles `[]` surrounded elements, conflicts are seen when parsing markdown. Simply escaping all `[ ]` to `[[ ]]` (as implied by the code in `CustomizableTextContainer`) does not work as it breaks other markdown elements.

As part of the fix, this testcase should also wait for the online load to complete before passing, as it currently doesn't.

**Comment by andy840119** [comment]
#2014 Find out and fixed this issue (use MarkdownTextFlowContainer instead TextFlowContainer in FencedCodeBlock)
.
And #2042 create CodeTextFlowContainer instead of use MarkdownTextFlowContainer in FencedCodeBlock
.
#2042 contained code in #2014(fix crash issue)

**Comment by frenzibyte** [comment]
Closing as already resolved in https://github.com/ppy/osu-framework/pull/2403, test case now waits for online request to finish as per https://github.com/ppy/osu-framework/pull/2618 as well.
