### ISSUE TITLE
Make Graphics API more abstract

### ISSUE THREAD

**Issue by jorolf** [ppy/osu-framework#2119]
Right now every OpenGL call is static. This is bad because it means that Drawables can only call functions which are going to be in OpenGL 3, 4, ES 2 & ES 3 (same for the shader code and you can't even specify glsl versions without possibly breaking a platform). 

I would propose that we have an abstract ``Graphics`` interface that exposes common methods like ``CreateShader`` and conditionals like ``IsOpenGL4`` to access OpenGL 4 methods. 

In the future this could allow for optimized shader code for specific versions or even a completely different graphics api like Vulkan or DirectX. It would also better support OpenTK 4 should we ever switch to it.

**Comment by swoolcock** [comment]
I would rather put the effort toward implementing something like Veldrid. It’s rather a large paradigm shift moving away from OpenGL.

OpenTK 4 will crash and burn before we ever look at using it.

**Comment by peppy** [comment]
I think our general direction has been to make every call architecture agnostic (in the hope of supporting more than GL and also potentially switching away from OpenTK to something more mature/supported like SDL)

**Comment by swoolcock** [comment]
As a first step, I would like to see us replace OpenTK with SDL just for input and window/lifecycle management.  We can continue to use the OpenGL bindings from OpenTK for now, as they handle the magic that automatically translates GL calls to corresponding GLES on mobile.  Replacing those OpenGL bindings would be the final thing required to remove OpenTK entirely.

Going forward we have a few options as I see it:

* Continue using OpenGL/ES, preferably with bindings other than OpenTK.
* Look at switching to [VulkanSharp](https://github.com/mono/VulkanSharp). which may require some integration with [MoltenVK](https://github.com/KhronosGroup/MoltenVK) for macOS and iOS.
* Look at switching to [Veldrid](https://github.com/mellinoe/veldrid) or something similar, which will handle the cross-platform portion for us.  Note that Veldrid includes individual bindings for SDL2, OpenGL, and Vulkan.

**Comment by jorolf** [comment]
Just fyi SDL was the reason raw mouse input was broken for me for a long time

**Comment by peppy** [comment]
That is unrelated and was because we were not handling that case correctly. It does not mean that SDL is inherently broken with raw input handling.

**Comment by swoolcock** [comment]
FYI: I just tested out the keyboard demo that comes with the libsdl source on my iPad with a smart keyboard, and it fires both a `SDL_KEYDOWN` and `SDL_KEYUP` when you hold down a key, then nothing when you release it.  It looks like we will still need to include the code from #2087 on iOS.

**Comment by tangalbert919** [comment]
From those three options, the third option would be best. As far as I can tell, that's the only option that doesn't threaten support for certain platforms or hardware that doesn't support Vulkan (unless you're on Linux, in which a Sandy Bridge iGPU does support Vulkan, but on Windows, it doesn't).

**Comment by orowith2os** [comment]
What's the current plan for this? If the framework decides to support more graphics APIs, it can be done in more of a crossplat way pretty easily, such as by keeping OpenGL for macOS and using DirectX (DXVK-native on Linux, this will also allow a Vulkan backend via DXVK on Windows) for other platforms that support the appropriate APIs.

The move to SDL2 seems to have also been done, so might be worth a small update post.

**Comment by peppy** [comment]
There are ongoing changes being made in this direction.

https://github.com/ppy/osu-framework/pull/5598
https://github.com/ppy/osu-framework/pull/5597
https://github.com/ppy/osu-framework/pull/5596

See https://github.com/ppy/osu-framework/issues/4909 for the ongoing task.

Will close this issue as we are tracking via more specific issues already.
