### ISSUE TITLE
Move audio components to the draw hierarchy

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2125]
The audio subsystem currently operates as its own hierarchy and misses out of the benefits of existing in the same place as everything else. With this change, we will allow all audio properties to be recursively and locally adjusted, and better manage lifetimes of audio components (as they will be spawned/cleaned with containers/screens/etc.

- `AudioManager` would be at a `Game` level and manage overall volume as it currently does.
- `AdjustableAudioComponents`, `Tracks` etc. could be added anywhere in the hierarchy. We would use DI or passing of state to maintain integrity in the hierarchy (similar to how `clock` is passed down currently).
- It should be possible to move a `Track` from one location to another and have it synchronise with its new additive/multiplicative parent adjustments.

This is a relatively high priority change as we need arbitrary local parameter adjustments and transforms on these parameters. After implementation we will be able to use the same transform system we use on `Drawable`s on `AudioComponent`s too.

Quick brainstorm on how I see this working:

![image](https://user-images.githubusercontent.com/191335/51889929-1eebea00-23de-11e9-975f-7cfc1861df08.png)

If we decide to use the DI approach, we will need to reassess the fact that DI is not performed a second time when a parent is changed.

Prerequisites:

- Possibly rename the draw hierarchy internally
- Make `Component` the base class of `Drawable`, rather than vice-versa (how it currently is for simplicity).
- Assess how clocks and audio components fit together. In many cases an audio component also acts as a clock.

**Comment by UselessToucan** [comment]
Note that we can't apply Flyweight pattern to the objects which are in the scene graph.

For example, we have the following class
```
class A
{
    private B b;
}
```
where `b` is in the scene graph as a child of `A`.

We won't be able to reuse this `b` object in a different `A` instance since we can't add `b` to the scene graph twice.

**Comment by smoogipoo** [comment]
W don't really use the flyweight pattern in the draw hierarchy.
