### ISSUE TITLE
Proposal: Remove inheritance `Drawable : Transformable`

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu-framework#2127]
I have been thinking about a refactor/redesign of `Drawable`. Eliminating `Transformable` seems a good first step.
As transformation is a public thing of `Drawable`, it should be possible conceptually.
Maybe data and logic separation of transformation logic can also be done.
Thoughts? @smoogipoo

**Comment by peppy** [comment]
Likely ties in to #2125.

I think it's very feasible to move transform logic to a class which is held as a member of `Drawable`. Before eliminating transformable, we may want to consider making `Transformable : Component` and describing what logic we expect `Component` to have, unless there's a specific reason this cannot happen first.

**Comment by smoogipoo** [comment]
I don't entirely see the point of removing Transformable, is there a deeper issue which this is trying to solve?

**Comment by peppy** [comment]
you do have a point, both `AudioComponent` and `Drawable` could derive `Transformable` as it currently stands.

**Comment by ekrctb** [comment]
I was thinking more conceptually, such as that `Transformable` doesn't require parent/children information (except for `propagateChildren` thing, which isn't essential). However, after your comments I'm not sure that reason justifies this change.
As a separate thing, I'm also thinking that separating `UpdateTransforms` from `Update` so we can have different update rate for transforms for example.

**Comment by ekrctb** [comment]
I think this issue alone doesn't make much sense and need a more concrete design for useful discussion.
