### ISSUE TITLE
Bindable isn't specific to configuration anymore

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu-framework#2133]
`Bindable` is used not only for listening configuration change but more general mechanism such as dependency injection.

- Namespace change. Bindables are currently in `osu.Framework.Configuration` namespace.
- Remove `IHasDescription` and `IParseable` from `IBindable`. It seems like `IHasDescription` is not used in both framework and osu. Possibly remove `IHasDefaultValue` and `ICanBeDisabled` too.

**Comment by peppy** [comment]
I was actually talking with @smoogipoo about bindables almost being worthwhile of splitting off into their own dedicated library. Would be interested in opinions on whether others see this as a useful thing to have for their non-osu-framework projects.

Can agree with moving to `osu.Framework.Bindables` or similar namespace.

**Comment by Aergwyn** [comment]
I'd love for this to happen so I don't get all the libraries and other stuff when I basically just want the functionality around Bindables.

**Comment by peppy** [comment]
A minimum requirement for this would be making bindables threadsafe (or deciding that that isn't something we care about), which is not on our current agenda. There would need to be enough external interest in seeing this through for it to happen.

**Comment by smoogipoo** [comment]
In the interest of keeping Bindables as high performance and lean as possible, they shouldn't be thread safe, imo.

**Comment by jai-x** [comment]
The original scope of this ticket was to move bindables from the `osu.Framework.Configuration` namespace to the `osu.Framework.Bindables` namespace, which has since happened.

Unsure if this issue should still be kept open to track moving bindables to it's own separate library/repo.

**Comment by frenzibyte** [comment]
Seems the repository is ready for that happen, closing the issue would makes this completely forgotten about. (although it's seemingly forgotten about currently)

**Comment by smoogipoo** [comment]
Can be closed.
