### ISSUE TITLE
Implement new osu!framework design

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-framework#2135]
![](https://user-images.githubusercontent.com/191335/52176754-64ebe800-27fa-11e9-9969-7a9bd203c740.png)

**Comment by UselessToucan** [comment]
Please provide more detailed description(see https://github.com/ppy/osu/issues/70, https://github.com/ppy/osu/issues/67, https://github.com/ppy/osu/pull/2430#issuecomment-383063327).

**Comment by peppy** [comment]
Please ask what you need descriptions for. Most everything should be self-explanatory.

**Comment by UselessToucan** [comment]
What exactly should be reimplemented? Only Visual Tests and Draw Visualizer?

**Comment by peppy** [comment]
See https://github.com/ppy/osu-framework/issues/1957#issuecomment-460050489

**Comment by jorolf** [comment]
How should selected sub test cases look? They don't have a background like the rest.

**Comment by peppy** [comment]
Very good question. @arflyte please check on this. Top-level items without groupings show a highlighted and non-highlighted state in the design, but nested don't really have either.

**Comment by arflyte** [comment]
![illustrator_190212-124326](https://user-images.githubusercontent.com/3632750/52610280-df37fe80-2ec3-11e9-9b1d-aae5fb2852a8.png)

The top shows when it's just expanded but not active.

The bottom shows when it's active, with an active sub item.

**Comment by jorolf** [comment]
Where did you get the arrow sprite from? afaik it isn't in the default font. Should I use something else instead? Currently ``...`` is being used instead of an arrow

![groups](https://user-images.githubusercontent.com/12570757/52888770-4df3b100-317d-11e9-9ae6-b7e31d5553ed.png)
(wip image)

**Comment by jorolf** [comment]
Actually what font does the design even use? The framework currently only has OpenSans. @peppy should more fonts be added or should I continue to use the same font?

**Comment by peppy** [comment]
The arrow is from FontAwesome I believe. You're more than welcome to transfer that class/font across to framework so we can use it there. I think it may be something many people will make use of, after all.

**Comment by jorolf** [comment]
My second comment was more about the actual font. The regular font isn't the same font that's in the framework now. In addition to that the frame recorder time and the draw visualiser use different fonts too

**Comment by peppy** [comment]
Ah, sorry, missed that. @arflyte please update us.

**Comment by arflyte** [comment]
The font used in Roboto and Roboto Condensed; available on Google Fonts

**Comment by jorolf** [comment]
Should the colours used in the design be centralized in a special class? (e.g. ``FrameworkColour``) Should they be static or loaded through the BDL?

**Comment by peppy** [comment]
static `FrameworkColour` is fine in this case, as i don't think we will ever be skinning them!

**Comment by jorolf** [comment]
What should I do with the record button? In the current implementation it changes background colour depending on the state (normal/recording/stopped). Should I also include that in the new design? Which colours should I use then?
![record](https://user-images.githubusercontent.com/12570757/56615422-50f69c00-661b-11e9-9d22-221b1252d40c.png)
![stop](https://user-images.githubusercontent.com/12570757/56615439-57851380-661b-11e9-84cc-2082c958cf12.png)
![reset](https://user-images.githubusercontent.com/12570757/56615473-6bc91080-661b-11e9-85d3-5d7730c12ef9.png)

**Comment by peppy** [comment]
Just go with what you think looks good. You could potentially drop the colours altogether if you can't find a good combiantion.

**Comment by jorolf** [comment]
what is this "record" circle supposed to do in the toolbar?
![grafik](https://user-images.githubusercontent.com/12570757/56760142-dfddf280-679a-11e9-86e1-0d97eae53ae0.png)

**Comment by jorolf** [comment]
In general, what should I do with that part of the toolbar? The design shows the current time however we only save frames.

**Comment by peppy** [comment]
Let's drop the colouring altogether. I think it will look better.

**Comment by jorolf** [comment]
What should we do about the top header and the bottom footer?
![footer](https://user-images.githubusercontent.com/12570757/59799169-18ee9b00-92e4-11e9-8458-2e5028e086bf.png)
![header](https://user-images.githubusercontent.com/12570757/59799217-2efc5b80-92e4-11e9-8789-6f09eab980ce.png)

They seem like a design for a custom window border...

**Comment by peppy** [comment]
For the time being it's fine to ignore these. Status bar may be added in the future (and replace the weird pop-up debug messages bottom-left with something less intrusive.

If you're looking for something left to do, the `DrawVisualiser` would be a good next target.

**Comment by jorolf** [comment]
How should step groups look in the new design?

![stepgroups](https://user-images.githubusercontent.com/12570757/60397162-40e2c780-9b4a-11e9-84d6-7dcee1c1cd29.png)
^ that's what they currently look like

**Comment by jorolf** [comment]
![fontcolour](https://user-images.githubusercontent.com/12570757/60397283-8eabff80-9b4b-11e9-8893-e7967ab93e72.png)
and what do these font colours mean? Currently the only colour change is from white to grey when they've been clicked. Why are there yellow steps now?

**Comment by peppy** [comment]
I think white is the current running step. Yellow seems to be the colour for clickable buttons.

Step groups I'm not sure, may need @arflyte input for that.

**Comment by peppy** [comment]
Design has been realised 👍
