### ISSUE TITLE
Remove bindable's implicit operator

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#2150]
I think we should discuss removing bindable's implicit operator that returns the inner value. It's very easy to go wrong with something like this:

`myObject?.MyBindable != null`

vs

`myObject?.MyBindable.Value != null`

Because in a lot of cases we use `myObject?.MyBindable` to refer to the value.
To add insult to injury, `IBindable<T>` doesn't have an implicit operator due to limitations of interfaces, so you can only refer to the inner value via `.Value`.

cc: @ekrctb / @peppy / @default0 / @Tom94

**Comment by ekrctb** [comment]
I was thinking the same. I agree.
