### ISSUE TITLE
Text-box focus problems with Windows Gaming Bar

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-framework#2198]
**Describe your problem:** Every text-box in osu!lazer behave strangely with the Windows Gaming Bar (`Windows` + `G`) when you close it. The best way to get everything back to normal is to focus another application, and then re-focus osu!lazer.

Also, if you type something after doing this, it causes all previously pressed keys (after closing the gaming bar) to appear at that moment.

One weird thing is that some keys still seem to work in some situations with this issue (like left and right arrows still interact with carousel).

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/105320502-881a2880-5bc6-11eb-8d40-735f5ae48954.mp4

In the video, I used the on-screen keyboard for a better demonstration, but the same happens without using it.
Also, you can see that I use applications that could interfere with shortcuts. I can confirm that by closing those programs, the problem persists.

**osu!lazer version:** `2019.227.0` (updated in: `2021.118.1`)

**Comment by Susko3** [comment]
This is a problem with SDL, upstream issue: https://github.com/libsdl-org/SDL/issues/4369
Same underlaying problem as https://github.com/ppy/osu-framework/issues/2525

*From https://github.com/libsdl-org/SDL/issues/4369:*
>The popup doesn't take window focus from the SDL window (the window will appear to be in focus), but it takes keyboard focus (pressing keyboard keys doesn't produce SDL_KEYUP/DOWN events).

The game bar also does this, so it's the same underlying problem with SDL.
