### ISSUE TITLE
Strange stutter at start of beatmaps

### ISSUE THREAD

**Issue by Pokidots** [ppy/osu-framework#2215]
I'm having a strage stutter at the start of many maps while using a custom skin other then YUGEN SD 
(i am not sure if the video provided shows it) stutter happens at around 0;30  
 https://youtu.be/R4tjKj9Km6s

**Comment by peppy** [comment]
I can't seem to see any stutter in the video.

**Comment by Pokidots** [comment]
> I can't seem to see any stutter in the video.

strange, the OBS picked it up when i replayed the recording. do you want me to take some extra recordings the next few times i run osu lazer?

**Comment by peppy** [comment]
We need performance log files as well.

**Comment by Pokidots** [comment]
all three log files?

**Comment by Pokidots** [comment]
> We need performance log files as well.

where are they located? i have spent almost 20 minutes trying to find them

**Comment by Joehuu** [comment]
Performance has improved since, so closing as stale (and not a framework issue).
