### ISSUE TITLE
Raw Input "ignores" mouse confinement

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-framework#2247]
Basically the raw input seems to "ignore" the `confine mouse cursor` feature in some situations. (previous issue: ppy/osu/issues/4463)

[Here's a demonstration](https://drive.google.com/file/d/1B6Dqd7PvHriqn1qfcQpbtnUTVwUuno-y/view?usp=sharing).

In summary, I noticed that (when raw input is enabled):
- The cursor can go outside the screen when in fullscreen/borderless mode if `confine cursor` is set to `never`
- The cursor can go outside the window in windowed mode when the left/right/scroll mouse button is held when `confine cursor` is set to `never` or `fullscreen`

**Comment by peppy** [comment]
See https://github.com/ppy/osu-framework/pull/1408 for the cause of this.

**Comment by Gabixel** [comment]
The issue seems to be fixed with the new "high precision mouse" option. Can be closed.
