### ISSUE TITLE
Submit Vector/Matrix additions to upstream OpenTK

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#226]
Now that we are using GameWindow, we can almost switch back to vanilla opentk. The only thing holding us back are a few custom additions we have.

https://github.com/ppy/opentk/commits/osu-gamewindow

We should get these merged into upstream if possible.

**Comment by Tom94** [comment]
We may want to hold off on that given that we likely need a custom fork for exclusive fullscreen support. 

Let's first ask them what exactly the regression was, that the nested window fixed, and if no longer relevant, whether the nested window can be removed upstream.

**Comment by SirCmpwn** [comment]
We should submit different pull requests for each of the changes we've made.

**Comment by Tom94** [comment]
We would certainly have to make major revisions to one of these changes in order to get a pull request with it accepted. We can save this work by conditioning it on the acceptance of the first pull request is what I am saying.

**Comment by peppy** [comment]
We'll get to this at some point, but as we have since added further changes to opentk which we are relying on this is low priority.
