### ISSUE TITLE
Suspended screens receive input while transitioning

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#2277]
Suspended screens are allowed to receive input while they're suspending. The following testcase demonstrates this:

```
[Test]
public void TestNonCurrentScreenDoesNotAcceptInput()
{
    ManualInputManager inputManager = null;

    AddStep("override stack", () =>
    {
        // we can't use the [SetUp] screen stack as we need to change the ctor parameters.
        Clear();

        Add(inputManager = new ManualInputManager
        {
            Child = stack = new ScreenStack(baseScreen = new TestScreen())
            {
                RelativeSizeAxes = Axes.Both
            }
        });
    });

    TestScreen screen1 = null;
    TestScreen screen2 = null;

    pushAndEnsureCurrent(() => screen1 = new TestScreen());
    AddStep("push", () => screen1.Push(screen2 = new TestScreenSlow()));
    AddStep("click centre of screen", () =>
    {
        inputManager.MoveMouseTo(screen1);
        inputManager.Click(MouseButton.Left);
    });

    AddAssert("screen 1 not clicked", () => !screen1.Clicked); // Currently fails
}
```

In the case of `suspendImmediately == false`, the previous screen should be allowed to receive input while the pushed screen is loading.

This causes https://github.com/ppy/osu/pull/4505.

**Comment by peppy** [comment]
Important we remove local workarounds for this when it is fixed (checks for `IsCurrentScreen()` and `Carousel.AllowSelection` come to mine).

**Comment by smoogipoo** [comment]
As a departure from my original statement, I believe even `suspendImmediately == false` screens should not receive input. There are two cases leading me to this judgement:

1. If we ever wanted to change the main screen stack to be `suspendImmediately = false`, then screens will start crashing again - you'll be able to enter results twice etc.
2. Along with (1), even if you don't use `IScreen` methods, you could still, change the state of the game - e.g. you could enter mod select and change mods while player is loading. This sounds unsafe to me.

Furthermore, we should at some point provide a method that tells a user of the `ScreenStack` that the screen is "pseudo suspended" for `suspendImmediately = false` stacks, so the user can add an overlay if desired.

Agree, @peppy ?

**Comment by peppy** [comment]
Agree. There should probably be a `Suspending` and `Suspended` (what we currently have) state for that particles scenario (which would typically be used to show a loading screen).
