### ISSUE TITLE
Properly ensure no 2 game hosts may exist at the same time.

### ISSUE THREAD

**Issue by Tom94** [ppy/osu-framework#229]
We may want this to be optional for certain unit tests (e.g. IPC), but in the general case we should be making sure.

**Comment by SirCmpwn** [comment]
Why?

**Comment by Tom94** [comment]
Because we rely on the fact that only one game host exists when doing performance counting via `FrameStatistics`. I don't think it's a good idea to pass a reference to the host to almost every component of the game that might want to increment performance counters, and I also don't think there is ever a good reason to have 2 game hosts within the same application domain except for unit tests where we want to not start 2 applications for convenience. We may be able to use `AppDomain`, though, in such unit tests.

**Comment by peppy** [comment]
Do you have anything against my idea of passing the relevant Host instance into FrameStatistics rather than making BasicGameHost static (which I'm still mostly against)?

**Comment by Tom94** [comment]
I think that's actually the best idea so far. That way we're keeping a high amount of encapsulation.

**Comment by peppy** [comment]
i think `public BasicGameHost Target;` would work well

**Comment by Tom94** [comment]
How would that help? I was thinking more along the lines of
`public static BasicGameHost Target { set; private get; }`

**Comment by peppy** [comment]
static, yes!
