### ISSUE TITLE
Tests getting stuck

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2290]
Example 1 (100% reproducible): https://ci.appveyor.com/project/peppy/osu/builds/23356732/tests
Example 2: https://ci.appveyor.com/project/peppy/osu-framework/builds/23350438

**Comment by smoogipoo** [comment]
These have now been fixed via https://github.com/ppy/osu-framework/pull/2304 + https://github.com/ppy/osu/pull/4541
