### ISSUE TITLE
DrawSize not updated after setting Width or Height before load cycle is complete

### ISSUE THREAD

**Issue by magnus97** [ppy/osu-framework#2291]
I have been messing with this lib on a different project not related to osu and hit a wall currently that i dont feel i should make work arounds for and should be fixed in the code.
When setting the Width or Height of the Container the RelativeAxis does not propergate propperly down before it is set again from a window screen size changed event.

This is the code i have:
```csharp
        [BackgroundDependencyLoader]
        private void load(JopeBotDesktop desktop)
        {
            desktop.ResizeEvent += DesktopOnResizeEvent;
            setSizeAuto(desktop.Size); //DrawRectangle is not updated
        }

        private void DesktopOnResizeEvent(int width, int height)
        {
            setSizeAuto(new Vector2(width, height)); //DrawRectangle is updated
        }

        private void setSizeAuto(Vector2 size)
        {
            Width = size.X - Position.X;
            Height = size.Y - Position.Y;
        }
```

I cant fully figure out what causes the problem but i know a workaround i can do in the meantime this is worked on.

**Comment by magnus97** [comment]
Never mind i think i know what is happening now.
When i query the desktop.Size it still isent propperly set in how large it actualy is and thus causes the issue i have where this happens ![](https://wildwolf.senpai.download/80b7492417.png)

**Comment by peppy** [comment]
-39 sounds very wrong..

**Comment by magnus97** [comment]
I dont know why it was -39 but i know after i set it on the event onLoadCompleate it fixed it self
