### ISSUE TITLE
Masking with Border has a weird interaction with Blending

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu-framework#2300]
Using masking for a border while also using blending to achieve an effect i. e. for hovering causes an "inner border" making it look unsightly.

Testcase to visualize:
```csharp
public class TestCaseButtonIssue : TestCase
{
    public TestCaseButtonIssue()
    {
        Children = new Drawable[]
        {
            new Box
            {
              Colour = Color4.Gray,
              RelativeSizeAxes  = Axes.Both
            },
            new FillFlowContainer
            {
                Width = 280,
                AutoSizeAxes = Axes.Y,
                Anchor = Anchor.Centre,
                Origin = Anchor.Centre,
                Direction = FillDirection.Vertical,
                Spacing = new Vector2(0, 10),
                Children = new Drawable[]
                {
                    new IssueButton
                    {
                        RelativeSizeAxes = Axes.X,
                        Text = "no blending"
                    },
                    new IssueButton
                    {
                        Hovered = true,
                        RelativeSizeAxes = Axes.X,
                        Text = "with blending"
                    }
                }
            }
        };
    }

    private class IssueButton : Button
    {
        public bool Hovered;

        [BackgroundDependencyLoader]
        private void load()
        {
            Height = 80;
            BackgroundColour = new Color4(50, 50, 50, 255);

            Content.Masking = true;
            Content.CornerRadius = 12;
            Content.BorderThickness = 4;
            Content.BorderColour = Color4.Black;

            Add(new Container
            {
                RelativeSizeAxes = Axes.Both,
                Child = new Box
                {
                    Alpha = Hovered ? 1 : 0,
                    RelativeSizeAxes = Axes.Both,
                    Blending = BlendingMode.Additive,
                    Colour = Color4.White.Opacity(0.1f),
                }
            });
        }
    }
}
```
Image to visualize:
![wat](https://user-images.githubusercontent.com/27222621/55076119-e5112a00-5094-11e9-81c1-6513731b0df6.png)

**Comment by nyquillerium** [comment]
So I've taken a look into this issue, and it has something to do with the `MaskingSmoothness`, as having a `MaskingSmoothness` of 0 removes the 1 pixel where the overlaid box has an incorrect weightning when determining color. The `MaskingSmoothness` gets used when determining the `BlendRange` for the `CompositeDrawNode` masking info, which according to the comment is approximately the size of a pixel. 

This blend range gets sent to the FS as `MaskingBlendRange`. Looking at the shader, the color is a blend of the border color and the inner box's color, depending on how far we are from the border. 

I've tried thinking through how this could happen as a result of `MaskingBlendRange` being at or above 1, but I've hit a brick wall. Wondering if @Tom94 has any suggestions or insights about this phenomenon.

**Comment by Aergwyn** [comment]
I think the milestone can be updated here.

**Comment by peppy** [comment]
We generally don't change milestones any more. I believe @smoogipoo is still quite intent on getting this one solved.
