### ISSUE TITLE
Better fullscreen support on linux

### ISSUE THREAD

**Issue by ddevault** [ppy/osu-framework#233]

**Comment by Nabile-Rahmani** [comment]
Works for me on my Intel GPU.

OS: Debian 8
CPU: Intel Celeron U3600
DE: GNOME on X

**Comment by jai-sharma** [comment]
Does not work for me:

OS: Arch Linux
CPU: Intel Celeron N2840
Graphics: Intel Integrated GPU
DE: None
WM: i3

osu! does go full screen on WM command though (super + F for i3)

**Comment by AkitakeKun** [comment]
Right now when in fullscreen, you're brought back into the osu! when trying to alt-tab out or click away on a second monitor (with mouse confinement disabled)

**Comment by peppy** [comment]
are you still talking about linux?

**Comment by AkitakeKun** [comment]
I don't really know if it's a linux only issue as I do not have a windows box to test it on.
But if it's not then a new issue should be open about it I suppose.

**Comment by Joehuu** [comment]
Fixed in SDL as of now (using Ubuntu).
