### ISSUE TITLE
Switch to System.Data.SQLite + EF

### ISSUE THREAD

**Issue by SirCmpwn** [ppy/osu-framework#234]
Pros:
- System.Data.SQLite is an ADO.NET provider (i.e. an idiomatic .NET SQL backend)
- S.D.SQLite isn't fragmented like sqlite-net
- It's more popular and more actively maintained (by a factor of 8)
- EF is more flexible
- It has i.e. more helpful exceptions

Cons:
- EntityFramework is kind of big

Alternatives:
- System.Data.SQLite + Fluent NHibernate - NH is lighter weight than EF, but more fragmented (not to the same extent as sqlite-net) and less popular. Actively maintained.

**Comment by peppy** [comment]
Completed in osu! game implementation.
