### ISSUE TITLE
Dynamic compilation is broken in vs19 (and possibly other versions)

### ISSUE THREAD

**Issue by jorolf** [ppy/osu-framework#2340]
From what I could gather it's broken because visual studio doesn't create or change the .cs files but instead creates temporary files and then renames them: https://github.com/dotnet/corefx/issues/9462#issuecomment-226461603

This means that neither the ``Changed`` event nor the ``Created`` event gets triggered.

(How did this work until now?!?)

**Comment by peppy** [comment]
I believe this may have changed recently, or is a setting in visual studio. We had one or two reports about this in the past but it always worked for me on a local VS install. May also be filesystem related.

**Comment by jorolf** [comment]
It broke for me when I switched from visual studio 17 to 19
