### ISSUE TITLE
Path color is not the same as the others

### ISSUE THREAD

**Issue by Altenhh** [ppy/osu-framework#2388]
I've noticed a strange bug while experimenting with paths where the path color does not match any other drawable's color
![](https://cdn.discordapp.com/attachments/527806902520905748/574654919047512074/unknown.png)

Here is a test script to recreate this problem:
```cs
Children = new Drawable[]
{
    new TexturedPath
    {
        Anchor = Anchor.TopRight,
        Origin = Anchor.TopRight,
        Vertices = new List<Vector2> { Vector2.One* 50, Vector2.One* 500 },
        Colour = new Color4(238, 93, 146, 255),
    },
    new Box
    {
        Size = new Vector2(500),
        Colour = new Color4(238, 93, 146, 255),
    }
};
```

**Comment by peppy** [comment]
This is definitely incorrect SRGB handling, likely due to the casting of `ColourInfo` to `Color4` in `PathDrawNode` where it should be using the linear version instead.
