### ISSUE TITLE
PreFrame() and PostFrame() in the Game class are never called

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu-framework#2414]

**Comment by peppy** [comment]
Very weird. Interesting to check where these came from / when they were lost.

**Comment by HoutarouOreki** [comment]
Checked commits by skipping back by a year to the initial commit, it seems like these were always present but were never used.

**Comment by peppy** [comment]
As a conclusion, you don't have a use for these functions, right? I think we best just remove them for now.
