### ISSUE TITLE
Container<T>

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#244]
A very common case is wanting to iterate or query a container's children, but not as Drawables.

This will allow it to happen.

`Container<T> where T : Drawable`
`Container : Container<Drawable>`

**Comment by UselessToucan** [comment]
What if children have different type? For example, I can put SpriteText and Button inside of one container.

**Comment by peppy** [comment]
you don't use this then?

**Comment by Tom94** [comment]
Exists now. There may still be some subtle issues with `DrawVisualiser` not picking up containers where  T != Drawable, but those may be fixed in the future.
