### ISSUE TITLE
WaveformGraph renders not precisely enough / jumps around

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu-framework#2441]
I don't know if I'm right to assume the problem lies in WaveformGraph. The higher the graph's resolution is, the worse it gets. In both games it's in a zoomable container (the transform is identical), and the jumping around happens when zooming.

video: https://youtu.be/4LR5ODoUZ-Q

Related: ppy/osu#3066

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu-framework/pull/3952 (can't close).
