### ISSUE TITLE
Handle sRGB to linear RGB conversions

### ISSUE THREAD

**Issue by kkartaltepe** [ppy/osu-framework#246]
Currently the framework stores all textures as GL_RGB for the internal format regardless of the real colorspace of the image data. Anything loaded from a PNG is most likely going to be sRGB and will cause many filters to work incorrectly (E.G. Gaussian blur shader currently manually converts to linear space and back again due to this).

There are a couple ways to approach this:
Make all textures to be used in the framework linear RGB by converting them on load from sRGB formats like PNG.

Support usage of the GL_SRGB texture internal format for framework textures. This will let texture samplers do the conversion transparently on the hardware on most implementations since this is a GL 2.1 feature. However https://www.opengl.org/wiki/Image_Format#sRGB_colorspace mentions that some older (pre 3.0) opengl implementations may incorrectly apply opengl implemented filters before conversion to linear RGB.

It's probably less work to implement the 2nd and assume all implementations will work correctly, but maybe keeping all textures in the framework in a single format is worth considering.

**Comment by Tom94** [comment]
Hi there, thanks for the suggestion! I switched us over partially here: https://github.com/ppy/osu-framework/pull/247

I say "partially" because I kept alpha blending in sRGB space as we want alpha to linearly correspond to _perceptual_ brightness, and not to the actual amount of radiance.

**Comment by kkartaltepe** [comment]
While the standard way to do alpha blending is in the linear space, assuming you've made this change because you think it looks better with alpha blending in the sRGB space I dont see much of a problem. Care should be taken if you find yourself blending many layers as that could result compounding the error due to using sRGB.

After a cursory look the only thing I noticed was that you manually convert from linear to sRGB in your fragment shaders return. This should be avoided. Since you are using GL_FRAMEBUFFER_SRGB and GL_SRGB texture formats the conversion back to SRGB "should" be done automatically, and may be adding extraneous gamma since opengl expects linear output from shaders. Unfortunately I dont have a dev environment or time to test this out.

Awesome job on implementing this so quickly!

**Comment by Tom94** [comment]
I am _not_ using GL_FRAMEBUFFER_SRGB for the reason, that GL_FRAMEBUFFER_SRGB does alpha blending prior to converting back to sRGB. I don't see a nicer alternative to converting manually back to sRGB in the shaders unfortunately. Tried a while to hack it to work with GL_FRAMEBUFFER_SRGB by raising the alpha to the gamma an additional time, but that didn't work in some edge cases.

**Comment by Tom94** [comment]
I'd much appreciate a nicer alternative in case you have some suggestions. :)

**Comment by kkartaltepe** [comment]
Doh, I saw the glEnable when browsing the commits but missed it being taken out in a later one!
