### ISSUE TITLE
Base UI components that need implementing

### ISSUE THREAD

**Issue by SirCmpwn** [ppy/osu-framework#250]
* [x] Sliderbars
  * [x] Basics
  * [x] Style
* [x] Checkboxes
  * [x] Basics
  * [x] Style
* [x] Dropboxes (#277)
* [x] Password text box

**Comment by Tom94** [comment]
Just a quick comment for those tackling these:

When implementing these things (sliderbars in particular) make sure to do it in a way that is general, i.e. works if your sliderbar is transformed by some arbitrary matrix. Just work in local or in parent-space coordinates to do that (see how `Container.Contains(Vector2 position)` is implemented as an example).

**Comment by UselessToucan** [comment]
> Dropboxes

I'm going to implement it in the Game repo after merging [FilteringSearchList](https://github.com/ppy/osu/pull/101)(It will store dropbox items and handle selection).
If we need basic UI element in the framework, I can add it. Do we need it?

**Comment by NeoAdonis** [comment]
[Already working on Dropboxes.](/NeoAdonis/osu-framework/tree/dropdown) IMO implementation is almost complete, and functional to a high degree. You would like to check it out, though, to see if it needs something else.

**Comment by Tom94** [comment]
We have dropboxes and sliderbars now. Also, peppy styled checkboxes.

**Comment by Tom94** [comment]
Done now.
