### ISSUE TITLE
Switching the keyboard language makes you unable to type in any textbox

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-framework#2525]
- Type some stuff in any textbox
- Switch language (no matter how many times) **(using Win + Space)**
- You can't type anymore (switching back doesn't help)

Tested on Win 10 1903 (buld 18362.145) with English/Russian languages.

**Comment by huoyaoyuan** [comment]
Also hitting this.
Only reproduces if you switch using Win+Space. Click on task bar switches successfully.

**Comment by huoyaoyuan** [comment]
Tested with #3013, SDL does not have this issue.

**Comment by Joehuu** [comment]
Seems to have regressed in 2020.609.0, probably in https://github.com/ppy/osu-framework/pull/3494.

**Comment by Susko3** [comment]
This is an issues with SDL: https://github.com/libsdl-org/SDL/issues/4369

**Comment by Susko3** [comment]
This issue is fixed in SDL with commit https://github.com/libsdl-org/SDL/commit/3b85e3fdfce01c528a6ebf9ac537bdc106ba4963
