### ISSUE TITLE
Pressing space in osu! Direct search does not move cursor.

### ISSUE THREAD

**Issue by Astatine69** [ppy/osu-framework#2526]
When searching for a map in the osu direct menu, pressing space does not make the cursor move making it appear like space was not pressed. 

Video: https://drive.google.com/open?id=1uH2S9KPPFDoh2vlsNVSwQCfACDH_0IPC

osu!lazer version: 2019.608.0 iOS

**Comment by Astatine69** [comment]
This is done with the stock iOS keyboard, I just have a skin tweak which doesn’t effect the usability.

**Comment by peppy** [comment]
Not important (since @swoolcock has confirmed) but that is not the stock keyboard.
