### ISSUE TITLE
ModelBackedDrawable seem to load while off-screen in a scroll container

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2528]
They should not load when offscreen but seem to be. Seen in `UpdateableCoverBackground` (osu!) when modified to be a `ModelBackedDrawable`.

**Comment by peppy** [comment]
Can't seem to reproduce this. @smoogipoo do you remember how/why this exists?

**Comment by smoogipoo** [comment]
Yeah this doesn't seem replicable anymore. I'm pretty sure the replication case was multiplayer lounge.
