### ISSUE TITLE
overriding with early returns

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#256]
Looking to see people's preference for implementing the scenario where a base.Implementation exits early (and thus anything deriving from it should also). Quite a common scenario. Two solutions come to mind with different pros/cons which should be readily visible.

solution 1:

```
Subclass : BaseClass
{
    protected override bool UpdateState(State state)
    {
        if (!base.UpdateState(state)) return; //required in every override

        //do stuff
    }
}

BaseClass
{
    protected virtual bool UpdateState(State state)
    {
        if (state == this.state)
            return; //early exit
    }
}
```

solution 2:

```
Subclass : BaseClass
{
    protected override void OnUpdateState(State state)
    {
        //do stuff
    }
}

BaseClass
{
    protected void UpdateState(State state)
    {
        if (state == this.state)
            return; //early exit

        OnUpdateState(state);
    }
}
```

**Comment by SirCmpwn** [comment]
2 seems like it would result in less code written in the long run. Would a better solution be to provide an interface to expose that state to the caller of UpdateState? Damned if we do, damned if we don't here.

**Comment by Tom94** [comment]
I prefer 2 as it's less susceptible to programmer error.

**Comment by peppy** [comment]
See decision in https://github.com/ppy/osu-framework/issues/22.
