### ISSUE TITLE
InputKey.MouseButton1 is misleading

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#2575]
It maps to M4 on the mouse, the first "extra mouse button". Should consider starting the extra buttons at `MouseButton4`.

**Comment by UselessToucan** [comment]
I suggest to consider adding suffix. Something like `ExtraMouseButton1`.

**Comment by peppy** [comment]
I agree with prefix. Starting from 4 is also a bit ambiguous.
