### ISSUE TITLE
Move ability to reset Anchor/Origin for each Child from TextFlowContainer to FillFlowContainer

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-framework#2582]

**Comment by UselessToucan** [comment]
Motivation? Can you provide any use cases where this will be useful?

**Comment by EVAST9919** [comment]
Well, it's simple. If we have a lot of objects with not default anchor/origin it'd be useful. But may be it's not worth it, because there not so much cases

**Comment by peppy** [comment]
Do you mean from a code quality perspective? So it isn't required in each child specification?

**Comment by EVAST9919** [comment]
Closing as not needed (even I don't remember why do I propose it)
