### ISSUE TITLE
Adding secondary taps/right-clicks to mobile

### ISSUE THREAD

**Issue by nobbele** [ppy/osu-framework#2596]
Makings taps while holding act as clicks without changing mouse position would allow lazer to implement the same streaming functionality as osu!droid had. [osu!droid streaming video](https://www.youtube.com/watch?v=2UfHNA0xhnY)

**Comment by smoogipoo** [comment]
This is not really osu!framework-related, and there's already a few osu!-side issues for this (https://github.com/ppy/osu/issues/4201, https://github.com/ppy/osu/issues/4195).
