### ISSUE TITLE
Implement l10n

### ISSUE THREAD

**Issue by ddevault** [ppy/osu-framework#261]
suggested: https://github.com/neris/NGettext

**Comment by SirCmpwn** [comment]
Some discussion is needed on a few things:

How to re-localize things like `protected override string Header => "Devices";` on the fly when the user changes the locale at runtime?

How to re-localize things at runtime anyway?

How to localize things like `protected override string Header => "Devices";` in the first place without the l10n catalog being a global singleton?

Pulling strings out to localize with gettext will require the use of a tool like xgettext, which should be portable but might want to be integrated into the build process.

Something to note: if we use gettext, we don't have to worry about using @"strings", we can just use normal strings and it'll detect the call to gettext and treat the string as localizable.

**Comment by FreezyLemon** [comment]
Seeing as a `LocalisationEngine` exists already, I tried implementing this (and got a very basic localisation working already), but I still have some questions:
1. Where should the translations be stored? In osu.Resources/Localisation would be fine, right?
2. How should they be stored? I suppose `<locale>.json` would work, with a dictionary-like style of storing the translations.
3. Should the english text just stay in code as a "default", or should it be replaced by a placeholder and then localised via en-gb?

**Comment by peppy** [comment]
1. They can be stored as resources in `osu-resources`, yes.
2 We probably want to share localisations with osu-web where possible, so a json format would be recommended. Make sure to check out how it's structured over there so we can follow the same layout if possible.
3. check osu-web. probably just use it as default to start with.

**Comment by FreezyLemon** [comment]
The topic just came up in the Discord `osu-web` channel, and the question was about moving to gettext.
If we want to properly share localisation files with osu-web, a few things have to be discussed:

#### Universal standards for "localisation keys"
Currently, the osu-web translations are structured with the website in mind, which probably wouldn't work too well with lazer. Maybe the files have to be rearranged in a way that allows proper sharing between the two.
Also, depending on the tool that gets used, the files might look very different. `gettext` for example will include the english translation of the text in code, and then find the proper translation through files. The current system is that of a dictionary-type lookup, which will not have any real text in code.

#### The lazer-side implementation
Seeing as osu-web will most definitely use a third-party tool for this, the two things that come up will be a) what tool will it be? and b) do we use the same thing for lazer? What I mean by (b) is that the framework supplies most of what we need to build our own system for this. A lot of the "framework" for localisation already exists, we just need to decide on naming conventions for files and especially locales (folders).

**Comment by peppy** [comment]
Should be safe to close this one, with the recent refactor (https://github.com/ppy/osu-framework/pull/3157).
