### ISSUE TITLE
DrawVisualizer won't let you select some Elements

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu-framework#2621]
Images to show which ones I tried.
![wat](https://user-images.githubusercontent.com/27222621/60498078-3cd3b880-9cb6-11e9-87d6-801c246be28b.png)
![wat](https://user-images.githubusercontent.com/27222621/60498114-4ceb9800-9cb6-11e9-81e8-5266cfbd6f71.png)
![wat](https://user-images.githubusercontent.com/27222621/60498164-6260c200-9cb6-11e9-8ec7-a5f287b79320.png)
![wat](https://user-images.githubusercontent.com/27222621/60498027-27f72500-9cb6-11e9-8f1a-95222a4cc0a6.png)
![wat](https://user-images.githubusercontent.com/27222621/60498313-a48a0380-9cb6-11e9-8f29-e63549ced9dc.png)
The last one is the weirdest. While it won't let me select the sprite for the length icon (and the rotated square as shown in that image) it does work for all the other ones...

**Comment by Aergwyn** [comment]
What I just now noticed... for the case of the second image (background of the FilterControl) it matters where you click. Even if it's highlighted if another element seems to be in front of it you can't select it.

**Comment by peppy** [comment]
I think @smoogipoo can explain this one better than I can. We had a discussion about this recently and I think there is room for improvement, but it may not be straightforward.

**Comment by peppy** [comment]
Can reproduce in `TestSceneTabControl` by attempting to target a tab.

**Comment by smoogipoo** [comment]
Resolved by https://github.com/ppy/osu-framework/pull/2763
