### ISSUE TITLE
Proposal for bindable clock that monitors time ranges

### ISSUE THREAD

**Issue by swoolcock** [ppy/osu-framework#2693]
We have a requirement in osu! to know when gameplay is currently within a break, for updating the visibility of the leaderboard.  https://github.com/ppy/osu/pull/5446

I propose we create a clock that can define time ranges and provide a bindable that monitors which time range the clock is currently positioned in.

Pseudo-definition:

```
public class BindableClock<T> : IClock
{
    public readonly Bindable<ClockRange<T>> CurrentRange = new Bindable<ClockRange<T>>();

    private readonly List<ClockRange<T>> clockRanges = new List<ClockRange<T>>();

    public void AddClockRange(double startTime, double endTime, T data) => clockRanges.Add(new ClockRange<T> { StartTime = startTime, EndTime = endTime, Data = data });
    
    // TODO: on update clock, check to see if the current time is within a different range, and update the CurrentRange bindable
}

public struct ClockRange<T>
{
    double StartTime;
    double EndTime;
    T Data;
}
```

Pseudo-usage, probably within `BreakOverlay`:

```
// create a new bindable clock with a source clock
BindableClock bindableClock = new BindableClock(gameplayClock);

// add ranges (for example, beatmap breaks) - may need to use weak references
foreach (var break in breaks)
    bindableClock.AddClockRange(break.StartTime, break.EndTime, break);

// use the bindable
bindableClock.CurrentRange.ValueChanged += e =>
{
    // we've entered or exited break time in a beatmap
};
```

**Comment by peppy** [comment]
I'd just implement it locally. Seems like a very rare use-case.

**Comment by swoolcock** [comment]
That's going to require a check every frame then to update the leaderboard UI if we've entered or left a break period.  I was hoping we could do that part through a bindable, even it meant introducing a new bindable class that essentially does the same thing.

I just wanted to get your thoughts in a proposal before doing any work on it, so all good. 👍

**Comment by peppy** [comment]
It can be done via a bindable exposed by `BreakOverlay`.

**Comment by swoolcock** [comment]
We would need to check the current clock time every frame then to see if we need to update the bindable.  Is this acceptable?

**Comment by peppy** [comment]
Would need to see implementation to comment on that. The important part is that it's done internally in `BreakOverlay`.
