### ISSUE TITLE
BufferedContainer always creates 3 framebuffers when it doesn't need to

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2695]
In the case blur is not being used, two can be avoided. This is a huge waste of memory.

**Comment by smoogipoo** [comment]
It is but I also missed that it isn't initialising them until they're used, so it isn't all that bad. You'd need to be wary of that with your changes though.

**Comment by peppy** [comment]
Aha, I see. Seems like that may be a regression then, as the underlying textures are being requested regardless.

**Comment by smoogipoo** [comment]
Closing this as this is not the case anymore - textures are only requested on bind, at which point the blur will be drawn.
