### ISSUE TITLE
MIDI input support

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [ppy/osu-framework#2723]
osu!framework should support taking input from MIDI devices such as digital pianos.

ManagedBass seems to have support for taking MIDI input, but this isn't included in its NuGet package since it is not compatible with some platforms. NAudio supports taking MIDI input (which I have previously implemented in a fork [here](https://github.com/HoLLy-HaCKeR/osu-framework/commit/3b184bb3c2d8eae477b28c8f6c9a35f4d0a92ff1)) but I don't know if this is cross-platform.

See also ppy/osu#4328 and ManagedBass/ManagedBass#54.

**Comment by peppy** [comment]
bass add ons are fulfilled by optional nuget packages, so there will be a matching one (https://www.nuget.org/packages/ManagedBass.Midi/)

**Comment by HoLLy-HaCKeR** [comment]
The ManagedBass.Midi package does not have support for taking MIDI input, which is why I opened ManagedBass/ManagedBass#54. It is filtered out in the NuGet builds using compiler directives.
