### ISSUE TITLE
Numlock is not considered for keyboard input

### ISSUE THREAD

**Issue by Xelostar** [ppy/osu-framework#2728]
**Describe the bug:** 
I use a seperate numpad for clicking as controls. However, it seems the numlock is completely ingored. As a result, I can only use the numbers as they are as input and I can't use the arrow keys on it for selecting maps. I usually have clicking set to "End" and "Arrow down", but in Lazer it can only be "1" and "2".

**Screenshots or videos showing encountered issue:** 
https://imgur.com/trLhs7H

**osu!lazer version:** 
2019.730.0

**Logs:** 
Runtime log (not really useful, but the only one that seemed somewhat logical):
https://pastebin.com/kgju6rGF

**Comment by Joehuu** [comment]
Seems to fixed in https://github.com/ppy/osu-framework/pull/3892 / https://github.com/ppy/osuTK/pull/67 for osuTK. In SDL though, when numlock is disabled, arrows work as expected but end, page down, key 5 that doesn't have a secondary input, home and page up still inputs 1,3,5,7,9.

**Comment by bdach** [comment]
@Joehuu how are you testing this? I can't seem to get arrows working with opentk either, but that might possibly be due to linux things.

**Comment by Joehuu** [comment]
I've tested on Windows in that comment. In Ubuntu, numlock is still ignored on both.
