### ISSUE TITLE
Raw Input makes mouse extremely fast or slow

### ISSUE THREAD

**Issue by Groctel** [ppy/osu-framework#2745]
**Describe the bug:** Rnabling raw input makes the mouse go extremely fast or slow if its speed is other than 1.0. The slider becomes unusable due to extremely low mouse speed if it's lower than 1.0 and the mouse travels from corner to corner at the slightest move if it's higher than 1.0. [Here's a video](https://www.youtube.com/watch?v=XKL6LKRwvPE).

**osu!lazer version:** 2019.809.0

**My system:**
- 5.2.7-arch1-1-ARCH #1 SMP PREEMPT Wed Aug 7 02:00:26 UTC 2019 x86_64 GNU/Linux
- Using i3-gaps with nvidia-xrun to properly use the nvidia card
  - The same happens on an intel-only session

**Comment by l3lackShark** [comment]
Duplicate of [this](https://github.com/ppy/osu/issues/5662) and [this](https://github.com/ppy/osu/issues/3489)?

**Comment by Groctel** [comment]
Oh, yes. I missed it, sorry :(
