### ISSUE TITLE
Joystick input seems broken on Linux

### ISSUE THREAD

**Issue by abbradar** [ppy/osu-framework#2752]
I have a HORI Taiko drum controller attached. [sdl2-jstest](https://gitlab.com/sdl-jstest/sdl-jstest) shows that buttons are working properly (I see a button activation on each drum press). In osu! it seems to work _randomly_ - that is, most presses don't do anything but sometimes they work. However, when I press and hold the button it works with some delay. My first feel was that osu! had some kind of `pollJoystickButtons` in the input loop which queries current joystick buttons pressed, and due to low frequency of the loop it misses my presses unless I hold the button long enough for the next poll to happen. However it doesn't seem to be the case as `input` frequency is shown to be 1000 Hz, which should obviously be fast enough.

I'm happy to help testing and even try fixing this by myself (I have .NET Core experience) given someone points me out in the right direction.

**Comment by jai-x** [comment]
The majority of Joystick input handling code was added in this PR: https://github.com/ppy/osu-framework/pull/1494/files, so maybe poke around in those files first.

If you find it's a more lower level issue with how SDL2 is being polled, you may need to check how it is implemented in our OpenTK fork found here: https://github.com/ppy/osuTK/tree/master/src/osuTK/Input

I don't know that much about the input handling but I hope that helps.
