### ISSUE TITLE
Sample channels with 0 frequencies do not function as intended

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#2760]
Sample channels with adjusted frequency to 0 should stop the played channel until the frequency has changed, but it seems that BASS only supports frequencies from 100Hz to 100000Hz only, 0 is the original rate of the channel, unsure if there's a way around it but there is a way to potentially fix that by setting channel volume to 0, but is actually a hacky way

**Comment by iiSaLMaN** [comment]
Another way this can be done which seems better for a workaround is to pause the channel and resume it on frequency changes (probably `OnStateChanged`)

**Comment by peppy** [comment]
If this is to be corrected for, it should be local to bass components. I'm not sure how straightforward this would be to do (probably maintaining an internal pause state).

**Comment by iiSaLMaN** [comment]
> If this is to be corrected for, it should be local to bass components. I'm not sure how straightforward this would be to do (probably maintaining an internal pause state).

I believe that's what I said above, pausing on 0 frequency.
