### ISSUE TITLE
Rendering freezes on iOS...... again?

### ISSUE THREAD

**Issue by fxzjshm** [ppy/osu-framework#2773]
(Sorry for my poor English)
It's the same phenomenon as #2049 described. 
I think this time it is related to this framwork, but I'm not sure.

Video: [VID_20190816_1656460000-2140.mp4](https://raw.githubusercontent.com/fxzjshm/Resources-Container/master/VID_20190816_1656460000-2140.mp4)
(The original link has run out of quota and it costed me 0.03 USD)

### How I Reproduce:
1) Open osu!lazer, I tested on 2019.813.1
2) Click "play" -> "solo".
3) Click the Home button on the device.
4) Wait until the music disappears. (Don't know if it is related.)
5) Re-open osu!lazer
6) Freeze! (About 60%-80% chance on my device.)

**Note** that when recording the screen, the freeze haven't happed during my test.

### Test Environment:
osu!lazer 2019.813.1
iPad mini 4 running iOS 12.3.1

Don't know how to get the debug log...... Sorry

**Comment by smoogipoo** [comment]
Needs further investigation, but this might be the app being in a crashed state due to us not handling `applicationDidEnterBackground:`. Can't replicate it locally though.

**Comment by fxzjshm** [comment]
This should have been fixed by #3321 (Confirmed on the device in the video)
Thanks!
