### ISSUE TITLE
Drawable.Handle does not get called for custom UIEvents

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [ppy/osu-framework#2792]
`Drawable.TriggerEvent(UIEvent)` will run the UIEvent through a switch case and call the relevant method which will in turn call `Drawable.Handle(UIEvent)`. The default case of the switch statement will simply return false without calling Handle. This causes custom UIEvents to never reach the Handle method.

**Comment by UselessToucan** [comment]
What is custom UIEvent?
