### ISSUE TITLE
TabControl's Items are inconsistent when accessed after set

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2813]
```chsarp
TabControl.AddItem(a);
TabControl.AddItem(b);

TabControl.Items.Count() // will be zero if an update has not yet run
```

We need to decouple the retrieval of items from requiring the drawable components to be in an updated state (or force such an update).

**Comment by iiSaLMaN** [comment]
What is your opinion in adding a new `AliveFlowingChildren` property ordering by `AliveInternalChildren` and make our current `FlowingChildren` order by `InternalChildren`? 

Might be a breaking change though.

**Comment by bdach** [comment]
That honestly just sounds confusing to me. What would the difference be? It feels really nebulous and not friendly to use at all.
