### ISSUE TITLE
Default audio device on Linux is empty

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [ppy/osu-framework#2827]
When the framework.ini config file gets generated on my system, the AudioDevice property is empty. To get working audio output I have to set it in osu!lazer and copy from its config (where it will then be `AudioDevice = PulseAudio Sound Server`).

I'm not sure if this is just a configuration issue on my system or something that should be addressed in the framework. I'm using a mostly fresh installation of [Pop!_OS](https://system76.com/pop) (derivative of Ubuntu).

Empty config value would look like this:
```
...
LastDisplayDevice = First
AudioDevice =
VolumeUniversal = 1.0
...
```

**Comment by UselessToucan** [comment]
Did you read the code?
1. This setting is [explicitly set to `string.Empty`.](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Configuration/FrameworkConfigManager.cs#L30)
2. According to `AudioManager.AudioDevice` [comment](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Audio/AudioManager.cs#L56), `string.Empty` is a valid value.

**Comment by HoLLy-HaCKeR** [comment]
It's most likely a configuration issue on my end as other programs have also had trouble with the default audio device. I'll close this for now and re-open it when I've done some proper testing and am sure it's a framework-related issue.
