### ISSUE TITLE
Image colour profiles may be handled incorrectly

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu-framework#2835]
Affected beatmapset: https://osu.ppy.sh/beatmapsets/1037591

![image](https://user-images.githubusercontent.com/20495991/64964950-aa16e300-d8ce-11e9-8788-c806492922f1.png)

Source image:
![enty](https://user-images.githubusercontent.com/20495991/64964986-b9962c00-d8ce-11e9-9b3b-39c0e6e61428.jpg)

Device: Windows 10 64-bit / AMD Radeon(TM) R7 Graphics

**Comment by peppy** [comment]
![image](https://user-images.githubusercontent.com/191335/64965311-ba7f8b80-d8d7-11e9-9d8c-9ae970732fac.png)

Probably relevant.

**Comment by HoLLy-HaCKeR** [comment]
My image viewer reports an error when I try to view its colorspace, it's probably just a bad file.

**Comment by peppy** [comment]
Closing for now as image seems to have an undefined / broken colour profile.
