### ISSUE TITLE
Appveyor never ending on dependency missing exception

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2845]
https://ci.appveyor.com/project/peppy/osu/builds/27515841

**Comment by smoogipoo** [comment]
May be fixed via #2841, requires testing.

**Comment by smoogipoo** [comment]
There's been a few fixes over time that have potentially fixed this issue. This may have been fixed by either the referenced PR or by https://github.com/ppy/osu-framework/pull/3061. I'm going to close it for now until it comes up again.
