### ISSUE TITLE
KeyBindingContainer throws AssertionExceptions in some scenarios

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu-framework#2850]
Getting _seemingly_ random AssertionExceptions regarding `KeyBindingContainer`.

Video of reproduction: https://streamable.com/gqato
Repository for reproduction: https://github.com/HoutarouOreki/InputCrashOsuFramework

Currently encountering this in TestBrowser, but it also came up in normal use in the past.
Steps to reproduce:
- hold down a key
- hover over something that has higher input priority
- release the key while hovering over that
- press another key back in the same place the first key was pressed
- crash happens when releasing the second key

I first tried to reproduce this with `OnKeyDown` and `OnKeyUp` but that resulted in no exceptions (even though it also didn't register key release) - happens only with `KeyBindingContainer`.

**Comment by smoogipoo** [comment]
This is fixed by https://github.com/ppy/osu-framework/pull/3193 . Please test that with any other project where you have encountered the issue and let us know if it still happens / provide an updated reproduction case.

**Comment by HoutarouOreki** [comment]
Sadly I haven't stored any other reproduction cases / configurations where it was happening, since it happened randomly around 5-6 times in a span of about a year before I pinpointed it in the provided reproduction case. I haven't encountered it anywhere since.
