### ISSUE TITLE
Key.Unkown desyncs the cursor in textboxes.

### ISSUE THREAD

**Issue by miterosan** [ppy/osu-framework#2852]
When the key "Key.Unkown" is raised from one of the keyboardinput implementations, the textboxes desync their cursor position.

**Comment by peppy** [comment]
Please provide a reproduction of where `Key.Unknown` can be triggered. If not, removing it may be a valid option.

**Comment by miterosan** [comment]
this issue can be closed, as all implementations of the keyboardhandler do not fire Key.Unknown.
