### ISSUE TITLE
Framework can't handle left and right trigger (LT and RT) on joystick

### ISSUE THREAD

**Issue by GSculerlor** [ppy/osu-framework#2854]
https://streamable.com/760vg

**Framework ver**: 2019.921.0
**Joystick used**: Xbox 360 Controller (Wireless) and Rexus Gladius GX2 (Wired)

**Comment by Jeremiidesu** [comment]
I think I found a way (on the latest master) to work around this problem.

The Xbox 360 controller I use (Wired), has LT and RT on axes 2 and 5 (AX3 and AX6 on the visual test scene). Plugging the controller or running the visual tests with the triggered **half-pressed** (not completely pressed, nor completely released) allows the visual tests to properly display pressed or release states. 

The main issue is that the values for the triggers go from -1 (completely released) to 1 (completely pressed down), causing the deadzone calculation to erroneously set the trigger deadzone to ~1.05 at line 223 here:

https://github.com/ppy/osu-framework/blob/b169c45c13e7cdc45b93f165d42ce23be4c028d5/osu.Framework/Input/Handlers/Joystick/OsuTKJoystickHandler.cs#L210-L225

Temporarily removing `axisValue +` from line 223 also solves the problem, with triggers being properly detected as axes as shown in the following screenshot: 

![LT and RT correctly displayed in AX3 and AX6 while the HTML5 Gamepad Tester reports B6 and B7, the triggers, as completely pressed](https://cdn.platea.moe/Jeremii/2020/05/brave_IbsRDutbXg.png)

Releasing the triggers turns the AX3 and AX6 squares red.

**Comment by peppy** [comment]
This should now be resolved via #3900 (with `--sdl` enabled). Going to tentatively close - please comment if you have an issue with a specific controller.
