### ISSUE TITLE
Proposal: better buttons

### ISSUE THREAD

**Issue by SirCmpwn** [ppy/osu-framework#286]
Buttons should be containers that support arbitrary children. ToolbarButton and SidebarButton (being introduced in the options PR on osu) can then use them.

**Comment by peppy** [comment]
so clickablecontainer?

**Comment by SirCmpwn** [comment]
Yes, with the semitransparent background and animations on hover/click.

**Comment by Tom94** [comment]
We have pretty good buttons now.
