### ISSUE TITLE
USB input device support in Android

### ISSUE THREAD

**Issue by DanielSvindseth** [ppy/osu-framework#2863]
Android Runs on a lot of devices, also tablets. Mouse support would mean a better experience more similar to those on traditional desktops and laptops.

Currently you can use a mouse but have to hold down M1 to move the in-game cursor, while disabeling mouse buttons (F10). A captured mouse pointer would be awesome.

**Proposal designs of the feature:** 

Since android O, `requestPointerCapture()` is able to capture the mouse-pointer like traditional platforms so a feature implementation would likely use this function.

EDIT: link to android developer about the function described: https://developer.android.com/training/gestures/movement#request_pointer_capture

- [x] Mouse support – https://github.com/ppy/osu-framework/pull/4989
- [ ] Joystick support – https://github.com/ppy/osu/discussions/18856

**Comment by bdach** [comment]
Expanding scope to cover other potential currently unsupported USB devices (although mice/tablets are the primary ones to handle)

**Comment by swoolcock** [comment]
This is less Android-specific now that iOS supports third party controllers.

**Comment by frenzibyte** [comment]
Mouse support for Android is already in place here (which should cover tablet as well using pointer capture feature). @bdach anything else left to track here?
