### ISSUE TITLE
Lazer crashes on big black, on SS replays on hard maps sometimes it shows that they got a good (100) when they didn't, and sometimes osu lazer breaks where you can't play the game. (mobile issues)

### ISSUE THREAD

**Issue by aryamanv** [ppy/osu-framework#2892]
so i don't have any pictures because this was on mobile and it was night and i was tired, but all of this is true sometimes on SS replays (hard maps) shows a good, meh or miss instead of great and on results it shows the still got a SS and no goods, mehs, or miss. And on big black and probably other high circle and slider count beatmaps, it crashes. The game is unresponsive, but the music is still playing.

**Comment by bdach** [comment]
1. This is the wrong repository to report lazer issues, this one pertains to the framework specifically.
2. Please keep issues focused in scope to one problem at a time.
3. The replay discrepancy is a known issue (see ppy/osu#5514).
4. Performance is a constant work-in-progress, but is not an immediate focus.

Closing on all above counts. Please think twice before opening issues and use the search functionality and issue tags.
