### ISSUE TITLE
Video playback starts early after beatmap loads

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu-framework#2894]
Video usually waits for the song to play so that it could be played at the same time. In lazer, this is not being followed correctly as stable does.

**Lazer:**
https://youtu.be/GfhO5y7tL6Q
**Stable:**
https://youtu.be/PBcag-GJmQU

**Comment by smoogipoo** [comment]
Duplicate of ppy/osu#6101. Also wrong repository.
