### ISSUE TITLE
Proposal: remove depth

### ISSUE THREAD

**Issue by SirCmpwn** [ppy/osu-framework#290]

**Comment by peppy** [comment]
at very least let's consider making Depth an int.

**Comment by Tom94** [comment]
We discussed this last weekend and came to the conclusion that depth is a too valuable tool to drop for now. Not only the convenience of automatic ordering of drawables, but also the fact that it serves as a key to find drawables in logarithmic time, which we would need an artificial substitute for if we were to drop depth.
