### ISSUE TITLE
Ensure consistent initial state in manual input visual test cases

### ISSUE THREAD

**Issue by bdach** [ppy/osu-framework#2909]
Running test cases which use manual input inside the visual test browser is susceptible to state pollution. This is especially pertinent in the case of mouse input, wherein the pre-existing mouse position within the test area can affect test execution, if the test author doesn't set the position explicitly themselves.

[Here's a video with an example.](https://streamable.com/d732k) I'm running the same test twice; once I purposefully (but might as well have accidentally) move the mouse over the test area, which then stays the same throughout the test, and once I make extra care not to do that, which makes the mouse stay at (0,0). This affects the outcome of the test - first case is a pass, the second is a fail.

I think this is an asterisk that doesn't need to be there - these sort of issues lead to devs running tests locally, seeing them pass, but then fail at CI time for not entirely clear reasons. Making sure there's a set initial state when using manual test input ensures consistent testcase execution and reduces chances of test interference.

I think mouse position is going to be the major and possibly only case here, as all of the other cases are probably less likely, but I haven't tested for sure.

**Comment by peppy** [comment]
This looks really weird. Tests are supposed to isolate input (see the "local" "test" buttons top-right) and it looks to be set to the correct isolation level here. I think the capturing/isolating may not be occurring due to the game context in the test you're testing with? ie. because that test is making an `OsuGame` which has its own `UserInputManager`

**Comment by iiSaLMaN** [comment]
I believe this is not really an issue anymore, unless i'm missing something?

**Comment by peppy** [comment]
I believe it should still be reproducible, but it would be nice to have a solid reproduction case.. @bdach happen to know what was causing the issue in your case? it looks like it could be that the window was considered non-active in the last run of your video?

**Comment by bdach** [comment]
I'm pretty sure it is still reproducible, yes, and it's not exclusive to scenes with nested input managers either. However I think it's (somewhat) easily fixable.

The default behaviour for manual input test scenes is to preserve any prior mouse position:

https://github.com/ppy/osu-framework/blob/77488e39f9dbf66a35f4161305a2e42c6937963a/osu.Framework/Testing/ManualInputManagerTestScene.cs#L24-L28

It's not a great default in my opinion and something better should be used instead (obvious candidate is `Vector2(0)`). I'd even advocate for entirely removing the `null` case for preserving prior position to guarantee independence and consistency of test case execution.

The worse part of this is that if a test scene inheriting `ManualInputManagerTestScene` has its own `[SetUp]` logic and doesn't call the base when overriding, the initial position won't be applied, which means manual review is required to catch such cases for now. It's yet another thing it would be helpful to have an analyzer for.
