### ISSUE TITLE
Overall performance regression

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2916]
I regularly test update frame performance at the osu! menu screen. It seems we have regressed roughly 50% over the last 3 months

2019-07-16: 
![image](https://user-images.githubusercontent.com/191335/67209951-35960d80-f453-11e9-9eb3-0bb2fd17587d.png)

2019-10-21:
![image](https://user-images.githubusercontent.com/191335/67209995-4ba3ce00-f453-11e9-9630-1cd15cce1b9c.png)

Requires further investigation / bisecting. Maybe a good time to automate this to some extent.

**Comment by UselessToucan** [comment]
> 2019-07-16:
> 2019-10-21:

Do you remember concrete commits?

**Comment by peppy** [comment]
those are release builds, so the closest tagged release to each.

**Comment by Itsyuka** [comment]
I've noticed this as well, this is most likely an issue with the intros, switching from circles to triangles has a large performance impact.

**Comment by peppy** [comment]
Thanks for the information, it looks like you may be on to something.

**Comment by peppy** [comment]
Resolved via osu!-side fix (https://github.com/ppy/osu/pull/6644).
