### ISSUE TITLE
Append to previous logs if existing

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu-framework#2919]
This would be helpful for people who have crashed the game but unaware-ly re-run the game without saving the logs. Appending to previous existing logs may help to catch the cause of their crash without having an empty log overwritten from a re-run.

**Comment by bdach** [comment]
This is a bit of a can of worms - simply appending might eat up a bit of space after a while. Having separate timestamped logs per execution with some kind of rotation policy could be nice, but makes things more complicated overall (and that includes support, too - getting people to upload logs is hard enough, worse yet when they have to guess which ones).

We also have sentry osu!-side - which is sometimes worse as the error is given with not much relevant context at times, but for simple enough cases it works fine.

**Comment by peppy** [comment]
Crashes should be reported / handled correctly, not rely on log submission.
