### ISSUE TITLE
Mouse issue (Linux on ChromeOS)

### ISSUE THREAD

**Issue by X4X5** [ppy/osu-framework#2942]
After opening Lazer, and the intro is done, the mouse won't do anything. I clicked on the osu! logo to get started with the game, but the mouse was unresponsive, meaning, the mouse can still move. But when I click, the cursor doesn't change color. It doesn't actually click on anything at all.

(runtime.log file from the terminal): https://docs.google.com/document/d/1HWRxGtwR3rL-PVrtV0_VyRuzLuAyTlcoQhs3gs0InXo/edit?usp=sharing

Version: 2019.1029.0

Input device: USB mouse

**Comment by bdach** [comment]
Going to go out on a limb and say this might very well have something to do with the ChromeOS-Linux compatibility layer, which will most likely make this very hard to reproduce and root-cause without owning the actual hardware.

**Comment by X4X5** [comment]
Weird case scenario, I updated the system, not the game, and the mouse started to work properly? Still closing this, however, as it hasn't really happened a second time in the last day or so since I opened this
