### ISSUE TITLE
Getting wrong input (probably encoding) from IME

### ISSUE THREAD

**Issue by huoyaoyuan** [ppy/osu-framework#2945]
Please test this carefully when #2525 is open. Always use mouse to toggle IME.

My system information:
Windows 10 Pro 18362.449
System display language: Simlified Chinese
Installed language: Simlified Chinese(PRC), English(US), Japanese
System codepage: 65001 (type `chcp` in cmd to confirm)

#### Simplified Chinese:
System draws an IME window (in poor quality)
![image](https://user-images.githubusercontent.com/5644458/68089064-2cb82980-fea0-11e9-8816-43108ccffeec.png)
![image](https://user-images.githubusercontent.com/5644458/68089084-53766000-fea0-11e9-82c6-135f6ea07c5a.png)
#### Japanese:
No IME window drawn. After typing something and press 1, something get selected and inputed into window, but obvioursly what I typed.
![image](https://user-images.githubusercontent.com/5644458/68089120-b4059d00-fea0-11e9-9715-5d8b1baf3812.png)

Visible characters in both scenario are korean characters that looks uncommon.

**Comment by smoogipoo** [comment]
Would be good if we can avoid drawing an IME window altogether, and completely handle it at osu!framework side. That said, IME is a whole mess which is not likely to be implemented before we move to Veldrid/SDL.

**Comment by huoyaoyuan** [comment]
After investigation, `osuTK.KeyPressEventArgs.KeyChar` returns the erroneous value. Nothing to do now since we are going to remove it.

**Comment by huoyaoyuan** [comment]
Tested with #3013, SDL does not have this issue. But is doesn't draw Chinese IME, like Japanese.

**Comment by Susko3** [comment]
@huoyaoyuan could you test with https://github.com/ppy/osu-framework/pull/4907.
Framework doesn't include CJK fonts, so you may need to copy over from osu-resources, or build osu! with framework changes.
