### ISSUE TITLE
Completed tasks will run a second time in Scheduler

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#2967]
```csharp

var scheduledHide = Scheduler.AddDelayed(() => currentScreen.Hide(), TournamentScreen.FADE_DELAY);

scheduledHide.RunTask();
```

This will run the task twice, as there is no `Completed` check in scheduler. When fixing this, special care should be taken for repeating tasks, which likely should clear their `Completed` status on reschedule.

**Comment by iiSaLMaN** [comment]
Should an exception be thrown if `RunTask()` is invoked but `Completed` flag is set?

**Comment by peppy** [comment]
as long as it works correctly with repeating delegates, i think that is fine. if you're attempting this please make sure to add good test coverage to all scheduler behaviour where it's not already present.
