### ISSUE TITLE
StyleCop MSBuild Integration

### ISSUE THREAD

**Issue by UselessToucan** [ppy/osu-framework#299]
I think we should consider using StyleCop.

Pros:
1. Code readability. It is easier to work when everything is written in the same style.
2. No formatting problems in Pull requests.

Cons:
1. We will have to do a lot of refactoring.

osu! framework repo, default StyleCop settings:
![screenshot 97](https://cloud.githubusercontent.com/assets/22450664/20143411/fa761938-a6a9-11e6-897c-176687ebb97b.jpg)

Related links:
[StyleCop home page](https://stylecop.codeplex.com/)
[Setting Up StyleCop MSBuild Integration](https://stylecop.codeplex.com/wikipage?title=Setting%20Up%20StyleCop%20MSBuild%20Integration)
[Force StyleCop to Ignore a File](http://sethflowers.com/blog/force-stylecop-to-ignore-a-file/)

**Comment by peppy** [comment]
How about you make a stylecop ruleset that meets our style standards and we'll work from there?

**Comment by peppy** [comment]
We are now using resharper/inspectcode for code standards. While it is not as strict as stylecop, we have the ability to add rules as necessary and will continue to improve conformity with stylecop rules where applicable.
