### ISSUE TITLE
Problems with setting up osu along with osu-framework 

### ISSUE THREAD

**Issue by kacmak7** [ppy/osu-framework#3071]
Hi all, 
I'd like to make some changes in the code of osu! and resolve some Issues, therefore I tried to configure osu and osu-framework projects locally, but I got some problems with it. I'm using VS Code, starting osu!lazer from command line is super easy, `dotnet restore` works great, but how to connect it with osu-framework? Maybe I could build packages of osu-framework and manually move them to `~/.nuget/packages`, but that'd be really painful. [Here](https://github.com/ppy/osu-framework/wiki/Development-and-Testing) it looks like gret dev setup but I couldn't manage to launch VisualTests environment. I'd appreciate any help, Thank you!

**Comment by bdach** [comment]
```
$ dotnet run --project osu.Framework.Tests
```
should run the visual tests project.

See [this guide](https://github.com/ppy/osu-framework/wiki/Testing-local-framework-checkout-with-other-projects) for testing local framework changes with osu!

**Comment by kacmak7** [comment]
I don't know how I could miss it. The script did the job. Thank you very much !
