### ISSUE TITLE
BindableList<T> events should provide the original list

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#3081]
When you need to run some post-processing on the list after an insertion or removal has occurred, there's currently no way to do this and retain access to the original list without storing an intermediate list, since if you access the bindable list during `ItemsRemoved` it will contain the post-mutated collection.

As for how to do this, there's a few things we have to consider:

1. Performance - raw performance + allocations. Do we want to incur the hit of allocating a new list with every event, and every propagation of said event?
2. The API - we probably want to return a custom class that we can adjust later on, similar to `ValueChangedEvent<T>`.

**Comment by iiSaLMaN** [comment]
Regarding of perfomance, there is a way to have an `IEnumerable` with custom enumerator to represent a list before an item was removed or after an item is added.

I can go through implementing this if this enumerable idea has been accepted, though I'm not sure what to name it, maybe `MutatedList`?

**Comment by peppy** [comment]
A better direction may be to standardise our events to follow .NET standards like https://docs.microsoft.com/en-au/dotnet/api/system.collections.specialized.notifycollectionchangedeventargs?view=netframework-4.8

**Comment by smoogipoo** [comment]
Bumping this up in priority, since it'll help with solidifying the implementation of things like `RearrangeableListContainer`.
