### ISSUE TITLE
AccessViolation when launching via remote desktop

### ISSUE THREAD

**Issue by huoyaoyuan** [ppy/osu-framework#3083]
Crashes at:
https://github.com/ppy/osu-framework/blob/576898e7957c5246a32dcf42ca1090351e8a711a/osu.Framework/Graphics/OpenGL/GLWrapper.cs#L705
Though it's uncommon to game via remote desktop, hard crash doesn't sound good.

**Comment by bdach** [comment]
Crashing because having no framebuffer bound seems okay to me? It's not like there's any better alternative if the game display just won't work because of it.

Also logs would be nice.

**Comment by huoyaoyuan** [comment]
I remember that stable can be used via remote desktop, in 2019. May do a check later to determine is there any fundamental change.

**Comment by bdach** [comment]
If this isn't a very simple fix (and currently I would guess that it isn't, quite the opposite in fact) I honestly don't think this is worth putting time into. The gaming experience over RDP is most likely going to be quite subpar even if we got the game to run.

**Comment by smoogipoo** [comment]
What RDP solution are you using? If you’re using Microsoft RDP, that actually has its own driver through which it passes all commands (GL or D3D). These days there are other solutions available, such as Parsec.

**Comment by huoyaoyuan** [comment]
I'm using Microsoft RDP. Maybe there's something broken by Windows Update. I'll use other games for comparison.

**Comment by peppy** [comment]
microsoft remote desktop has never worked with opengl.

https://stackoverflow.com/questions/51705471/current-state-and-solutions-for-opengl-over-windows-remote
