### ISSUE TITLE
Have BindableNumber<T> support more types

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#3092]
Up until now, `BindableNumber<T>` was abstract and only implementations of it could be used, of which there were 4 default choices provided by the framework - `BindableDouble`, `BindableFloat`, `BindableLong` and `BindableInt`.

As of https://github.com/ppy/osu-framework/pull/3089, `BindableNumber<T>` can now be instantiated, however it only supports the types `float`, `double`, `int` and `long`. All other types will throw `InvalidOperationException`s: https://github.com/ppy/osu-framework/blob/61cbe268a6656455bbe6ff69515721f7121c5732/osu.Framework/Bindables/BindableNumber.cs#L119-L129

All methods in this class should be updated to support the types defined by the ctor: https://github.com/ppy/osu-framework/blob/61cbe268a6656455bbe6ff69515721f7121c5732/osu.Framework/Bindables/BindableNumber.cs#L24-L33

The exceptions in such methods can then also be removed.

**Comment by peppy** [comment]
I strongly disagree that this is required in a milestone. We have done without it for now, which suggests the remaining types are likely never going to be used.

**Comment by smoogipoo** [comment]
I really dislike leaving things in a half-implemented state. That's fine osu! side but it's not the way I'll ever develop o!f.

Either:
1. Functionality is removed completely.
2. Functionality is implemented completely.

I don't really see a reason for (1) considering there are a limited amount of integral types (all of which have been covered above). So I tend to (2).
