### ISSUE TITLE
Consider removing finalizers wherever possible

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#3118]
Adding a finalizer to an object will:
1. Immediately promote that object to the Gen 1 heap.
2. Increase construction time by around an order of magnitude.

e.g.

|        Method |       Mean |     Error |    StdDev |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|-------------- |-----------:|----------:|----------:|-------:|-------:|------:|----------:|
|   NoFinalizer |   5.390 us | 0.0622 us | 0.0582 us | 7.6447 |      - |     - |  23.44 KB |
| WithFinalizer | 134.180 us | 2.3708 us | 2.1017 us | 7.5684 | 3.6621 |     - |  23.44 KB |

(over construction of 1000 objects with nothing but the ctor/finalizer)

In the case of `Drawable`, this increases construction time from ~250us to 2ms per 1000 `Drawable`s (tested via `Sprite`).

We should implement finalizers sparsely only where unmanaged resources are used.

**Comment by huoyaoyuan** [comment]
`GC.SupressFinalizer` should eliminate the runtime overhead, but the code maintenance overhead still exists.

**Comment by smoogipoo** [comment]
Indeed, most of it is eliminated. Updated benchmarks (https://gist.github.com/smoogipoo/5d3ccacc7cd2c3f475fcf15303b542ac):

|        Method |      Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|-------------- |----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
|   NoFinalizer |  7.969 us | 0.1785 us | 0.4857 us |           - |           - |           - |            23.44 KB |
| WithFinalizer | 40.669 us | 1.0009 us | 1.7265 us |           - |           - |           - |            23.44 KB |

Although I'd still say we should only use finalizers when we need to, rather than blanketing them everywhere where `IDisposable` is implemented.

**Comment by huoyaoyuan** [comment]
Consider: when finalizer is invoked, write to log. Finalizer should be the last defensive route, invoking it means `Dispose` fails to cover it gracefully.

**Comment by UselessToucan** [comment]
Note that we have a finalizer in the `Drawable` class (see https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/Drawable.cs#L60). I.e. we have it almost everywhere.

**Comment by bdach** [comment]
Closing in favour of #4229, I guess?
