### ISSUE TITLE
Hard crash on attempting to load unrecognised image file via STBi

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#3120]
Full reproduction at https://github.com/ppy/osu/issues/7179#issuecomment-565884682. Has been fixed for the erroneous case osu!-side, but still have potential to cause issues in its current state.

**Comment by Tom94** [comment]
At first glance this looks like a problem with StbiSharp---when directly using STBI from C++, it gracefully fails with an "invalid format, or corrupt" error message.

**Comment by Tom94** [comment]
Fixed [here](https://github.com/Tom94/stbi-sharp/commit/7270b520b423e127e47680739be67c5ddbe8f829)

Dependabot should take care of it. :)
