### ISSUE TITLE
Front-to-back should be enabled for Sprites

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#3129]
FtB currently isn't enabled for `Sprite`, since the drawn `Texture` is not guaranteed to be fully opaque.

`TextureGLSingle` should compute the opaqueness of its texture, initially just as "fully opaque" or "not fully opaque".
Then, `SpriteDrawNode` needs to be updated to draw the opaque interior (in this case, the full sprite). See `BoxDrawNode` as an implementation reference.

**Comment by bdach** [comment]
I suppose `TextureGLSingle.SetData()` would be the proper place to compute this at, right?

I was also thinking we might want to do something with this along the way:
https://github.com/ppy/osu-framework/blob/86096b3c930b932dc97f35d5a72b92cd3ffb07e2/osu.Framework/Graphics/OpenGL/Textures/TextureGL.cs#L17
Only write usage I can see is here:
https://github.com/ppy/osu-framework/blob/86096b3c930b932dc97f35d5a72b92cd3ffb07e2/osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs#L304
Value read is used in `Bind()` to prevent from binding transparent textures to slots. We could consolidate this with an opaqueness flag by doing something like:
```csharp
public enum TextureTransparency
{
    PartiallyOpaque,   // default - no applicable optimisations
    FullyTransparent,  // early-return false when trying to bind
    FullyOpaque        // enable front-to-back
}
```
Computation could be done in a single loop by having two flags tracking full transparency/opaqueness; if both flags become false during iteration, can early-return `PartiallyOpaque`.

This could go well with some bit-twiddling to make it as fast as possible on CPU, but I'd have to benchmark. Was also thinking about having the computation as a shader somewhere but returning the value out to CPU would *probably* be horrible on opengl?

**Comment by peppy** [comment]
doing this on cpu is fine. i believe we do it in stable (or maybe we *used* to do it in o!f).

**Comment by bdach** [comment]
Unassigning myself for now as I'm a little low on bandwidth to submit code recently.

**Comment by peppy** [comment]
Removing from milestone as not super-high priority.
