### ISSUE TITLE
Implement color picker

### ISSUE THREAD

**Issue by andy840119** [ppy/osu-framework#3134]
Is there any design for color picker?

**Comment by smoogipoo** [comment]
There isn't a framework design for this. For now you could implement it in a similar way to https://user-images.githubusercontent.com/1329837/42362645-3ba29dda-812f-11e8-9cd3-77c8b3bae66b.png

The implementation should be split into two parts: the abstract implementation that has no design, and the basic implementation that looks similar to the above but uses the osu!framework design language (no rounded corners, `FrameworkColour`, `FrameworkFont`).

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/71334003-49571080-2577-11ea-90e8-95d1592e42c6.png)

Should this be label or textbox?

**Comment by smoogipoo** [comment]
probably a textbox

**Comment by andy840119** [comment]
![image](https://user-images.githubusercontent.com/9100368/71346189-3c9be200-25a2-11ea-9600-0d26ab5a3aea.png)
Working progress.
It might take a while because too many bindables.

**Comment by Flutterish** [comment]
I also made a color picker (https://github.com/Flutterish/Hitokori/releases/tag/0.18.4-2021.03.15). If you want to use something similar feel free to copy my code but I do not have the time necessary to make it framework-ready.
