### ISSUE TITLE
Tab control should select next tab when current tab is closed

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#3152]

**Comment by crabn3bula** [comment]
Hey. I wanted to ask what behavior should be implemented if the current tab is the last one. Should the first tab in the list or the previous one be selected?

**Comment by peppy** [comment]
previous. use a browser's tab control as a guide for behaviour if unsure.

**Comment by crabn3bula** [comment]
#3614

**Comment by smoogipoo** [comment]
Resolved via #3614
