### ISSUE TITLE
Password box has distinguishable key sounds

### ISSUE THREAD

**Issue by redline2466** [ppy/osu-framework#3280]
**Describe the bug:** 
The password box for signing in has different sound effects for lowercase and capital letters.
This somewhat hints to nearby listeners what the password could be.

**Screenshots or videos showing encountered issue:** 
[http://battletrains.org/bug.mp4](http://battletrains.org/bug.mp4)

**osu!lazer version:** 
2020.215.0

**Comment by peppy** [comment]
May be a good time to move sounds out of the framework implementation while we're here.

**Comment by iiSaLMaN** [comment]
Will work on it.

**Comment by peppy** [comment]
@frenzibyte still gonna take a look at this?

**Comment by frenzibyte** [comment]
> @frenzibyte still gonna take a look at this?

Yes, had it scheduled for today but postponed it due to resolving review conversations on another PR, I'll get it done by tomorrow.
