### ISSUE TITLE
There should be an option to prevent screen suspension

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#3308]
It may be desirable to prevent the screen from suspending. For example, if a replay is being watched or if a long break is entered.

Should be provided at a GameHost level as a `BindableBool`, which is referenced in both iOS and Android projects.

**Comment by TimOliver** [comment]
Merged. :)

**Comment by peppy** [comment]
If you use `Closes #issuenumber` in your PRs it will automatically close the issues, for what it's worth.

Also this function isn't yet implemented osu!-side, we may want to look at that.
