### ISSUE TITLE
Revisit iOS input polling

### ISSUE THREAD

**Issue by swoolcock** [ppy/osu-framework#3312]
Following on from https://github.com/ppy/osu/issues/8008

The original OpenTK implementation for iOS locks the `Update` and `Render` events at the same rate.  It's up to the developer as to whether they want to use `CADisplayLink` by calling `RunWithFrameInterval(int frameInterval)` or to use an `NSTimer` by calling `Run(double updatesPerSecond)`.  A `CADisplayLink` will attempt to synchronise with a fraction of the display refresh rate, whereas an `NSTimer` can run at whichever rate the developer specifies.

We currently use `public void Run() => RunWithFrameInterval(1);`, which will attempt to call the `RunIteration` function at the display's refresh rate.  This (previously) would call `Update` and `Render` exactly once per loop.

Since we use our own draw thread, I added the `ShouldCallOnRender` and `ShouldCallOnUpdate` properties to avoid the extra `glBindFramebuffer` that was causing flickering and crashes.

https://github.com/ppy/osuTK/blob/master/src/osuTK.iOS/iOSGameView.cs#L929

On iOS we currently only use the `Update` event to queue pending inputs.  Since we're not using the `Render` event at all, I don't see any reason to keep it as a `CADisplayLink` when we could request a specific rate for input polling.

I suggest changing `gameView.Run();` to `gameView.Run(120);` in `GameAppDelegate` to use 120hz as a baseline for input polling as it will cover the current maximum sample report rate for iOS devices.

https://github.com/ppy/osu-framework/blob/master/osu.Framework.iOS/GameAppDelegate.cs#L33

**Comment by peppy** [comment]
@swoolcock see https://github.com/ppy/osu-framework/pull/3301, which also requires changes here. that PR wants the "input" thread (ie. main window thread) to run at the refresh rate, at very least.

Currently it doesn't, and seems to be locked to 60hz even on an ipad pro.

**Comment by peppy** [comment]
Closing this for now as we are now in a pretty good state (via #3316).
