### ISSUE TITLE
Build error on case sensitive filesystems: SliderBar.cs not found

### ISSUE THREAD

**Issue by Ferdi265** [ppy/osu-framework#338]
Build fails with

	CSC: error CS2001: Source file `Graphics/UserInterface/SliderBar.cs' could not be found

This can be resolved by renaming `Sliderbar.cs` to `SliderBar.cs`.

Build error encountered on Linux on an `ext4fs` filesystem.

**Comment by peppy** [comment]
you could have just submitted a pull request you know

**Comment by Ferdi265** [comment]
Yeah, could have done that, but it was after midnight, and I was too tired to fork and create a commit with the rename.

Would have done it today if it wasn't fixed already.

Thanks for the quick response and fix by the way.
