### ISSUE TITLE
Switch SDL2 libraries (proposal)

### ISSUE THREAD

**Issue by swoolcock** [ppy/osu-framework#3449]
As previously discussed, it may be worth moving to an SDL2 wrapper that's more actively maintained, as Veldrid.Sdl2 is quite far behind the SDL2 repository and hasn't had a stable release in a long time.

SDL2# looks to be a good choice, but the author seems to be vehemently against NuGet in principle and suggests that consumers submodule the repository instead.  I would prefer not to do that, nor would I feel comfortable using any of the many "unofficial" packages.  It might be worth forking and building our own packages.

https://github.com/flibitijibibo/SDL2-CS

Assuming we move to SDL2#, it would mean writing our own window event loop.  I'm not against this, as the Veldrid.Sdl2 one leaves a lot to be desired.

Would also be worth testing a simple SDL2# app on iOS and Android.  I have not tested Veldrid.Sdl2 on mobile as it has been low priority and can still run with osuTK if required (for now).

**Comment by smoogipoo** [comment]
Gonna be honest, the complete disregard for nuget by that author gives me the heebie jeebies. 

We're definitely not submoduling, transitive project dependencies have historically not worked well with C# - when testing osuTK I've always had to reference the osuTK project in all of our projects that referenced anything osuTK.
That's ok when you're writing an isolated game, not ok when you're writing a framework for other games to build off of.

I wouldn't be against forking and publishing our own nuget package if anything.

**Comment by swoolcock** [comment]
Looking more into SDL2#, all the bindings are `[DllImport]` referring directly to `"SDL2"`.  This won't work for iOS, which requires static libraries to be embedded and referred by `"__Internal"`.

It may be worth just wrapping the bare minimum we need ourselves using delegates as per the current `Sdl2Functions` class.  That should work for all platforms, as Veldrid.Sdl2 uses mellinoe's NativeLibraryLoader as a transitive dependency.

**Comment by smoogipoo** [comment]
You should be able to get SDL2# to work by adding DllMap bindings (`app.config`) to `__Internal`.

**Comment by swoolcock** [comment]
Noting here for visibility:

SDL2-CS has been forked and cleaned up for our use.
https://github.com/ppy/SDL2-CS/pull/1

Have successfully tested on iOS, but will require an additional line to app.config, as well as potentially a custom build of `libSDL.a` to ensure it doesn't include its own `main` function.

Will be making a PR soonish replacing Veldrid.SDL2 with SDL2#.

**Comment by huoyaoyuan** [comment]
Note:
For native binding issues on iOS, I think we should wait for .NET 5 SDK (half a year from now). It has planned to unify capabilities on platforms. At least, we should examine what feature it would provide.

**Comment by swoolcock** [comment]
It's not a big deal, I got lazer building and running on device in the end.  It's actually simpler to initialise than the osuTK backend.

**Comment by smoogipoo** [comment]
This one has been resolved since.
