### ISSUE TITLE
Borderless Mode extends 1 extra pixel right and 1 down.

### ISSUE THREAD

**Issue by CheeseManFuu** [ppy/osu-framework#3456]
**Describe the bug:** 

On my triple 1920x1080 setup, I noticed Borderless Window mode bled onto my other monitor by one pixel. I'm not sure if this is exclusive to 1080p or multiple monitors. It happens regardless of screen scaling. My taskbar is on the bottom of the rightmost monitor, and hides.

While writing this, after realizing I could use in-game screenshots to test if it also happened when there "wasn't" an extra pixel of workspace to go to (i.e. the rightmost monitor), I also found out that it was not only 1921 pixels wide, but also 1081 pixels tall.

**Screenshots or videos showing encountered issue:** 

![borderlosu](https://user-images.githubusercontent.com/7471405/79525580-d4797c00-8028-11ea-961a-8792a4dbcb82.png)
(hard to tell at a glance on a stitched image, but a rectangle select of osu! will show a 1921x1080 area)

![Annotation 2020-04-16 214009](https://user-images.githubusercontent.com/7471405/79526438-e78d4b80-802a-11ea-964f-d98bbff503b7.png)
(unedited screenshot and its properties)

**osu!lazer version:** 
Appeared in 2020.325.0 (I hadn't touched Lazer since, but also hadn't noticed at that point), still appears in 2020.413.0

Using Windows 10 Professional v1903.

**Comment by peppy** [comment]
Bumping into milestone. Worth investigating if this is still required or not (would be nice to be able to remove it if it was a stable-specific thing).

**Comment by CheeseManFuu** [comment]
Gladly; I'll check again tomorrow for Lazer, Stable, and Cutting Edge first chance I get.

**Comment by CheeseManFuu** [comment]
Yeah, some 10 minutes. I was stopped for a while by my incompetence reinstalling Lazer.

Anyway, what I've found: Still happens in Lazer, and only in borderless. Stable/CE unaffected in both, as expected.

[ppy/osu#5586](https://github.com/ppy/osu/issues/5586) did remind me of its potential downfall due to leaking onto other monitors in the form of Microsoft's very infuriatingly incompetent Win10-only bug where a window playing pretty much any sort of animation on a lower refresh rate monitor will cap every other animation everywhere else in the monitorspace to the lower refresh rate, which means an animated window even a single pixel on a 60hz monitor will make things on every monitor only display animation up to 60fps. Win7 doesn't have this issue, Linux doesn't have this issue, Mac might not? It was even addressed recently (at least, hearsay said it happened) by Microsoft to be fixed in June/July. It's August ~~already~~.

It didn't occur to me until now because two of my three monitors are 144hz, and coincidentally they're my center and right monitor, which means I would only be leaking from the 60hz onto the 144hz with the expectation of the game displaying 60fps.

**Comment by swoolcock** [comment]
With the osuTK backend we manually implement "borderless" in `DesktopGameWindow.UpdateWindowMode` by:
* Setting the window state to maximised
* Hiding the window border
* Setting the window location to the top left corner of the display
* Setting the window internal size to the display bounds plus 1 (hence the above issue)

With SDL we actually use the `SDL_WINDOW_FULLSCREEN_DESKTOP` fullscreen mode to do all this for us in a "correct" way for the platform.

Could you please test with SDL and confirm whether this is still an issue for you?

Assuming you are running lazer from a shortcut, add `--sdl` to the command line arguments.

**Comment by CheeseManFuu** [comment]
> Could you please test with SDL and confirm whether this is still an issue for you?

Absolutely works! The only issue is just behaves like normal fullscreen mode, in that the mouse is captured and the window disappears when tabbing out, but at the very least with borderless mode set in-game, it is now constrained to just the monitor it is meant to fill.

![Screenshot 2020-10-08 230143](https://user-images.githubusercontent.com/7471405/95541951-4f10cc00-09ba-11eb-892d-c4f7680c3a5f.png)

**Comment by peppy** [comment]
That sounds like the very reason we had the 1px adjustment in place. Some drivers required this to avoid the window switching to exclusive fullscreen automatically.
