### ISSUE TITLE
_ instead of - in project template

### ISSUE THREAD

**Issue by Tudi20** [ppy/osu-framework#3463]
![Folder Structure Actual](https://user-images.githubusercontent.com/13798839/79702230-9c31a200-82a3-11ea-83e0-3ac4981a6674.png)
![Folder Structure Assumed](https://user-images.githubusercontent.com/13798839/79702247-b7041680-82a3-11ea-88f3-bc1efea5d87d.png)

**Comment by peppy** [comment]
i'm pretty sure this is correct. are you facing issues? if so, please include the actual error.

**Comment by Tudi20** [comment]
When you create a new project with `-` separating words, in some places (like the actual files) are generated with `-`, while in some places (like the reference to those files in the solution file) are generated with `_`. This essentially results in an unloadable projects.
For example: `dotnet new osu-framework-game -n osu-framework-test` creates a broken solution, while `dotnet new osu-framework-game -n osu_framework_test` creates a working solution.
![Projects became unloadable](https://user-images.githubusercontent.com/13798839/79749723-fd8f5a80-830f-11ea-9537-599f073dca16.png)
After you do a Replace all in the .sln files, the projects become loadable, but the references, are obviously still wrong, and at many places, I would assume this is broken.

**Comment by bdach** [comment]
See dotnet/templating#1920.
