### ISSUE TITLE
Resizing window below minimum size is being corrected manually, window doesn't have a native minimum size

### ISSUE THREAD

**Issue by glaciyan** [ppy/osu-framework#3501]
Video demonstration: https://www.youtube.com/watch?v=zEg1ePfI0Ns
This has, in some cases, crashed osu!lazer, but I unfortunately don't have a recording of that. A similar issue has occurred when running the sample game on gnome 3.34 which almost randomly resizes the window every few frames when you try to normally resize it.

**Comment by swoolcock** [comment]
This will be fixed with SDL.

**Comment by peppy** [comment]
This applies to windows/macOS too

**Comment by Joehuu** [comment]
This seems to do the trick, not sure if correct.

```diff
diff --git a/osu.Framework/Platform/SDL2DesktopWindow.cs b/osu.Framework/Platform/SDL2DesktopWindow.cs
index e3dcd7348..00b7a07d8 100644
--- a/osu.Framework/Platform/SDL2DesktopWindow.cs
+++ b/osu.Framework/Platform/SDL2DesktopWindow.cs
@@ -978,6 +978,8 @@ private void updateWindowStateAndSize()

                     SDL.SDL_SetWindowSize(SDLWindowHandle, Size.Width, Size.Height);

+                    SDL.SDL_SetWindowMinimumSize(SDLWindowHandle, sizeWindowed.MinValue.Width, sizeWindowed.MinValue.Height);
+
                     updateWindowPositionFromConfig();
                     break;
```

**Comment by frenzibyte** [comment]
It can be set right after the creation of the SDL window, yeah?

**Comment by Joehuu** [comment]
Right, so here then?

```diff
diff --git a/osu.Framework/Platform/SDL2DesktopWindow.cs b/osu.Framework/Platform/SDL2DesktopWindow.cs
index e3dcd7348..181156e6c 100644
--- a/osu.Framework/Platform/SDL2DesktopWindow.cs
+++ b/osu.Framework/Platform/SDL2DesktopWindow.cs
@@ -407,6 +407,8 @@ public virtual void Create()

             SDLWindowHandle = SDL.SDL_CreateWindow(title, Position.X, Position.Y, Size.Width, Size.Height, flags);

+            SDL.SDL_SetWindowMinimumSize(SDLWindowHandle, sizeWindowed.MinValue.Width, sizeWindowed.MinValue.Height);
+
             Exists = true;

             MouseEntered += () => cursorInWindow.Value = true;
```

**Comment by frenzibyte** [comment]
Yeah, that's correct now. one note though, this should not just arbitrarily take the minimum window size from the bindable's `MinValue`, I would define a static `MinSize` in `IWindow` that both the config setup and the window should use.

**Comment by peppy** [comment]
I believe the user can also make changes to this in their own project? Should probably handle bindable events as well (although from the looks of things `BindableSize` doesn't currently implement these...)
