### ISSUE TITLE
Restore failed when a runtime is specified

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-framework#3507]
This is caused by https://github.com/ppy/osu-framework/pull/3497
I usually build osu! with `--runtime` flag so it only include a specific set of dependencies for that runtime. But after the PR, doing it causes the restore failed.
`dotnet publish osu.Desktop --no-self-contained --configuration Release --runtime arch-x64 --output ~/osuLazerBin > ~/dotneterr.txt`

[dotneterr.txt](https://github.com/ppy/osu-framework/files/4565429/dotneterr.txt)

**Comment by smoogipoo** [comment]
Please try again with the referencing PR, I can't compile `arch-x64` but had the same/similar on `osx-x64` and it now works for me.

**Comment by huupoke12** [comment]
The PR resolved the issue
