### ISSUE TITLE
Support mouse input on iPadOS 13.4

### ISSUE THREAD

**Issue by TimOliver** [ppy/osu-framework#3524]
With the release of iPadOS 13.4, it's possible to pair Bluetooth mice to an iPad, and control the device with a native cursor that appears on the screen.

At the moment, this interaction doesn't play very nicely with osu! framework's tablet implementation. The osu! mouse cursor is still visible, but doesn't move unless the mouse is clicked and dragged. Until then, the osu! mouse stays stationary, but the iPadOS mouse moves around.

There's probably two ways to improve this experience:
* Suppress the osu! mouse cursor icon and route all input through the native mouse cursor.
* (Not sure if this is possible) Hide the iPadOS mouse icon, and route all input through the osu! mouse cursor.

![IMG_0899](https://user-images.githubusercontent.com/429119/81258597-9a6c2a80-9068-11ea-8b50-79bc39059320.jpg)

**Comment by peppy** [comment]
Hiding the iOS cursor is indeed possible and done by multiple apps already live. This would be the preferred direction.

**Comment by TimOliver** [comment]
Got it working on a very basic level. 😄

https://puu.sh/FHNKS/d7f50541b4.mov

Yeah, in typical Apple fashion, the API is very limiting. All of the input events come through an interaction object that needs to be attached to a view, and the events only occur when the cursor is over the view (So I just attached one to the whole game window).

As far as I can tell, it's not possible to override the position of the cursor (eg, if the user dragged the mouse somewhere else by touch, but then went back to the trackpad, the cursor would snap back to where the cursor still is)

**Comment by ThatsNiceGuy** [comment]
Closing my issue #3414 as this is the same thing and my issue is now redundant.
