### ISSUE TITLE
iOS Simulator Crashes on Launch with Storage Exception

### ISSUE THREAD

**Issue by TimOliver** [ppy/osu-framework#3526]
After pulling from `master`, I could no longer build the osu!framework test suite in the iOS simulator due to the following exception.

![Screen Shot 2020-05-07 at 10 35 29 pm](https://user-images.githubusercontent.com/429119/81311434-f6aa6b00-90b7-11ea-89de-c37803ff84c3.png)

After consulting with @smoogipoo, it appears this is a regression due to #3522. Reverting to a commit before that PR being merged fixes the issue.

**Comment by peppy** [comment]
@TimOliver are you going to look at a fix for this? is it just tests? does running on a device still work?

**Comment by TimOliver** [comment]
Just tested on my iPhone 11 Pro and can confirm the same crash happens.
Sure! I'll see if I can make a fix for this. :)

**Comment by peppy** [comment]
Only in tests, right?

**Comment by TimOliver** [comment]
Uh, as opposed to what else exactly? osu! itself?

**Comment by peppy** [comment]
The information you've given so far is ambiguous as to where this is occurring. The changes in the PR you point at basically should have no effect outside of the newly added tests (which understandably will fail on iOS).

I'm trying to attain whether this is an issue with standard runtime. My hypothesis is that it should not even affect framework visual tests, nor samplegame.
