### ISSUE TITLE
Change GL bindings (proposal)

### ISSUE THREAD

**Issue by swoolcock** [ppy/osu-framework#3538]
## Proposal
Eventually we will need to change our GL bindings when we make the full switch to SDL and remove the osuTK package.  There are a number of ways we can do this.

Requirement of #2448 

## 1. Wrap osuTK GL bindings
The idea being that there would be no direct references to osuTK GL types and functions.  Once we remove osuTK, the wrapper would load procs solely with `SDL_GL_GetProcAddress`.

### Pros
* No references to `osuTK.Graphics.ES30` or SDL outside of the wrapper

### Cons
* Requires copying enums and structs
* Wrapping could introduce overhead depending on how it's done
* A lot of work

## 2. Split osuTK GL bindings to a standalone package
Rather than copying code or making wrappers, it might be worth retaining part of the osuTK library solely for its GL bindings.  This is something we could remove in future when we look at going API-agnostic, but for now it would save a lot of effort and reinventing the wheel.

### Pros
* Requires minimal changes to osu!framework
* SDL `PassthroughGraphicsBackend` would continue to work fine
* Can be retained once we are ready to remove the other osuTK packages
* We know it works

### Cons
* osuTK GL bindings use osuTK's `Vector*`, `Matrix*`, and `Color4` types
* Could be a lot of other cross dependencies we would need to resolve when splitting the package

## 3. Move to another GL binding library
We could also look at finding another cross-platform OpenGL binding library.  There are plenty available, but we'd need to ensure they're netstandard compatible and work fine on Xamarin.

### Pros
* Keeps GL bindings self-contained (though splitting osuTK would serve the same purpose)

### Cons
* Potentially requires a lot of changes to osu!framework
* Might not work the same on all platforms
* Could introduce regressions

## Summary

My personal preference would be to split the osuTK GL bindings, as it requires the fewest changes in osu!, osu!framework, and consumers' projects.  It's also proven to work on all platforms we currently target.

I welcome other suggestions and opinions.

**Comment by smoogipoo** [comment]
Personal preference is splitting out osuTK's GL bindings. One thing that may be considered is removing all the typed overloads for methods since the future is for consumers to not use any native methods _at all_, and instead submit commands via the o!f graphics abstraction layer which then invoked appropriate native commands whether vulkan/opengl/d3d/etc.

**Comment by swoolcock** [comment]
> One thing that may be considered is removing all the typed overloads for methods since the future is for consumers to not use any native methods _at all_

I agree, since this would also avoid the dependency issue of needing osuTK's colour and math types.  It might be worth moving some of the typed overloads into osu!framework as `[Obsolete]` extension methods, just to ease migration in the short term.  There are only a handful we use, and these can be removed along with the `Colour4` and `System.Numerics` changes.

**Comment by smoogipoo** [comment]
Doesn't need to be internal, we can re-expose them under the correct namespace from within o!f. Not sure about obsoleting just yet - I envisioned the implementation of the abstraction layer to have a "raw" command even if only temporarily, something like:
```
SubmitViewport(...);
SubmitOrtho(...);
SubmitUnsafeRaw(api =>
{
    /* do custom stuff with whatever graphics API you wish, keeping in mind this is unsafe */
    GL.Scissor(...);
});
SubmitVertices(...);
...
```

**Comment by swoolcock** [comment]
Looking more into it, the GL bindings in osuTK are incredibly tightly coupled with the rest of the library.  Splitting might be more effort than it's worth.

As for an abstraction layer, that's still a ways down the track.  I was hoping to get in something small and self-contained to replace the osuTK bindings so that we can eventually remove it entirely.

**Comment by swoolcock** [comment]
Looks like there's a fourth option that combines 2 and 3.  Someone has already done the work for us. :)

https://github.com/giawa/opengl4csharp

> This code started as a limited subset of the Open Toolkit bindings to OpenGL, but has evolved to include the latest functionality by parsing the OpenGL man pages directly.

I've converted the framework to these bindings and it seems to work fine with the SDL backend.  Will check to see what needs to be done in regards to the osuTK backend.

**Comment by swoolcock** [comment]
I have an initial attempt at splitting osuTK into GL and core packages.  Low priority, but the point is that it can be done without too much effort.

https://github.com/swoolcock/opentk/tree/package-split

**Comment by Perksey** [comment]
For those who aren't in the discord: more than happy to help out where I can if the team are willing to use Silk.NET as I'm the main author over there and can fill in missing functionality where needed.

If the Silk.NET route were to be pursued, what would end up happening is we'd use the Silk.NET.OpenGLES package but with a custom GetProcAddress (potentially SDL as described in option 1) and custom context.

Let me know if you have any questions - it's probably best you direct them to me in the Discord, I'm @Perksey over there too, ping me but just don't spam me with pings k :P

**Comment by Perksey** [comment]
Oh and btw, Silk.NET like OpenTK does provide a pretty solid and pretty extensible windowing and input API (currently only supports desktop via GLFW though, mobile support won't come until November) so as a potential future/stretch goal we could move over to that instead of GameWindow later down the line - not right now obviously as that'd be a *lot* of work.

**Comment by Perksey** [comment]
One last thing (I promise I'll stop with the comments now :D ) I notice that you've currently got a IWindow abstraction in the works, and Silk.NET already has a pretty solid abstraction so even if you only wanted an abstraction and not necessarily our first-party implementation, you can still consume the APIs defined in Silk.NET.Windowing.Common (we have an IView interface and an IWindow interface, the latter of which building on the former)

**Comment by swoolcock** [comment]
What's the reasoning behind the November timeline?  Is it purely lack of manpower, or are you specifically waiting for .NET 5?

**Comment by Perksey** [comment]
We’re lining up the release of Sik.NET 2.0 with the .NET 5 release yeah
because we’ll be using some of the latest language and framework features

**Comment by peppy** [comment]
Closing this one as we have mostly abstracted away bindings with the new renderer framework, and will continue to track this there.
