### ISSUE TITLE
Log overlay sometimes displays messages out of order

### ISSUE THREAD

**Issue by Jeremiidesu** [ppy/osu-framework#3591]
![image](https://user-images.githubusercontent.com/20820425/83341298-1d884580-a2e2-11ea-884a-c2da7a528434.png)

The log in the Rider console never gets out of order, but the log overlay sometimes displays messages out of order. (Notice how the first two lines are swapped here in the log overlay)

**Comment by peppy** [comment]
Just to confirm, you're comparing to the console output not log file, right?

**Comment by Jeremiidesu** [comment]
Yes, I'm comparing the console output to the log overlay.
