### ISSUE TITLE
Using non-default font size in BMFont results in incorrect font sizing

### ISSUE THREAD

**Issue by Jeremiidesu** [ppy/osu-framework#3606]
I am using a font that's fairly narrow, so high font sizes effectively render pixelated. 

![image](https://user-images.githubusercontent.com/20820425/83911556-c3b5ce80-a76c-11ea-93d1-612fc97c612c.png)

A way to work around this is to set a bigger glyph size at export in BMFont while not changing any other setting. 

When doing so, this happens:
![image](https://user-images.githubusercontent.com/20820425/83912093-90c00a80-a76d-11ea-94db-7db02081e159.png)

Expected behavior would be to have sharper text like so: 

![image](https://user-images.githubusercontent.com/20820425/83911788-2c9d4680-a76d-11ea-9d2e-f3e1b557974a.png)

*The glyph size use in this example was 200px instead of 100px, resulting in glyphs effectively being twice as big.*

**Comment by peppy** [comment]
As discussed in discord, this can be solved by creating your own `FontStore` with the correct size parameter:


```csharp
var myFonts = new FontStore(scaleAdjust: 200);

Fonts.AddStore(myFonts);

AddFont(Resources, "BigFont", myFonts);
```
