### ISSUE TITLE
Switching logger storage should copy logged files from previous directory

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#3615]
Switching `Logger.Storage` to a new storage directory would cause missing up useful information logged previously from being moved into the new log files. By useful information, I mean like the GL initialization text.

May also propose clearing up all log files in the previous directory.

**Comment by peppy** [comment]
Sounds weird. Can it not just be set earlier in your use case?

**Comment by frenzibyte** [comment]
> Sounds weird (a logger shouldn't be doing file copy/move operations – just logging). Can it not just be set earlier in your use case?

Well (should've mentioned this), the use case here is osu!lazer, when switching the game user data folder to another location, the logs in the new location will not have the GL header text, which is kind of bad as the GL header may provide useful information to help identifying the issue.

Decided to open the issue here as it doesn't seem feasible to fix lazer-side, but can be transferred if so anyways.

**Comment by peppy** [comment]
First thought would be to change the logger's storage earlier. Have you tried that?

**Comment by frenzibyte** [comment]
> First thought would be to change the logger's storage earlier. Have you tried that?

Haven't, but now after reading through, sounds like it could be fixed by adding a `SetupStorage(Storage hostStorage)` method for the game and let `OsuGameBase` setup the wrapped storage from there, sounds good?

**Comment by frenzibyte** [comment]
Here are branches showing off what I'm talking about fwiw:
https://github.com/ppy/osu-framework/compare/master...frenzibyte:switch-logger-earlier
https://github.com/ppy/osu/compare/master...frenzibyte:switch-logger-earlier

**Comment by peppy** [comment]
Maybe we should just set the storage to the game one at a framework level. @smoogipoo thoughts? We already set the `Logger.GameIdentifier` and `Logger.VersionIdentifier` at the same location.

**Comment by smoogipoo** [comment]
Framework's `Game` doesn't have the concept of its own `Storage` right now. Maybe the `GameHost.CreateGameStorage()` method can be moved to `Game`. The real issue is then how do you deal with per-platform storages, do you like, take _in_ a `Storage` (the `GameHost`'s default one) and spit out a new `Storage` that may or may not be the same one given?

**Comment by peppy** [comment]
Right, missed that fact. Returning a different storage to the one arriving may not be what we want, sound a bit suspicious..

**Comment by smoogipoo** [comment]
Going to bump this one up in priority since the current osu!-side implementation is eating lines (see: https://github.com/ppy/osu/issues/9404, missing opengl report).

**Comment by frenzibyte** [comment]
Yeah opened the issue mostly because of missing OpenGL header osu!lazer-side.
