### ISSUE TITLE
Primary touch and mouse down events can trigger on different drawables

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#3667]
The primary touch is always passed through as mouse down and doesn't respect the blocking behaviour of the hierarchy. This can cause the touch down and mouse down input to be received by different Drawables in the same frame.

```csharp
public class TestSceneTesting : ManualInputManagerTestScene
{
    [Test]
    public void TestPrimaryTouchNotForwardedAsMouseIfHandledAsTouch()
    {
        MouseTarget mouseTarget = null;
        TouchTarget touchTarget = null;

        AddStep("create hierarchy", () =>
        {
            Children = new Drawable[]
            {
                mouseTarget = new MouseTarget { RelativeSizeAxes = Axes.Both },
                touchTarget = new TouchTarget { RelativeSizeAxes = Axes.Both }
            };
        });

        AddStep("touch down", () => InputManager.BeginTouch(new Touch(TouchSource.Touch1, mouseTarget.ScreenSpaceDrawQuad.Centre)));
        AddStep("touch up", () => InputManager.EndTouch(new Touch(TouchSource.Touch1, mouseTarget.ScreenSpaceDrawQuad.Centre)));

        AddAssert("touch target received input", () => touchTarget.ReceivedOnTouchDown);
        AddAssert("mouse target not received input", () => !mouseTarget.ReceivedOnMouseDown);
    }

    private class MouseTarget : Drawable
    {
        public bool ReceivedOnMouseDown;

        protected override bool OnMouseDown(MouseDownEvent e)
        {
            ReceivedOnMouseDown = true;
            return true;
        }
    }

    private class TouchTarget : Drawable
    {
        public bool ReceivedOnTouchDown;

        protected override bool OnTouchDown(TouchDownEvent e)
        {
            ReceivedOnTouchDown = true;
            return true;
        }
    }
}
```

**Comment by peppy** [comment]
Just to better understand: what's a case where this would lead to bad/unwanted behaviour? I'm not actually sure we need to worry about this. Basically any case where an application is handling touches, it would outright want to disable the mouse cursor propagation part, right? Otherwise you'd be handling two events (at the same drawable or otherwise) and things would get weird.

**Comment by smoogipoo** [comment]
Well think of osu! for example. HitCircles will handle both touches and mouse inputs. If you touch on a hitcircle and then have the touch also propagate down as a mouse input and hit another circle underneath, does that not sound wrong to you? How would you expect a user to be able to sanely handle that scenario - create a custom input manager and bind to `HandleMouseXStateChange` and flip the value of `MapPrimaryTouchToMouse`?

One input event must not be handleable by more than one Drawable.

**Comment by peppy** [comment]
I would not expect a mouse input to propagate, because that's a scenario where we would be handling touches. Think of it as an opt-in thing, where the mouse propagation is a default (where the user doesn't want to specifically handle touch events).

`RulesetInputManager` would set `DisableTouchToMousePropagation` or whatever we decide to call the flag.

I "touched" on this here: https://github.com/ppy/osu-framework/pull/3269#discussion_r444667554

**Comment by smoogipoo** [comment]
That's too much knowledge for a user to understand to avoid fundamentally incorrect input at the point where they begin handling their first touch event. Do you disagree with my assertion?

**Comment by peppy** [comment]
Hmm, yeah I do tend to disagree.

I see touch input as its own thing, in a similar way to keyboard not blocking mouse, or gamepad not blocking mouse. The touch to mouse propagation is just supposed to be a sane default when the user is not handling touch at all.

**Comment by peppy** [comment]
I guess the argument against this may be something like: how do we implement `ScrollContainer` to support mouse and touch? In which case what you're asking for may make more sense, since I can't think of how that can be done currently (unless it checks the containing input manager's TouchToMouse state..)

**Comment by smoogipoo** [comment]
But those are different inputs. Keyboard is not mouse, gamepad is not mouse. It makes sense for them to not block each other, but here we're explicitly treating the primary touch as a mouse event. We've made the connection that touch1 == mouse.
They can't be treated as every other input.

Put it this way, I would rather that input be fixed and that `DisableTouchToMousePropagation` did not exist at all. I wouldn't expect to make hitcircles handle touch input and be required to make some change on an `InputManager` in order to fix completely breaking the game. I don't see why input couldn't always be forwarded as mouse and everything could still work correctly.

Let's ask a different question - when would you ever want to handle _both_ touch input and mouse input, in the same frame, from the same input source?

Regarding `ScrollContainer`, I don't see a problem? `OnTouch*` would occur when you have a touch event, and _only_ when you have a touch event, because you'd return `true` from it. `OnMouse*` would occur when you have a mouse event, and _only_ when you have a mouse event, because you're returning true from `OnTouch*`.

**Comment by smoogipoo** [comment]
Also, ideally what should be happening is that the propagation of both would occur in lock-step (touch -> mouse -> next drawable -> touch -> mouse -> next drawable -> etc), but that's a bit of a different discussion.

**Comment by peppy** [comment]
OnTouch is a simple one. What about OnMouseMove where we generally don't want to handle/block it? Now you have some components which are receiving two events from the same source. I don't think this is how we want to handle touch.

Let me reiterate: the idea behind the touch-to-mouse mapping is that it's *only* there for compatibility or very simple scenarios.

**Comment by smoogipoo** [comment]
I don't understand. Are you talking about explicitly handling `OnTouchDown` but expecting to receive/only handling touch position changes inside `OnMouseMove`? That sounds all kinds of wrong, and likely you shouldn't be using `OnTouch*` because `OnMouseMove` gives you no distinction.

Or are you saying that because we generally don't block in `OnMouseMove` (and `OnTouchMove`) we can potentially iterate through the hierarchy twice? Because I'm fine with that, so long as two things cannot _handle_ the same input (i.e. return `true` to the same input). If two completely separate drawables can return `true` to both of those events in the same frame, there is definitely a problem.

I don't disagree it's for compatibility. But once you handle touch input once, you also shouldn't expect your entire application to potentially break because there's some API hidden inside `InputManager` that you need to work with to make things work correctly.

**Comment by peppy** [comment]
Let's try an example then:

You can a cursor which is handling input before the gameplay (it's at a top level for argument's sake). You only want this cursor to show on mouse input, not touch. How do you do this?

**Comment by smoogipoo** [comment]
That's a different case which is not what I want fixed here. The point of this issue is that two Drawables should not be able to handle two different events from the same source.

How your scenario could be achieved, well, here's two ways:
1. You could change the type of the events passed through - instead of passing through a `MouseMoveEvent` you'd pass through a `MouseMoveFromTouchEvent` that inherits from `MouseMoveEvent`. For consumers that don't care it would be transparent, for consumers that do it would fit in with the [existing inheritance model of events](https://github.com/ppy/osu-framework/wiki/Handling-input-events#input-events), and allows individual Drawables to be concerned with making that distinction.
2. You could have the `InputManager` bool override as you said, but you'd also have to keep in mind that it is global for the hierarchy contained - meaning your cursor hierarchy cannot contain Drawables that handle both mouse-only and touch-as-mouse events.

But again, that's a different discussion.

**Comment by peppy** [comment]
I guess there's no harm in adding blocking the mouse events, I can't think of a breaking scenario.

**Comment by frenzibyte** [comment]
I was aware of these mouse-from-touch issues but didn't want the initial touch support to include even more logic for reviewing ease, so I decided to leave it as a follow-up PR.

My plan to tackle this issue (along with reading the above discussion) is by: Whenever a drawable has handled a certain touch event, no mouse input would be performed as it is useless anyways, will push a branch and PR to close this.

Also, as for the other issue, which I believe is simply about how input-reading drawables would distinguish between a normal mouse event and mouse-from-touch event: I also think @smoogipoo's first suggestion is a good one, but the indication should be in an internal-setter bool property to share between all `MouseEvent`s, for blocking other mouse events as well.

**Comment by peppy** [comment]
"should be in an internal-setter bool property to share between all MouseEvents, for blocking other mouse events as well." please elaborate as this sentence is very hard to understand

**Comment by frenzibyte** [comment]
As in like this:
```csharp
public class MouseEvent : UIEvent
{
    /// <summary>
    /// Whether the mouse input of this event has been performed from a primary touch input source.
    /// </summary>
    public bool FromPrimaryTouch { get; internal set; }

    // ...
}
```

**Comment by peppy** [comment]
why? unless there's a reason for putting it here i would be against it.

**Comment by frenzibyte** [comment]
Otherwise, each of `MouseEvent`'s derivers (`MouseDownEvent`, `DragEvent`, etc...) would need to apply the same to what smoogipoo has suggested. (`MouseDownFromTouchEvent`, `DragFromTouchEvent`, etc...)

**Comment by peppy** [comment]
Make an interface for it instead `IMouseEventFromTouchSource`

**Comment by frenzibyte** [comment]
Correct me if I'm wrong, but that sounds like it wouldn't add anything? and may even be redundant since we're still going to declare a class for each event? unless that's not a marker interface?

**Comment by peppy** [comment]
I'm so lost with your explanations. The interface would allow a consumer to block *all* touch source events, which is what I understood your last comment to be wanting.

**Comment by frenzibyte** [comment]
Is that interface going to be used per-drawable?

**Comment by smoogipoo** [comment]
What he's saying is that you can then do something like:
```
override Handle(e)
    if (e is IMouseEventFromTouchSource)
        return false;
    ...
```

**Comment by frenzibyte** [comment]
As I said and will repeat (in hopefully an understandable way), we will still add subclasses inheriting the original `MouseEvent`s right? like, this still needs to happen:
```csharp
public class MouseDownFromTouchEvent : MouseDownEvent
{
}

public class DragFromTouchEvent : DragEvent
{
}
```

---

What I'm suggesting is to provide a property to signify so, and save up doubling the length of existing mouse event classes:
```csharp
public class MouseEvent : UIEvent
{
     public bool FromPrimaryTouch { get; internal set; }
}
```
so it can be used like:
```csharp
override Handle(e)
    if (e is MouseEvent me && me.FromPrimaryTouch)
        return false;
```

**Comment by peppy** [comment]
I'm not sure where the "doubling of length" exists. If you mean the fact we have to make one deriving class per event type, I think that's completely fine?

**Comment by frenzibyte** [comment]
Ah, if that's the case then I'm fine as well then, wasn't sure at first.
