### ISSUE TITLE
Midi Timing Event f8 causes Exceptions

### ISSUE THREAD

**Issue by GenesisEB** [ppy/osu-framework#3683]
I use a Yamaha PSR-410 Piano and its midi transmission includes a timing signal for other midi devices, I cannot turn it off and it creates this repeating exception:

2020-07-03 21:42:22 [verbose]: osu 2020.629.0.0
2020-07-03 21:42:22 [verbose]: Running on Microsoft Windows NT 6.2.9200.0, 8 cores
2020-07-03 21:42:22 [verbose]: ----------------------------------------------------------
2020-07-03 21:42:22 [error]: An exception occurred while reading MIDI data from sender 1: F8
2020-07-03 21:42:22 [error]: System.IndexOutOfRangeException: Index was outside the bounds of the array.
2020-07-03 21:42:22 [error]: at osu.Framework.Input.Handlers.Midi.MidiInputHandler.readEvent(Byte[] data, String senderId, Int32& i, Byte& eventType, Byte& key, Byte& velocity)
2020-07-03 21:42:22 [error]: at osu.Framework.Input.Handlers.Midi.MidiInputHandler.onMidiMessageReceived(Object sender, MidiReceivedEventArgs e)

In the menu I can change the keybindings with the midi device, no problem. However once a song is started it seems to ignore the midi device inputs completely.

**Comment by bdach** [comment]
Not very well-versed with midi input but it seems that the midi event reading code is wrongly assuming the `0xF8` event has three bytes to read:

https://github.com/ppy/osu-framework/blob/7574a2f03f28497b60fe37d11da65811ee54ad6d/osu.Framework/Input/Handlers/Midi/MidiInputHandler.cs#L141-L142

while some online resources seem to claim [only one should be present](https://www.recordingblogs.com/wiki/midi-clock-message). In general all of the events from the range `0xF8-0xFF` [would seem to be one-byte](https://www.recordingblogs.com/wiki/midi-system-realtime-messages).

**Comment by GenesisEB** [comment]
This was kind of 2 issues, I downloaded the source and looked into it today. This issue specifically isn't causing the broken midi input.
Opening a new issue detailing the missing handling of MidiKeyInput. 

The issue with the timing signal is still valid.

**Comment by bdach** [comment]
Looking more at the other midi events, events from the range `[0xF0,, 0xF7]` are also not properly handled (and are not as easy to handle in general, as the `0xF0` event can have an arbitrary length and is delimited by a `0xF7` byte.

@HoLLy-HaCKeR As you're the original author of this code: out of curiosity, was there a particular reason why the midi event parsing was done manually instead of [using `MidiEvent.Convert()`](https://github.com/atsushieno/managed-midi/blob/311b9e354ff70d551f9cc140a19e0a400e3c4dce/Commons.Music.Midi.Shared/SMF.cs#L312-L333)? Think I'd rather reuse that than roll our own to fix this.

**Comment by HoLLy-HaCKeR** [comment]
That does seem better, if it handles rolling status. I wasn't aware that API existed, should have checked better.

I noticed there have been quite a few issues related to Midi input, so I'd like to apologize if my implementation wasn't as well tested as it should have been. I'll try to do better in the future.

**Comment by bdach** [comment]
Well, even if it doesn't, I don't see a reason why we can't do just the rolling status thing ourselves but offload the actual raw parsing to that method.

I don't think apologies are necessary, things are best tested in the real world (as has been evidenced several times with android) :wink:
