### ISSUE TITLE
Midi Input not handled by PassThroughInputManager

### ISSUE THREAD

**Issue by GenesisEB** [ppy/osu-framework#3686]
This function has no new MidiKeyInput declaration so the midi keypress isn't registering all the way over to osu.

https://github.com/ppy/osu-framework/blob/14000d688e663089c7064179d3a58f71036aa983/osu.Framework/Input/PassThroughInputManager.cs#L90

I added it in my local copy:

`case MidiEvent key:
    new MidiKeyInput(key.Key, key.Velocity, key.IsPressed(key.Key)).Apply(CurrentState, this);
    break;`

And now osu is properly registering hits with the midi keybinds.

**Comment by bdach** [comment]
Seeing that you've already gone through most of the trouble, would you like to submit that change as a PR?

**Comment by GenesisEB** [comment]
I dont have a clean repo setup so feel free to make the PR.
