### ISSUE TITLE
Scale joystick axis values according to deadzones

### ISSUE THREAD

**Issue by Jeremiidesu** [ppy/osu-framework#3712]
## Current situation

Currently, the way axis deadzones work in the framework is:

- If the current axis value is within the deadzone, the provided axis value is 0
- Otherwise, the provided axis value is the raw value

In the situation where the deadzone is large (say, 0.5), reported axis values would be as follows:

|Raw value|Provided value after deadzone application|
|---|---|
|0|0|
|0.25|0|
|0.5|0.5|
|0.75|0.75|
|1|1|

![image](https://user-images.githubusercontent.com/20820425/87251794-a6140d00-c46e-11ea-98c7-076193d67e80.png)

## My suggestion

Scaling them down as such would mitigate the sudden jumps:

|Raw value|Provided value after deadzone and scale|
|---|---|
|0|0|
|0.25|0|
|0.5|0|
|0.75|0.5|
|1|1|

![image](https://user-images.githubusercontent.com/20820425/87251808-b75d1980-c46e-11ea-9fa5-5b1b9ace93d1.png)

Here's an [interactive GeoGebra file](https://www.geogebra.org/graphing/qjuhtxnv) to help visualize the idea.

**Comment by peppy** [comment]
Definitely should be the case.
