### ISSUE TITLE
Internal members not seen in dynamic compilation

### ISSUE THREAD

**Issue by MiraiSubject** [ppy/osu-framework#3727]
Inside a visibility container (named Slide) I have an `IEnumerable<T>` (named Tiles) that gets elements added to by the Main Screen. On first compiles every time this works, but on dynamic compilation I get these compiler errors: 

```
[runtime] 2020-07-15 14:54:00 [error]: Error with dynamic compilation!
[runtime] 2020-07-15 14:54:00 [error]: System.AggregateException: One or more errors occurred. (/Users/subject/DevProjects/csharp/10foot/Launcher.Game/Screens/MainScreen.cs(44,29): error CS0117: 'Slide' does not contain a definition for 'Tiles')
[runtime] 2020-07-15 14:54:00 [error]: ---> System.InvalidOperationException: /Users/subject/DevProjects/csharp/10foot/Launcher.Game/Screens/MainScreen.cs(44,29): error CS0117: 'Slide' does not contain a definition for 'Tiles'
[runtime] 2020-07-15 14:54:00 [error]: --- End of inner exception stack trace ---
[runtime] 2020-07-15 14:54:00 [error]: at osu.Framework.Testing.DynamicClassCompiler`1.recompileAsync(Type targetType, String changedFile)
```

These errors happen whenever I modify anything in `Tiles`, like this: 

```csharp
    mainSlide = new Slide
    {
        Anchor = Anchor.BottomCentre,
        Origin = Anchor.BottomCentre,
        Tiles = new[]
        {
            new Tile
            {
                Text = "Test 2",
                Action = null,
            }
        }
    }
```

in the Slides class this is how it gets initialised:

```csharp
public class Slide : ControllableVisibilityContainer, IKeyBindingHandler<InputAction>
    {
        internal IEnumerable<ControllableButton> Tiles;
```

Setting it to `public` or `public get internal set` works around this, but is this intended behaviour?

In the back of my head it kind of makes sense because `VisualTests` is in a different assembly and that is trying to get from the Enumerable on dynamic recompilation.

I have a private GitHub repo that I can invite anybody to that can look into this for reproduction if necessary.

Tested on `2020.714.1` on macOS

**Comment by smoogipoo** [comment]
Unfortunately, this is intended. `internal` is a very strong pain point for dynamic compilation, since we're promoting some types to a new assembly but leaving `internal` types in another.
It's something that we can potentially fix in the future (requires fixing all other type resolution issues) so I'll keep this open, but the suggested solution is to always use `public` unless you absolutely need `internal`.

**Comment by MiraiSubject** [comment]
Alright, thanks for letting me know!

**Comment by peppy** [comment]
This should definitely be added to the wiki page for dynamic compilation.

**Comment by frenzibyte** [comment]
Should be resolved with https://github.com/ppy/osu-framework/pull/4006.
