### ISSUE TITLE
Sample does not play when in the game.

### ISSUE THREAD

**Issue by clyde-not-found** [ppy/osu-framework#3784]
I was testing the framework's audio, and when I put an .ogg to play, it just doesn't play. The file is in the right place, and if I start a music player from my computer it will play fine. But in the framework it doesn't touch.

```cs
using osu.Framework.Allocation;
using osu.Framework.Graphics;
using osu.Framework.Graphics.Audio;
using osu.Framework.Graphics.Textures;
using osu.Framework.Input.Events;
using osu.Framework.IO.Stores;
using osu.Framework.Logging;
using osu.Framework.Screens;

namespace Sandbox.Game
{
    public class SandboxGame : SandboxGameBase
    {
        private ScreenStack screenStack;

        private DrawableSample jumpSound;

        public static TextureStore GTextureStore { get; private set; }

        [BackgroundDependencyLoader]
        private void load()
        {
            jumpSound = new DrawableSample(Audio.Samples.Get("jump.ogg"));
            
            GTextureStore = new TextureStore(Textures, filteringMode: osuTK.Graphics.ES30.All.Nearest);
            Fonts.AddStore(new GlyphStore(Resources, @"Fonts/SuperMarioWorld"));

            // Add your top-level game components here.
            // A screen stack and sample screen has been provided for convenience, but you can replace it if you don't want to use screens.
            Child = screenStack = new ScreenStack { RelativeSizeAxes = Axes.Both };
        }

        protected override bool OnKeyDown(KeyDownEvent e)
        {
            if (e.Key == osuTK.Input.Key.Space)
            {
                jumpSound.Play();
                Logger.Log($"Jump Sound State: {jumpSound.Playing}");
            }

            return base.OnKeyDown(e);
        }

        protected override void LoadComplete()
        {
            base.LoadComplete();

            screenStack.Push(new MainScreen());
        }
    }
}
```

I see the state of the audio and it says it's playing on the Logger.

In fact, neither the Flappy template nor the audio doesn't play, and I didn't even touch anything in the template.

Does anybody know how to solve this?

**Comment by bdach** [comment]
That suggests a general audio failure as the flappy-don template should be playing sounds. Could you attach logs from either your game or the template for inspection? Also, would you happen to be running linux?

**Comment by clyde-not-found** [comment]
No, I am running on Windows. Where do I find these logs?

**Comment by bdach** [comment]
Should be somewhere under `%AppData%/${YOUR_PROJECT_NAME_HERE}` (`Sandbox`?)

**Comment by peppy** [comment]
In the provided code you have not added the sample to the hierarchy.

**Comment by clyde-not-found** [comment]
[performance-update.log](https://github.com/ppy/osu-framework/files/5022943/performance-update.log)
[runtime.log](https://github.com/ppy/osu-framework/files/5022944/runtime.log)
[performance.log](https://github.com/ppy/osu-framework/files/5022945/performance.log)
[performance-draw.log](https://github.com/ppy/osu-framework/files/5022946/performance-draw.log)
@bdach here the Sandbox log files

@peppy How to add the sample in the hierarchy?

**Comment by bdach** [comment]
The log is showing a BASS initialisation header so audio should be working for all intents and purposes.

Adding the sample to the drawable hierarchy is kind of self-explanatory - you add it to a screen or container, the same way the sample game and the tests do:

https://github.com/ppy/osu-framework/blob/3ed9af1937885fd73ea18017e39eb95c7f09f933/osu.Framework.Tests/Visual/Audio/TestSceneSamples.cs#L171-L175

https://github.com/ppy/osu-framework/blob/e6fa465fb7b20e7e1a3b0d91e7bbec882c958ba6/osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/Elements/Bird.cs#L75

**Comment by clyde-not-found** [comment]
**System.ArgumentNullException:** *'Value cannot be null. '*
```cs
AddInternal(jumpSound = new DrawableSample(samples.Get("Samples/jump.ogg")));
```

he keeps giving this error in my class

**Comment by bdach** [comment]
okay, yes, maybe not *word for word* like the examples i cited. i mostly meant the `Add()` call, dependency injection is a separate thing entirely and it doesn't work at the game level like that. please read [this article](https://github.com/ppy/osu-framework/wiki/Dependency-Injection) for info.

for now please try getting the sample via the `Audio.Samples.Get()` method you used earlier, and i'm also reasonably certain the `Samples/` prefix in the path is not necessary. all things considered it would be way easier if you put your code in a place where it could be viewed/cloned instead of us trying to whack-a-mole at what the problem is.

**Comment by clyde-not-found** [comment]
But why the hell does the Flappy Game sound not play if I haven't changed anything about it?

**Comment by bdach** [comment]
* have you got your example to a working state?
* the framework automatically chooses an audio device for playback out of all the devices available on your machine; sometimes it can happen that it will select an undesirable one by default. in your case the chosen device seems to be

  ```
  Realtek Digital Output(Optical) (Realtek High Definition Audio)
  ```

  please confirm whether that is your primary output audio device, and if not, try temporarily disabling the aforementioned one and seeing if the game selects another, more appropriate device. the choice is stored in `%AppData%/${GAME_NAME}/framework.ini`, under the `AudioDevice` key, but I wouldn't recommend entering a value manually.

**Comment by peppy** [comment]
Can you confirm you fixed your issue?

**Comment by clyde-not-found** [comment]
Oh I'm sorry, I managed to solve it, I just installed the audio driver again and it worked. Thank you for your help!
