### ISSUE TITLE
Auto-detect joystick axis origins 

### ISSUE THREAD

**Issue by Jeremiidesu** [ppy/osu-framework#3802]
Currently, each axis' origin is its center which makes sense for analog sticks, but not for triggers.

Trigger origins are often on one end or the other of the axis currently, which, along with the current automatic deadzone system, renders these triggers unusable. 

My suggestion: detect the axis origin at the same time as the deadzone, by taking the origin to which it is the closest to (whether `-1`, `0`, or `1`)

Examples:

Analog sticks' resting positions are centered, auto-detection should therefore use an origin of `0`.
Triggers' resting position are on the `-1` end of the axis, therefore, their origin should be auto-detected to `-1`.

That being said, SDL would remove the need for such detection given that triggers seem to be handled directly at SDL level if we look at #3708 as well as this piece of documentation:
https://wiki.libsdl.org/SDL_GameControllerAxis // https://wiki.libsdl.org/SDL_GameControllerGetAxis

**Comment by peppy** [comment]
This should now be resolved via #3900 (with `--sdl` enabled). Going to tentatively close - please comment if you have an issue with a specific controller.
