### ISSUE TITLE
Transforms affecting overlapping target members do not combine correctly

### ISSUE THREAD

**Issue by bdach** [ppy/osu-framework#3817]
Originally reported by @LumpBloom7 [on discord](https://discord.com/channels/188630481301012481/188630652340404224/743152124757803049).

To explain the title: applying transforms simultaneously on i.e. `Y` and `Position` does not work properly due to the per-member tracker separation done in #3779.

Minimal reproducer example is:

```csharp
        [Test]
        public void TestMultipleTransformTargets()
        {
            boxTest(box =>
            {
                box.Delay(500).MoveToOffset(new Vector2(0, 0.25f), 500);
                box.MoveToY(0.5f, 250);
            });

            checkAtTime(double.MinValue, box => box.Y == 0);
            checkAtTime(0, box => box.Y == 0);
            checkAtTime(250, box => box.Y == 0.5f);
            checkAtTime(750, box => box.Y == 0.375f);
            checkAtTime(1000, box => box.Y == 0.25f);
            checkAtTime(1500, box => box.Y == 0.25f);
            checkAtTime(750, box => box.Y == 0.375f);
        }
```

(stick it in `TestSceneTransformRewinding` to see the failure - it should fail at the last step; you can also run the first two steps manually in test browser to see it break in real time on rewind). Debug shows the following:

![2020-08-12-221106_705x478_scrot](https://user-images.githubusercontent.com/20418176/90062966-ddcdd900-dce8-11ea-9c99-e20912a93386.png)

<hr>

Opening mostly for paper trail. I might circle back to look at how to fix this properly but as I'm reasonably certain this will not be related to the game-side follow point regression that I want to look into first and foremost so I don't want this to get lost.

**Comment by peppy** [comment]
I knew there was going to be *something* which relied on transforms all being in one list. Now it's time to brainstorm how to resolve this one. The simplest solution would be to combine, reorder, then reapply transforms to be rewinded (only changes performance characteristics during rewind) so I might go with that initially unless anyone has a better idea?

**Comment by bdach** [comment]
I'm not sure that any solution that doesn't combine `Position`, `X` and `Y` trackers entirely is valid. Don't have a confirmed counterexample to prove it but I think forward application of transforms can also suffer from bugs resulting from processing the separated trackers in creation order.

**Comment by peppy** [comment]
Yeah, may be the case.

So we need to somehow define all targets affected for the cases of shared application, and store them to the same tracking instances. The easiest way sounds like introducing a new overrideable that lets us group by something other than `TargetMember` (but defaults to `=> TargetMember`)

**Comment by bdach** [comment]
That sounds like a good direction to me.

**Comment by peppy** [comment]
@bdach in your test, did you get the check numbers wrong?

```csharp
            checkAtTime(0, box => box.Y == 0);
            checkAtTime(250, box => box.Y == 0.5f);
            checkAtTime(750, box => box.Y == 0.625f);
            checkAtTime(1000, box => box.Y == 0.75f);
            checkAtTime(1500, box => box.Y == 0.75f);
            checkAtTime(750, box => box.Y == 0.625f);
```

is more what i'd expect...?

**Comment by peppy** [comment]
Ah, I think you meant to be using `MoveTo()`, not `MoveToOffset()`

**Comment by peppy** [comment]
No, apparently your logic is correct as `MoveToOffset()` ignores `MoveToX` / `MoveToY`. I'm just going to pretend I didn't see that for now....

**Comment by bdach** [comment]
Yep, I was also confused by that at first. For the test case `MoveTo` should be fine; I mostly used it as the reported fail case did so too.
