### ISSUE TITLE
Seeking a non-loaded animation throws a NullReferenceException

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#3847]
```
[runtime] 2020-08-26 11:05:26 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
[runtime] 2020-08-26 11:05:26 [error]: at osu.Framework.Graphics.Transforms.Transformable.get_Time()
[runtime] 2020-08-26 11:05:26 [error]: at osu.Framework.Graphics.Animations.AnimationClockComposite.consumeClockTime()
[runtime] 2020-08-26 11:05:26 [error]: at osu.Framework.Graphics.Animations.AnimationClockComposite.set_PlaybackPosition(Double value)
[runtime] 2020-08-26 11:05:26 [error]: at osu.Framework.Graphics.Animations.AnimationClockComposite.Seek(Double time)
[runtime] 2020-08-26 11:05:26 [error]: at osu.Framework.Graphics.Animations.Animation`1.GotoFrame(Int32 frameIndex)
```

The code that throws this looks pretty inconspicuous:
```csharp
if (lightContainer != null)
{
    if (isHitting.NewValue)
        Column.TopLevelContainer.Add(lightContainer);
    else
        Column.TopLevelContainer.Remove(lightContainer);

    if (light is TextureAnimation lightAnimation)
        lightAnimation.GotoFrame(0);
}
```
The issue is that `GotoFrame()` throws the nullref in the case that the animation is not loaded, which requires the above code to be transformed into:
```csharp
if (lightContainer != null)
{
    if (isHitting.NewValue)
    {
        Column.TopLevelContainer.Add(lightContainer);

        if (light is TextureAnimation lightAnimation)
            lightAnimation.GotoFrame(0);
    }
    else
        Column.TopLevelContainer.Remove(lightContainer);
}
```

**Comment by bdach** [comment]
Sounds like we might just want to throw a guard in to not touch the clock if the drawable isn't loaded?

https://github.com/ppy/osu-framework/blob/598494e8e9f0a8bbd19dba8981d05eaa81851203/osu.Framework/Graphics/Animations/AnimationClockComposite.cs#L82-L98

Or even in `consumeClockTime` itself - does it make sense to consume time during load?

**Comment by smoogipoo** [comment]
Would that work for `GotoFrame` with a non-zero frame? I think that's a thing that should be supported.

**Comment by bdach** [comment]
I *think* it should? As long as the manual clock receives the value it should be ok. The consume is just to avoid additional time leaps on top of the seek I'm pretty sure.

I'll go and actually have a look on my own.
