### ISSUE TITLE
Sub-menus should not overflow outside the parenting bounds

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#3861]
Top-level menus clamp to the sides of the parenting container, but their sub-menus do not. Example:

![image](https://user-images.githubusercontent.com/1329837/91988304-14d45f00-ed6a-11ea-8f5f-4c42269ca2f6.png)

Not sure if clamping makes sense as it does for the top-level menu as opposed to it appearing on the other side.

**Comment by MiraiSubject** [comment]
fwiw sub menus in context menus on Windows and macOS appear on the left side when it's close to the right edge of the monitor. Haven't used any Linux DE extensively enough to say that they have the same behaviour.

**Comment by Corne2Plum3** [comment]
![osu_2021-05-13_21-40-07](https://user-images.githubusercontent.com/57914482/118185074-66c29e00-b43c-11eb-9e3f-682bb5912cb2.png)

I have this bug with the new skin editor.

Version: 2021.514.0

**Comment by bdach** [comment]
yes, we are aware. see link to game-side issue directly above your comment.
