### ISSUE TITLE
Proposal for the templates.

### ISSUE THREAD

**Issue by rubiksmaster02** [ppy/osu-framework#3862]
Change out 
`using GameHost host = Host.GetSuitableHost($"AppName");`
with
`using GameHost host = Host.GetSuitableHost(nameof(AppName));`

**Comment by frenzibyte** [comment]
What is this useful for? also a PR would have been definitely better for such a one-liner non-behaviour-affecting suggestion.

**Comment by frenzibyte** [comment]
https://github.com/ppy/osu-framework/blob/master/osu.Framework.Templates/templates/template-empty/TemplateGame.Desktop/Program.cs#L11

**Comment by rubiksmaster02** [comment]
Because you should almost never hardcode strings, especially when they are meant to represent a name of something.

**Comment by frenzibyte** [comment]
That string is meant to be for putting the actual name of your own game on (i.e. with symbols that can't be added to the project name, e.g. `osu!`), not the codename or the project namespace, that's likely the reason it doesn't use `nameof`, not because it can be it must be.

**Comment by peppy** [comment]
As mentioned, it is correct the way it is. It's not supposed to represent the class name but the user-facing name of your game/application.
