### ISSUE TITLE
ChildrenOfType<> test extension should support arbitrary types

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#3872]
There's no reason someone shouldn't be able to do `ChildrenOfType<IHasText>().First()`, but currently the entire extension method sits behind a `where T : Drawable` constraint making this impossible.

**Comment by UselessToucan** [comment]
Is it enough to support types from osu! projects? Or any BCL type(for example, `IEnumerable`) must be supported?

**Comment by smoogipoo** [comment]
Support all types and call it a day.
