### ISSUE TITLE
The Resources Store for Tracks and Samples is not working.

### ISSUE THREAD

**Issue by zenpakuh** [ppy/osu-framework#3914]
Good morning, I'm learning to use osu! Framework, and I tried to learn to use his audio. But I was looking at the documentation and it says:

```
Game will automatically create the following stores that point to the respective paths for each store:

/Textures (TextureStore)
/Tracks (AudioManager.Track)
/Samples (AudioManager.Sample)
/Shaders (ShaderManager)
/Fonts (FontStore)
```

Okay, I set up the resource project folders for me to put an amazing theme song for my game.

But when I put:

```cs
        private ISampleStore sampleManager;
        private ITrackStore trackManager;

        [BackgroundDependencyLoader]
        private void load(AudioManager audio)
        {
            AddRangeInternal(new Drawable[]
            {
                ...its work...
            });

            sampleManager = audio.Samples;
            trackManager = audio.Tracks; // and
            Track myTrack = trackManager.Get("mainmenu");
            myTrack.Looping = true; // the error is caused by that line
        }
```

The game hits me right off the bat like this:

```diff
- System.NullReferenceException: 'Object reference not set to an instance of an object.'

- myTrack was null.
```

I tried all the ways, check if the folders are correct, the names of the files, but nothing works!

![image](https://user-images.githubusercontent.com/49321124/94991744-63d50600-055b-11eb-8506-6bb1eab8b3bb.png)
![image](https://user-images.githubusercontent.com/49321124/94991749-6899ba00-055b-11eb-934d-e579a1cddd8b.png)

**OBS**: This is a fan game for Super Mario World! :3

**Comment by bdach** [comment]
To clarify, what is your project structure? Do you have a separate project for the `Game` itself and a separate project for the resources?

If so, did you make sure to register the appropriate `DllResourceStore`, as done in the FlappyDon template?

https://github.com/ppy/osu-framework/blob/e6fa465fb7b20e7e1a3b0d91e7bbec882c958ba6/osu.Framework.Templates/templates/template-flappy/FlappyDon.Game/FlappyDonGameBase.cs#L22-L23

**Comment by zenpakuh** [comment]
Yes, I did, and there is a resource project that the template itself generates from the game.

Here the file where I imported the resource project:

```cs
    public abstract class PlatformGameBase : osu.Framework.Game
    {
        private TextureStore textures;
        private PixelTextureStore pixelTextures;
        private LevelAudioManager levelAudioManager;

        private DependencyContainer dependencies;

        [BackgroundDependencyLoader]
        private void load(FrameworkConfigManager config)
        {
            Resources.AddStore(new DllResourceStore(PlatformResources.ResourceAssembly));

            textures = new TextureStore(Textures);
            pixelTextures = new PixelTextureStore(Textures);

            dependencies.Cache(textures);
            dependencies.Cache(pixelTextures);

            var tracks = new ResourceStore<byte[]>();
            tracks.AddStore(new LevelAudioStore());

            levelAudioManager = new LevelAudioManager(Host.AudioThread, tracks, new ResourceStore<byte[]>())
            { EventScheduler = Scheduler };

            dependencies.Cache(levelAudioManager);

            config.GetBindable<FrameSync>(FrameworkSetting.FrameSync).Value = FrameSync.Unlimited;

            Host.Window.Title = "Platform Game";
        }

        protected override IReadOnlyDependencyContainer CreateChildDependencies(IReadOnlyDependencyContainer parent)
            => dependencies = new DependencyContainer(base.CreateChildDependencies(parent));
    }
```

**Comment by bdach** [comment]
Did you try explicitly specifying the extension of the audio file (as in `mainmenu.mp3`)? I'm pretty sure it's required.

**Comment by zenpakuh** [comment]
As I said, I tried anyway, not even putting the extension with the name it doesn’t stick.

I also tried to check the number of tracks that the Audio Manager took, I put it like this: 
```cs
Logger.Log(message: $"COUNT: {audio.Tracks.GetAvailableResources().ToList().Count});
```

and returned zero.

**Comment by bdach** [comment]
do you have a repository i can check out or something? it's counterproductive for me to do remote debugging over github comments.

**Comment by zenpakuh** [comment]
I don't have a repository with this, but I will send it now.

**Comment by zenpakuh** [comment]
https://github.com/zenpakuh/platform @bdach

**Comment by bdach** [comment]
I'm not seeing an exception after cloning here, the track is returned (and even started, if I start it) correctly.

**Comment by zenpakuh** [comment]
Uai, how so? Why doesn't mine return?

**Comment by zenpakuh** [comment]
![image](https://user-images.githubusercontent.com/49321124/94992872-4e63da00-0563-11eb-8fec-5dbe620b1f18.png)

**Comment by zenpakuh** [comment]
I cloned the repository, compiled the project and returned the track.

**Comment by zenpakuh** [comment]
I managed to fix it! Thanks a lot for the help!
