### ISSUE TITLE
Add sprite sheet system to the framework

### ISSUE THREAD

**Issue by zenpakuh** [ppy/osu-framework#3918]
It would be easier to separate sprites using Spritesheet, to separate these textures from one another and place them inside an Array to get each one.

It's a pretty stupid suggestion. However, I tried to implement this system, but I don't know the properties of the "Sprite" component so well.

It would be more or less like that, an object called SpriteSheet and that in the constructor put the original texture where it contains the image of the spritesheet, and it would have a method called Slice, and that has parameters of "crop size", "offset" and everything, after he would put everything separate in an Array, where we can get the separate sprites.

That way it would be easier to make animations or other things.

**OBS:** I don't know if I can make suggestions here, if not, is there a place where I can do that?

**Comment by bdach** [comment]
I don't know that a sprite sheet system is all that necessary to add to the framework. We already do texture atlassing internally (press <kbd>Ctrl</kbd>+<kbd>F3</kbd> to have a look), so from a performance standpoint you can just use single images and get roughly the same result.

I guess it could be a nice convenience feature, however, to at least allow *importing* assets from sprite sheets which we would then reatlas internally (so basically just read an asset file and an XML description of the sprite extents, and blit the sheet sprites onto our own atlas implementation). We don't really have a pressing need for things like that game-side, however, so I wouldn't say such a feature would be likely to make it in anytime soon.

**Comment by peppy** [comment]
The only reason I can think of here is to support some common sprite sheet format which other apps export to. Is that the use case @zenpakuh?

**Comment by zenpakuh** [comment]
> The only reason I can think of here is to support some common sprite sheet format which other apps export to. Is that the use case @zenpakuh?

Yes!!

**Comment by peppy** [comment]
Could you mention which format/application you are using?

**Comment by zenpakuh** [comment]
> Could you mention which format/application you are using?

Krita, Photoshop and Aseprite.
All formats are PNG.

**Comment by zenpakuh** [comment]
Anyway, I managed to create a system that separates the sprites from a spritesheet, all that was needed was to use the "Crop" function of the "Texture" class. Thank you!
