### ISSUE TITLE
TextBox crashes if Current is disabled after a Text set

### ISSUE THREAD

**Issue by bdach** [ppy/osu-framework#3919]
Found while looking at ppy/osu#10412.

Given the following test case (place in `TestSceneTextBox`):

```csharp
[Test]
public void TestTextAndCurrent()
{
    InsertableTextBox textBox = null;

    AddStep("add textbox", () =>
    {
        textBoxes.Add(textBox = new InsertableTextBox
        {
            Size = new Vector2(200, 40),
            Text = "hello"
        });
    });

    AddStep("set text and disable current", () =>
    {
        textBox.Text = "goodbye";
        textBox.Current.Disabled = true;
    });
}
```

the result is a crash to desktop with the following stack trace:

```
Unhandled exception. System.InvalidOperationException: Can not set value to "" as bindable is disabled.
   at osu.Framework.Bindables.Bindable`1.set_Value(T value) in /home/dachb/Dokumenty/opensource/osu-framework/osu.Framework/Bindables/Bindable.cs:line 95
   at osu.Framework.Graphics.UserInterface.TextBox.updateCursorAndLayout() in /home/dachb/Dokumenty/opensource/osu-framework/osu.Framework/Graphics/UserInterface/TextBox.cs:line 333
   at osu.Framework.Graphics.UserInterface.TextBox.UpdateAfterChildren() in /home/dachb/Dokumenty/opensource/osu-framework/osu.Framework/Graphics/UserInterface/TextBox.cs:line 353
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in /home/dachb/Dokumenty/opensource/osu-framework/osu.Framework/Graphics/Containers/CompositeDrawable.cs:line 875
```

It's not a blocker for the issue, since there was another problem game-side, but this really ought to get fixed, as there's still a possibility for the game to hit this and I can't get to it today, so opening for tracking.

Yet another reason to dive into `TextBox`, I guess?

**Comment by peppy** [comment]
Had an attempt at fixing this but it's not gonna be a simple one. Stopping the crash is easy enough (add a `Current.Disabled` check at one of two valid points) but it will leave the textbox's current text in a non-synced state.

I think the valid path forward is reassessing why we have this schedule logic in the first place, and doing a rewrite/refactor of the class to fix it up. Probably not a low-effort fix, so if we decide the stopping the crash short-term is for the best I can commit the fix, but it will still fail the final assert:

![image](https://user-images.githubusercontent.com/191335/95412533-20680680-0964-11eb-9cc2-2569957fa68b.png)

**Comment by bdach** [comment]
I've come up with [this branch](https://github.com/ppy/osu-framework/compare/master...bdach:fix-disable-textbox-crash) - while it's not the cleanup/rewrite we're yearning for, it feels like maybe an incremental improvement due to:

* tying `ReadOnly` and `Current.Disabled` together (were entirely uncoupled)
* improving `Current` value transfer a little (that `textAtLastLayout != text` check is really headache-tier as far as I'm concerned)
* and finally fixing the issue.

I prodded the schedule from a few other angles but got no luck, and it's been there from [the very first version, still osu!-side, back in 2016](https://github.com/peppy/osu/commit/b3e233917524f9adc6df5cb778b888f829bd9976), so I'm *very* worried about touching it more...
