### ISSUE TITLE
IWindow hierarchy needs serious refactoring

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#3990]
Currently working with (trying to follow control flow) `IWindow` is nigh impossible.

I've tried twice now to refactor it but it's too complex to handle, so a rewrite from scratch may be the better approach. This *needs* to happen before progressing further with SDL2.

The issues I ran into while trying to do this:

- Knowing what actually works (and is implemented via SDL). A lot of properties, bindables etc. exist but aren't actually hooked up. But due to all the control flow there's 2-4 events/methods/bindables related to them to the point it can take over a minute of following the trail to understand if they are being used or actually have an implementation anywhere
- Keeping mental track of the flow and correctly moving implementation across from `WindowBackend` to `Window`. Especially difficult when implementation exist as bindables at one side and properties at the other.
- The urge to destroy things from dealing with the code (may be a personal issue).

My best effort is on [this branch](https://github.com/ppy/osu-framework/compare/master...peppy:remove-window-backend?expand=1) but likely won't be useful for anyone looking at this issue in the future (myself included).

Proposals:

- Imperative: `IWindowBackend` is removed. There's no need for this to exist and it is the main issue. The implementation should be in `Window`/`DesktopWindow`.
- Optional: Remove `OsuTK` completely. This can be done if it's seen to ease the process of refactoring the hierarchy in general. This would see the removal of `IGameWindow`.
- Optional: All non-bindables should be converted to bindables in `IWindow`/`Window`. Things like `CursorState` and `VerticalSync`
- Optional: Remove all properties/bindables which aren't consumed by the framework. Bring implementation down to the MVP to allow the refactor to be completed.

**Comment by smoogipoo** [comment]
@swoolcock because it's been long forgotten - what was the reason for having `IWindowBackend` in the first place?

**Comment by swoolcock** [comment]
> @swoolcock because it's been long forgotten - what was the reason for having `IWindowBackend` in the first place?
So that we can use a different windowing implementation on non-desktop platforms if required.

**Comment by bdach** [comment]
There was this ole diagram that seems to have been eaten up in the edit history of #2448 that's perhaps demonstrative to the idea:

![obraz](https://user-images.githubusercontent.com/20418176/98649115-7f3fe780-2337-11eb-84e6-3276894bc3f9.png)

**Comment by peppy** [comment]
Interestingly, that diagram doesn't have the `WindowBackend` even listed. Which is good, because my argument is that it's a pointless level of redirection (there's small chance of a `Window` implementation using two different `WindowBackend`s).

Note that I have nothing against the graphic backend because there may be value in that in the future (and it doesn't come with the same insane control flow obfuscating burden that `WindowBackend` has).

**Comment by smoogipoo** [comment]
Regarding the graphics backend - it's also currently sitting inside the window which I'm not fine with.

**Comment by peppy** [comment]
yeah, should be moved out. with my changes there was zero usage in the window (apart from passing `this` into it) so shouldn't be a huge deal compare to the rest of the refactor.
