### ISSUE TITLE
TextAwesome Crashes

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-framework#4]
When trying to draw to any value casted to a string using ToString(), TextAwesome triggers the assert found in TextrureGLSub.cs
![Code](http://i.imgur.com/I3vYeVr.png)

The error message:
![Error](http://i.imgur.com/lQ6J7sz.png)

**Comment by peppy** [comment]
Known issue. Textures are being finalised from the cache calls in the ctor of SpriteText.

I'm in the process of refactoring text rendering, and already have a fix for this.

**Comment by peppy** [comment]
This should be resolved.
