### ISSUE TITLE
Proposal: Add WASAPI support (Low priority)

### ISSUE THREAD

**Issue by jaeeonr** [ppy/osu-framework#400]
We should be able to implement WASAPI rather easily.
https://managedbass.github.io/api/ManagedBass.html

I tried for a few hours and I hit the wall hard but it's probably because I'm not skilled enough. I could ask a million question but why bother when somebody else can do it for a tiny fraction of time one would spend answering me...

While Directsound only adds about 10 milliseconds of delay in most desktops, some laptops and tablets come with weird OEM-customized sound driver implementation that can add hundreds of milliseconds of delay depending on how poorly written the driver is. WASAPI is the only hope for these people.

**Comment by peppy** [comment]
You're welcome to submit a WASAPI implementation. We don't need proposals like this open though.
