### ISSUE TITLE
App freezes if it has no focus for ~6 seconds (using SDL)

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-framework#4004]
**Describe the issue:** If you keep the window without focus for ~6 seconds (using `--sdl`), Windows (10, in my case) says that the application is not responding, but you can still hear that the app is running (with music, for example).

**Screenshots or videos showing encountered issue:**
- [Here's an example with osu!lazer](https://drive.google.com/file/d/1Kk0Z4IfatTeGUHlK2Sg1T4cJhBJUC1hy/view?usp=sharing)

**Useful details:**
- Threading mode: Multithreaded
- Frame limiter: 2x refresh rate

**Comment by peppy** [comment]
Are you able to check with the latest window changes (https://github.com/ppy/osu-framework/pull/3996)? I can't reproduce this.

**Comment by Joehuu** [comment]
Also using windows 10.

Normal release of osu!lazer with `--sdl`: can reproduce

`master` framework visual tests with `--sdl`: can reproduce

Linked PR: can reproduce

Linked PR with `--tk`: cannot reproduce

---

After more testing, opening file explorer fixes the freeze but will freeze after unfocused for >6 seconds again.

**Comment by peppy** [comment]
Gonna need more information.

Either a view of threads in visual studio / rider when this happens (pause execution and take a screenshot is fine) or a process dump from task manager (make sure you're doing this from framework visual tests if you share it publicly, so it doesn't contain any confidential information).

Also just a hunch, but last time this kind of behaviour came up it was related to the alt key being pressed. Can you also confirm that this happens just by clicking away from the window?

**Comment by Joehuu** [comment]
Oddly enough, I can't reproduce on rider debug, only run. Maybe a reason why you can't reproduce it? Will send framework dump (~400mb(?)) later if that's not the case.

> Can you also confirm that this happens just by clicking away from the window?

Yep.

**Comment by peppy** [comment]
Okay I managed to reproduce, but it seemingly took much more than 6 seconds.

**Comment by Joehuu** [comment]
FWIW, this regressed in https://github.com/ppy/osu-framework/pull/3986, so it was recent.

**Comment by peppy** [comment]
Thanks, that helps a lot. May actually be an upstream issue in that case.

**Comment by peppy** [comment]
Have confirmed this only happens with nightly releases (dating back to the first one available via buildbot).

Reported here to figure out a path forward, will roll back the release we're using for now. https://discourse.libsdl.org/t/nightly-builds-freezing-on-windows-focus-loss/28359
