### ISSUE TITLE
SDL doesn't change resolution when window is maximized or screen mode is changed

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-framework#4033]
(on Windows 10)
![sdl window](https://user-images.githubusercontent.com/43073074/100091313-babcd480-2e54-11eb-99c2-5e4e2f11407a.gif)

Looks like it keeps the last windowed resize:
![resize](https://user-images.githubusercontent.com/43073074/100091718-49315600-2e55-11eb-86fd-94ba7014f5ef.gif)

**Comment by peppy** [comment]
Already fixed in https://github.com/ppy/osu-framework/pull/4013
