### ISSUE TITLE
Touch screen does not work on Linux

### ISSUE THREAD

**Issue by SysError99** [ppy/osu-framework#4046]
**Describe the bug:** 
Can't interact with anything on the screen using touch input on KDE Plasma Desktop 5

**Screenshots or videos showing encountered issue:** 
![an image of screenshot of KDE plasma desktop with osu!lazer running](https://i.postimg.cc/SQ2P7020/Screenshot-20201201-005008.png)

**osu!lazer version:** 
2020.1121.0 Linux AppImage
**Logs:**

**Additional notes:**
OS: KDE neon with Plasma 5.18.6, Framework Version 5.76.0, Qt version 5.15.1, NVIDIA Optimus Driver Version 455.38 GLX version 1.4 (Linux x86_64 5.4.0-54-generic)
Touch screen: Elan Microelectronics Corp. Touchscreen, Generic Human Interface Device Driver (builtin)

**Comment by peppy** [comment]
Does your touch input work with all other applications on your system? Usually a windowing system will map touch to mouse for the majority of applications which don't specifically implement touch support (and this should also work in lazer/framework).

**Comment by SysError99** [comment]
Yes, all other applications work properly (tested with basic UI interactions, Chromium and Firefox), but not on Osu! I guess it occurs with some of desktop environments. I will try on other distributions to see if it does happened on others too.

**Comment by SysError99** [comment]
Update: Tested again on 2020.1203.0, it's now working flawlessly again! Closing this issue.
