### ISSUE TITLE
Add a built in latency benchmark

### ISSUE THREAD

**Issue by Snowmander** [ppy/osu-framework#4047]
As the game is reaching maturity, I want to suggest a way to easily benchmark audio latency in software, as more testing will likely be required if WASAPI exclusive mode were to be implemented.

Here's the process I've been using on stable:

1. Put a microphone near a mouse and a headphone
2. Disable music track and make a custom hitsound with no lead in time and is obnoxiously loud
3. Get into a custom beatmap I've made, click the mouse hard on the hitcircles, and record the two sounds. Repeat several times.
4. Analyze the time delta in audacity.

My proposal:

A button to be pressed with a mouse (or a keyboard) which will produce a loud pure tone beep hitsound using the same code pathway that an ingame hitsound would take.

The tester will still need to manually determine the latency in audacity as I can't imagine a way to automate this.

**Comment by bdach** [comment]
Not sure why this was opened in framework. Also this "benchmark" seems quite useless - if you need external tools to measure anyway, you might as well measure against keystrokes in textboxes or something.

**Comment by smoogipoo** [comment]
This does not sound like something we'd want in either the game or o!f. You can code something like this in 5 minutes, but that doesn't mean it's something that should be integrated in any way.

**Comment by peppy** [comment]
The method hasn't changed for decades: set latency as low as you can until you hear underrun artifacts. Shouldn't require any special test as the menu music should be enough to discern this. This can be explained in a simple descriptive text next to the setting once we have that UI in place.
