### ISSUE TITLE
Held mouse buttons aren't updated when the cursor is outside of the window

### ISSUE THREAD

**Issue by Morilli** [ppy/osu-framework#4055]
To reproduce:
(0. use windowed mode)
1. hold any mouse button
2. leave the game window

The mouse button state should be updated, but isn't until the cursor returns to the window. This can be seen in the visual tests already.

**Comment by peppy** [comment]
This is another case where it's not going to be something we can fix locally without bypassing SDL for input handling. We're not doing anything special around this code that could result in this behaving this way.
