### ISSUE TITLE
Cursor can interact with windows taskbar with SDL enabled

### ISSUE THREAD

**Issue by Pennek** [ppy/osu-framework#4066]
Opening a separate issue for part of https://github.com/ppy/osu/issues/10927
I am able to interact with the windows taskbar while the game is running on top

Sadly, I can't capture much of a meaningful video as obs blackscreens whenever the application window is switched (Eg. the taskbar is interacted with and game minimizes). I am running osu! in fullscreen with 2x refresh rate, and multithreading enabled. If I run with `--tk` the taskbar also shows.

Specs:
- AMD Ryzen 7 3700X
- NVIDIA GeForce RTX 2060
- Windows 10

If there's any additional info that would be helpful I'd be happy to provide it

**version:** 2020.1203.0

**Comment by peppy** [comment]
I don't understand the issue.... at a stretch you are able to click things on your windows taskbar while the game is running?

What version of windows are you on and do you have any customisations which could cause this (becuase if it happens on both osutk and sdl it sounds like probably-not-our-issue).

**Comment by Pennek** [comment]
> you are able to click things on your windows taskbar while the game is running?

Correct. When the game is open and I click where the taskbar would be, it interacts with the taskbar and minimizes the game.

I couldn't see the taskbar in the previous release (osutk) and haven't changed my osu! settings in the meantime. I am running Windows 10 without any modifications. I have no idea what could be causing this if you can't reproduce it

**Comment by Pennek** [comment]
With some testing: This seems to fix itself when going into gameplay, and un-fix itself when alt-tabbing

**Comment by Pennek** [comment]
Closing as it's probably a windows issue. Rebooting fixed the problem on my end
