### ISSUE TITLE
Add back minimum window size in SDL

### ISSUE THREAD

**Issue by Morilli** [ppy/osu-framework#4067]
The game window can be resized to any ridiculous size, which wasn't possible before and probably shouldn't be allowed.

![image](https://user-images.githubusercontent.com/35152647/101050696-ec384d00-3584-11eb-9771-2d3a314b2b7a.png)

**Comment by Joehuu** [comment]
Gonna track this in https://github.com/ppy/osu-framework/issues/3501.
