### ISSUE TITLE
Borderless fullscreen runs exclusive on some graphics cards

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-framework#4068]
Should match stable behavior.
![byOakAurlh](https://user-images.githubusercontent.com/35318437/101105481-864ac600-3582-11eb-8644-2f70d1fb32e8.gif)

**Comment by peppy** [comment]
Can you confirm that borderless is not running exclusive full screen for you under SDL? I believe that may be the cause.

**Comment by Joehuu** [comment]
Seems like it is running exclusive fullscreen.

![chrome_BX6GIpenYa](https://user-images.githubusercontent.com/35318437/101112105-72f32700-3591-11eb-9407-b944783464d5.jpg)

**Comment by peppy** [comment]
Aha, that's going to be the cause of what you're seeing then. Will repurpose this issue thread tracking that (SDL is missing the one-pixel-hackery required to force borderless on some graphics card drivers).
