### ISSUE TITLE
The taskbar limit is ignored if the app is maximized before (and after) switching between Windowed and Fullscreen/Borderless screen mode

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-framework#4070]
**Describe your problem:** If the app is in windowed mode (but maximized), and you switch from windowed to fullscreen/borderless and switch back to windowed, for some reason the app forgets about the taskbar "limit" (on my Windows 10 setup) and it maximizes until it reaches the bottom edge of the screen.

**Screenshots or videos showing encountered issue:** [Video example with osu!lazer](https://streamable.com/u4q6js)

**Comment by frenzibyte** [comment]
Can reproduce this, you have to exactly do these steps:
1. maximize window
2. switch to borderless or fullscreen, then back to windowed
4. un-maximize then re-maximize.

Will attempt investigating this one.
