### ISSUE TITLE
Changing from fullscreen to borderless doesn't work

### ISSUE THREAD

**Issue by Morilli** [ppy/osu-framework#4097]
Tested on current windows 10 in osu!lazer; seems to just stay on fullscreen mode.

**Comment by peppy** [comment]
Which commit / build? When was the last time it worked for you? Need some more details here..

**Comment by Morilli** [comment]
I'm using the current osu!lazer 2020.1212.0 release, and I *think* this has never worked for me before, but given that for a long time borderless didn't work at all I can't really say for sure.

**Comment by peppy** [comment]
I can reproduce this. Looks like it may have regressed at some point.
