### ISSUE TITLE
Can't change FontStore filtering mode

### ISSUE THREAD

**Issue by boswelja** [ppy/osu-framework#4102]
I'm trying to import a pixel font, VT323, but FontStore defaults to linear filtering with no apparent way to change it. The result is not great when I start scaling text up.
I can open up a PR to pass filtering mode through to the underlying TextureStore, is there any reason why this isn't an option already?

**Comment by peppy** [comment]
The only reason is probably that no one had such a use case until now. Feel free to add this.
