### ISSUE TITLE
Random GL disposal-related crashes

### ISSUE THREAD

**Issue by bdach** [ppy/osu-framework#4108]
Got booted out of game with this trace today:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at osu.Framework.Graphics.OpenGL.GLWrapper.checkPendingDisposals()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
```

[Other people corroborate seeing similar](https://discord.com/channels/188630481301012481/188630652340404224/792065902375469086).

Seemingly most obvious candidate as to where this regressed is https://github.com/ppy/osu-framework/pull/4013. It's gotta be one of the accesses to `item`, I think - maybe the lock-free access to the item is racing with internal list operations and reading a `null`. Not even honestly sure how to confirm this, though.

**Comment by ThePooN** [comment]
to clarify on this issue, i got it a few times but sadly very inconsistently. seems to mostly happen while loading different menus, going in and out of multiplayer for example. but i've never had it happen while casually playing singleplayer or multiplayer, despite regularly going through song select. i've had it once at song select still though.

**Comment by bdach** [comment]
I've attempted to stress the disposal queue with the following:

```csharp
// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

using System.Threading;
using NUnit.Framework;
using osu.Framework.Graphics.OpenGL;

namespace osu.Framework.Tests.Visual.Testing
{
    public class GLWrapperDisposalTest : FrameworkTestScene
    {
        protected override double TimePerAction => 30;

        [Test]
        public void TestStressDisposalQueue()
        {
            int successfulDisposals = 0;

            AddRepeatStep("enqueue very many disposals", () =>
            {
                for (int i = 0; i < 10000; i++)
                    GLWrapper.ScheduleDisposal(() => Interlocked.Increment(ref successfulDisposals));
            }, 100);

            AddUntilStep("all disposals succeeded", () => successfulDisposals == 1000000);
        }
    }
}
```

but got no crash. I am noticing that finalisers are scheduling disposals, [some of which are using method groups](https://github.com/ppy/osu-framework/blob/b91be9523355e0257a1577f99ea0b35fd17b6ed3/osu.Framework/Graphics/OpenGL/Textures/TextureGLSingle.cs#L100) - maybe related? Would really be helpful to get at least a semi-consistent reproduction rather than just a rare one outta nowhere once a day...

**Comment by voidedWarranties** [comment]
I experienced this issue within my own project, and I reduced my use-case into something a bit simpler
Here is a test case that can usually replicate the issue within 20 seconds - 4 minutes (so some patience is required):
```cs
// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

using System.Linq;
using NUnit.Framework;
using osu.Framework.Graphics;
using osu.Framework.Graphics.Containers;
using osu.Framework.Graphics.Shapes;
using osuTK;

namespace osu.Framework.Tests.Visual.Testing
{
    public class GLDisposeCrashTest : FrameworkTestScene
    {
        private FillFlowContainer fillFlow;

        protected override double TimePerAction => 0.01;

        [SetUp]
        public void SetUp()
        {
            Add(fillFlow = new FillFlowContainer
            {
                RelativeSizeAxes = Axes.Both,
                Direction = FillDirection.Full
            });
        }

        [Test]
        public void TestAddRemoveDrawable()
        {
            AddRepeatStep("add/remove drawables", () =>
            {
                for (int i = 0; i < 50; i++)
                {
                    fillFlow.Add(new Box { Size = new Vector2(5) }); 
                    if (fillFlow.Count > 100)
                    {
                        fillFlow.Remove(fillFlow.First());
                    }
                }
            }, 100000);
        }
    }
}
```

Running framework-side, this raises a `NullReferenceException` [here](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/OpenGL/GLWrapper.cs#L151)
![image](https://user-images.githubusercontent.com/14946719/103434966-590f2900-4bbd-11eb-9e57-01946ffbeb53.png)

Hopefully it helps

**Comment by bdach** [comment]
Thanks, that is helpful; I have managed to trip the crash at least twice now with the test case.

(As an aside, for completeness `[SetUp]` should be scheduled.)

**Comment by bdach** [comment]
I think the race we're dealing with is as follows:

```

Thread A                                                                   | Thread B
                                                                           |
(GLWrapper.ScheduleDisposal)                                               | (GLWrapper.checkPendingDisposals)
    lock (pending_disposal_actions)                                        |
        pending_disposal_actions.Add(new PendingDisposal(disposalAction)); |
                                                                           |
(List.Add)                                                                 |
    _version++;                                                            |
    T[] array = _items;                                                    |
    int size = _size;                                                      |
    if ((uint)size < (uint)array.Length)                                   |
    {                                                                      |
        _size = size + 1;                                                  |
                                                                           |     for (var i = 0; i < pending_disposal_actions.Count; i++)
                                                                           |         var item = pending_disposal_actions[i];
                                                                           |
                                                                           | (List.this[int])
                                                                           |     if ((uint)index >= (uint)_size) // passes
                                                                           |     return _items[index];
        array[size] = item;                                                |
```

Expanding the list is actually *not* (that much of?) a problem when enumerating because the underlying array buffer is swapped in a single instruction, so the race window is nonexistent or extremely slim in that case. This race *also* seems unlikely but given that this code runs every frame at hundreds of fps...

The conventional solution to this is a reader-writer lock, but I'm not sure whether that won't destroy performance. I guess I'll have to benchmark it.

**Comment by bdach** [comment]
Over the day I came up the following branch: https://github.com/ppy/osu-framework/compare/master...bdach:fix-gl-disposal-crashes. Commit messages and inline comments should hopefully explain the main idea. From testing:

* It passes the 100k drawable stress test given above.
* I've benchmarked it on the test using dotTrace. Also tried adding a Benchmark.NET, but it's not trivial as it requires an actual game host and measuring that would probably be useless. It doesn't seem to be worse with the reworked concept, and it certainly seems to be better with the optimisation (times given are total times of the appropriate operations, measurement was once each time, over 2 minutes of running the stress test):

| | current `master` | with `GLDisposalQueue` | with optimised `GLDisposalQueue` |
| :- | -: | -: | -: |
| scheduling disposals | 342ms | 311ms | 301ms |
| checking disposals | 2267ms | 2179ms | 622ms |

For a more realistic usage pattern I should probably repeat that against a framework checkout game-side, but before I go further on this:

* @voidedWarranties - would you be OK with me including the test case as written and credited in the above branch?
* @peppy - do you see any obvious code or correctness issues with the above branch I might have missed?

**Comment by voidedWarranties** [comment]
Yeah, I have no problem with you including it

**Comment by peppy** [comment]
I think it looks fine on a 5 minute check.

**Comment by bdach** [comment]
Alright, will submit as a pull for proper consideration soonish. Just finishing up benchmarking game-side actually.
