### ISSUE TITLE
Switching to fullscreen in SDL crashes all DirectX apps

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu-framework#4133]
Using fullscreen mode in SDL causes *every* DirectX app to crash. Some of them are able to recover (like the example below) but others crash as a whole (e.g. League of Legends). I also tested OpenGL apps but those do not crash.

Example (emulator using Direct3D): 
https://user-images.githubusercontent.com/56885706/103477913-7b729380-4dc3-11eb-838f-f914f941a8d5.mp4
This is an SDL only bug, this issue does not occur using osuTK.
Event viewer logs (probably useless): https://www20.zippyshare.com/v/PIB7sGcI/file.html

**Comment by peppy** [comment]
I can't reproduce this at my end with arbitrary direct 3d apps, so it may be driver, software or hardware dependent.

Have you tested with another game or application using SDL2?

**Comment by bdach** [comment]
Attached event viewer log has no useful information as far as I can see (also I would ask that those are attached in English so that I don't have to try and jam through a translator).

**Comment by Joppe27** [comment]
> I can't reproduce this at my end with arbitrary direct 3d apps, so it may be driver, software or hardware dependent.
> 
> Have you tested with another game or application using SDL2?

Just tested with another SDL app (Z-Snes), same issue occurs. Hardware: Intel i5-7500, GTX 1060, 8GB RAM, Windows 10 Pro (2004)

> Attached event viewer log has no useful information as far as I can see (also I would ask that those are attached in English so that I don't have to try and jam through a translator).

Sorry, my Windows installation doesn't use English as it's main language. No idea how to change the language of a log (I already selected English when exporting).

**Comment by bdach** [comment]
> Just tested with another SDL app (Z-Snes), same issue occurs. Hardware: Intel i5-7500, GTX 1060, 8GB RAM, Windows 10 Pro (2004)

To clarify: are you saying that zsnes will clash with something else that uses D3D (like league or whichever), or that it will clash with lazer? If it's the former then there's nothing really to be done on our behalf except for report upstream to bugzilla or switch windowing backends again I guess.

**Comment by Joppe27** [comment]
Yes, the former: Z-Snes also crashes all DirectX apps. It is, indeed, most likely a problem with SDL.

**Comment by peppy** [comment]
I've tested with 5 directx games running and there is no issue.

The issue is most definitely something on your end. Please try updating your drivers and unloading any overlays you may have running (ie. discord or nvidia recording utilities).

**Comment by Joppe27** [comment]
Are you sure? I've just updated my drivers and have no overlays running but the issue still persists. I've tried this on two machines with very different configurations and roughly the same issue occurs on both of them (on my other machine, lazer itself crashes instead of the DirectX app. [logs here](https://www11.zippyshare.com/v/ZqQU2ZqW/file.html)) Are you testing in a VM? That might be why you're not seeing this issue. If not, I have no idea. This will be my last comment, no need to lock this thread if this is not of use.

**Comment by peppy** [comment]
Maybe it's something to do with multiple monitors (you haven't mentioned it but from your video it seems like you have two connected)?

Either way, if you have reproduced with another SDL2 application, then your report will need to be against SDL2, not us (we can't fix it).
