### ISSUE TITLE
The mouse is permanently confined in Borderless even if the confinement option is changed

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-framework#4134]
The mouse confinement seems to have some issues with the `Borderless` screen mode:
- If the confine is set to "during gameplay" and you finish a song or exit the player loader, you can't move your cursor to a second screen anyway (even if you set the confinement to "never")
- ^ after replicating the above problem, if you set the screen mode to `Windowed`, the cursor still remains confined to the current screen (ignoring the size of the game window)
- the issue seems to be fixed when you resize/drag/unfocus the window (so after performing the second point), or alt-tabbing when in `Borderless` screen mode.

**Comment by Gabixel** [comment]
I was thinking of opening another similar issue, but it appears to be identical, so to avoid making duplicates I will describe it here:
When you're in `Borderless` screen mode and change the mouse confinement from "always" to "during gameplay" or "never", the cursor is still confined to the current screen. Also, when you change to `Windowed` screen mode, the issue is still the same as described above.

**Comment by peppy** [comment]
@Gabixel can you confirm that everything is fine if you *start* the game (or framework) with confine mode set to disabled and window set to borderless? It's only after toggling it on once that it gets "stuck"?

**Comment by Gabixel** [comment]
Yes, when I start the game (or the framework) with those settings, everything looks fine, and I can move the cursor anywhere I want between the two monitors (even if you set the confinement to "during gameplay" since it doesn't confine the cursor when the game starts).

Summing up the first two posts: it gets stuck when the game begins to confine the cursor in borderless mode (e.g. when I change the option from "never" to "always" and then back to "never", it still confines), then I change to windowed mode, trying to move the cursor to the other monitor and failing because it gets stuck to the current monitor's boundaries (more specifically: the game's ones when it was in borderless) until I unfocus the game window.

**Comment by peppy** [comment]
@Gabixel I've tried to reproduce this issue following your instructions but cannot make it happen. Could you please test this again, as we've made considerable progress on fixing edge cases of window handling over the last few weeks?

**Comment by Gabixel** [comment]
One of those edge-case fixes seems to have covered my issue as well since I can't reproduce it anymore! It can be closed.
