### ISSUE TITLE
Dynamic compilation does not work in template-based projects

### ISSUE THREAD

**Issue by voidedWarranties** [ppy/osu-framework#4138]
### Reproduction
1. Create a new project based on the instructions on the wiki, or clone a recent o!f-based project from the Dependents list
2. Open the project using VSC
3. Select `VisualTests (Debug)` configuration and run without debugger
4. Open a random test scene, and save it without making any changes
5. The following exception is thrown:
```
[runtime] 2021-01-06 21:40:53 [error]: System.IndexOutOfRangeException: Index was outside the bounds of the array.
[runtime] 2021-01-06 21:40:53 [error]: at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
[runtime] 2021-01-06 21:40:53 [error]: at osu.Framework.Testing.RoslynTypeReferenceBuilder.updateFile(String fileName)
[runtime] 2021-01-06 21:40:53 [error]: at osu.Framework.Testing.RoslynTypeReferenceBuilder.GetReferencedFiles(Type testType, String changedFile)
[runtime] 2021-01-06 21:40:53 [error]: at osu.Framework.Testing.DynamicClassCompiler`1.recompileAsync(Type targetType, String changedFile)
```

Issue occurs for both flappy and empty templates.
Dynamic compilation functions on osu!, osu-framework, as well as when running the template project via osu-framework's `TemplateGame.Game.Tests` configuration.

Tested on `ppy.osu.Framework.Templates` version: `2020.1229.0`

Dynamic compilation was last working on templates version `2020.501.0` with framework version `2020.421.0`
Manually updating this template to framework version `2020.501.0` breaks dynamic compilation.

**Comment by peppy** [comment]
Have you checked the arguments being sent to `recompileAsync`? Sounds like it might be something to do with the path it's receiving for `changedFile`.

**Comment by voidedWarranties** [comment]
It seems that with the current setup, it is necessary to use .NET 3.1 SDK, as enforced in osu [here](https://github.com/ppy/osu/blob/d344268df7fa3bdc4f421d60c352719bbced0061/global.json) and also framework-side [here](https://github.com/ppy/osu-framework/blob/master/global.json), but never within the template

On .NET 5, `solution.Workspace.Diagnostics` contains messages like:
```
The SDK resolver type "WorkloadSdkResolver" failed to load. Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```
for each of the projects, and this results in each of the projects having no documents.

Would the best solution for now be to just copy the `global.json` file to the template?

**Comment by Semro** [comment]
Close this issue due to https://github.com/ppy/osu-framework/pull/4147 closed?
