### ISSUE TITLE
Crashes caused by MIDI callbacks on garbage collected delegates

### ISSUE THREAD

**Issue by sirloinsteak11** [ppy/osu-framework#4141]
After trying to open osu!lazer, nothing happens at all. 

This is what I got from the event viewer: https://imgur.com/c3rvu8n 

osu!lazer version: 2020.1229.0

Logs:
[session.log](https://github.com/ppy/osu/files/5784253/session.log)
[update_success.log](https://github.com/ppy/osu/files/5784254/update_success.log)
[runtime.log](https://github.com/ppy/osu/files/5784255/runtime.log)

Computer Specifications: 
CPU: Intel Core i3-6100T CPU @3.20GHz
GPU: AMD Radeon R9 M470X
8 GB RAM
2024 MB VRAM
Windows 10

**Comment by frenzibyte** [comment]
After investigating a bit, this may be a result of not closing input on disabling / disposing input handler, which can be the case if you have "raw input" on, as that modifies the `ignoredInputHandlers` bindable list and lead to disposing previous handlers (including midi handler) and re-creating new ones, I'll PR a fix for that now.

**Comment by peppy** [comment]
Tentatively closing as I believe the merged PR should have fixed this. Will be live in the osu! release, @sirloinsteak11 would be great if you can confirm that that point.
