### ISSUE TITLE
Integrate font size

### ISSUE THREAD

**Issue by A-BCDe** [ppy/osu-framework#4173]
I wish there is a feature for a fixed-sized text, regardless of the window size.

**Comment by peppy** [comment]
That's how the framework works by default. Is that not what you're seeing? Could you explain further?

**Comment by A-BCDe** [comment]
Running the template project, the height of the text "Main Screen" is a bit longer than my mouse cursor, while it becomes twice longer when I change the project to full screen.

I wonder if there is a way not to change its size.

I'm still looking around the framework and might have missed some details, so please tell me if I did.

**Comment by peppy** [comment]
The template project comes with predefined behaviour to scale game content based on the window size. You can disable this by removing the `DrawSizePreservingFillContainer` in https://github.com/ppy/osu-framework/blob/master/osu.Framework.Templates/templates/template-empty/TemplateGame.Game/TemplateGameGameBase.cs#L21

**Comment by peppy** [comment]
@A-BCDe confirm that you got things working as you want them to?

if you're working with osu-framework, i'd highly recommend you join the discord network as we are open to help you through your dev process.
