### ISSUE TITLE
Flappy game template fails to build

### ISSUE THREAD

**Issue by plaguemask** [ppy/osu-framework#4174]
After installing the .NET 5.0 SDK and Visual Studio 2019, I followed the [template readme](https://github.com/ppy/osu-framework/blob/master/osu.Framework.Templates/README.md), opting to start with the flappy bird clone after installing the template package.

But opening the folder in VS, opening MyNewFlappyGame.sln, and attempting to build it gives this error:

`[...]\MyNewFlappyGame\MyNewFlappyGame.Game\Elements\Bird.cs(58,27,58,39): error CS0246: The type or namespace name 'ISampleStore' could not be found (are you missing a using directive or an assembly reference?)`

The offending line in Bird.cs is the load function signature: `private void load(ISampleStore samples)`

Both of the automated suggested fixes solve the problem -- one adds `using osu.Framework.Audio.Sample;` and the other changes the signaure to `private void load(osu.Framework.Audio.Sample.ISampleStore samples)`. As someone with no experience though, I can't say which is a better solution, or if something else is necessary.

**Comment by frenzibyte** [comment]
Right, `ISampleStore` has been changed from the awkward namespace `osu.Framework.Audio.Track` into `osu.Framework.Audio.Sample` but the templates hasn't updated its usages yet.

And yeah the fix is simply adding a `using osu.Framework.Audio.Samples;` line, will open a PR updating the templates.
