### ISSUE TITLE
Application window has no icon if the app is started in borderless/fullscreen mode

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-framework#4184]
Start the app in `borderless`/`fullscreen` mode, then change it to `windowed`.

Here's an example with osu!lazer:
![image](https://user-images.githubusercontent.com/43073074/106615507-cae7e300-656c-11eb-8beb-0e00ad1d970d.png)

How it should be:
![image](https://user-images.githubusercontent.com/43073074/106616103-72651580-656d-11eb-8e79-adc26b90ef4e.png)

**Comment by peppy** [comment]
Going to milestone this as it's super-weird and should probably be reported or looked into (if it's our end).

**Comment by Joehuu** [comment]
Seems fixed in SDL3.

**Comment by Joehuu** [comment]
Seems to have regressed with some SDL3 update (tested on latest osu! release and `master`).
