### ISSUE TITLE
CTRL is in a incorrect location when remapped

### ISSUE THREAD

**Issue by DavidHusicka** [ppy/osu-framework#4193]
**Describe the bug:** 
When you run `setxkbmap -option "ctrl:swapcaps"` to swap CTRL and CAPS LOCK keys then osu! does not respect this and all shortcuts are mapped to `CAPS LOCK + key` combo instead.

**osu!lazer version:** 2021.212.0

Platform: Linux

**Comment by bdach** [comment]
This will be essentially the same thing as https://github.com/ppy/osu/issues/11143. If the behaviour that seems to be expected here is to be achieved, then default keybindings would have to be unmapped against the user's current keyboard layout (so that the physical <kbd>Ctrl</kbd> is always used by the game, regardless of the layout).

I'm not even honestly sure if it's correct to do so - I think the *logical* key position should be the one that matters (i.e. the one indicated by the keyboard layout), not the *physical* one. In other words, I think the current game behaviour is more correct.

**Comment by peppy** [comment]
At least on windows and macOS, my assumption is that any remapped keys would follow their remapped variants (and they do).

**Comment by DavidHusicka** [comment]
> This will be essentially the same thing as https://github.com/ppy/osu/issues/11143. If the behaviour that seems to be expected here is to be achieved, then default keybindings would have to be unmapped against the user's current keyboard layout (so that the physical <kbd>Ctrl</kbd> is always used by the game, regardless of the layout).

Looks like the same issue to me (just the key in the question isn't ctrl)

> I'm not even honestly sure if it's correct to do so - I think the *logical* key position should be the one that matters (i.e. the one indicated by the keyboard layout), not the *physical* one. In other words, I think the current game behaviour is more correct.

I am little confused here. The one reported by the mapping should be always used instead of scancodes in my opinion (keycodes > scancodes) so yes, you are right there. The issue is that osu seems to prefer scancodes over keycodes in this case (it thinks that ctrl is in a place of caps because it assumes that ctrl is in left bottom of a keyboard which is wrong). In what way is the current behavior more correct? If there is any misunderstanding please tell me. I might made mistake and wrote something in a way it could confused you.

**Comment by bdach** [comment]
I've tested with `setxkbmap` and I'm pretty sure that after swapping I was getting a caps lock scancode after pressing physical Ctrl, and vice versa. Which seems correct, again, unless I'm misunderstanding, which I might be as this is very confusing.

**Comment by peppy** [comment]
@DavidHusicka can you confirm this behaviour? Maybe with screenshots attaching what you expect the case to be?

To my eyes, correct behaviour would be that osu/osu-framework sees the post-rebound key, as @bdach has implied. So in your osu! settings you would see 'caps lock' for the key which works as 'caps lock' everywhere else on your system.

**Comment by DavidHusicka** [comment]
Is this what you want to see? 

https://youtu.be/ZblF0Uw0tgE

The overlay is `screenkey`

**Comment by bdach** [comment]
That... doesn't help much? How are we to know that the overlay isn't showing scan codes rather than key codes, or vice versa?

The least confusing thing that you could provide in my opinion is an actual real world video of you pushing the actual real world keys. Alternatively a keyboard overlay that shows the layout, as long as it reflects reality.

**Comment by DavidHusicka** [comment]
The overlay shows the keys the way these keys are mapped so when I press physical `caps lock` which I has mapped to `ctrl` then the overlay shows `ctrl` because these are my mappings and this is how the presses should be recognized.

There is the video of me pressing the keys. I am sorry for the mess on my table.

https://youtu.be/gj2gF9ZkTko

**Comment by DavidHusicka** [comment]
Note: I tried to make the led for `caps lock` visible so you can clearly see that my physical `ctrl` is in fact a `caps lock`.

**Comment by frenzibyte** [comment]
That video you linked does confirm the behaviour that's been questioned about, osu!lazer looks to receive `Key.ControlLeft` instead of `Key.CapsLock` when pressing <kbd>Ctrl</kbd> physically, on your end. (assuming you didn't confuse/modify the game key binding configuration into doing that)

**Comment by DavidHusicka** [comment]
> Might in the end be a duplicate of https://github.com/ppy/osu/issues/11143 (wrong key received, from scancode instead of keycode, linux-only)

I think this most likely is a duplicate of the issue linked above. It's the same behavior, just with different keys.
