### ISSUE TITLE
Changing from duplicate to extend displays or vice versa breaks fullscreen on windows 10

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-framework#4196]
Doesn't matter the initial screen mode. Also happens on framework. Input on keyboard still works when focused.

https://user-images.githubusercontent.com/35318437/108006088-56bb2f80-6faf-11eb-954b-db6638b01260.mp4

Ref: https://osu.ppy.sh/comments/1461677

**Comment by peppy** [comment]
Does the window appear on your second display, or is it completely non-existent everywhere?

**Comment by Joehuu** [comment]
The window is non-existent everywhere.

**Comment by Joehuu** [comment]
Can't seem to reproduce anymore.
