### ISSUE TITLE
Android GL context is lost on leaving the application (causing a crash)

### ISSUE THREAD

**Issue by Yilliee** [ppy/osu-framework#4200]
The app will still be running when minimized or if the screen turns off.

Currently as soon as the screen turns off the osu app closes on Android. Or even if I minimize it. Usually when I'm playing and have to talk to someone I pause my game but sometimes the screen turns off and the game gets kill so pls make it such that the app will reopen from the resume screen or where ever I was after the screen is turned on again/device is unlocked again.

**Comment by bdach** [comment]
This was mostly fixed by https://github.com/ppy/osuTK/pull/74. There's another issue which was introduced by that change but I'll open a separate tracking issue for it.
