### ISSUE TITLE
Expose a "Resizable" Property on DesktopWindows

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu-framework#4206]
Our project Vignette is catered towards specifically for live streamers which means they will need a consistent and expected window size thus a resizable window would not be ideal. Forcing the game to always be in borderless full screen or exclusive full screen may also not be ideal in terms of user preference and experience.

SDL2 has `SDL.SetWindowResizable(IntPtr, SDL_bool)` but I'm not sure about OpenTK's counterpart.

**Comment by peppy** [comment]
If we were to decide this is out of scope, are you able to call it directly yourself?

**Comment by LeNitrous** [comment]
If by calling it directly myself without making changes in this repository, then no. The SDL window handle is marked as internal under `SDL2DesktopWindow` and I'm still looking for OpenTK's counterpart.

**Comment by peppy** [comment]
Well you shouldn't be using OpenTK/osuTK anyway.

We might want to consider exposing the handle, not sure. Supporting fixed size windows may be something we want but definitely not an immediate priority.

**Comment by LeNitrous** [comment]
Exposing the handle is definitely more than enough. Although using it inappropriately may cause certain internals to behave inappropriately which is the risk when done so. I could make a PR making the change in the accessor but it would still be the team's call whether it should be done or not.
