### ISSUE TITLE
Expose the aggregate track adjustment values through IAdjustableAudioComponent

### ISSUE THREAD

**Issue by H2n9** [ppy/osu-framework#4208]
Currently, `IAdjustableAudioComponent` exposes each of the adjustments as `BindableNumber` already.
https://github.com/ppy/osu-framework/blob/72eef659d4374052e04021361ba1549bafa7c442/osu.Framework/Audio/IAdjustableAudioComponent.cs#L16-L31
These however don't represent the updated values after adjustments are applied and will always return 1. (whether that is intended or not).

Therefore there is no way to actually fetch the true Tempo/Frequency/etc.. values from ITrack.

Use case,
https://github.com/H2n9/osu/blob/e3e06addb45c0b0ebd75a728c366130d4b261948/osu.Game/Rulesets/Mods/ModPitchShift.cs#L62

**Comment by bdach** [comment]
Aren't `Aggregate{Volume,Balance,Frequency,Tempo}` what you're looking for?

**Comment by H2n9** [comment]
They aren't exposed through the interface no? And therefore not available through `ITrack`. My specific use case is here if maybe I'm missing something.

https://github.com/H2n9/osu/blob/e3e06addb45c0b0ebd75a728c366130d4b261948/osu.Game/Rulesets/Mods/ModPitchShift.cs#L62

**Comment by bdach** [comment]
PRing a change to make `ITrack` implement `IAggregateAudioAdjustment` would probably take about as much time as opening this issue.

> My specific use case is here if maybe I'm missing something.

I've seen the link the first time. No need to point it out again.

**Comment by H2n9** [comment]
Ahh, I missed that class somehow; didn't think it was as straightforward as that. My bad, I'll pr the change then.
