### ISSUE TITLE
Thread pool completely broken on iOS

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4214]
Opening this issue since it isn't tracked anywhere else. This is the reason for lack of iOS deployments in recent times. I finally have a reproduction going locally in a debug environment, which means we can actually begin to make some forward progress on the issue.

Both of the following reproductions can be performed on `master` in a debug/device configuration. In my testing, I intentionally reduced the size of our `CompositeDrawable` `TaskScheduler`s to 1 thread just to avoid any potential issues due to total active thread count (probably irrelevant though).

Reproduction 1:

- Run `TestSceneTextures` to completion.
- Should freeze on "get texture" step in `RefCountTextureAvailability`.

![20210224 170935 (Visual Studio)](https://user-images.githubusercontent.com/191335/108967600-12bcde80-76c3-11eb-8eea-1cf27db4e30d.png)

Reproduction 2:

- Run `TestSceneVideo`
- Should freeze on getting the video from network

![20210224 170455 (Visual Studio)](https://user-images.githubusercontent.com/191335/108967108-6bd84280-76c2-11eb-800f-de0052530696.png)

At first sight, this looks to be standard .NET ThreadPool saturation, although I am having difficulty asserting this as the Visual Studio debugger seems to not show any running thread pool threads (I have seen some show up, but I guess it's hiding or doing something weird to paused/sleep/waiting threads?)

On the osu-side, this can be completely resolved by changing the startup sequence to anything that isn't triangles. This is likely due to the video decoding loop also using the threadpool (it's actually surprising how few things we have using the threadpool..).

Checking `ThreadPool.GetAvailableThreads(out int wrk, out int compl);` shows results of `200` for each count. Doesn't really mean much, but that's about all the visibility I can get without going deeper.

I've confirmed that thread pool tasks aren't hitting any exceptions, so am at a bit of a loss as to where the threads are going.

I intend on digging deeper into this one, but worthwhile to have a thread open in case anyone has a bright idea.

**Comment by sr229** [comment]
From what I can tell, iOS only has a maximum of 64 threads, really worth investigating at the moment, I assume only threading is affected since from what I can deduce from the initial findings,  any intro but triangles work.

**Comment by peppy** [comment]
Please, re-read my opening post. The reason it fails is due to TPL threadpool usage. This is already a known.

**Comment by sr229** [comment]
One of the recommendations I got from asking through the .NET community was run the debugging using LLDB, quoting: 

![image](https://user-images.githubusercontent.com/14976516/109954500-5f846300-7d1c-11eb-9ae9-3f1291c36797.png)

They also recommend Jetbrains Rider for this since they seem to catch which threads are precisely running.
