### ISSUE TITLE
WebRequest sends multipart body even if no parameters were specified

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu-framework#4221]
https://github.com/ppy/osu-framework/blob/master/osu.Framework/IO/Network/WebRequest.cs#L308 
If the request does not have a raw body, it seems to be sending it to multipart even though there is no actual content.
I think it should send zero-body instead of sending blank multipart body. 
_(Some web framework seems to fail to validate this body, like asp.net core. could fix this at server side by disabling body but i think this should be fixed)_

(Problems occurred at this code, with using osu-framework)
https://github.com/ppy/osu/blob/master/osu.Game/Online/API/Requests/JoinChannelRequest.cs
https://github.com/ppy/osu/blob/master/osu.Game/Online/API/Requests/LeaveChannelRequest.cs
Request:
```
PUT /api/v2/chat/channels/1/users/1 HTTP/1.1
Host: localhost:23212
User-Agent: osu!
Authorization: Bearer test
Accept-Encoding: gzip, deflate
Content-Type: multipart/form-data; boundary=-----------------------------28947758029299
Content-Length: 98
```

Body:
```
-------------------------------28947758029299

-------------------------------28947758029299--
````

**Comment by bdach** [comment]
Seems valid, but I'm confused by this remark:

> (Problems occurred at this code, using osu-framework)

What does this mean? I'm pretty sure channel joining and leavin works in game, does it not?

**Comment by ilsubyeega** [comment]
> Seems valid, but I'm confused by this remark:
> 
> > (Problems occurred at this code, using osu-framework)
> 
> What does this mean? I'm pretty sure channel joining and leaving works in game, does it not?

yep, it definitely works with osu-web but i was trying to recreating features and not worked by own environment and found this bug(?)
