### ISSUE TITLE
Investigate pinned objects on Gen0

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4238]
dotMemory is telling us this:

![20210302 122024 (Parallels Desktop app)](https://user-images.githubusercontent.com/191335/109591909-c0ac0b00-7b51-11eb-8184-8f5d6b4235d0.png)

We should probably figure out what is causing this and stop doing it.

**Comment by smoogipoo** [comment]
Are these permanently in Gen0? What was the case you were testing here? Because some things are bound to get pinned at least temporarily (sample data during load).

**Comment by peppy** [comment]
It happens during startup and it does look to be temporary.

**Comment by peppy** [comment]
Closing this one as I haven't seen it come up in quite a while.
