### ISSUE TITLE
Port across TouchHandler from osu-stable to disable common windows touch handling

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4258]
```
                    Native.SetProp(windowHandle, pressAndHoldAtomStr,
                        Native.TABLET_DISABLE_PRESSANDHOLD |
                        Native.TABLET_DISABLE_PENTAPFEEDBACK |
                        Native.TABLET_DISABLE_PENBARRELFEEDBACK |
                        Native.TABLET_DISABLE_FLICKS |
                        Native.TABLET_DISABLE_SMOOTHSCROLLING |
                        Native.TABLET_DISABLE_FLICKFALLBACKKEYS |
                        Native.TABLET_ENABLE_MULTITOUCHDATA);
```

I believe we want these disabled automatically so the user doesn't need to turn them off at a system level.

**Comment by Susko3** [comment]
Looks like SDL already sets this (in a different way): https://github.com/libsdl-org/SDL/blob/7e15ad2fc4f610482c2f7b23a6fb2838c8759f93/src/video/windows/SDL_windowsevents.c#L1297-L1310.

(Noticed the SDL code while looking at something else, have not tested if any of this actually disables as advertised.)

**Comment by peppy** [comment]
Nice find. Will close this for now.

The remaining issues with touch input are being tracked via https://github.com/ppy/osu-framework/issues/5033.
