### ISSUE TITLE
Android activity closes when an overlay or another activity is on top of it

### ISSUE THREAD

**Issue by adryzz** [ppy/osu-framework#4269]
https://user-images.githubusercontent.com/46694241/110622384-abf7f480-819b-11eb-8696-b63ed3721827.mp4

The video shows the brightness overlay (activated by sending keycode `221` to simulate the physical key as my device doesn't have that key) closing an osu!framework activity.
It also shows how in a normal Xamarin app this behaviour does not happen.

This happens with other overlays too, but the brightness overlay is easy to trigger and reproduce, so i showed this one.

System information
Android version: 9, 10, 11 (the last two in the AVD emulator)
Latest build of osu!framework

Reproduction steps:
Open an osu!framework based app.
Send keycode `220` or `221` (Brightness- and Brightness+ respectively)
The activity should close.
(To send those key presses without a keyboard you can use `adb shell input keyevent 220`)

**Comment by peppy** [comment]
This is probably due to whatever android system you're using making the background window inactive while it displays the overlay. Making this a duplicate of https://github.com/ppy/osu-framework/issues/4200.
