### ISSUE TITLE
EnumExtensions optimizations.

### ISSUE THREAD

**Issue by Redageddon** [ppy/osu-framework#4273]
EnumExtensions GetValues should use generic caching to prevent repeated getValues call. And example of an implementation is at [GenericCache](https://github.com/Redageddon/X10D.Performant/blob/Master/X10D.Performant/src/Custom/EnumExtensions/EnumExtensions.cs#L46). And another question is, why is T for GetValuesInOrder not binded to enum, it throws  an error if a non enum type is passed, so enum should be a generic constraint to enum for compile time check instead of runtime checks.

**Comment by peppy** [comment]
Can you give a bit of background here to why you think this is necessary? Are you using it in a project? Can you show profiling or benchmarks where it is proving to be an overhead (>0.5% of execution
time)?

**Comment by Redageddon** [comment]
Its not exactly necessary, i can create some benchmarks here in a second. It was just something that i had done and thought it could be useful here. The enum map only calls GetValues once.

**Comment by peppy** [comment]
I'm sure in an isolated usage it is definitely faster, but it'd need to actually show some benefit to us in order to consider it, and warrant the (albeit small) memory overhead that comes with this change.

**Comment by Redageddon** [comment]
Im making the benchmarks rn, give me like 5 mins for them to run

**Comment by Redageddon** [comment]
[Benchmark + Code](https://gist.github.com/Redageddon/57803644c33302638edb77764c6915d0)

**Comment by Redageddon** [comment]
here is the benchmark if i just use it as an array instead of ienumerable and set the first element to A
`
|            Method |          Mean |      Error |     StdDev |        Median |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------ |--------------:|-----------:|-----------:|--------------:|-------:|------:|------:|----------:|
| NonCacheBenchmark | 3,162.1762 ns | 37.8810 ns | 33.5805 ns | 3,164.6019 ns | 0.1793 |     - |     - |     752 B |
|    CacheBenchmark |     0.0155 ns |  0.0236 ns |  0.0209 ns |     0.0073 ns |      - |     - |     - |         - |
`

**Comment by Redageddon** [comment]
I personally am just a performance junkie, and this is something that I that would definitely benefit even if the waterfalled is minor. And it is easy to implement.

**Comment by peppy** [comment]
Thanks for the benchmark. The original looks already quite performant enough for the usages we have. Of course, we will reconsider this approach if we ever begin using `GetValues()` in an actual execution path. Currently it's used at startup time, or only in tests. 0.003ms and a small alloc overhead is acceptable.
