### ISSUE TITLE
Move osu-framework to GitHub Actions

### ISSUE THREAD

**Issue by sr229** [ppy/osu-framework#4288]
As part of making the entire workflow stick to Actions (and to keep us always up to date with .NET upstream since it's Microsoft-supported), moving to Actions might be a best idea considering most of our workflow is supported by Actions.

**Comment by bdach** [comment]
I don't really find the arguments here overly convincing. I see no particular reason to switch CI. There are way more important things to do.

**Comment by smoogipoo** [comment]
It's low priority for sure, but definitely something we're looking to do in the long term.

**Comment by peppy** [comment]
Would be great if someone would do this for us. I believe there were previous attempts but they weren't completed / merged. That may have been osu! side though.

**Comment by sr229** [comment]
The reason I opened this because I asked in-stream if there were any stopgaps of moving to Actions, so I'm happily volunteering myself to do the migration (which may take time considering the Build Cake script is AppVeyor only)

**Comment by bdach** [comment]
Cake should probably be done away with as part of this migration, actually. This was the plan a while ago, and I don't think we have much of a reason to keep it around.

**Comment by sr229** [comment]
Got it, I'll keep that in mind while I'm writing it.

**Comment by sr229** [comment]
Almost done porting the entire pipeline to Actions, I won't be able to clean out the AppVeyor script to prevent unnecessary failures. A follow-up PR is imperative once we transition completely to Actions.

![image](https://user-images.githubusercontent.com/14976516/116080263-6ea7e180-a6cb-11eb-8a8d-691dca7ef8a2.png)
