### ISSUE TITLE
No audio Linux pipewire

### ISSUE THREAD

**Issue by mrlinuxfish** [ppy/osu-framework#4290]
**Describe the bug:** 

I don't get any audio when I launch osu. I have an error `BASS faulted with error code 46: Busy.` when I select my audio device running pipewire audio framework. I cannot use plain pulse audio as it doesn't work very well with my audio interface.

I'm also getting theses errors in my terminal. The alsa one is definitely tied to the audio issues and the Xlib one seems to only show up when osu runs tiled with my terminal emulator.

```
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
Xlib:  extension "NV-GLX" missing on display ":0".
```

I'm running up to date Arch Linux with i3 as my window manager and pipewire as the audio server. 

I see that ppy/osu#11591 and ppy/osu#11991 are similar bugs but were closed due to not having enough information. I can provide additional details if necessary to help diagnose exactly what the issue is.

**Screenshots or videos showing encountered issue:** 

Screenshots of no sound don't seem very helpful

**osu!lazer version:** 

2021.312.0

**Logs:**

I somehow have 2 logs directories `logs` and `Logs` so I have included both

logs/
[runtime.log](https://github.com/ppy/osu/files/6168677/runtime.log)
[network.log](https://github.com/ppy/osu/files/6168678/network.log)
[performance.log](https://github.com/ppy/osu/files/6168679/performance.log)
[database.log](https://github.com/ppy/osu/files/6168680/database.log)

Logs/
[update_success.log](https://github.com/ppy/osu/files/6168687/update_success.log)
[session.log](https://github.com/ppy/osu/files/6168688/session.log)
[runtime.log](https://github.com/ppy/osu/files/6168689/runtime.log)

**Comment by peppy** [comment]
Bass reports `Busy` when it cannot access the audio device. Do you have it set to some kind of exclusive mode?

**Comment by mrlinuxfish** [comment]
It might be because of how I have Jack configured from my old audio setup. I'll test another install to see if I royally messed up the audio and see if this error is reproducable. I think how it's currently working, osu is trying to take control of the audio device directly instead of working with pipewire.

**Comment by Thesola10** [comment]
Cannot reproduce using Default or JACK (with pw-jack). Ideally, you should use Pipewire as the primary audio server on the system, using Arch's `pipewire-pulse` and `pipewire-jack` packages, and launch osu with `pw-jack` to use Pipewire's JACK server.

**Comment by Thesola10** [comment]
Also, check `pw-top` to see if any audio app is able to connect to your Pipewire session manager, as well as the output for `journalctl --user --unit=pipewire.service --unit=pipewire-pulse.service --unit=pipewire-media-session.service` to see if PipeWire is working

**Comment by sr229** [comment]
I'd like to note that this is not really a framework issue, since this is most probable a configuration issue with Pipewire and JACK. I was not able to reproduce this against Fedora Rawhide and WSL2.

**Comment by mrlinuxfish** [comment]
I'm really thinking it might be an issue with my audio interface. I'll reopen this issue with more information if I can confirm it's not just a configuration issue.

**Comment by AZMCode** [comment]
I've stumbled upon this issue, and am slightly disappointed to see that it got closed. In any case, I'm running Ubuntu 21.04, and I recently switched to `pipewire-pulse`. I can confirm my setup works perfectly with other applications, and even with an external USB sound card, yet no dice with osu!lazer. I'm currently running the latest AppImage (2021-815.0-lazer), and I'm willing to provide any logs necessary to help reproduce the issue.

**Comment by gagahpangeran** [comment]
Based on your logs, you got different error compare to OP. `BASS faulted with error code 3: Driver.`

From what I get by searching through old issue about 'BASS faulted' in [framework](https://github.com/ppy/osu-framework/issues?q=is%3Aissue+BASS+faulted+is%3Aclosed) and [osu!](https://github.com/ppy/osu/issues?q=is%3Aissue+bass+faulted+is%3Aclosed), this is most likely caused by your audio setup.

You can try some tips from https://github.com/ppy/osu/issues/11991#issuecomment-794864483 especially the last point. (because you mentioned that you are using pipewire).

> You are using PulseAudio (most distros are using it by default) or PipeWire, but you don't have the necessary ALSA plugin and configuration to make ALSA-only application able to use the PulseAudio/PipeWire as a device. How you do this depends on your distro. Such as on Arch Linux, you need to install `pulseaudio-alsa` if you are using PulseAudio, `pipewire-alsa` if you are using PipeWire.

**Comment by AZMCode** [comment]
Sorry for that then. I'll see what I can do to debug this issue, and if it persists I'll open a new one. Thanks for the help!
