### ISSUE TITLE
osu Tablet Driver

### ISSUE THREAD

**Issue by BadLvckCharm** [ppy/osu-framework#4292]
Upon testing the new built-in driver in lazer I came across a few things of note.

osu! did find my tablet and its name fine however the driver was not functional in any way. I was able to sort this out by running my usual Driver, Devcon Driver, and then my tablet worked fine and function with the built-in driver.  So I was able to change my tablet area in-game but only when having another driver running in the background.

Before doing this I did try unplugging my tablet however upon doing so the game client just crashed.

The enable toggle doesn't appear to be doing anything from what I can see. For reference, I simply moved my tablet area to the opposite side of the area yet pressing this button does not seem to change anything, it's as if it's still on

**Comment by peppy** [comment]
For tablet compatibility issues, please open an issue over at https://github.com/OpenTabletDriver/OpenTabletDriver. Make sure to follow their issue templates when you do (including device information etc.).
