### ISSUE TITLE
Tablet mapping incorrect when starting game in borderless

### ISSUE THREAD

**Issue by Starwort** [ppy/osu-framework#4294]
**Describe the bug:** 
Resetting to 'full area' leaves the right and bottom of the screen unreachable  
This implies that the game thinks the tablet is larger than it really is

**Screenshots or videos showing encountered issue:** 
![](https://user-images.githubusercontent.com/16487249/111869938-98a60f80-8979-11eb-9f8c-6b5a6b34b3e5.png)
(Pen positioned at the bottom right of the tablet's active area)

**osu!lazer version:** 2021.320.0, as visible

**Logs:**

[performance.log](https://github.com/ppy/osu/files/6175564/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6175565/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6175566/updater.log)
[network.log](https://github.com/ppy/osu/files/6175567/network.log)

My suggestion for an improvement to the tablet configuration would be to allow setting the top left and bottom right corners of the active area, and having osu! use that as the 'full area'

**Comment by Starwort** [comment]
Oh, also - I don't know if it's related or not, but sometimes my cursor decides it doesn't want to use tablet presses as clicks in menus (seems to also be fixed by changing the fullscreen mode)

**Comment by bdach** [comment]
> Oh, also - I don't know if it's related or not, but sometimes my cursor decides it doesn't want to use tablet presses as clicks in menus (seems to also be fixed by changing the fullscreen mode)

Possibly related to [this comment](https://github.com/ppy/osu-framework/pull/4162#pullrequestreview-606734518) and [this discord message](https://discord.com/channels/188630481301012481/188630652340404224/821613654062399549).
