### ISSUE TITLE
BindableSize does not propagate `MinValue`/`MaxValue` changes to bindings

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#4307]
I've attempted in addressing that until I realized that I don't really need it at the moment. I've done it by abstracting the `MinValue` and `MaxValue` propagation to a base `ConstraintedBindable` class, to avoid a bad amount of duplicated code.

Here's my changes: https://github.com/ppy/osu-framework/compare/master..frenzibyte:constrained-bindable

Can open a PR for it but would like to hear whether it's in the right direction, as I don't really want to open yet another bindable PR here to stay dead for a couple of months.

**Comment by bdach** [comment]
What is "min/max value" even supposed to be defined as for size? Component-wise min/max? Seems arbitrary. You seem to have an even weirder implementation there (does width then height first for some reason?)

What do you need this for?

**Comment by peppy** [comment]
FWIW I hit this same limitation before switching to use `Vector2` instead of `Size`. The `BindableSize` class is about halfway where it should be in terms of implementation, but I'm not sure we're using it in enough places to warrant the maintenance cost.

Also interested to know your use case for it.

**Comment by frenzibyte** [comment]
Was gonna need it since I was initially gonna make use of the framework config's window size bindable for specifying the minimum and maximum window size value, but I've found adding the two properties at `IWindow` is a better choice.

At this point `BindableSize` can actually be removed altogether, it's only used now with https://github.com/ppy/osu-framework/pull/4308 to clamp value instead of attempt to set size beyond the specified range, but that's not a reason to keep it around for now.

**Comment by bdach** [comment]
PR that and we can review it properly.
