### ISSUE TITLE
Cursor sometimes jumps when going from tablet to mouse

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#4317]
It doesn't happen all the time, seems to occur more often when the cursor is away from the centre of the screen.

Demonstration: https://drive.google.com/file/d/1f1ZgBxTgwS0Xfhxd5m51YowxT7D8XStP/view?usp=sharing
Kinda hard to show, but the frame statistics bars show the type (mouse: purple, tablet: cyan). Happens a few attempts in, not from the start of the video.

**Comment by peppy** [comment]
Are you able to reproduce this with high precision mouse turned on?

**Comment by smoogipoo** [comment]
Can repro with both on and off. Linux.

**Comment by peppy** [comment]
Just to confirm we're seeing the same thing, can you follow this and confirm the behaviour is the same on linux as on windows?

- Framework test `TestSceneInputManager`
- Toggle cursor visibility (so you can see the host cursor position)
- Move on tablet
- Move on mouse and confirm the ingame cursor always follows the (absolute) position of the host

https://user-images.githubusercontent.com/191335/112810770-59349d00-90b6-11eb-8c88-752948d4d9d3.mp4

**Comment by smoogipoo** [comment]
Yes, it's the same behaviour. The tablet cursor just needs to affect the host cursor.
