### ISSUE TITLE
Switching/Minimizing the window does not work when using Fullscreen mode

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu-framework#4322]
The window stays on top, the only change being that the game stops accepting input (clicking LMB returns the control of the mouse). Neither Alt+Tab (for task switcher) nor Win+D (for minimizing all windows) works. The fps doesn't get limited to 60 as well, so it probably doesn't go into unfocused state at all? This happens only since the last release.

Here is how it looks (obs couldn't capture the task switcher, sorry for using the camera):
https://streamable.com/mj8z1y

Here is DxDiag if that is of any help (note this is a Nvidia Optimus laptop, but I'm running the game using the integrated graphics):
[DxDiag.txt](https://github.com/ppy/osu-framework/files/6231610/DxDiag.txt)

**Comment by Susko3** [comment]
Only happening if `High precision mouse` is turned on.

With it disabled, Alt+Tabbing works as expected, and the game renders at 60 fps in the background.
But the osu!lazer window still doesn't minimize. The window is also visible after Win+D

Alt-Tabbing to another windows and then pressing Win+D leaves osu! in a weird state where it'll be the topmost window, but will pass clicks trough it, Right click open the desktop right click menu.

**Comment by Sinamer** [comment]
Thanks for the tip, disabling `High precision mouse` does help with switching the window via Alt+Tab. Also having the same behavior with Win+D still leaving the game window on top, although in unfocused state now.

**Comment by peppy** [comment]
This will likely be improved in the next release. Please report back when that happens!

**Comment by Susko3** [comment]
This issue isn't completely fixed on latest master. Alt+Tabbing now works, but Win+D still doesn't. The game stays on top of the desktop, regardless if relative mode is enabled or disabled. Also broken when just opening Start with the Win key. Start opens, but the game window is still visually in the foreground. Clicking in the Start menu will click on Start, as if Start was in foreground.
