### ISSUE TITLE
Tablet area offset when the built-in tablet driver is disabled

### ISSUE THREAD

**Issue by Thomzzz** [ppy/osu-framework#4323]
As discribed in the title I disabled the new built-in tablet driver, so I would expect it does not mess with the cursor.
I use the Hawku tablet driver and I set it to a smaller area and shifted it to the top left, so off center.
When I start osu the middle of the tablet is the middle of the screen (not correct).
If I reset the Hawku driver it is fine again and I can do every thing.
When I select a song it is still fine. Only after the song has been loaded and it starts playing the problem occurs again.
And it also remains after the song in the main menu.

(When the shifting problem is there I cant reach the bottom or the right border of the screen and on the left and top I can get the cursor out of view)

Update: If I disable the Hawku driver completely and enable the built-in osu driver things seem to work fine (except I have to match the settings from the Hawku driver).

**Comment by frenzibyte** [comment]
Are you running in `Fullscreen` mode while encountering this issue?

**Comment by bdach** [comment]
It sounds like you might need to disable "high precision mouse" if it's enabled, and you want to continue using the "hawku driver".

**Comment by Thomzzz** [comment]
I tried it out just now. So with the hawku driver on and build-in driver disabled.
Setting the "confine mouse cursor to window" to "never" also fixed the problem.
I tested it with  both "high precision mouse" enabled and disabled, and there were no problems.

My Windows UI scaling is at 150%.
(I also run borderless instead of full screen and vertical and horizontal scale set to 64%)

**Comment by peppy** [comment]
If you are willing to make the changes temporarily, can you try turning all scaling to 100% and see if this fixes your issue?

**Comment by Thomzzz** [comment]
It was not entirely clear if you meant scaling Windows or the horizontal/vertical, so I tested both.
In all test these conditions were the same:
- Hawku driver was running
- Tablet: Disabled
- High precision mouse: Enabled
- Confine mouse cursor to window: During gameplay

I tried all 4 combinations of (vert/hor scaling at 100% and 64%) and (Windows at 100% and 150%)
In all situations the problem persisted. 
Very rarely at Windows 100% the problem did not occur, but I did not notice any reason why.
To be honest I'm not even certain if the problem rarely not occuring can be linked with Windows at 100%

I hope this was of any help.
I'm always open to any other testing with this issue

**Comment by peppy** [comment]
So there is likely some weirdness with the usage of [ClipCursor](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-clipcursor). Possibly the external "driver" you are using is also relying on clipping being set, and having osu! also manage cursor clip locally is causing issues.

This will still require further investigation, but I can confirm that the SDL logic to handle mouse grabbing matches your reproduction (requires relative/raw mode to be enabled):

https://github.com/libsdl-org/SDL/blob/89b6209313cc65260f88a28ea99ec0df6dd807fc/src/video/SDL_video.c#L2658

**Comment by peppy** [comment]
One extra thing to try (looking through hawku reported issues) is to minimise the hawku UI window. It looks to be clipping the mouse to some extend and may be conflicting with our usage.

**Comment by Thomzzz** [comment]
When you minimize the UI window it is automatically "closed" and put in the hidden icons tab in Windows. When I normally start my PC it automatically starts up in hidden mode, so I never see the UI unless I actually open it myself. I don't expect having the UI open or hidden makes a difference.
