### ISSUE TITLE
osu!lazer not detecting G640 on Debian based OS

### ISSUE THREAD

**Issue by osufan11** [ppy/osu-framework#4335]
Hi! Im a person from india who just wants to  play osu! (I play on stable too on my windows install)
And then i hopped on to linux to see if i would get less lag and yes i did get less lag, but there was a problem. The in-built drivers werent detecting my tablet. I use the  XP-pen Star G640, if anyone could help it would be nice! 
PS : I get an outofrangeexception on start up,  i'm not really an expert of .NET core.

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please include the crash information at very least.

**Comment by osufan11** [comment]
> We cannot do anything with this information, sorry. Please include the crash information at very least.

![Screenshot from 2021-04-02 13-23-01](https://user-images.githubusercontent.com/81799802/113394886-a5cdf000-93b6-11eb-92bf-f60d89d12262.png)
so far i don't know how to download log files but heres some screenshots
![Screenshot from 2021-04-02 13-25-07](https://user-images.githubusercontent.com/81799802/113395026-de6dc980-93b6-11eb-9cd2-5a6275fc1dc1.png)

**Comment by peppy** [comment]
Sorry but we can't support you if you are unable to attach logs.

**Comment by osufan11** [comment]
> Sorry but we can't support you if you are unable to attach logs.

I found a way sorry. 
[database.log](https://github.com/ppy/osu-framework/files/6248400/database.log)
[performance.log](https://github.com/ppy/osu-framework/files/6248402/performance.log)
[runtime.log](https://github.com/ppy/osu-framework/files/6248403/runtime.log)

**Comment by smoogipoo** [comment]
Follow the instructions at https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#argumentoutofrangeexception-value-0-15

**Comment by osufan11** [comment]
@smoogipoo It's only freezing my console, Plus i made a new issue on the OTD repository i told them the exact same thing.

**Comment by smoogipoo** [comment]
Please use another OS.
