### ISSUE TITLE
Investigate font cache failures

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4337]
There have been two cases reported where fonts don't show in game due to a corrupted cache. We need to investigate how this can happen and hopefully prevent it (potentially writing the initial cache to a different file before performing an atomic rename).

https://github.com/ppy/osu/issues/12174#issuecomment-806304053
https://github.com/ppy/osu/issues/12257#issuecomment-812537556

**Comment by peppy** [comment]
I've looked into this one but can't see how this could happen. Also I checked the second report and it doesn't look like there are zero filled files in this case, although there are some zero-byte files:

![20210406 121746 (Finder)](https://user-images.githubusercontent.com/191335/113654125-256b0000-96d2-11eb-8b9b-51600ebf3084.png)

These were generated quite a while back, so it may have been something we've since fixed.

**Comment by NotGumballer91** [comment]
So I've done something after 2021.707.0 released.

I tried replacing my own old cache (only the cache, not online.db and client.db).
My issue is fixed. The star rating number does show without a problem.
[ppy/osu#12257 (comment)](https://github.com/ppy/osu/issues/12257#issuecomment-812492491)

However, I also tried replacing my cache with the first report's uploaded cache as well.
[ppy/osu#12174 (comment)](https://github.com/ppy/osu/issues/12174#issuecomment-806356473)
What's interesting is the fonts works fine. But some textures of doesn't show it all.
![osu_2021-07-08_00-34-48](https://user-images.githubusercontent.com/64581009/124797867-57b42400-df85-11eb-998b-79fe7dafb7e1.png)
![osu_2021-07-08_00-35-07](https://user-images.githubusercontent.com/64581009/124797873-597de780-df85-11eb-98c5-a401fa6cf29b.png)
![osu_2021-07-08_00-37-32](https://user-images.githubusercontent.com/64581009/124797879-5aaf1480-df85-11eb-83df-d398d8f990e9.png)
![osu_2021-07-08_00-37-49](https://user-images.githubusercontent.com/64581009/124797895-5daa0500-df85-11eb-9c1c-abdb50b0b3dd.png)

I believe you guys fixed it in a previous build but only partially.

**Comment by peppy** [comment]
I'm unsure what you are even stating. Loading broken caches in place is of course going to still be broken?

**Comment by peppy** [comment]
Closing this for now. I believe we fixed the underlying issue via #4777.
