### ISSUE TITLE
`cursorInWindow` is wrongfully assumed to be true on startup

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-framework#4400]
https://github.com/ppy/osu-framework/blob/b8e905548bdf517af5bb9790c0bc0b1b8f0205b9/osu.Framework/Platform/SDL2DesktopWindow.cs#L170

This assumption causes `cursorInWindow` not to match the actual cursor state when the mouse is outside the window on startup.

Steps to repro:
1. Open `visual-tests` > `Platform` > `ActiveState`
2. Set window mode to windowed
3. Close visual-tests
4. Open visual-tests, but keep your cursor outside the window
5. `host.Window.CursorInWindow` doesn't match the cursor state (being outside of the window)

In this state, the framework (as seen in `visual-tests` > `Input` > `InputManager`) does not see mouse move events until the cursor enters the window. With the default being false, this works as expected.

I've tracked the change of default to true to https://github.com/ppy/osu-framework/commit/e9d59b6af012a1ff83f588b5d4f31afc6c7a35d0.

**Comment by peppy** [comment]
@Susko3 just to confirm, you've tested with default `false` and it looks to work fine on windows? is there anything stopping you from making a pull request for this?

**Comment by Susko3** [comment]
Everything works as expected on Windows with `false`.

I originally discovered this oddity when working on #4341. With `cursorInWindow` being queued, changing the default to `false` would make the cursor start in the center of the screen in fullscreen mode. But everything works fine now.

Anyway, making a PR.
