### ISSUE TITLE
RelativeSize performance / caching

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#442]
As seen in osu!'s options menu, deeply nested trees which all rely on relativesize in one of more axis can get very slow due to upward tree traversal to get a material size.

![image](https://cloud.githubusercontent.com/assets/191335/22684802/3b2670ce-ed61-11e6-9b3a-ae9434542d69.png)

**Comment by Tom94** [comment]
Addressed with https://github.com/ppy/osu-framework/pull/470
