### ISSUE TITLE
iOS unable to build due to AOT compiler issues

### ISSUE THREAD

**Issue by ProgrammingPleb** [ppy/osu-framework#4434]
A few days ago, I was trying to build [ppy/osu](https://github.com/ppy/osu) and this showed up in the build errors tab:
`/Users/pleb/Downloads/osu-2021.502.0/osu.iOS/MTOUCH: Error MT3001: Could not AOT the assembly '/Users/pleb/Downloads/osu-2021.502.0/osu.iOS/obj/iPhone/Debug/device-builds/ipad6.11-14.2/mtouch-cache/3-Build/Microsoft.Diagnostics.Runtime.dll' (MT3001) (osu.iOS)`

I was looking through some other issues about this and a person was asked to do a command for debugging purposes, which in my case was this: `/Users/pleb/Downloads/osu-2021.502.0/osu.iOS/obj/iPhone/Debug/device-builds/ipad6.11-14.2/mtouch-cache/3-Build/Microsoft.Diagnostics.Runtime.dll`. This resulted in another error: `zsh: illegal hardware instruction  mono --aot`. I tried to reproduce it with other dlls from different libraries and they did not raise the same error.

Looking through the codebase, I found that the library was used here, and I tried building osu!lazer again with lower versions of `Microsoft.Diagnostics.Runtime` and found out that version 2.0.151903 was able to build the framework test app, and osu!lazer itself.

This is a video of the latest lazer release (2021.502.0) with some custom rulesets running on my iPad:

https://user-images.githubusercontent.com/22746909/117129056-cc75b100-add0-11eb-96e8-fc82b9c97fd9.mp4

**Comment by peppy** [comment]
We are well aware of this issue. Unfortunately there are larger problems plaguing iOS deployments (random hard locks in random locations) so we aren't even considering fixing this for now.

You're welcome to PR a fix and we'll consider getting it in, but be warned that there are other issues at hand.
