### ISSUE TITLE
Run Audio Tests in Linux against a dummy audio driver

### ISSUE THREAD

**Issue by sr229** [ppy/osu-framework#4435]
I'm not so sure if we can do this in the current state of how we use SDL in osu!framework, but #4430 is failing when running audio tests. The only way to probably get these to run is to run them against a dummy driver which SDL already provides. SDL has a "dummy" driver which is enough to make a program using the library "think" there's a valid audio driver.

**Comment by smoogipoo** [comment]
This isn't related to SDL - it's BASS not being able to initialise the no sound device for some reason.
