### ISSUE TITLE
Detect HandleInput requirements better

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#444]
Currently `HandleInput` is defaulting to `true` on all containers, even when they are not required to process input. A better default would be `false`, but we need to discussion the level of automation for handling input on a per-case basis (without the user explicitly specifying `true`), if any.

**Comment by Tauntawn** [comment]
Perhaps it would be better to create interfaces for common UI events (Though this also means we would need to create a UI input event system to support it). e.g IBeginDragHandler, IClickHandler etc. This would also unify the UI Logic and allow for bubbling.

I'm no expert by any means but it seems like a much simpler and open solution then the current one. I'm saying this on the assumption that containers are only ever used for Drawables, which it looks like they are.

**Comment by Tom94** [comment]
I don't see how this would simplify the problem we need to tackle here: We _need_ early stopping of the downward recursion for performance reason when we have large collections of drawables that all do not handle input. So with your proposed solution we would still need some wort of automatic detection of whether any children handle input, but unlike with the `HandleInput` bool this can not be changed at the type-level automatically on-the-fly.

**Comment by smoogipoo** [comment]
Resolved by the HandleInput changes a while back.
