### ISSUE TITLE
Overridden virtual members called through base BDL cannot access derived class's `[Resolved]` fields

### ISSUE THREAD

**Issue by bdach** [ppy/osu-framework#4442]
Spotted in https://github.com/ppy/osu/pull/12688.

Illustrative example because title is bad (wrote in issue editor, please don't yell if doesn't compile):

```csharp
public abstract class BaseComponent : CompositeDrawable
{
	protected abstract Drawable CreateContent();

	[BackgroundDependencyLoader]
	private void load()
	{
		InternalChild = CreateContent();
	}
}

public class DerivedComponent : BaseComponent
{
	[Resolved]
	private ColourProvider colourProvider { get; set; }

	protected override Drawable CreateContent() => new Box
	{
		RelativeSizeAxes = Axes.Both,
		Colour = colourProvider.GetColour()
	}
}
```

Something like this will die on a nullref in the derived `CreateContent()`, because it's being called from the base BDL, and the derived's `[Resolved]` fields have not been injected yet.

This feels like a major pain point, although it might also indicate that there is too much inheritance going on - but this is a pattern that basic UI components use a lot, and the workaround to me (storing references to the drawables in the overidden methods and then using the derived BDL to do the rest, as the aforementioned PR currently does) seems really bad to me.

It also feels that fixing this might be as "easy" as making sure all `[Resolved]` fields are injected before running any BDLs in the inheritance hierarchy... but I'm not entirely confident enough to say that is 100% what we want.

**Comment by peppy** [comment]
99% sure this is "as intended" and not sure we can do better. it's the same issue as virtual methods in constructors and doesn't have a simple solution.

**Comment by smoogipoo** [comment]
It's as intended because BDL is supposed to be akin to constructors, but I think the question to be answered is whether this scenario is different from BDL.

That is, is the following scenario different?:
```csharp
public abstract class BaseComponent : CompositeDrawable
{
    protected abstract Drawable CreateContent();

    [BackgroundDependencyLoader]
    private void load()
    {
        InternalChild = CreateContent();
    }
}

public class DerivedComponent : BaseComponent
{
    private ColourProvider colourProvider;

    [BackgroundDependencyLoader]
    private void load(ColourProvider colourProvider)
    {
        this.colourProvider = colourProvider;
    }

    protected override Drawable CreateContent() => new Box
    {
        RelativeSizeAxes = Axes.Both,
        Colour = colourProvider.GetColour()
    }
}
```
Ignoring the fact that it's identical to `[Resolved]` - imagine it being some more complex logic.

I think there's a reasonable argument to say that these two scenarios are different, because one is just primitive dependency injection while the other is more like dependency injection + logic.
If these are not different scenarios, then I would be against changing the order of BDL, as that method is supposed to match ctors as mentioned above.

**Comment by peppy** [comment]
As per previous discussion where you explained this to me, I see both of these as the same thing (they should not behave differently). So my opinion is we either support both or none. And supporting both isn't really feasible.

But I can see the value in offering different behaviour here, so I'm not sure.

**Comment by frenzibyte** [comment]
Not sure if my opinion matters, but I would tend to think they're different scenarios, if a dependency is required outside of BDL scope, then it should be `[Resolved]` outside of BDL, rather than set it to a certain field from inside the BDL then use elsewhere on an overridden method, which would sound like it would result in different behaviour.

**Comment by smoogipoo** [comment]
Here's another interesting one - `[Cached]` works on the entire hierarchy before anything is loaded at all, unlike `[Resolved]`:

```csharp
public class TestSceneCached : FrameworkTestScene
{
    public TestSceneCached()
    {
        Child = new B();
    }

    public class A : CompositeDrawable
    {
        [Cached(Name = "A")]
        private readonly object objA = new object();

        [BackgroundDependencyLoader]
        private void load()
        {
            InternalChild = new C();
        }
    }

    public class B : A
    {
        [Cached(Name = "B")]
        private readonly object objB = new object();
    }

    private class C : Drawable
    {
        [Resolved(Name = "B")]
        private object objB { get; set; }

        [BackgroundDependencyLoader]
        private void load()
        {
            Assert.That(objB != null);
        }
    }
}
```
Arguably, in this case it's going through `CreateChildDependencies()`, which is overrideable at any point.

**Comment by bdach** [comment]
> That is, is the following scenario different?

I kinda see it as different. Having BDL methods run in base-to-derived obviously makes sense. But I don't think about `[Resolved]` attributes as initialisation logic, comparatively. It feels more like data at that point. Like a `static readonly` field with an initialiser, to give a bad example.

The point about potentially mutating the dependency container is very valid, though, and throws a spanner into the entire thing. If a base class is to be able to substitute in a dependency (and we have actual usages of that pattern), then none of the above makes sense anymore and the only applicable time to inject anything is after base BDLs have run, since there is an actual data dependency there in that case.

**Comment by bdach** [comment]
I'm going to go ahead and close this the explanations above are enough to convince me that this can't work as proposed and there's a viable workaround available in the case of the aforementioned PR.
