### ISSUE TITLE
Application execution may never end (deadlock in MIDI library)

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4486]
A user provided a memory dump of a stuck instance of osu!, which could be traced back to the internals of the MIDI library we're using:

![20210604 122328 (Parallels Desktop app)](https://user-images.githubusercontent.com/191335/120741255-abb78d00-c52f-11eb-9882-ef30c6ff40ed.png)

This looks to be a lock contention issue, but it's not immediately obvious why this is happening. The library itself is unmaintained so we will likely need to look at fixing ourselves (and submitting a PR with hope it is merged and deployed).

As an aside, it looks like another user has encountered this same issue and published a potential fix for it to their own fork:

https://github.com/Knuhl/managed-midi/commit/f8799f165dab619fdbed2e092c3fc66d64723392

**Comment by tutacat** [comment]
Since that was merged, this can probably be closed now.

**Comment by peppy** [comment]
@tutacat what is "that" referring to? if you can provide a link for confirmation that would be appreciated.

**Comment by bdach** [comment]
https://github.com/atsushieno/managed-midi/pull/74 probably. That said, this fix is in 1.10.1, and we haven't upgraded to that version yet. So if anything we'd need a bump to get that change in.
