### ISSUE TITLE
Consider changing `KeyCombination.ToString`'s implementation

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4487]
Currently the fact that `KeyCombination` returns a comma separated list of `int`s makes understanding it hard for two reasons:

## When looking at tests, it's hard to know where adjacent `KeyCombination`s are delimited

In this example, there are *two* `KeyCombination` arguments provided to these tests. There's no way of knowing which one of them has multiple keys:

![20210604 131534 (JetBrains Rider-EAP)](https://user-images.githubusercontent.com/191335/120744918-03a5c200-c537-11eb-8575-91cbfff112cd.png)

## They are showing as `int`s rather than understandable `string`s

We already have a readable string implementation so should probably be using it here.

Opening as an issue because the `ToString` implementation is currently used as a "serialisation" method for these, which is also accepted in the `ctor` of `KeyBinding`. If we're changing the format we would need to support the old and new in some way.

As reference, here's the same tests above with a more readable `ToString()` implementation:

![20210604 131802 (JetBrains Rider-EAP)](https://user-images.githubusercontent.com/191335/120745089-58e1d380-c537-11eb-9791-74ba43d84b8a.png)

**Comment by Joehuu** [comment]
Isn't this a duplicate of https://github.com/ppy/osu-framework/issues/4338.

**Comment by peppy** [comment]
I had a feeling of deja vu.
