### ISSUE TITLE
Switching to fullscreen in macOS disables outer functionalities completely

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#4488]
We may not want fullscreen to disable everything else outside the game (e.g. menu bar, dock, desktops navigation), that's inconsistent with other platforms like Windows.

---

When in fullscreen mode in settings (not the native macOS fullscreen green button thing or borderless), it seems I can't use the rest of the OS and have to exist osu to use or see anything else. Is there a way to get out of it or is it an issue thats not fixed yet?

Borderless isn't viable for me because it seems changing resolution doesn't work or is unimplemented yet and playing at native resolution makes my mac go to 80C with terrible FPS

I'm running version 2021.602.0 on a 2015 MacBook Pro i5 13"

_Originally posted by @NafeeJ in https://github.com/ppy/osu/discussions/13351_

**Comment by peppy** [comment]
That is how macOS works.
