### ISSUE TITLE
`FrameworkFont` does not work outside of Visual Tests

### ISSUE THREAD

**Issue by jai-x** [ppy/osu-framework#4524]
osu!framework version: `2021.601.0`

Reproduction Repo:
https://github.com/jai-x/font-test

Running `dotnet run -p FontTest.Game.Tests`:
![font_test_working_test](https://user-images.githubusercontent.com/8362491/122387388-b712ab80-cf66-11eb-9428-4c12a39b9deb.png)

Running `dotnet run -p FontTest.Desktop`:
![font_test_not_working_desktop](https://user-images.githubusercontent.com/8362491/122387419-bed25000-cf66-11eb-9a1f-277f9b5f6f81.png)

**Comment by bdach** [comment]
Cause is pretty obvious here. The test browser is loading the fonts on its own.

https://github.com/ppy/osu-framework/blob/0b4a9c6834041119e25cab1d00e79acfdfceb980/osu.Framework/Testing/TestBrowser.cs#L143-L149

For this to be fixed the framework fonts would have to be registered in `Game`, the same way Open Sans and FontAwesome currently are. Which may be fine to do but it may cost a bit of startup time.

**Comment by peppy** [comment]
Might need to be opt-in. I don't think we want to be loading even more fonts than we already are.

Maybe want to consider opt in/out of OpenSans/FontAwesome too, not sure.

**Comment by bdach** [comment]
Well, an opt-in option is for the users to call `AddFont()` on their own if they know what to add. Maybe there should be an `AddFont(FontUsage)` overload that checks against `FrameworkFont` or something?

I also considered lazy-loading on first reference but that seems like a not-good idea...
