### ISSUE TITLE
Interpolation throws a `TypeInitializationException` when using with `Colour4`

### ISSUE THREAD

**Issue by devclyde** [ppy/osu-framework#4581]
I'm trying to do a little animation on a `SpriteText` in the `Update` method, what I want is to make the text color change every 500ms, from golden to lighter golden.

I saw in the documentation, in the topic [Transformations and Tweening](https://github.com/ppy/osu-framework/wiki/Transforms-and-Tweening), that in order for the transformation to occur at each frame, it is recommended to use interpolation.

Here is the code:
```cs
protected override void Update()
{
    textLogo2.Colour = Interpolation.ValueAt(Clock.ElapsedFrameTime, Colour4.Gold, Colour4.Gold.Lighten(1), 0, 200, Easing.OutQuint);

    base.Update();
}
```

The result is an Exception:
```
[runtime] 2021-07-08 00:01:02 [error]: An unhandled error has occurred.
[runtime] 2021-07-08 00:01:02 [error]: System.TypeInitializationException: The type initializer for 'GenericInterpolation`2' threw an exception.
[runtime] 2021-07-08 00:01:02 [error]: ---> System.NotSupportedException: Type osu.Framework.Graphics.Colour4 has no interpolation function. Implement the interface osu.Framework.Utils.IInterpolable`1[osu.Framework.Graphics.Colour4] interface on the object.
[runtime] 2021-07-08 00:01:02 [error]: at osu.Framework.Utils.Interpolation.GenericInterpolation`2..cctor()
[runtime] 2021-07-08 00:01:02 [error]: --- End of inner exception stack trace ---
[runtime] 2021-07-08 00:01:02 [error]: at osu.Framework.Utils.Interpolation.ValueAt[TValue,TEasing](Double time, TValue startValue, TValue endValue, Double startTime, Double endTime, TEasing& easing)
[runtime] 2021-07-08 00:01:02 [error]: at osu.Framework.Utils.Interpolation.ValueAt[TValue](Double time, TValue startValue, TValue endValue, Double startTime, Double endTime, Easing easing)
```

**Comment by gagahpangeran** [comment]
Looks like `Interpolation` only support `Color4` but not `Colour4`.

https://github.com/ppy/osu-framework/blob/d44d62688fb9e6cabb0e036c2f938657a926e3eb/osu.Framework/Utils/Interpolation.cs#L138-L139

**Comment by devclyde** [comment]
> Looks like `Interpolation` only support `Color4` but not `Colour4`.
> 
> https://github.com/ppy/osu-framework/blob/d44d62688fb9e6cabb0e036c2f938657a926e3eb/osu.Framework/Utils/Interpolation.cs#L138-L139

Thanks, I tested it and it worked. It should have an interpolation implementation for `Colour4`.

**Comment by frenzibyte** [comment]
As an aside, if you want to perform a looping transform on the drawable, you can append the `Loop` method at the end of the transform sequence and pass the number of milliseconds the loop would pause for.

So in your case (based on how you described what you want):
```csharp
protected override void LoadComplete()
{
    textLogo2.FadeColour(Colour4.Gold) // initial colour
                      .FadeColour(Colour4.Gold.Lighten(1), 200, Easing.OutQuint); // colour to fade to
                      .Loop(300); // loop the above sequence, with a pause of 300ms after each iteration.
}
```
