### ISSUE TITLE
`Sprite` does not fill the screen like `Windowed` if it is in `Fullscreen` mode

### ISSUE THREAD

**Issue by devclyde** [ppy/osu-framework#4584]
I need `Sprite` to fill the entire screen like it did in windowed mode, with the spacing at the top and bottom as you can see in its screenshot in windowed mode.

My problem is that I can't make it look the same as it is in windowed mode except fullscreen, if I increase the size it will go over the limits in windowed mode and it's fine in fullscreen mode.

I expected this result from the size:
![Windowed Mode](https://user-images.githubusercontent.com/49321124/125000219-48d17e00-e026-11eb-8953-b45267eb1c52.png)

But it didn't turn out the way I wanted:
![Screenshot_20210708_194322](https://user-images.githubusercontent.com/49321124/125000239-56870380-e026-11eb-8900-ee9668effc1d.png)

The code I'm using to call `Sprite`:
```cs
// I am using C# 9

public class PacmanMaze : CompositeDrawable
{
    private Sprite mazeSprite;
    [BackgroundDependencyLoader]
    private void Load(NearestTextureStore textures)
    {
        var mazeTexture = textures.Get(@"maze");
        AddRangeInternal(new Drawable[]
        {
            mazeSprite = new()
            {
                Anchor = Anchor.Centre,
                Origin = Anchor.Centre,
                Texture = mazeTexture,
                Size = mazeTexture.Size * 3
            }
        });
    }
}
```

I called `PacmanMaze` for the hierarchy like this:
```cs
// I am using C# 9

AddRangeInternal(new Drawable[]
{
    maze = new()
    {
        Anchor = Anchor.Centre,
        Origin = Anchor.Centre,
    },
    scoreText = new()
    {
        Anchor = Anchor.TopLeft,
        Origin = Anchor.Centre,
        Text = "SCORE: 0",
        RelativePositionAxes = Axes.Both,
        X = 0.07f,
        Y = 0.05f
    }
});
```

**Comment by frenzibyte** [comment]
Seems like you're looking for `DrawSizePreservingFillContainer`, which is explained in https://github.com/ppy/osu-framework/wiki/Coordinate-and-Layout-System#scaling-absolute-values-to-screen-size.

**Comment by devclyde** [comment]
Exactly what I was looking for! I haven't read this topic in the documentation, I'm going to make a point of reading it. Thanks!
