### ISSUE TITLE
Framework key bindings not working on Linux

### ISSUE THREAD

**Issue by devclyde** [ppy/osu-framework#4585]
I need to get some info from a `Drawable` of the game but live, with all the updates and everything, from what I saw in the topic [Framework Key Bindings](https://github.com/ppy/osu-framework/wiki/Framework-Key-Bindings), it is possible to call the `DrawVisualiser` and show that info.

The problem is that these key bindings are not working on Linux, only the `CycleFrameStatistics` key binding is working.

This one is the specs of the operating system I use:
```abnf
Operating System: Manjaro Linux x86_64
Host: Inspiron 5548 A04
Resolution: 1920x1080
Desktop Enviroment: KDE Plasma 5.21.5
Window Manager: kwin
CPU: Intel i7-5500U (4) @ 3Ghz
GPU: AMD ATI Radeon R7 M260/M265 / M340/M360 / M440/M445 / 530/535 / 620/625 Mobile 
GPU: Intel HD Graphics 5500
```

Is there any way to change these key bindings?

**Comment by peppy** [comment]
There is no way to change these key bindings. You will need to figure what it eating them on your system.

**Comment by jai-x** [comment]
@devclyde Just to resolve some possible ambiguity, these keybinds do actually work when running the framework on Linux. You should be able to see the keybinds being logged and handled in the debug runtime log. If you can't see these logged, then something on your system is swallowing this inputs

**Comment by devclyde** [comment]
> @devclyde Just to resolve some possible ambiguity, these keybinds (Ctrl+F1, Ctrl+F2, etc) do actually work when running the framework on Linux. You should be able to see the keybinds being logged and handled in the debug runtime log. If you can't see these logged, then something on your system is swallowing these inputs.

Apparently the KDE Plasma hotkeys were using them to switch desktops. I managed to solve it!
