### ISSUE TITLE
Support WebAssembly rulesets

### ISSUE THREAD

**Issue by poly000** [ppy/osu-framework#4592]
The idea is from [feather](https://github.com/feather-rs/feather/)'s [plugin](https://github.com/feather-rs/quill) system.

1. implement wasm VM in osu-framework
2. write wasm API, for languages supported target to WASM, like rust, go, ...

This will allow developers who don't know C# well to develop custom rulesets

**Comment by peppy** [comment]
wrong repository, but also out of scope and not going to happen ever.

**Comment by devclyde** [comment]
The framework is independent of osu!(the game itself), i think you made the issue in the wrong repository

**Comment by poly000** [comment]
> The framework is independent of osu!(the game itself), i think you made the issue in the wrong repository

Thanks. I guess this should be put in [osu](https://github.com/ppy/osu)
