### ISSUE TITLE
Opening game sets `WindowedPositionX/Y` to (0.5, 0.5)

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-framework#4608]
I've been testing this on Windows only.

Every time osu!/visual tests are opened, `WindowedPositionX` and `WindowedPositionY` get set to `0.5`. This happens with all `WindowMode`s: windowed, borderless and fullscreen.

To repro:
1. Open game
2. Set to windowed
3. Move window to a position that is not the center of the screen
4. Close game
5. Open game
6. (Bonus) Check `framework.ini` (values will be 0.5)
7. Cycle `WindowMode` to windowed (3x<kbd>F11</kbd>)
8. The window will be in the center of the screen, and not in the position it opened in.

**Comment by peppy** [comment]
Would be helpful if someone can figure which PR/commit this regressed with. It used to work.

**Comment by peppy** [comment]
Bumping up in priority as this is pretty broken (window position is not being stored after a second execution currently).

**Comment by bdach** [comment]
For what it's worth, I've just tried to repro with both framework visual tests and game on my linux box, and cannot. Possibly platform-specific, somehow? SDL bug even?

**Comment by peppy** [comment]
It's windows specific yeah. Was a regression from one of the recent changes I made to fix a separate issue.

**Comment by Susko3** [comment]
Not sure which commit this regressed with, but `WindowedPositionX/Y` gets set to `0.5` at startup by this code

https://github.com/ppy/osu-framework/blob/d67f53a4ef7b2b9d21630664b6f81a4601386d64/osu.Framework/Platform/SDL2DesktopWindow.cs#L1128-L1133

This was added by https://github.com/ppy/osu-framework/commit/ebee2dceaa66ef6213b590ac69eb9132639e7a14. Haven't looked at the code too much, but I'm guessing this was used to center the window when changing the display in fullscreen.

Why should changing the display always center the window? The window probably only needs to be centered in fullscreen and borderless. But the framework doesn't expose a way to change the display, and the user isn't normally able to move a (borderless) fullscreen window, so it should always be centered.

Additionally, borderless and fullscreen windows don't use `windowPositionX/Y`. It's only used for windowed:

https://github.com/ppy/osu-framework/blob/d67f53a4ef7b2b9d21630664b6f81a4601386d64/osu.Framework/Platform/SDL2DesktopWindow.cs#L901-L902

https://github.com/ppy/osu-framework/blob/d67f53a4ef7b2b9d21630664b6f81a4601386d64/osu.Framework/Platform/SDL2DesktopWindow.cs#L992-L1000

The purpose of this code is really cryptic to me. I'd say it's best to remove it. Removing it fixes this issue.

**Comment by peppy** [comment]
@Susko3 have you confirmed whether the game starts centered given no previous configuration? That's the likely goal of the code you mention, so unless it's specified somewhere else, at very least it needs to be moved.

**Comment by Susko3** [comment]
The defaults set here work as expected.

https://github.com/ppy/osu-framework/blob/d67f53a4ef7b2b9d21630664b6f81a4601386d64/osu.Framework/Configuration/FrameworkConfigManager.cs#L28-L29

**Comment by peppy** [comment]
Hard to say then. Have you tested switching between monitors while the game is in a windowed state? The only thing I can think of is that this was added to guarantee the window stays on screen. If you've confirmed that is still the case, maybe we can drop the code.

**Comment by Susko3** [comment]
Modifying `WindowedPositionX/Y` doesn't actually move the window. Those values are read and applied in `readWindowPositionFromConfig()`. Which is only called in `updateWindowStateAndSize()` when `WindowState` is `Normal`. Which is only called in `updateWindowSpecifics()` when `pendingWindowState != null`, so when the user has changed the window mode (or on startup).

**Comment by peppy** [comment]
I'd definitely push the change then. We'll have to do some testing across platforms to make sure there are no regressions, but sounds promising.

**Comment by Susko3** [comment]
Will PR the changes shortly.

Also, the defaults here guard against the window being off-screen. In each direction, the window will at least be half on-screen.

https://github.com/ppy/osu-framework/blob/d67f53a4ef7b2b9d21630664b6f81a4601386d64/osu.Framework/Configuration/FrameworkConfigManager.cs#L28-L29
