### ISSUE TITLE
Restore window settings on startup.

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#461]
- [x] Save/restore window position to framework configuration.
- [x] Save/restore fullscreen state.
- [x] Bonus points for adding borderless support (including restoring borderless on restart).

Note that window position should be stored as a *relative position* where (0.5,0.5) is centre of monitor and (0,0) means the window's top-left corner is in the monitor's top-left corner.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41841004)](https://www.bountysource.com/issues/41841004-restore-window-settings-on-startup?utm_source=41841004&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by freakode** [comment]
Currently taking a crack at this.
