### ISSUE TITLE
Improve message of `Drawable`-related exceptions for identifying failing drawable

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#4610]
Right now it's impossible to determine what drawable is causing exceptions to be thrown, especially `FillFlowContainer`-related ones (which I've been struggling with right now).

A simple way I can think of right now would be appending the name of all parents of the failing drawable in the exception message.

**Comment by peppy** [comment]
Can you give an example scenario? Is something happening in layout code which doesn't trigger the debugger?

**Comment by frenzibyte** [comment]
Like this one for example:
https://github.com/ppy/osu-framework/blob/768729cb9a6255e009d64f46eae142daceafc6e2/osu.Framework/Graphics/Containers/FillFlowContainer.cs#L245-L253

Attaching a debugger wouldn't help:
![CleanShot 2021-07-16 at 05 30 43](https://user-images.githubusercontent.com/22781491/125882583-7bd2472e-d136-49a2-9b97-ec1feff4855e.png)

It would be very handy if it brings me to the `Drawable` context rather than the rethrow logic in `GameThread`, is that feasible through IDE somehow?

**Comment by peppy** [comment]
You have turned off "break on all exceptions". Please turn it back on.

**Comment by frenzibyte** [comment]
Right, thanks. Should the issue remain open? not sure anymore now that debugger can be used for it.

**Comment by peppy** [comment]
Not sure. Ideally we would be able to throw specifically from the location but I think due to our exception flow that's not feasible for cases like this. @smoogipoo may be able to give a better answer on that one.

**Comment by smoogipoo** [comment]
Yeah, I don't think this is possible due to the rethrow on the input thread :/.

**Comment by peppy** [comment]
Will close this for now.
