### ISSUE TITLE
`KeyCombination.ReadableString()` should take user's keyboard layout into account

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-framework#4618]
This is the framework-side issue for https://github.com/ppy/osu/issues/11143.

I think the underlying way keybinds work should remain as it is now, use scancodes to map keys to actions.
What needs changing is how those keybinds are displayed to the user. Right now, it maps scancodes (technically, `InputKey` is used, but it's a 1:1 mapping to scancodes) to keys on a English (US) keyboard.

Going forward, the way keybinds are stringified for display to the user should change. It should respect the curretly selected keyboard layout: if the user presses the key <kbd>Đ</kbd> for a keybind, it should be reflected as <kbd>Đ</kbd> in the UI. Since we will take the current keyboard layout into account, the implementation will become platform-dependant (as each platform will have a different way to get the current keyboard layout, and to convert scancodes/`InputKey`s to user-readable strings).

For platforms using SDL2, [SDL_GetKeyName](https://wiki.libsdl.org/SDL_GetKeyName) seems like the best and easiest to implement option. Trough a simple series of conversions, we can convert `InputKey`s to user-readable strings:

- `InputKey` &rarr; `SDL_Scancode` (reverse of [SDL2Extensions.ToKey](https://github.com/ppy/osu-framework/blob/192b0eeeb1af9457bac12658d36a24c657bbed04/osu.Framework/Platform/SDL2/SDL2Extensions.cs#L13))
- `SDL_Scancode` &rarr; `SDL_Keycode` (https://wiki.libsdl.org/SDL_GetKeyFromScancode) (this part of the conversion is dependant on the current keyboard layout)
- `SDL_Keycode` &rarr; key name (https://wiki.libsdl.org/SDL_GetKeyName)

These key names are specific to the current keyboard layout, and seem to work perfectly, I've tested multiple keyboard layouts on Windows, and the key names returned by `SDL_GetKeyName` are a perfect match to the keys on the keyboard layout. (There are some problems with specific keys on some keyboard layout, but nothing major.)

I would like to implement this, but I'm not sure about some things:
- Since this is platform-specific code, I'm not sure where to put it. We will probably have a unified implementation for SDL2 desktop platforms, and (in the future) separate implementations for Android and iOS (which should fall back to what we currently have for the time being).
- There seem to be inconsistencies in how some `InputKey`s are stringified:
    - `BracketLeft` and `BracketRight` show `(` and `)`, while those keys are actually square brackets: <kbd>[</kbd> and <kbd>]</kbd>
    - On the numpad (with NumLock on): Pressing number keys `0-9` shows `Numpad1`, `Numpad2` etc., while `+-*/,` show `KeypadDivide`, `KeypadDecimal` etc. (I suggest we use `Numpad*` or `NumpadMultiply`, etc. for those.
    - Minus and plus show `Minus` and `Plus` instead of `-` and `+`. I presume this is on purpose, as to make the keys readable in combinations: `Ctrl--` and `Ctrl-+` look bad.

I'd like some clarification on those inconsistencies and where exactly to implement this.

Also, I'd be grateful if someone can test this on Linux and macOS with various keyboard layouts. [Code here](https://gist.github.com/Susko3/85580d02d2ff7ecb19de95a3a76c0b10).

**Some extra notes**

According to the Microsoft Keyboard Layout Creator, all the keys shown in white can be customized by a keyboard layout:

![image](https://user-images.githubusercontent.com/16479013/126154532-e1b3dc31-66d4-48a1-b1ef-7ef9648e5d2b.png)

We cannot assume that the number row will be numbers (example is the Slovak keyboard, which doesn't have numbers in the number row). We also cannot assume that the numpad decimal separator is always a dot (`.`), as some keyboards have a comma (`,`) 

We can assume that Space will always be Space because trying to put a non-space character on space results in:

![image](https://user-images.githubusercontent.com/16479013/126154800-1f46209b-9550-465f-89e8-eb40b9b913b2.png)

Characters/strings returned by `SDL_GetKeyName` for non-English characters are usually lowercase. We should do a `.ToUpper()` on the returned value.

In the new implementation, I think we should use `SDL_GetKeyName` only on keys that can be customized by a keyboard layout, and use our current system for all other keys.

Since the new key names are dependant on the current keyboard layout, if a user changes the keyboard layout, all the currently displayed key combinations names should be invalidated and recreated.

**Comment by bdach** [comment]
> Since this is platform-specific code, I'm not sure where to put it. We will probably have a unified implementation for SDL2 desktop platforms, and (in the future) separate implementations for Android and iOS (which should fall back to what we currently have for the time being).

I think that if SDL functions are going to be used for this then the piece of code that does it needs to not live in or be directly referenced by `KeyCombination`, because there's just no reasonable clean way to make it work there. Something like a `IReadableKeyCombinationProvider`, that the game host would cache and anything that needs it could resolve, would probably be one of the cleaner options. If the game host doesn't provide that it could fall back to a generic implementation of that interface that just performs he current logic.

> * `BracketLeft` and `BracketRight` show `(` and `)`, while those keys are actually square brackets: [ and ]
> * On the numpad (with NumLock on): Pressing number keys `0-9` shows `Numpad1`, `Numpad2` etc., while `+-*/,` show `KeypadDivide`, `KeypadDecimal` etc. (I suggest we use `Numpad*` or `NumpadMultiply`, etc. for those.

These sound fine to change/unify.

> * Minus and plus show `Minus` and `Plus` instead of `-` and `+`. I presume this is on purpose, as to make the keys readable in combinations: `Ctrl--` and `Ctrl-+` look bad.

These should remain as `Minus` and `Plus` I think. Agree with the above rationale.

**Comment by Beyley** [comment]
> Also, I'd be grateful if someone can test this on Linux and macOS with various keyboard layouts

I ran the app and played around with 4 different layouts on my bedrock linux install (all apps on an arch stratum)
[link](https://www.youtube.com/watch?v=AQbfaYQW0-M)

**Comment by frenzibyte** [comment]
Can confirm it's working properly on macOS testing with various keyboard layouts (colemark, right-handed/left-handed dvorak, etc.)

I can also switch layouts and the program will report the right key code on the go.

**Comment by Beyley** [comment]
> I can also switch layouts and the program will report the right key code on the go.

Thats odd, maybe its KDE doing that then, i might install some other DEs and see if they also fail at changing on the fly

**Comment by Susko3** [comment]
I've (mostly) implemented an SDL2 readable key name provider, but I've run into a problem.

When the keyboard layout is changed, all currently displayed key combinations should be invalidated. SDL2 provides a `SDL_KEYMAPCHANGED` event, but I'm not sure what's the best way to propagate this to / consume this event from users of `KeyCombination.ReadableString()`.

First that comes to mind is to go trough `SDL2DesktopWindow` &rarr; `KeyboardHandler` &rarr; (new) `KeymapChange` `IInput` &rarr; `...` &rarr; (then finally) `KeymapChange` `UIEvent` that gets consumed by a drawable via `OnKeymapChange()`.
Is this too complicated for such a niche event?

@bdach any guidance on this?

**Comment by bdach** [comment]
Sounds like a perfect use case for a bindable, if I'm honest. I'd recommend taking a look at `LocalisedBindableString` et al. for a similar use case but for language localisation.

**Comment by frenzibyte** [comment]
Thought it may as well go under `LocalisableString` as a `KeyBindingString` but a bit unsure about refreshing everything on keymap changes, it'll simplify a lot of the flow required to propagate the change to sprite texts but not sure on the performance side and whether it's worth it.

**Comment by Susko3** [comment]
All displayed key combinations must update on keyboard layout change, this is required to provide a consistent UX.

If this weren't the case (eg. if key combinations only updated on game startup, or when changing the key binding) the following unwanted scenario could happen:

- user open osu! and realizes they have the wrong keyboard layout set
- the user changes the keyboard layout
- later, the user goes to change key bindings
- now, current keybinds use the old layout, while newly set ones use the new layout, creating a confusing UX

Looking to the future, we might decide to teach the user keyboard shortcuts by showing educational text on screen (eg. "Press Ctrl-S to save"). If the user changes their keyboard layout, the text should reflect that.

Also, I noticed that the font used for keybinds in osu! has very limited support for international characters. Since keyboard layouts can have many different characters, that font will have to change.

**Comment by frenzibyte** [comment]
> All displayed key combinations must update on keyboard layout change, this is required to provide a consistent UX.
> 
> If this weren't the case (eg. if key combinations only updated on game startup, or when changing the key binding) the following unwanted scenario could happen:
> 
> * user open osu! and realizes they have the wrong keyboard layout set
> * the user changes the keyboard layout
> * later, the user goes to change key bindings
> * now, current keybinds use the old layout, while newly set ones use the new layout, creating a confusing UX

I'm not talking about refreshing the displayed keybindings on layout change, I'm literally talking about everything refreshing, every sprite text displayed on the screen, which is why I'm mainly concerned about performance. But I think it should be a negligible overhead when nothing in the sprite text gets invalidated.

**Comment by bdach** [comment]
@frenzibyte putting keybinding stuff in localisablestring is plain wrong. i only ever brought it up as a demonstrative *example* of how this could be done.

also, if using bindables to reload text is a worry, then you would also have to redo the localisation system from scratch too.

**Comment by Susko3** [comment]
> I'm not talking about refreshing the displayed keybindings on layout change (that's obviously wrong), I'm literally talking about everything refreshing, every sprite text displayed on the screen, which is why I'm mainly concerned about performance. But I think it should be a negligible overhead when nothing in the sprite text gets invalidated.

The change would never reach all `SpriteText`s, only those using readable `KeyCombination`s. As is the case with `LocalisedBindableString`, only updated if using `ILocalisableStringData` and not is updated and propageted if using plain `string`s. See this method for mode details:

https://github.com/ppy/osu-framework/blob/197a30cd6d545aac29d3da2d19316fd97a593ee3/osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs#L28

**Comment by frenzibyte** [comment]
> @frenzibyte putting keybinding stuff in localisablestring is plain wrong. i only ever brought it up as a demonstrative _example_ of how this could be done.
> 
> also, if using bindables to reload text is a worry, then you would also have to redo the localisation system from scratch too.

Yeah I backed down from that approach altogether on the second paragraph, never mind that.
