### ISSUE TITLE
AudioDevice switching behaviour

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#464]
A summary of the behaviour we expect from audio devices.

- [x] Switching audio device should not result in any interruption to playback. This should be done at a bass level where possible, or via framework classes (sample/track) failing that.
- [x] If the default device is selected, it should follow the system default device (ie. when you [change the default device in windows](https://puu.sh/tW4aH/59422e5fd0.gif)
- [x] If a custom device is selected, it should remain the device saved to config even if it is lost (disconnected). It should be used again when reconnected.
- [x] During the period a custom device is unavailable, the system default should be used (but not saved to config).
- [x] An event should be available to let framework consumers know that a new device has become available or a device has been disconnected (so they can update their UI).
- [x] Update the options dropdown / device list with the latest available devices.
- [x] Display a non-empty device name in the options dropdown when the device selected by the config is not available.
- [ ] We should be able to run and play the game without an audio device being present (should not hard crash). Timing will be handled by clocks; that is outside the scope of this issue. https://github.com/ppy/osu-framework/issues/157

**Comment by Tom94** [comment]
First 5 points are addressed by https://github.com/ppy/osu-framework/pull/468 .

The next 2 points will be addressed by an osu-level PR, and the last point is conceptually a bit different since it related to the clocks / timing logic we use, rather than audio device selection.

**Comment by Tom94** [comment]
Moved last point into a new issue since it's somewhat disconnected from all the other problems in here which have already been addressed.
