### ISSUE TITLE
Investigate reverting SDL flag state with upstream fix

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4640]
In https://github.com/ppy/osu-framework/pull/4348, we set the value of `SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS` to fix an issue, but the default behaviour has since changed upstream (see https://github.com/libsdl-org/SDL/issues/4039#issuecomment-888631425). We will want to test the next SDL bump and see whether we still need this flag.

**Comment by Joehuu** [comment]
Closing as stale. It has been configurable as a setting since https://github.com/ppy/osu-framework/pull/6094.
