### ISSUE TITLE
Kills desktop effects globally

### ISSUE THREAD

**Issue by martmists-gh** [ppy/osu-framework#4642]
Desktop effects are killed globally when an osu-framwork application is running; Some parts like disabling decorations are fine, but transparency, wobbly windows, smooth animations for actions, etc are all disabled as long as it is running.

See also https://github.com/vignette-project/vignette/issues/223

**Comment by frenzibyte** [comment]
Is this an issue you're currently having? what platform is this?

**Comment by peppy** [comment]
We can't deal with reports like this, sorry.

**Comment by martmists-gh** [comment]
> Is this an issue you're currently having? what platform is this?

Yes, this is running on Arch Linux.

**Comment by martmists-gh** [comment]
> We can't deal with reports like this, sorry.

Why not? Is there not enough information, or is it because it's a third-party application?

**Comment by smoogipoo** [comment]
"Arch Linux" doesn't tell us anything. We need to know what WM/DE you're running.

Also, sounds like you've got some setting in your compositor allowing OpenGL applications to disable it. I know there's such a setting for KWin though I can't exactly remember whether it's fullscreen only or not.

**Comment by martmists-gh** [comment]
> "Arch Linux" doesn't tell us anything. We need to know what WM/DE you're running.
> 
> Also, sounds like you've got some setting in your compositor allowing OpenGL applications to disable it. I know there's such a setting for KWin though I can't exactly remember whether it's fullscreen only or not.

KDE Plasma, OpenGL 3.1, happens in windowed mode. I can't see a setting in System Settings to allow/disallow programs to forcibly disable KWin rules.

**Comment by smoogipoo** [comment]
![image](https://user-images.githubusercontent.com/1329837/127641865-422e7ca0-4c13-4386-98b0-901cb8222ab1.png)

It's this "allow applications to block compositing" checkbox.

**Comment by martmists-gh** [comment]
That seems to fix it. A side note from the original issue though:

> For Vignette though, I'd assume that there are gonna be a lot of cases where you'd want to show yourself working on something on your desktop while having your Live2D avatar be animated in the background or something, and having the compositor disabled would be indeed a pain. *But then*, the issue is that the osu!framework seemingly doesn't allow *not* to block compositing.

**Comment by smoogipoo** [comment]
From our side, it looks like we may be able to set the SDL2 flag `SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR` to `0` to prevent this behaviour.

Can you test whether the environment variable `SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0` works for you @martmists-gh? I'd prefer not adding such a flag to o!f (not sure if it can actually be set during runtime in the first place), so if that works then Vignette themselves could set it.

**Comment by Speykious** [comment]
```fish
SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0 dotnet run --project Vignette.Desktop
```
@smoogipoo I just tested this with the latest version of Vignette, on Arch Linux + KDE Plasma: the compositor stays enabled while running!

So I would suggest to add a feature (or instructions in a wiki somewhere) to the osu!framework that lets you choose whether you want your application to disable the compositor by default or not. It is very understandable for games as they take a lot of resources and desktop effects suck up some performance, but seeing that the osu!framework can be used for other kinds of applications, I think it should be a toggleable option.
