### ISSUE TITLE
Add proper text kerning

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#465]
Kerning values are stored and parsed already from fnt files, but are not used in SpriteText. Adding support shouldn't be a huge task.

**Comment by ScottSWu** [comment]
I poked around this, and it seems the Cyotek library has a bug which makes `font.GetKerning` always return 0.
https://github.com/cyotek/Cyotek.Drawing.BitmapFont/blob/master/src/Cyotek.Drawing.BitmapFont/BitmapFont.cs#L256
The kernings dictionary key stores previous character, current character, and amount of kerning, but when looking up, amount is set to 0.

This can be verified by setting a breakpoint at https://github.com/ppy/osu-framework/blob/master/osu.Framework/IO/Stores/GlyphStore.cs#L49 and breaking until a font like Exo-2.0 is being loaded.

```
> font.GetKerning((char)32, (char)34);
0
> int value;
> font.Kernings.TryGetValue(new Kerning((char)32, (char)34, 0), out value);
false
> font.Kernings.TryGetValue(new Kerning((char)32, (char)34, -1), out value);
true
> value;
-1
```

Will look to fix this on the bitmap font side.

**Comment by RemieRichards** [comment]
It's the fault of this line I believe:
```https://github.com/cyotek/Cyotek.Drawing.BitmapFont/blob/master/src/Cyotek.Drawing.BitmapFont/BitmapFont.cs#L261```

It makes a new Kerning struct with the values, as the dictionary is keyed with a Kerning struct, except the two structs won't equate to each other. the Kerning class needs an override of ```==``` that returns true if the values are the same.

**Comment by ScottSWu** [comment]
Some samples with the fix:

- Menu without kerning
![menu-no-kerning](https://user-images.githubusercontent.com/3599407/28050337-1eae1c7a-65cb-11e7-83ed-a3a825d24323.png)

- Menu with kerning
![menu-kerning](https://user-images.githubusercontent.com/3599407/28050345-2651f10e-65cb-11e7-8eb2-8a6506579666.png)

- Song select without kerning
![song-select-no-kerning](https://user-images.githubusercontent.com/3599407/28050350-2f2b3a6a-65cb-11e7-84e2-23b345422402.png)

- Song select with kerning
![song-select-kerning](https://user-images.githubusercontent.com/3599407/28050357-35218316-65cb-11e7-82a3-96eba44eee37.png)

The E and V in "DEVELOPMENT BUILD" look a bit close with kerning.

**Comment by peppy** [comment]
The DEVELOPMENT issue is weird... I wonder if the font has incorrect kerning values?

Also I find it interesting that the text on the main menu does not change *at all* with kerning. Can you double-check that?

**Comment by ScottSWu** [comment]
Looks like the play, edit, etc. buttons don't have a Font specified
https://github.com/ppy/osu/blob/master/osu.Game/Screens/Menu/Button.cs#L107
and the default font doesn't have kerning.

**Comment by peppy** [comment]
Exo (the defalut) does have kerning specified, though.

**Comment by ScottSWu** [comment]
Ohh right - I'll revisit this. Thanks for checking!

**Comment by peppy** [comment]
Was this ever implemented in a pull request? It doesn't look like we're using kerning data yet. @ScottSWu

**Comment by smoogipoo** [comment]
This has been implemented since sometime 2019 when the entire text layout system was rewritten.
