### ISSUE TITLE
Minor memory leak with SpriteText

### ISSUE THREAD

**Issue by Jumprocks1** [ppy/osu-framework#4679]
Each time a `SpriteText` is loaded, it calls `LocalisationManager.GetLocalisedString`, this method adds a binding to `LocalisationManager.currentParameters`. From what I can tell, this binding is never removed. This causes `LocalisationManager.currentParameters.Bindings` to grow each time a `SpriteText` is created. Even after the binding is garbage collected, the reference remains in the bindings list because of how `WeakList` works. Here is a simple TestScene that demonstrates this behavior:

```csharp
using System;
using osu.Framework.Allocation;
using osu.Framework.Graphics.Sprites;
using osu.Framework.Localisation;
using osu.Framework.Logging;

namespace osu.Framework.Tests.Visual
{
    public class TestSceneMemoryLeak : FrameworkTestScene
    {
        [Resolved] LocalisationManager localisationManager { get; set; }
        int j = 0;
        protected override void Update()
        {
            for (var i = 0; i < 50; i++) Add(new SpriteText());
            Clear(); // this calls Dispose on all the SpriteText we just created
            if (j == 200)
            {
                GC.Collect();
                // Since we're adding 50 SpriteText each update and doing this every 200 updates, expect exactly 10000 growth per log
                // Note: I had to switch all these fields to internal instead of private in order to view this count
                //    you can also view this count with dotnet-dump, which is how I discoved this in the first place
                Logger.Log($"Binding count: {localisationManager.currentParameters.Bindings.list.list.Count}");
                j = 0;
            }
            j++;
            base.Update();
        }
    }
}
// Output:
//   [runtime] 2021-08-10 23:13:22 [verbose]: Binding count: 10271
//   [runtime] 2021-08-10 23:13:23 [verbose]: Binding count: 20271
//   [runtime] 2021-08-10 23:13:24 [verbose]: Binding count: 30271
//   [runtime] 2021-08-10 23:13:25 [verbose]: Binding count: 40271
//   [runtime] 2021-08-10 23:13:26 [verbose]: Binding count: 50271
//   [runtime] 2021-08-10 23:13:27 [verbose]: Binding count: 60271
//   [runtime] 2021-08-10 23:13:27 [verbose]: Binding count: 70271
```

The binding count starts at 10271 instead of 10000 presumably because there are 271 `SpriteText`s in the visual test interface.

The cost of this seems to be at least 40 bytes for each `SpriteText`. In my game, each beatmap can consist of 1000's of `SpriteText` due to the way the notes are drawn. This was enough for the memory usage to noticeably increase during testing.

I have a very limited understanding of how `Bindable`/`WeakList` work, but it seems like the solution would be to unbind this binding at some point. I'm not sure whether or not this is worth fixing. It is also possible that this is just an intended side effect of `WeakList`.

**Comment by smoogipoo** [comment]
The list internal to `WeakList` is only cleared when the `WeakList` is iterated over (i.e. `GetEnumerator()`). But this is a case where there's a lot of traffic to a bindable which very rarely (if ever) gets its value updated.

We could tackle this two ways:
1. Supplement with a Gen2 GC notification, but I'm unsure about threadsafety.
2. Have a heuristic which causes this removal to also take place in some but not all `WeakList.Add()` invocations.

However, I also question whether a better solution is to use `DrawablePool<>` instead and keep only 10-20 `SpriteText`s (the ones visible) allocated at any time.

**Comment by frenzibyte** [comment]
Interesting what you've noted, but it looks like `LocalisedBindableString` indeed binds to the global current parameters bindable and never unbinds from it.

One simple way to fix this would be to override `UnbindAllInternal` and unbind there, as that's what `LeasedBindable` also does to revert the original properties.

Though this sounds like a case where `Bindable`s should have `IDisposable` implemented instead, so that `UnbindAll` remains for unbinding bindings and events only, not destroying the `Bindable` completely. Probably for later though, thoughts?

**Comment by Jumprocks1** [comment]
Yeah I did see that if I called `Count()` on the internal `WeakList` that it got cleared. I guess one way to clear the list would be to intentional trigger the bindable to update, since from what you said it sounds like this would trigger an enumeration.

I also definitely agree that some sort of static pool of `SpriteText`s would alleviate any memory issues this would cause in my game, I just haven't implemented anything like that since it would severely complicate my drawing code for not a lot of benefit. My game uses somewhat complex rendering code for each note, so generating all of the notes (along with their `SpriteText`) at the start of the track was the easiest method.

I mostly just opened this issue incase this was not intentional behavior that may also exist elsewhere. In pretty much all practical cases, the wasted memory caused by this will not be a problem.

@frenzibyte When I was trying to come up with my own fix for this, I tried calling `UnbindAll` in the destructor for `LocalisedBindableString`, but for whatever reason this didn't end up reducing the number of items in the `WeakList` (instead it just created a lag spike whenever the garbage collector called that destructor). It's possible I was doing something wrong though.

**Comment by frenzibyte** [comment]
`UnbindAll` won't do anything that way, and you definitely shouldn't call it in a destructor of a bindable.

This is how it should be done to achieve it:
```csharp
internal override void UnbindAllInternal()
{
    parameters.UnbindAll();
    base.UnbindAllInternal();
}
```

**Comment by smoogipoo** [comment]
@frenzibyte For a leak to happen, something that is _live_ has to hold a reference to the `LocalisedBindableString`. Just simply binding is not going to cause a memory leak, that's half the purpose of `Bindable`s.

**Comment by peppy** [comment]
Another consideration is that we can avoid the binding altogether until hitting an actual localised case:

https://github.com/ppy/osu-framework/blob/a72b44d6ec8491a68c6eed594d64ef70376777fc/osu.Framework/Localisation/LocalisationManager_LocalisedBindableString.cs#L37

ie. store a reference to `LocalisationManager` or the incoming `parameters` but only do the binding in first relevant `updateValue`.

It's orthogonal to the fix required here, but would avoid polluting that single bindable with non-localised `SpriteText` cases, which should also be a consideration as we've seen that in practice single bindables/events with large subscriber counts are going to cause performance issues, regardless of leak or otherwise (ie. what we had with `SkinChanged` in osu! in the past).
