### ISSUE TITLE
BassMix causes lagg/synchronization issues on Linux.

### ISSUE THREAD

**Issue by codecnotsupported** [ppy/osu-framework#4686]
It's technically not lagg since it renders all the other non-music synchronized elements at 60 fps.
(Fun fact: this includes the Osu logo on startup)
But there definitely synchronization problems going on.  

Reasoning:
I verified this by building a release build with the master branch.
It was fine on the 2021.731.0 build. 2021.808.0+ have this issue.
#4291 was probably the cause.

Any idea how to further debug this issue?
Master branch:

https://user-images.githubusercontent.com/2294209/129462556-2bc6d4f7-26ae-4b65-a0ab-f7219fddbdcb.mp4

2021.731.0 build:

https://user-images.githubusercontent.com/2294209/129462633-0044e15e-c255-412a-bfc6-fd0729b0b0d0.mp4

**Comment by peppy** [comment]
Have you tried the latest release where this was fixed?

**Comment by peppy** [comment]
Tentatively closing as resolved by https://github.com/ppy/osu-framework/pull/4684.

**Comment by codecnotsupported** [comment]
> Have you tried the latest release where this was fixed?
Yes, as I wrote, I used builded the master branch.

**Comment by peppy** [comment]
Which commit hash?

**Comment by codecnotsupported** [comment]
`git rev-parse HEAD`
`9e799efb1d4c99106f4046de86fbbec8f9ad0887`

**Comment by codecnotsupported** [comment]
I do presume you mean the commit hash of the Osu git repo. Not osu-framework.

**Comment by codecnotsupported** [comment]
I did a rebuild and now it works fine?
Always "fun" when issues magically disappear.
Stranger still is that I can no longer reproduce the bug, on the build I had previously it tested on.

**Comment by peppy** [comment]
You may have not pulled updated nuget dependencies the first time. Glad to hear it's working now. Please let us know if you manage to reproduce it.
