### ISSUE TITLE
Option to disable osu!framework applications from blocking compositors

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#4693]
As discussed in https://github.com/ppy/osu-framework/issues/4642, we probably want an option to disable the compositor-blocking default behaviour of SDL, which can be controlled via `SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR`.

We may even want this to be the default, since I believe other applications like browsers/electron apps don't block the compositor. This is a low-priority issue for us.

**Comment by turbedi** [comment]
Fixed by #4976
