### ISSUE TITLE
Can't compile default framework template because the Desktop namespace cant find Game

### ISSUE THREAD

**Issue by willmexe** [ppy/osu-framework#4697]
I'm interested in the framework and wanted to try to compile the template build osu-framework-game but i got the error "The type or namespace name 'Game' does not exist in the namespace 'framework-test'"

Is this something wrong with my C# install or am i missing a download?

**Comment by bdach** [comment]
What commands did you run to create the project from the templates, exactly?

If you passed a name with hyphens to `dotnet new` via the `-n` switch, then please try with a name that does not contain hyphens. C# by convention usually uses camel case and dots for namespacing (i.e. `ParentNamespace.ChildNamespace`).

**Comment by willmexe** [comment]
Thank you so much it worked by removing the hyphens in the name.
