### ISSUE TITLE
About FFmpeg prebuilt for macos

### ISSUE THREAD

**Issue by EYHN** [ppy/osu-framework#4738]
Hi everyone. Sorry to interrupt your work.

I was seeing that there is a prebuilt copy of ffmpeg for macos in the `osx-x64/native` directory. But I can' t find the build script for it.

I am developing a dotnet cross-platform application and I need packaged ffmpeg, I am curious how you guys are building ffmpeg for macos.

**Comment by peppy** [comment]
https://evermeet.cx/ffmpeg/ (linked from official page).

**Comment by EYHN** [comment]
@peppy  Thank you for your quick reply.

I looked on this page and i can;'t find the download link that included shared library.
