### ISSUE TITLE
`KeyBindingHandler` consumes repeats when original key is not handled

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4773]
https://github.com/ppy/osu-framework/blob/1f7f73735e1dae2add77f6e6ad417a322acb0b1b/osu.Framework/Input/Bindings/KeyBindingContainer.cs#L118-L119

Consumption should be based on whether the original (non-repeat) event was handled or not, rather than whether any binding matches it. As seen in https://github.com/ppy/osu/issues/14428#issuecomment-918865134.

Should probably be addressed after https://github.com/ppy/osu-framework/pull/2601 is merged, as a lot of the logic around this has changed.

**Comment by peppy** [comment]
This might get a bit complex to handle, as it probably should be making the decision on a per-binding level (ie. rather than returning early in the `Handle` function, it would need to do a lookup for the currently pressed keys in the incoming event, match and ensure it should actually be blocked).

A better path forward may be to just remove/obsolete `SendRepeats` alongside the `UIEvent` change, as it shouldn't be required with the new event arguments.

**Comment by Joehuu** [comment]
Closing as resolved.
