### ISSUE TITLE
`FlushingStream` disposal can fail

### ISSUE THREAD

**Issue by bdach** [ppy/osu-framework#4779]
See [following CI run](https://github.com/ppy/osu-framework/runs/3631010396?check_suite_focus=true):

```
 The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.IO.FileStream.get_IsClosed()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at osu.Framework.Platform.FlushingStream.Dispose(Boolean disposing) in D:\a\osu-framework\osu-framework\osu.Framework\Platform\FlushingStream.cs:line 24
   at System.IO.FileStream.Finalize()
```

The nullref is clearly the internal `_fileHandle`. Apparently this is [only possible if the `FileStream` ctor throws](https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs#L21), if that inline comment is to be trusted.

There are also [other](https://github.com/ppy/osu-framework/pull/4778/checks?check_run_id=3640074332) [CI failures](https://github.com/ppy/osu-framework/runs/3640074332?check_suite_focus=true) related to files that _may_ potentially be caused by `FlushingStream` but I have no concrete evidence that they are.

Only ever seen windows failures so far, so marking as windows-specific for the time being.

**Comment by peppy** [comment]
Sounds like we may just want to try-catch this? Not sure if there's a better alternative. We've had to do similar for windows in other locations.

**Comment by bdach** [comment]
Yeah, there is no actual other way to handle that, the file handles are not exposed.

The other errors about files being held open by some unnamed process are weird though. Would need to look at that more but am not on windows right now.
