### ISSUE TITLE
`CompositeDrawable`'s default child comparer breaks if drawable under another parent is given

### ISSUE THREAD

**Issue by bdach** [ppy/osu-framework#4807]
I wasted about an hour on this today (while trying to fix https://github.com/ppy/osu/pull/14939). Essentially what I did there is, I moved `hitCircleOverlay` a level down to be in another container (`OverlayLayer`), but then forgot to update a `ChangeInternalChildDepth()` call  to `OverlayLayer.ChangeChildDepth()`.

You would expect that I should get this exception:

https://github.com/ppy/osu-framework/blob/5ed9c8ecdaae5102da96f9ce5f99d1ac37c2dc05/osu.Framework/Graphics/Containers/CompositeDrawable.cs#L591-L593

But I didn't, and the thing crashed deep in absolute transform sequences instead. About an hour of debugging later it turned out that `IndexOfInternal()` was returning `0` for `hitCircleOverlay` when called from `LegacyMainCirclePiece`,  even though *it was not even a direct child of it anymore* at that point.

This will happen if the `CompositeDrawable`'s comparer doesn't check that both drawables are actually its child, which the default implementation does not, as it just reads the drawables' direct properties:

https://github.com/ppy/osu-framework/blob/5ed9c8ecdaae5102da96f9ce5f99d1ac37c2dc05/osu.Framework/Graphics/Containers/CompositeDrawable.cs#L365-L380

This also breaks things like `ContainsInternal()`:

https://github.com/ppy/osu-framework/blob/5ed9c8ecdaae5102da96f9ce5f99d1ac37c2dc05/osu.Framework/Graphics/Containers/CompositeDrawable.cs#L442-L445

The obvious fix (to me) would be to swap out that broken check to a `drawable.Parent != this` check, but I'm not super sure if that's always valid...? (especially around things like proxying), which is why I'm opening this in the first place.

**Comment by smoogipoo** [comment]
> but I'm not super sure if that's always valid...? (especially around things like proxying)

It should be valid. The parent check sounds good to me.
