### ISSUE TITLE
Attempting to construct a `TrackBass` manually will throw on first usage

### ISSUE THREAD

**Issue by ALiwoto** [ppy/osu-framework#4813]
Hi, I wrote [this code](https://github.com/ALiwoto/OsuTest1) with version `2021.630.0` of the osu!framework (can see it in [this file](https://github.com/ALiwoto/OsuTest1/blob/c0bc506f3bd9b8e5a11d4b447fc968e3cee7aabe/test1.csproj#L10))
I was trying to play an audio in one of my other projects (with latest version of osu!framework which is `2021.1004.0`) that found out it throws an exception called `CLR/System.AggregateException` when I try to start the `TrackBass` variable.
I checked all other possibilities (such as file corruption, the stream being unreadable, etc...), but my code completely works without any problem with version `2021.630.0`.

<hr/>

I opened my old project and tried to use the latest version of library on that too.
Exactly got the same exception on [this line](https://github.com/ALiwoto/OsuTest1/blob/e0bde2de3a9e95077a431a88cb30cf71b79cf0f4/Client/GameClient.cs#L35) which is using `TrackBass.Start` method.
Here is the exception message:
```
Exception has occurred: CLR/System.AggregateException
An exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.NullReferenceException : Object reference not set to an instance of an object.
   at osu.Framework.Audio.Track.TrackBass.startInternal()
   at osu.Framework.Audio.Track.TrackBass.<StartAsync>b__34_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

<hr/>

Am I doing something wrong in my code? Since it's not a complicated code (and also stack traces are not pointing at my code), I don't think that's the case. Have you changed something critical between these two versions of osu!framework? (such as needing to initialize an object in `Game.Audio` or something similar) Or, are you using an additional library which is not available on my pc?
Is there any other way to fix the problem? (besides using the old version of osu!framework, since I want to have the new features).
If something is wrong on my side, please guide me on how to fix it!

(thanks in advance for helping me out!)

**Comment by peppy** [comment]
you will need to add a resource store for the location, see the link i provided.

**Comment by jai-x** [comment]
I think this should be possible if your stream source implements `IResourceStore` and is added as a track resource.
A streaming resource store fetching from the network is already implemented with https://github.com/ppy/osu-framework/blob/master/osu.Framework/IO/Stores/OnlineStore.cs which you can also leverage.

**Comment by ALiwoto** [comment]
Oh, thanks for this tip; I will use a field for `ITrackStore` value from now on.
One more thing, as `ITrackStore` is implementing `IDisposable` interface, it has `Dispose` method in it. So, is there anyway to find out if a value of it is disposed or not?
I was expecting something like this:

```csharp
private ITrackStore onlineTrackStore;

....

if (onlineTrackStore == null || onlineTrackStore.IsDisposed)
{
    onlineTrackStore = Audio.GetTrackStore(new OnlineStore());
}
var t = await onlineTrackStore.GetAsync("song_url");
Audio.AddItem(t);
t.Start();
```

But the problem is that `ITrackStore` has no property called `IsDisposed`... is there any other way to determine if it's disposed or not? Isn't it possible to add a property like this to this interface?

**Comment by Mempler** [comment]
> One thing to note when using the sample code above is that if you are using the constructed store multiple times, you should be storing it somewhere to a field rather than adding a new store each time. Creating a new store for each usage will cause a (slow) memory leak as it is stored in the global audio manager permanently after calling `GetTrackStore`.

Question is, will it also leak when it gets disposed or will it remove itself from the given audio manager ?
