### ISSUE TITLE
Audio performance degradation / sporadic failure

### ISSUE THREAD

**Issue by Tom94** [ppy/osu-framework#488]
Samples sometimes fail to play. This can be easily reproduced by playing with a few toggles and sliders in the options menu, or playing beatmaps.

This is accompanied by a gradual degradation in performance of the audio thread, which should always easily run at 1000hz, but becomes more and more busy with time.

**Comment by peppy** [comment]
There is also an issue with audio track playback, where sometimes it doesn't play (and skips to the end of the track).

**Comment by Tom94** [comment]
It'd probably be a good start to move _all_ bass calls onto the audio thread. Currently queries like the current playback state are queried on the main thread which frequently leads to bass-internal errors which are not handled.

**Comment by Tom94** [comment]
Fixed by a couple recent changes.
