### ISSUE TITLE
Hard crash on startup with no audio devices

### ISSUE THREAD

**Issue by Tom94** [ppy/osu-framework#489]
We should be able to run and play the game without an audio device being present (should not hard crash). Timing will be handled by clocks. Extracted from https://github.com/ppy/osu-framework/issues/464 and https://github.com/ppy/osu-framework/issues/157

**Comment by DerivativeOfPiX** [comment]
ah yeah, but seems impractical, are there any particular reasons for it?

**Comment by peppy** [comment]
because this is a game framework which should support such conditions.

**Comment by peppy** [comment]
See #1302 for a more active issue. Closing as a duplicate.
