### ISSUE TITLE
Exceptions thrown from a `Game`'s BDL do not get logged to disk sometimes

### ISSUE THREAD

**Issue by bdach** [ppy/osu-framework#4920]
Opening as an issue as I'm at a loss as to why this is the case. Originally reproduced with some game-side realm migration failures, but a minimal repro with `SampleGame` is as follows:

```diff
diff --git a/SampleGame/SampleGameGame.cs b/SampleGame/SampleGameGame.cs
index 3b97ebaeef..6b8c5bf0b0 100644
--- a/SampleGame/SampleGameGame.cs
+++ b/SampleGame/SampleGameGame.cs
@@ -1,6 +1,7 @@
 ﻿// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
 // See the LICENCE file in the repository root for full licence text.
 
+using System;
 using osu.Framework;
 using osu.Framework.Graphics;
 using osuTK;
@@ -17,6 +18,8 @@ public class SampleGameGame : Game
         [BackgroundDependencyLoader]
         private void load()
         {
+            throw new InvalidOperationException("test");
+
             Add(box = new Box
             {
                 Anchor = Anchor.Centre,
```

When ran either in debug or release *without debugger attached*, the `InvalidOperationException` is not logged to `runtime.log`, despite being visible in stdout.

It appears that even despite the unhandled exception callback being installed before the above code executes here:

https://github.com/ppy/osu-framework/blob/fe00cc23f6393fd8891fc1d94e3ee37041e242fc/osu.Framework/Platform/GameHost.cs#L642-L643

it does not fire for this particular thrown exception and the process is just dropped without ever hitting the log.

A "solution" is to catch explicitly, log and rethrow in `GameHost.bootstrapSceneGraph()`, but it's ugly and generally the fact that the `UnhandledException` event seemingly cannot be relied upon is pretty spooky.

A piece of key information and a possible clue is that running with debugger causes this to no longer reproduce, i.e. the handler fires correctly, which indicates there may be a race of some kind.

**Comment by smoogipoo** [comment]
Hmm, I thought we had a try-catch around `bootstrapSceneGraph` at some point... Situation sounds weird.

**Comment by peppy** [comment]
@bdach I know you mentioned when working on this that you tested flushing the logger, but did that end up not working?

The following patch looks to resolve the issue for me:

```diff
diff --git a/osu.Framework/Platform/GameHost.cs b/osu.Framework/Platform/GameHost.cs
index e3f0572d7..23d42a228 100644
--- a/osu.Framework/Platform/GameHost.cs
+++ b/osu.Framework/Platform/GameHost.cs
@@ -314,6 +314,7 @@ private void unobservedExceptionHandler(object sender, UnobservedTaskExceptionEv
         private void logException(Exception exception, string type)
         {
             Logger.Error(exception, $"An {type} error has occurred.", recursive: true);
+            Logger.Flush();
         }
 
         /// <summary>
```

**Comment by peppy** [comment]
It wouldn't make much sense if that fixes the issue in all cases, as there's already a `Logger.Flush` in `GameHost.Dispose`, which should be getting run regardless of exception state (I think?).

Which leads me to believe that it may also be related to the unbind operations of `UnhandledException` running in the same `Dispose` method. Potentially getting unbound before the event is propagated outwards? I do remember the global `UnhandledException` having some interesting delays on when it fires..

If you can still repro with the above change, try commenting out these two lines:

https://github.com/ppy/osu-framework/blob/db24b545fef57d47389d4070e1d1eb6f558d741a/osu.Framework/Platform/GameHost.cs#L1081-L1082

**Comment by bdach** [comment]
I did try to add flush calls in several places to no effect, but not the particular one you mention. I haven't tested the above yet, but from what I recall in my testing the unhandled exception handler was seemingly never executed at all, so I'm at a loss why such a flush call would help here.

**Comment by peppy** [comment]
Very weird. I can repro 100% without the flush, but can't with it. Will wait for you to give it another test. Again, there's a flush in `GameHost.Dispose` which should be getting run regardless, so unless something is happening before the `Logger.Flush` that's inhibiting it from performing it correctly I'm still unsure...

**Comment by bdach** [comment]
@peppy so I'm not sure how this happened, but I've tested [your diff from above](https://github.com/ppy/osu-framework/issues/4920#issuecomment-982299870) and it also seems to help when testing here... not sure where I was putting the flush before at this rate, but clearly I must have been doing something wrong.

Although I will say that I think the following location may be a better one to call this flush in?

```diff
diff --git a/osu.Framework/Platform/GameHost.cs b/osu.Framework/Platform/GameHost.cs
index c95809e842..461a2f5096 100644
--- a/osu.Framework/Platform/GameHost.cs
+++ b/osu.Framework/Platform/GameHost.cs
@@ -332,6 +332,8 @@ private void abortExecutionFromException(object sender, Exception exception, boo
             AppDomain.CurrentDomain.UnhandledException -= unhandledExceptionHandler;
             TaskScheduler.UnobservedTaskException -= unobservedExceptionHandler;
 
+            Logger.Flush();
+
             var captured = ExceptionDispatchInfo.Capture(exception);
             var thrownEvent = new ManualResetEventSlim(false);
 
```

It seems to work there still, and doing this in the "abort" path rather than on every exception feels maybe slightly nicer? I dunno.

I have verified however that the disposal flush does not execute. That may well be because the `unhandledExceptionHandler`'s event args have `IsTerminating = true` set, so the CLR probably doesn't much care about clean exits and disposals at that point.
