### ISSUE TITLE
Setting `SDL_VIDEODRIVER=wayland` on NVIDIA results in no output

### ISSUE THREAD

**Issue by keksbg** [ppy/osu-framework#4924]
After forcing SDL2 to utilize the wayland driver on NVIDIA on sway, there is no visible game output, although audio is still played and it appears in `nvidia-smi`, implying the game is still rendered:
```
keksbg@alpha-centauri ~ % nvidia-smi
Thu Dec  2 19:15:26 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 495.44       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 29%   61C    P0    50W / 163W |    317MiB /  4039MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1875      G   sway                              129MiB |
|    0   N/A  N/A      5389      G   dotnet                            142MiB |
+-----------------------------------------------------------------------------+
```
This may or may not be an upstream SDL issue, or novideo being novideo, and as such I'd like to get your thoughts on it. The game still works if ran under xwayland, even if it has (at best) trash performance. [Logs](https://github.com/ppy/osu-framework/files/7643910/runtime.log) are attached in any case, even if I don't see anything relating to SDL.
Game version: `2021.1202.0-1` from commit 16e9569a3fb613732accc1e701c9eac4d53cbb93, self-built on Arch Linux with the [osu-lazer-git package](https://aur.archlinux.org/packages/osu-lazer-git/), using [nvidia-all](https://github.com/Frogging-Family/nvidia-all) version 495.44-187
Running the game: `vblank_mode=0 GBM_BACKEND=nvidia-drm __GLX_VENDOR_LIBRARY_NAME=nvidia SDL_VIDEODRIVER=wayland osu-lazer`

**Comment by bdach** [comment]
https://github.com/ppy/osu/search?q=wayland&type=issues
https://github.com/ppy/osu/search?q=wayland&type=discussions
https://github.com/ppy/osu/discussions/15625
