### ISSUE TITLE
Adding special characters in the multiplayer lobby name causes issues

### ISSUE THREAD

**Issue by janneslessmann** [ppy/osu-framework#4978]
**Problem:**
If you type one of the below listed characters in the title of a multiplayer lobby by creating or editing one, it will cause a problem. The input will not get printed on the screen, until you typea character, which is not included in the list.

**Known characters:**
- "@"
- "|"
- "\" (Backslash)
(To be continued...)

**Showing the behavior:**
![osu!lazer-multiplayer](https://user-images.githubusercontent.com/88435053/147863254-9d9f24ce-2c91-4440-9fe4-1662f106d1b7.gif)

**Comment by janneslessmann** [comment]
Issue not related to the framework, but to osu!

**Comment by bdach** [comment]
it actually is related to the framework.

duplicate of #1965
