### ISSUE TITLE
`GLWrapper.BindTexture()` behavior can lead to incorrect assumptions.

### ISSUE THREAD

**Issue by Pizzabelly** [ppy/osu-framework#5000]
In `GLWrapper.BindTexture()` if called with a texture that is already bound to the requested unit, the function will return early and not call `GL.ActiveTexture()` or `GL.BindTexture()`. This can lead to a situation where you call `GLWrapper.BindTexture()` to _update_ a texture, instead of binding it for drawing, and the function returns early because that texture it already bound to that unit. The issue is, in this case it's possible for the current active texture unit to be a different value than what you called `GLWrapper.BindTexture()` with which will cause your texture to not be updated.

This causes an issue here:
https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/Video/VideoTexture.cs#L86
https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/Video/VideoTexture.cs#L117

The issue is the `VideoTexture` being updated can also be the last bound `VideoTexture` causing `GLWrapper.BindTexture()` to return early while the active texture unit is still changed from `VideoTexture.Bind()`.

It results in a frame with mismatched chroma and luma components, like this:
![image](https://user-images.githubusercontent.com/8285260/150869494-d7606772-4d05-4621-b513-cf5731519ca0.png)
(Notice the color of the cursor is on circle 2 but the cursor is still on the slider.)

I can think of 3 potential fixes:
1. Have `VideoTexture` manually change the texture unit if it needs to. (I don't think this fixes the root problem)
2. Have `GLWrapper.BindTexture()` reset the active texture unit to `Texture0` after binding the texture.
3. Have `GLWrapper.BindTexture()` call `GL.ActiveTexture()` before it returns false.

**Comment by peppy** [comment]
Your linked screenshot is of stable, which doesn't use o!f. Did you perhaps upload the wrong image?

**Comment by Pizzabelly** [comment]
The screenshot shows a video playback test program using osu!framework playing back a video of stable. Sorry for the confusion.

**Comment by peppy** [comment]
Ah, I see...

Wondering if this can be somehow related to https://github.com/ppy/osu/issues?q=is%3Aissue+is%3Aopen+unicode+.

**Comment by smoogipoo** [comment]
Very good catch, thanks! Are you able to test with https://github.com/ppy/osu-framework/pull/5001 to see if it's working as expected now?

**Comment by Pizzabelly** [comment]
Yes, I just tested with #5001 and it works as expected. Thank you :+1:.
