### ISSUE TITLE
Declaring a function inside a loop

### ISSUE THREAD

**Issue by ringlorn** [ppy/osu-framework#5008]
https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/Containers/FillFlowContainer.cs#L139-L144

**Comment by bdach** [comment]
do you have a particular point to make about the function in question? i don't get it.

**Comment by ringlorn** [comment]
> do you have a particular point to make about the function in question? i don't get it.
Every iteration of the loop redeclares the function. I assume there's *some* reason for this but otherwise, just what ?????

**Comment by bdach** [comment]
this is not how any of this works, actually. C# local functions are just syntactic sugar. recommended reading:

* https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions
* https://fuqua.io/blog/2017/07/the-implementation-of-csharp-local-functions/
* https://sharplab.io/#v2:D4AQzABCBMEMIBsCGBnFBYAUAbyxfUkIALBALICmALgBYD2AJgBQCUeBumB3EAMnQGMkCEAFYqASzoA7VgG52PCIp4gAjADYopfkJHipstlyUROpiAF8V1zJaA==
