### ISSUE TITLE
`ClearTransforms` can discard autosizing indefinitely

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#5064]
Performing `ClearTransforms` clears autosizing transform, and therefore never make the container autosize until `childrenSizeDependencies` becomes invalidated again by updating any size-relevant properties.

One way I can see to fix this would be to invalidate `childrenSizeDependencies` on `ClearTransforms` so that the autosize transform resumes next frame if nothing else has invalidated that layout member.

Failing test case to demonstrate the issue at hand:
```csharp
        // in TestSceneCompositeDrawable
        [Test]
        public void TestClearTransformsOnDelayedAutoSize()
        {
            Container container = null;

            AddStep("create hierarchy", () =>
            {
                Child = container = new Container
                {
                    AutoSizeAxes = Axes.Both,
                    AutoSizeDuration = 1000,
                    Child = new Box { Size = new Vector2(100) },
                };

                container.OnLoadComplete += __ =>
                {
                    // query size to validate children size dependencies and trigger autosize transforms...
                    _ = container.Size;
                    // ...then clear transforms to interrupt autosize transform.
                    container.ClearTransforms();
                };
            });

            // expectation: container eventually autosizes to 100 size.
            // actual: container never autosizes and remains at 0 size.
            AddUntilStep("container autosized", () => container.Size == new Vector2(100));
        }
```

**Comment by bdach** [comment]
I think the proposed fix makes a decent amount of sense. I assume that would be local to `CompositeDrawable`, right? Overriding `ClearTransforms()` etc?

**Comment by frenzibyte** [comment]
Yep, that's right.

**Comment by peppy** [comment]
Sounds fair. Maybe should only be invalidated if `AutoSizeDuration` is non-zero.

**Comment by smoogipoo** [comment]
Note that this is also going to be the case with `FlowContainer`'s transform.

**Comment by smoogipoo** [comment]
> Maybe should only be invalidated if `AutoSizeDuration` is non-zero.

What do you mean by this?

**Comment by peppy** [comment]
The issue only affects cases where `AutoSizeDuration` is above zero, so I think it makes sense to only invalidate `                childrenSizeDependencies` (as proposed) in such cases.

If that's seen as premature optimisation then that's fine too, was just a suggestion as the actual implementation is conditional as such:

https://github.com/ppy/osu-framework/blob/68dbe10ce00859f66e6ef77b4753cbe5500238b2/osu.Framework/Graphics/Containers/CompositeDrawable.cs#L1923-L1930

**Comment by frenzibyte** [comment]
> Note that this is also going to be the case with `FlowContainer`'s transform.

Looking at it, `FlowContainer`'s case is going to be a bit problematic, as it applies the layout transforms to the children themselves, unlike `CompositeDrawable`'s case which applies the autosize transform on itself.

**Comment by smoogipoo** [comment]
For the `FlowContainer` case, I wonder if it's possible to transfer the transforms into the parenting `CompositeDrawable`...

**Comment by frenzibyte** [comment]
It might potentially be possible by populating the transforms using the child and add it to the parenting composite, but the very first thing that needs to be removed is the following check:
https://github.com/ppy/osu-framework/blob/7757de9eb4b11ac10bd156a40bba4f3aa5fed084/osu.Framework/Graphics/Transforms/Transformable.cs#L359-L364

**Comment by smoogipoo** [comment]
I was thinking more like `FlowTransform` becomes a manually-implemented transform on the parent which mutates the position of a child, rather than a `TransformCustom`.
