### ISSUE TITLE
Touch input is rotated 90 Degrees on Steam Deck when tablet support enabled and an external monitor is connected.

### ISSUE THREAD

**Issue by ILOVEPIE** [ppy/osu-framework#5071]
The Steam Deck uses a portrait touchscreen display that is setup in landscape mode, this confuses lazer when you have another monitor that is connected that is not a portrait display setup in landscape.

Imho, best way to solve this issue would probably be to use the touchscreen portion of the steam input APIs if the game is running on the steam deck (there's an API to check if the game is running on a steam deck) and to ignore the touchscreen in the tablet driver, that way external tablets can be used but the screen will function correctly.

**Comment by Susko3** [comment]
If touchscreen input is going trough the tablet driver, you can just rotate the tablet in osu! settings. Is the rotation not applying?

**Comment by ILOVEPIE** [comment]
It accepts input in landscape, I suspect the tablet driver is pulling raw device information, not using the touchscreen APIs. As for the solution of rotating the tablet, that doesn't solve it because it only does this with an external screen connected. This is because the device outputs a display signal to the portrait screen that is rotated and a landscape screen that is upright. It's this mixed-orientation situation that osu! lazer isn't handling right.

**Comment by ILOVEPIE** [comment]
If the tablet would be rotated in the osu! tablet driver to fix this issue, as soon as you disconnect the monitor it would be broken again as it would rotate 90 degrees the other way.

**Comment by bdach** [comment]
My opinion on this is - if this is fixable in opentabletdriver then that is the correct place to fix it. Framework itself doesn't (and shouldn't) manually handle such input idiosyncrasies for singular specific devices.

Not to mention that resolving this pretty much requires owning the device to test, which I certainly don't and OTD devs might also not. Patches welcome, though.

**Comment by peppy** [comment]
Please report to OTD or provide logs so we can on your behalf. If this is only occurring when OTD is on then the first part is understanding why. Which we can't do without logs.

**Comment by X9VoiD** [comment]
OTD should not be detecting steam deck as a device as it specifically requires adding a new device configuration to support something, unless steam deck is reporting its touch screen as another already known tablet device. I agree that we need logs to diagnose this issue.

**Comment by ILOVEPIE** [comment]
Ill get them for you. I don’t personally have a steam deck but I’ll get the
friend who tried it on the deck to get those logs for you.

**Comment by ILOVEPIE** [comment]
any launch options you need for logs?

**Comment by bdach** [comment]
there are no launch options that would influence the verbosity of logs, as far as i'm aware.

**Comment by ILOVEPIE** [comment]
Ok, I just tested this, and the weird behavior no longer appears (although there is another odd behavior in it's place, it's one valve needs to solve) as valve seems to have changed the way they handle external displays. I put in a feature request with valve that should allow for better control schemes for osu! through steam input. I'll close this issue now.
