### ISSUE TITLE
Green strips

### ISSUE THREAD

**Issue by DublikuntMux** [ppy/osu-framework#5090]
OS: Windows11
.NET Core: 6.0
osu framework version: 2022.325.0

Green strips appear on the screen when launching the downloaded standard project
![Image](https://user-images.githubusercontent.com/73074789/161433647-cb3fe86f-2327-46d0-a1b8-292b8c48b61c.png)

**Comment by bdach** [comment]
Unfortunately this is going to be a hardware or driver related problem. Please try updating your device drivers.

**Comment by DublikuntMux** [comment]
After installing the old version and reinstalling the drivers, nothing has changed (checks were carried out earlier). As it turns out, when you start the game in full screen mode, the stripes disappear. While playing osu!lazer, there were no such problems.

**Comment by DublikuntMux** [comment]
it also turned out that flickering depends on the fps limit

**Comment by bdach** [comment]
Sounds like a buggy driver then. Full screening is not a valid fix for this in any case, and I can assure you this is not happening on my machine.

Going to go ahead and close this since there is very little chance that this is a problem with the framework unless there's really good evidence provided to the contrary.

**Comment by smoogipoo** [comment]
If the green strips are the "flickering", and it's dependent on FPS, then it's likely a GPU power issue too. SampleGame specifically pegs my GPU at 100%.

**Comment by DublikuntMux** [comment]
if this is a problem with GPU power, then why does not this happen when the load is 100% with other applications. And why do the stripes only appear on an application running on the osu framework.

**Comment by smoogipoo** [comment]
Because other games aren't 100%. There's no game other than osu!, to my knowledge, that supports unlimited framerate. And it is something we will likely not be supporting either going forward.

**Comment by DublikuntMux** [comment]
I tried to run the application not on the built-in GPU, but on a static GPU. And this helped the application stopped flickering.
