### ISSUE TITLE
Set up GH Actions to build NativeLibs binaries automatically

### ISSUE THREAD

**Issue by boswelja** [ppy/osu-framework#5093]
See ppy/SDL2-CS workflow for implementation details
https://github.com/ppy/SDL2-CS/blob/master/.github/workflows/build.yml

**Comment by peppy** [comment]
@boswelja for the record, are you planning on looking into this task?

**Comment by boswelja** [comment]
I can if you'd like, but I'm not super familiar with GH Actions and only have weekends to spare right now

**Comment by peppy** [comment]
That's fine either way. We'll see who gets to it first.

**Comment by FreezyLemon** [comment]
Is this still needed? I could take a look at this, but it looks like version updates of native libraries are done manually at the moment.

**Comment by peppy** [comment]
I'm not too sure what this issue is tracking anymore. We do have https://github.com/ppy/osu-framework/blob/master/.github/workflows/deploy-nativelibs.yml which seems to do nativelibs deploys, although it hasn't been used yet (we rarely update the package).

Just going to close this for now.
