### ISSUE TITLE
Alt-F4 on windows forcefully closes osu!

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-framework#5117]
Currently, the framework has `SDL_HINT_WINDOWS_NO_CLOSE_ON_ALT_F4` set:
https://github.com/ppy/osu-framework/blob/ffbd32fcd9ef53629aa5621e82d917002048e779/osu.Framework/Platform/SDL2DesktopWindow.cs#L430

and we are handling alt-f4 locally:
https://github.com/ppy/osu-framework/blob/9d1e5183998847b30f3c3c1865162c17acaeab68/osu.Framework/Platform/Windows/WindowsGameHost.cs#L82
https://github.com/ppy/osu-framework/blob/ffbd32fcd9ef53629aa5621e82d917002048e779/osu.Framework/Game.cs#L370-L383

`Close()` bypasses the exit flow. It should be calling `RequestClose()` instead:
https://github.com/ppy/osu-framework/blob/03a103a4d827f132df50878cedebc5a5c8ee1fb8/osu.Framework/Platform/SDL2DesktopWindow.cs#L529-L533

but it's not exposed in `IWindow`.

---

There are two ways to fix this:
- remove the hint and the platform action logic (sdl close event already handles the exit flow)
- expose `RequestClose()` in `IWindow` and call that instead

I prefer the first one as it is weird that only windows is handled locally and is cleaner, but I don't know if others are using `PlatformAction.Exit` exclusively for Windows.

It's also weird no one has reported this (maybe they like the forceful close?).

**Comment by bdach** [comment]
This came up before but then somehow broke along the way... See https://github.com/ppy/osu-framework/pull/3921#issuecomment-706147424.

**Comment by bdach** [comment]
Also see https://github.com/ppy/osu-framework/pull/3889 for why Alt-F4 is even being handled locally via platform actions.

**Comment by peppy** [comment]
Going to bump this up to p0, pretty shocking news (I haven't used windows with a keyboard for a while, so I've been exiting using the close button and presuming all is OK).
