### ISSUE TITLE
PlatformAction.Redo is bound to Ctrl+Shift+Z but not Ctrl+Y

### ISSUE THREAD

**Issue by Flutterish** [ppy/osu-framework#5157]
`ctrl + y`, as an alternative to `ctrl + shift + z` is commonly used as the redo action, especially with art software (for example because you can bind control and z and y to 3 close button on a graphics tablet and that's where you usually hold your hand. Having ctrl bound instead of the undo/redo action to 2 buttons is better because you can essentially have 2 times more binds with and without the modifier) but it is not a default platform key binding. There are no conflicting bindings, I think it should be added. I found it confusing I could not redo until I found its bound to the keyboard-normal `ctrl + shift + z`.

**Comment by peppy** [comment]
I think it's fine to add support for this. These days it's a general expectation.

Note that it shouldn't be added for macOS.
