### ISSUE TITLE
Windows natural scroll setting not applied correctly to horizontal scrolling

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#5167]
See https://github.com/ppy/osu/discussions/18175

**Comment by peppy** [comment]
I... don't think this is a "natural scroll" related issue. We actually look to be handling the direction back-to-front, even on macOS. I believe we somewhat arbitrarily implemented it earlier on without too much consideration, and got it wrong.

We're likely going to need to fix this with a breaking change.

**Comment by Susko3** [comment]
Tested on a windows precision touchpad, and with a mouse that has a tilting scrollwheel.
Changing natural scrolling on the touchpad properly inverts framework handling, so it's not related to that.

In both cases vertical scrolling works as expected, while horizontal scrolling is inverted (goes in the wrong direction).
"Forced" horizontal scrolling (when the `ScrollContainer` only scrolls horizontally, so vertical scrolls are translated to horizontal) works as expected.

Windows doesn't have default handling for 'hold shift for horizontal scroll' -- maybe something we want to implement locally?

**Comment by peppy** [comment]
For reference: https://github.com/ocornut/imgui/issues/4019#issuecomment-852093067

**Comment by Susko3** [comment]
`TestCursor` used in `ManualInputManager` inverts the vertical axis only. And this makes it move according to expectation: scrolling up moves it up, tilting left moves it left -- is this how it behaves on macOS?

https://github.com/ppy/osu-framework/blob/c945622b6e8c268e6729446a499a3597b8293bcd/osu.Framework/Testing/Input/TestCursorContainer.cs#L149

**Comment by frenzibyte** [comment]
on macOS, only the vertical axis is inverted on "natural scroll", yes. And o!f works pretty well with it as-is, unlike Windows (seemingly).

**Comment by frenzibyte** [comment]
Actually to clarify, I haven't tested a tilting scroll wheel, and answering this will have to depend on whether enabling/disabling "natural scroll" on macOS affects the horizontal direction as well. 

I had been thinking about this with trackpad in mind (where dragging towards any direction moves to the opposite side of it).

**Comment by Susko3** [comment]
> I had been thinking about this in my previous comment with trackpad in mind (where dragging towards any direction moves to the opposite side of it).

Same happens on windows, the red dot moves opposite the scroll direction. 

But the red dot is wrong, it moving up scrolls the contents down (expected), but it moving left scrolls the contents left (wrong). And since the red dot is wrong, that means that windows/SDL is also wrong and reports horizontal scrolling inverted.

I think the only thing we need to do is invert the horizontal axis at `InputHandler` level, since we treat that axis opposite of the [`SDL_MouseWheelEvent`](https://wiki.libsdl.org/SDL_MouseWheelEvent) spec. If linux conforms to the spec, then this fix should work there as well.

(Plus fix the red dot.)

https://user-images.githubusercontent.com/16479013/168634209-099d17c1-c6cb-4cfa-bda1-69c6e73c817b.mp4

**Comment by SonoSooS** [comment]
I did some tests.

- macOS (10.14.6):
    - natural scrolling on: natural scrolling works in both directions on the mod overlay as expected
    - natural scrolling off: scrolling works as expected still, both axes are inverted as they should logically
- Windows (10 1703):
    - natural scrolling on: natural scrolling works vertically, but horizontally it's inverted
    - natural scorlling off: vertical scrolling scrolls as expected, but now horizontal scroll acts as natural scroll (so it's inverted)
- Linux (Solus 4.3, KDE Plasma 5.23, X11):
    - natural scrolling on: same as on Windows
    - natural scrolling off: same as on Windows

The weird thing is is that in osu.Framework.Tests, the red dot scrolls properly on Linux in both directions, so I don't know which one to believe.

**Comment by peppy** [comment]
> on macOS, only the vertical axis is inverted on "natural scroll", yes. And o!f works pretty well with it as-is, unlike Windows (seemingly).

For the record, this is incorrect. At an OS level it inverts both axes. At an osu!framework level, this is correctly received:

https://user-images.githubusercontent.com/191335/168727921-7e02f3b7-3250-4ebf-8de6-5f11fd8cfb29.mp4

On `master`, right scroll and down scroll are negative when natural, positive when non-natural.

https://user-images.githubusercontent.com/191335/168728107-a5d6c2c8-9708-4f8e-89d2-eb23279bd456.mp4

In safari, both axes are inverted (again, scrolling right and down physically in both cases).

**Comment by frenzibyte** [comment]
Indeed, I wasn't aware you could change directions in trackpad, and only realised horizontal scrolling gets flipped when disabling natural scroll in "Mouse" (which somehow affected trackpad) while I was looking at #5179. Disregard my comment, natural scroll inverts both vertical and horizontal direction.
