### ISSUE TITLE
Failure to create an SDL2 GL context on Linux

### ISSUE THREAD

**Issue by developomp** [ppy/osu-framework#5175]
I have the [flatpak version of osu!lazer](https://github.com/flathub/sh.ppy.osu) installed on Linux, and I'm having a bit of trouble trying to launch the game. After a bit of testing, I concluded that the error is coming from osu!framework so I'm opening a issue here.

Result of running the `flatpak run sh.ppy.osu` command:
```
Unhandled exception. System.InvalidOperationException: Failed to create an SDL2 GL context (Invalid window)
   at osu.Framework.Platform.SDL2.SDL2GraphicsBackend.CreateContext()
   at osu.Framework.Platform.PassthroughGraphicsBackend.Initialise(IWindow window)
   at osu.Framework.Platform.SDL2.SDL2GraphicsBackend.Initialise(IWindow window)
   at osu.Framework.Platform.SDL2DesktopWindow.Create()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Desktop/Program.cs:line 109
```

I tried to pinpoint where the error is coming from but every path seem to lead to a dead end. The solution might be obvious for the developers which in that case I can close this issue immediately, but if it's not, but don't waste any time trying to solve it. I will just leave this issue opened until somebode with a solution stumbles upon this issue.

The current version of osu! I have installed is 2022.509.0 but 2022.515.0 showed the same log when I quickly tested it using [this command](https://github.com/flathub/sh.ppy.osu/pull/35#issuecomment-1126866391). Just on a different line number (105).

**Comment by bdach** [comment]
Not sure why this is opened here rather than in the flatpak repo. I can tell you for sure that this does not happen with the appimage.

**Comment by peppy** [comment]
Please try the appimage release. If you have issues please open a discussion on the osu! repo, and make sure to provide logs.

**Comment by developomp** [comment]
I do not know how, but it fixed itself after an update.
