### ISSUE TITLE
Natural scrolling should only affect `ScrollContainer`s

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#5180]
Originally [sparked](https://discord.com/channels/188630481301012481/589331078574112768/975857507589312622) in a discussion about #5179.

Right now, natural scrolling affects all `ScrollEvent`s in general, rather than `ScrollContainer`s specifically. 

This causes scroll key bindings to report `WHEEL DOWN` when scrolling up, and general drawable components which handle `OnScroll` for increasing/decreasing to work opposite to non-natural (e.g. osu!'s volume overlay now increase volume when scrolling down rather than when scrolling up).

Opening this up for more opinions on the proposed direction, as right now things feel quite weird for natural scroll users. I'm not yet sure how we can figure out whether "natural scroll" is used, however ([`SDL_MouseWheelEvent`](https://wiki.libsdl.org/SDL_MouseWheelEvent) has a `direction` flag, but it works on macOS only).

**Comment by SonoSooS** [comment]
My opinion is this:

For new players, and/or especially for those who aren't computer-savvy, this is definitely a good idea, as natural scrolling does make more sense for scrollable containers, especially in this day and age, where basically almost everyone and their grandparents have a touchscreen phone. But considering that you slide up/right to adjust your brightness to be brighter, it does make sense to make this distinction between scrollable containers, and scroll-adjustable controls, like Trackbar, or NumericUpDown.

But for more experienced and longer-term computer users using natural scroll, they are probably already used to down = increase when scrolling over an adjustable control, so having this a global hardcoded setting for everyone would be certainly a mild inconvenience for those who are already used to this difference.

In my opinion, if we really really want to implement this, only implement it if it can be configured by the user to restore down = increase behavior.
Here is my idea:
- swap scrolling direction - swaps scrolling direction only for ScrollContainer
- swap value adjustment direction - swaps which direction sliders and other adjustable controls get changed
This could be either two checkboxes, or a dropdown box with four options.

Having these two boolean options, it's possible to
- enable natural scrolling for those who don't have an easy support to swap scroll direction in the driver itself
    - or completely enable "old" natural scroll behavior for those who use multiple operating systems, but their current one doesn't support natural scroll
- swap *just* volume and/or slider adjustment for those who want the most logical way of natural scroll implementation
- swap *just* ScrollContainer scrolling for those who don't have natural scrolling support

**Comment by peppy** [comment]
It should always respect the user's OS setting.

**Comment by frenzibyte** [comment]
Fair enough, now that I think about it, everything running will have scroll directions inverted (e.g. zooming in with GIMP using scroll). I suppose it's fine, unsure how to feel about keybindings also being flipped but matching it may not be better either.
