### ISSUE TITLE
Support horizontal scrolling via Shift key on non-Apple platforms

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#5183]
Continuing track of what was left in https://github.com/ppy/osu-framework/pull/5179#issuecomment-1128404268 + https://github.com/ppy/osu-framework/pull/5179#issuecomment-1128739985.

**Comment by peppy** [comment]
So far, the consensus is generally that we want to apply this to all scroll input game-wide, not just in `ScrollContainer`s.

To make this happen, we will somehow need to obtain the shift-pressed state in `SDL2DesktopWindow` around this call:

https://github.com/ppy/osu-framework/blob/0b4522ebf8f47bdd9e19053e56ad08e94ac8912e/osu.Framework/Platform/SDL2DesktopWindow.cs#L1548

Of note, macOS applies this at an OS level, so we would need to update the pass-through logic to unapply this, or factor it in as a consideration (so we don't apply twice). A more sane option may be to remove the pass-through logic altogether, and apply directly at https://github.com/ppy/osu-framework/blob/dde9eb08ede4aa94d21590f92b7c60f85cac3947/osu.Framework/Platform/MacOS/MacOSWindow.cs#L47-L48

**Comment by Susko3** [comment]
Putting this logic in [`MouseScrollRelativeInput.Apply`](https://github.com/ppy/osu-framework/blob/8d1bae03f5f79e02e525b4e11af72c33ba2d4f6a/osu.Framework/Input/StateChanges/MouseScrollRelativeInput.cs#L29) makes more sense to me, as we have access to the input state. Having it here means that it'll work for Android as well.

I was thinking something like this, only flipping if there isn't already a horizontal scroll:
```cs
if (Delta.X == 0 && state.Keyboard.ShiftPressed)
    Delta = Delta.Yx // or new Vector2(Delta.Y, 0) to be more explicit.
```

**Comment by peppy** [comment]
Good point, that's quite a nice location to have it.

> I was thinking something like this, only flipping if there isn't already a horizontal scroll:

So far I've heard mixed opinions on how this should work. Best to check everyone agrees with this before deciding on this implementation, but it is by far the simplest to implement.

**Comment by smoogipoo** [comment]
Is there a reason for flipping only if there isn't horizontal scroll? What's the macOS functionality in cases like this (e.g. when zoomed in a browser and scrolling in 2D)?

**Comment by peppy** [comment]
> Is there a reason for flipping only if there isn't horizontal scroll? What's the macOS functionality in cases like this (e.g. when zoomed in a browser and scrolling in 2D)?

Just tested and it behaves as proposed on macOS. Horizontal will not become vertical when holding shift.

**Comment by smoogipoo** [comment]
Interesting. Fine to go with the proposal in that case. As mentioned in Discord, it should probably not apply to `IsPrecise = true` inputs either.
