### ISSUE TITLE
Simplify exiting flow

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-framework#5194]
While debugging #5193, I was genuinely confused as to why the exiting process is so convoluted, requiring a lot of back and forth between `Game`, `GameHost` and `IWindow`. With each part seemingly forwarding events/return values, while `Host.Exit()` and `Game.OnExiting()` are the only things that are actually doing useful work.

This part of the current process is really worrisome. Currently, it fails with single threaded, and blocks on the input/main thread in multithreaded.

https://github.com/ppy/osu-framework/blob/f932f8df053f0011d755c95ad9a2ed61b94d136b/osu.Framework/Platform/GameHost.cs#L398-L421

I propose something like this in `Game`:

```cs
/// <summary>
/// Called when the window close (X) button or <see cref="PlatformAction.Exit"/> is pressed.
/// </summary>
/// <remarks>
/// Override to block the exit process as required.
/// Always run from the update thread.
/// </remarks>
public virtual void ExitRequested()
{
    Exit();
}
```

This somewhat reminds me of #5044, where I first had a complicated blocking/allowing process, but in the end it was simplified to something similar to the above.

**Comment by smoogipoo** [comment]
The proposal sounds fine at face value.

**Comment by peppy** [comment]
I'm not too against it, but not 100% on having the `Exit` call requirement. It feels like a flow where you need to read and understand the base method (ie. reflect or decompile the code), unless explained in the xmldoc.

Would another alternative to empty the `base` implementation and move that elsewhere?

ie.

```csharp
/// <summary>
/// Called when the window close (X) button or <see cref="PlatformAction.Exit"/> is pressed.
/// </summary>
public virtual void ExitRequested() => true;
```

The issue of whether `true` or `false` performs the exit is the biggest concern with this approach, I think.
