### ISSUE TITLE
Adding `TextureStore`s to the `Game.Textures` does not work as expected

### ISSUE THREAD

**Issue by Flutterish** [ppy/osu-framework#5220]
Creating a new `TextureStore` (which should use its own atlas, filtering mode etc.) and adding it to the game textures, only adds it as a `TextureUpload` lookup source, rather than a texture lookup source.
I understand that the game `TextureStore` is a `ResourceStore<TextureUpload>` with the added ability to get textures from its resources, however I find it unintuitive that adding a `TextureStore` to it doesnt use it as a texture lookup source.

My idea how to fix this would be to make `TextureStore` an `IResourceStore<Texture>` instead of a texture upload store, with an ability to add texture upload stores to it using the same method (`AddResourceStore(IResourceStore<TextureUpload>)`). `Game.Textures` would be replaced with some class which would aggregate `IResourceStore<Texture>`s. There still remains the problem of it being a breaking change since many BDLs request a `TextureStore` which would be replaced

**Comment by peppy** [comment]
Going to give this p1 as it feels like a pretty ugly flow right now, and may be a blocker for new users attempting to use o!f.
