### ISSUE TITLE
ConfigManager Set() issues

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#533]
Using one of the `ConfigManager.Set()` methods with optional nullable properties not passed to the functions incorrectly parses values from the config.

For example, `ConfigManager.Set(prop, 5);` will attempt instantiate a `Bindable<int>` (note: _not_ a `BindableInt`), which will not parse correctly from the file.

There are a few ways to fix this off the top of my (sleepy) head:
1. Add `try { Value = (T)Convert.ChangeType(s, typeof(T), CultureInfo.InvariantCulture) } catch { /* next case */ }` to the base `Bindable<T>.Parse()`. This is somewhat hackish and likely won't cover all the cases so:
2. Have a `BindableFactory` of some sort which returns the correct Bindable type for `ConfigManager.Set<U>()`, depending on `typeof(U)`.

**Comment by peppy** [comment]
Is this still relevant? I don't believe we're ever calling `Set` on a `ConfigManager` from outside of itself (to initialise defaults) now that we have welding.
