### ISSUE TITLE
`IContainer.RemoveAll` is dangerous

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#5378]
We have time and time again used it in cases where drawables are to be removed permanently, without understanding that it bypasses disposal (and leaves things like `Bindables` bound, potentially forever).

Proposal:

```diff
diff --git a/osu.Framework/Graphics/Containers/IContainer.cs b/osu.Framework/Graphics/Containers/IContainer.cs
index 415821f23..73469599b 100644
--- a/osu.Framework/Graphics/Containers/IContainer.cs
+++ b/osu.Framework/Graphics/Containers/IContainer.cs
@@ -24,7 +24,7 @@ public interface IContainerEnumerable<out T> : IContainer
     {
         IReadOnlyList<T> Children { get; }
 
-        int RemoveAll(Predicate<T> match);
+        int RemoveAll(Predicate<T> match, bool disposeImmediately);
     }
 
     public interface IContainerCollection<in T> : IContainer
@@ -39,7 +39,7 @@ public interface IContainerCollection<in T> : IContainer
         void Add(T drawable);
         void AddRange(IEnumerable<T> collection);
 
-        bool Remove(T drawable);
-        void RemoveRange(IEnumerable<T> range);
+        bool Remove(T drawable, bool disposeImmediately);
+        void RemoveRange(IEnumerable<T> range, bool disposeImmediately);
     }
 }

```

Intentionally a breaking change to allow consumers to reassess existing usages.

cc/ @smoogipoo @bdach @frenzibyte

**Comment by frenzibyte** [comment]
Looking at the case in #19959, I would've changed `RemoveAll` to dispose by default similar to `Clear`, as I imagine it to be expected that removing a specific drawable shouldn't dispose as it happens when moving one drawable to another parent, while removing by predicate or clearing all drawables should dispose as those drawables are likely to be never used again.

But that being said, it is always better to have things explicit instead so I'm not against having a second bool parameter for disposing on `Remove`/`RemoveRange`/`RemoveAll`.

**Comment by peppy** [comment]
I'm not sure about changing to dispose by default. There are some scenarios we *don't* want to dispose which would regress. Which is why I'm proposing a completely breaking change.

**Comment by bdach** [comment]
Personally I'm fine with the breaking change as proposed.

**Comment by peppy** [comment]
> Looking at the case in [ppy/osu#19959](https://github.com/ppy/osu/pull/19959), I would've changed `RemoveAll` to dispose by default similar to `Clear`, as I imagine it to be expected that removing a specific drawable shouldn't dispose as it happens when moving one drawable to another parent, while removing by predicate or clearing all drawables should dispose as those drawables are likely to be never used again.

Reading this again it makes quite a lot of sense. I think we can add the new parameter only for `Remove`/`RemoveRange`.

**Comment by peppy** [comment]
Maybe not. Going through usages, this is one example where disposal would cause breakage:

![JetBrains Rider 2022-08-26 at 05 11 08](https://user-images.githubusercontent.com/191335/186826855-74207bb9-6fe3-42f2-be06-5df820dd29b7.png)

I'll add everywhere for now. We can add a default argument in the future if it's seen as annoying to have around.
