### ISSUE TITLE
`Container<T>` enumerator does not throw if the list is modified

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#5379]
`Container<T>` uses a custom enumerator:

https://github.com/ppy/osu-framework/blob/0894ea15a0b54c5f6fea478aa45f20356f68bbdb/osu.Framework/Graphics/Containers/Container.cs#L472-L495

This does not throw if the underlying list is modified, for example...
```
foreach (var child in container)
    container.Remove(child);
```

**Comment by frenzibyte** [comment]
For reference, `List<T>` achieves this by keeping track of a version field that updates whenever the list is mutated, and throws if it no longer matches during iteration.
