### ISSUE TITLE
`TextureAtlas.Add` is inaccessible for external use.

### ISSUE THREAD

**Issue by naoei** [ppy/osu-framework#5399]
I have recently come across a particular use case where I would have to use the `Add` method within `TextureAtlas`, where I'm generating a ton of textures from a cropped sprite sheet (some sprites can be duplicated in the same texture area horizontally and vertically) for file optimization reasons.

I'm pretty much required to have an allocated texture atlas for this, as for one, the generated textures would definitely overflow the set 1024x1024 texture atlas limit, and secondly, without it, I would end up having thousands of draw calls each frame potentially slowing down the GPU bus.

I have a sample project that can be run over on [GitLab](https://gitlab.com/Altenhh/gd.renderer), specifically over at [SpritesheetTextureStore on line 46](https://gitlab.com/Altenhh/gd.renderer/-/blob/master/gd.render.two/Textures/SpritesheetTextureStore.cs#L46).

**Comment by peppy** [comment]
On a quick check, it looks quite safe to expose this function?

**Comment by smoogipoo** [comment]
I wasn't aware this class was public in the first place. Need to make sure it has all the correct checks and balances too, such as disposal.
