### ISSUE TITLE
The window is severely deformed when switching back from the background

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#5407]
### Discussed in https://github.com/ppy/osu-framework/discussions/5406

<div type='discussions-op-text'>

<sup>Originally posted by **RBQcat** September 14, 2022</sup>
win+D minimize window and switch back
problem appear
Switching back to the window again will return to normal
But the cursor will be limited to the upper left corner
I am playing on windows 11
![image](https://user-images.githubusercontent.com/74862110/190079100-51501849-a54b-4177-b3eb-f6bb5861532c.png)
[updater.log](https://github.com/ppy/osu/files/9563543/updater.log)
[runtime.log](https://github.com/ppy/osu/files/9563545/runtime.log)
[network.log](https://github.com/ppy/osu/files/9563546/network.log)
[performance.log](https://github.com/ppy/osu/files/9563547/performance.log)
</div>

**Comment by smoogipoo** [comment]
Perhaps this is a recurrence of the recent (well, "recent" - been going on for a few months now) Linux issues, allowing these sorts of states to happen:
![image](https://user-images.githubusercontent.com/1329837/190084345-1f13684d-c6e7-448a-9bea-573c74874b1c.png)

**Comment by Susko3** [comment]
On windows, this can only be reproduced in borderless fullscreen.

**Comment by peppy** [comment]
I'll look to update SDL after the next release.

**Comment by Susko3** [comment]
- Fixed with https://github.com/ppy/osu-framework/pull/5476
