### ISSUE TITLE
Incorrect handling of multiple key events on a single input frame

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#542]
Currently if two keys a pressed down on the same frame, two `OnKeyDown` events are triggered. This brings up a few issues:

- There are no refreshes of the input queues between these events. This means that if one key causes a target to stop handling input, it will still receive the second event incorrectly.
- The ordering of events is not necessarily stable.

Proposed solution: OnKeyDown should receive an array of keys, rather than a single key. The receiver should be responsible for deciding how to handle such a scenario.

**Comment by peppy** [comment]
Will be resolved by #630

**Comment by thomastanck** [comment]
Close this issue?

**Comment by peppy** [comment]
Yes, this is resolved.
