### ISSUE TITLE
Wacom CTL-472 tablet seems to cause NullReferenceExecption in TabletDriver.cs

### ISSUE THREAD

**Issue by srb2thepast** [ppy/osu-framework#5481]
![image](https://user-images.githubusercontent.com/19241426/197561835-e4571f80-47b8-4802-94df-3e6a140cfc3c.png)
![image](https://user-images.githubusercontent.com/19241426/197561885-ca659879-d14c-4927-b295-a49be81e0317.png)
Only started happening when I upgraded from v2022.722.0 to 2022.1022.1. Before launching worked with the HawkuTabletDriver open, but now regardless of whether or not it's open this error occurs. The same thing applies for OpenTabletDriver, but I've only tested it after the bug started occuring. 
Importantly, when a tablet is connected without a tablet driver via windows ink, after the program closes you cannot move the cursor at all anymore.
Likely related to #5423 and #5424.

**Comment by peppy** [comment]
Track via #5423.
