### ISSUE TITLE
Mobile build workflow do not cover errors from executable projects

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#5553]
Coming from https://github.com/ppy/osu/actions/runs/3571414877/jobs/6003262801. Currently the workflow only builds `osu.Framework.{iOS,Android}`, which are only library projects. It should include building `SampleGame` projects alongside it to cover errors like the ones seen above.

**Comment by smoogipoo** [comment]
I'm not sure how we can do this, because it fails with:
```
Error: /Users/runner/.dotnet/sdk/5.0.408/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/Users/runner/work/osu-framework/osu-framework/osu.Framework/osu.Framework.csproj]
```
Yet another situation where moving to .NET 6 would help.

**Comment by frenzibyte** [comment]
I would imagine this to work similar to how building `osu.iOS` `osu`-side was working all this time.

**Comment by smoogipoo** [comment]
`osu.iOS` depends on `osu.Game` which is only `netstandard2.0`.

`SampleGame.iOS` depends on `osu.Framework` which is `netstandard2.0` + `net6.0`. The msbuild process dies on that `net6.0` step.

**Comment by frenzibyte** [comment]
With the migration to .NET 6, we're now able to build via solution filter and cover executable projects. Closing as fulfilled.
