### ISSUE TITLE
Input order does not match display order

### ISSUE THREAD

**Issue by C0D3-M4513R** [ppy/osu-framework#5581]
Scenario: We have a Drawable Hierarchie, as follows:
```c#
new CompositeDrawable{
    InternalChildren = new Drawable[]{
        new SomeClickableThing{
        },
        new SomeOtherClickableThing{
            Depth = 1f
        },  
    }
}
```

Currently IsHovered (as well as everything affected by `PositionalInputQueue` and `buildPositionalInputQueue`) will not take Depth into account. This means sometimes you click on Elements that are behind others, if a earlier child has a lower depth value.

This is a limitation I ran into in [osu/#21119](https://github.com/ppy/osu/pull/21119), which I will now consider as blocked from merging until this issue gets resolved (or my workaround is in a acceptable state).
I do have a fix currently in place [see this commit](https://github.com/ppy/osu/pull/21119/commits/32d99015ce159de639be8d70a8ec7b8c4bc018c7), but that causes the Settings of selected Elements to ease-in all of their settings every MouseDragEvent, which is also not ideal.
(also just whilst writing this I see that this fix is somewhat stupid. I really only need to run that when the Ordering of Items inside a DrawableList actually changes. That still wouldn't solve the core issue though.)

I believe this could be solved adding a `OrderBy(d => d.Depth)` in InputManager. I am not sure of the exact Consequences of this, which is why this is not a pr.
https://github.com/ppy/osu-framework/blob/7f7ce8149623f5efcb2cc1110fec1b503b812693/osu.Framework/Input/InputManager.cs#L611

**Comment by Feodor0090** [comment]
Not sure how this works, but looking at `BuildPositionalInputQueue()` in `CompositeDrawable` it's iterating on children list, which is always sorted by depth (see `ChangeInternalChildDepth()`, `ChildComparer` and `Compare(Drawable x, Drawable y)` in CompDrawable).

I have tried the following:
```
[Test]
        public void A()
        {
            AddStep("1", () =>
            {
                Add(new Container
                {
                    new BasicButton()
                    {
                        Depth = -1,
                        Text = "this is 2nd",
                        Size = new Vector2(170,80),
                        Action = () => Logger.Log("2")
                    },
                    new BasicButton
                    {
                        Depth = -1,
                        Text = "this is top",
                        Size = new Vector2(180,30),
                        Action = () => Logger.Log("1")
                    },
                    new BasicButton
                    {
                        Text = "this is 3rd",
                        Size = new Vector2(160,200),
                        Action = () => Logger.Log("3")
                    },
                    new BasicButton
                    {
                        Depth = 1,
                        Text = "this is 4nd",
                        Size = new Vector2(150,440),
                        Action = () => Logger.Log("4")
                    }
                });
            });
        }
```

This is how it looks:
![изображение](https://user-images.githubusercontent.com/53872073/207170480-bf5a73fb-bbfb-444c-b71a-3776d3a176f8.png)
For me, clicks work as intended. Hovering works on all hovered buttons too (which is also intended afaik).
