### ISSUE TITLE
Incorrect colours on Volterra ARM64 developer kit

### ISSUE THREAD

**Issue by Beyley** [ppy/osu-framework#5618]
When running osu!framework (or osu!lazer) i get garbage colours (perhaps an invalid colour space?)
![image](https://user-images.githubusercontent.com/34501060/210293649-9df26a34-b0f7-4b87-a9a8-577b408e38f3.png)
![image](https://user-images.githubusercontent.com/34501060/210293728-e9f1cca2-19be-4f2d-8399-ae58287d58d8.png)
![image](https://user-images.githubusercontent.com/34501060/210293756-bb00a204-ecad-411d-82c2-bb790ef13c2f.png)
Im really not sure what is causing this, but its possible its due to the OpenGL -> D3D12 translation layer Microsoft uses on Volterra 
https://opengl.gpuinfo.org/displayreport.php?id=8303 (heres the gpuinfo report for Volterra)

**Comment by peppy** [comment]
Probably. Best just wait for native direct x support to come online.

**Comment by Beyley** [comment]
I'll be sure to test it once it is merged in! Ive had success running Veldrid on Volterra using its DX11 backend (with only minor graphical issues caused by screen clearing not working i have yet to debug)

**Comment by adiantek** [comment]
I have the same problem:
<img width="685" alt="1" src="https://user-images.githubusercontent.com/13407885/217707782-f6b1ab63-1fba-44a7-ab6f-63886faac7fb.png">
<img width="1062" alt="Screenshot 2023-02-09 035356" src="https://user-images.githubusercontent.com/13407885/217707809-cdf97b4a-a0fa-4c25-9c4c-5b9de1cdc640.png">

Is there any way to change the renderer to DirectX? Classic osu! works fine, but it's not arm64.

**Comment by Beyley** [comment]
> I have the same problem:
> <img width="685" alt="1" src="https://user-images.githubusercontent.com/13407885/217707782-f6b1ab63-1fba-44a7-ab6f-63886faac7fb.png">
> <img width="1062" alt="Screenshot 2023-02-09 035356" src="https://user-images.githubusercontent.com/13407885/217707809-cdf97b4a-a0fa-4c25-9c4c-5b9de1cdc640.png">
> 
> Is there any way to change the renderer to DirectX? Classic osu! works fine, but it's not arm64. (osu-framework & osu lazer compiled into arm64 have good performance, but it's with incorrect colours)

dx rendering will come with veldrid

**Comment by Beyley** [comment]
This has seemingly been fixed during the move to veldrid, even using the legacy OpenGL backend, all colours are correct, havent bisected the exact fix commit, but it *is* seemingly fixed now

**Comment by peppy** [comment]
Great to hear!
