### ISSUE TITLE
`FocusedOverlayContainer` makes `PopIn`/`PopOut` optional despite requiring implementation

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#5621]
After wasting an hour wondering why a focused overlay container doesn't receive any input despite actually having content displayed, it turns out the visibility state was actually set to "hidden" ([and it doesn't seem like I was the only one](https://discord.com/channels/188630481301012481/188630652340404224/1062427654680219778)).

`VisibilityContainer` by default requires inheritors to implement `PopIn`/`PopOut`, but `FocusedOverlayContainer` overrides those to perform focus logic. This results in `FocusedOverlayContainer` inheritors to not have to implement `PopIn`/`PopOut` despite actually needing to.

One way I can see to improve this would be for `FocusedOverlayContainer` and other classes of similar usage to override `UpdateState` instead, so that `PopIn` and `PopOut` remain abstract for non-abstract inheritors to implement, but I'll leave this as an issue thread for more feedback first.

**Comment by jai-x** [comment]
Inclined to agree with this. I had the same moment when implementing the chat overlay.
Although adding a new overlay isn't that common that you run into this often, it is something that would be better if fixed.

**Comment by peppy** [comment]
The proposal sounds good.
