### ISSUE TITLE
Sourcelink no longer works

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#5695]
After switching to github actions for nuget upload, we broke sourcelink.

quoting smoogi from discord: 
> yeah, it would need to generate + push the .snupkg, probably have to read into how the cake build used to work to generate it
This + making the action upload that
>
> ![](https://cdn.discordapp.com/attachments/589331078574112768/1085827673189781515/image.png)

**Comment by bdach** [comment]
Last release deployment confirms that this was fixed by #5705.
