### ISSUE TITLE
`SDL error: Couldn't find display mode match` on some iOS devices

### ISSUE THREAD

**Issue by NiceAesth** [ppy/osu-framework#5709]
When launching the game, the following error appears. (note: it does not cause a crash)
`Failed to get fullscreen display mode. Display index: 0. SDL error: Couldn't find display mode match`

Happens regardless of the settings used

Can reproduce on:
- iPhone 12 Pro Max
- iPhone 13 Pro
- iPad Pro 11" (2021)

[logs.zip](https://github.com/ppy/osu-framework/files/11072652/logs.zip)

**Comment by dumbuz** [comment]
This occurs on my iPad Pro 2018 too.

**Comment by frenzibyte** [comment]
Tracking in https://github.com/ppy/osu/issues/22997.
