### ISSUE TITLE
Game crashes when switching display mode in DirectX

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#5712]
> Excerpt from the log, looks like a problem with `AllowTearing` in the renderer.
> 
> ```cs
> 2023-03-27 01:24:52 [error]: An unhandled error has occurred.
> 2023-03-27 01:24:52 [error]: SharpGen.Runtime.SharpGenException: HRESULT: [0x80070005], Module: [General], ApiCode: [E_ACCESSDENIED/General access denied error], Message: [Access is denied.
> 2023-03-27 01:24:52 [error]: ]
> 2023-03-27 01:24:52 [error]: at SharpGen.Runtime.Result.ThrowFailureException()
> 2023-03-27 01:24:52 [error]: at Vortice.DXGI.IDXGIFactory.CreateSwapChain(IUnknown device, SwapChainDescription desc)
> 2023-03-27 01:24:52 [error]: at Veldrid.D3D11.D3D11Swapchain.recreateSwapchain()
> 2023-03-27 01:24:52 [error]: at osu.Framework.Graphics.Veldrid.VeldridRenderer.set_AllowTearing(Boolean value) in E:\osu!source\osu-framework\osu.Framework\Graphics\Veldrid\VeldridRenderer.cs:line 41
> 2023-03-27 01:24:52 [error]: at osu.Framework.Graphics.Rendering.Renderer.osu.Framework.Graphics.Rendering.IRenderer.set_AllowTearing(Boolean value) in E:\osu!source\osu-framework\osu.Framework\Graphics\Rendering\Renderer.cs:line 1098
> 2023-03-27 01:24:52 [error]: at osu.Framework.Platform.GameHost.DrawFrame() in E:\osu!source\osu-framework\osu.Framework\Platform\GameHost.cs:line 484
> 2023-03-27 01:24:52 [error]: at osu.Framework.Threading.GameThread.processFrame() in E:\osu!source\osu-framework\osu.Framework\Threading\GameThread.cs:line 451
> ```

### Discussed in https://github.com/ppy/osu-framework/discussions/5708

<div type='discussions-op-text'>

<sup>Originally posted by **BlueZenithAm** March 27, 2023</sup>
I found that the game will crash when switching display mode between boardless fullscreen/windowed and exclusive fullscreen. It only happens in DirectX mode, other surfaces work properly. 

https://user-images.githubusercontent.com/20235467/227791850-753bfd49-986a-4e5c-bac2-95f0120a2763.mp4

logs:
[runtime.log](https://github.com/ppy/osu-framework/files/11073853/runtime.log)
[input.log](https://github.com/ppy/osu-framework/files/11073854/input.log)
[performance.log](https://github.com/ppy/osu-framework/files/11073855/performance.log)

</div>

**Comment by smoogipoo** [comment]
I believe this is fixed now with https://github.com/ppy/veldrid/commit/0ec05acb9b7ed04649f57ef979548bcfb5797694 ?

**Comment by frenzibyte** [comment]
According to [relevant discord discussion](https://discord.com/channels/188630481301012481/589331078574112768/1091734040819810364), that looks like it.
