### ISSUE TITLE
Changing from Metal to OpenGL broke the game

### ISSUE THREAD

**Issue by Minorsonek** [ppy/osu-framework#5733]
Hi, the story goes as follows - I download newest april version, read in changelog about "10x performance on metal", realise it didn't do anything and performance is still shit, and then I tried to experiment a little bit and changed engine to OpenGL, which now broke the game as it hangs itself on start screen, showing only pink circle in the middle (without osu text). 

Macbook M1 Max

What can I do to fix that, because I can't really find any config file inside the app, can I somehow tweak this setting back to Metal without opening the game?

**Comment by frenzibyte** [comment]
`OpenGL` has regressed on this release and a hot-fix release will happen very soon. For now, either delete the `framework.ini` file in your osu! game folder or open it and remove the line `Renderer=OpenGL`.

Afterwards try running on `OpenGL (Legacy)` instead or revert back to the previous release for now.

**Comment by Minorsonek** [comment]
![Screenshot 2023-04-03 at 10 48 57](https://user-images.githubusercontent.com/25911229/229459514-f53b8290-5627-4e18-8ee4-9fd5cecc063a.png)
![Screenshot 2023-04-03 at 10 49 22](https://user-images.githubusercontent.com/25911229/229459614-243e09d8-61a0-4eb6-9b3d-06bf9d9b1821.png)


There is no "framework.ini" file inside osu folder, how can I find it?

**Comment by Minorsonek** [comment]
open

**Comment by peppy** [comment]
download the latest version

**Comment by Minorsonek** [comment]
works, thanks for the hotfix
