### ISSUE TITLE
Further TabControl/DropDown cleanups

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#574]
Files pending comments:
- [x] [Graphics/UserInterface/Tab/TabControl.cs](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/UserInterface/Tab/TabControl.cs)
- [x] [Graphics/UserInterface/Tab/TabItem.cs](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/UserInterface/Tab/TabItem.cs)
- [ ] [Graphics/UserInterface/DropDownHeader.cs](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/UserInterface/DropDownHeader.cs)
- [ ] [Graphics/UserInterface/DropDownMenu.cs](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/UserInterface/DropDownMenu.cs)
- [ ] [Graphics/UserInterface/DropDownMenuItem.cs](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/UserInterface/DropDownMenuItem.cs)

Move:
- [ ] `Graphics/Containers/TabFillFlowContainer.cs` => `Graphics/UserInterface/` (and make internal?)

**Comment by SirCmpwn** [comment]
What sort of comments are you expecting?

**Comment by smoogipooo** [comment]
Public/Protected/Internal members should have a comment explaining the purpose they serve.

E.g.
`PinTab()` should explain what a "pinned tab" is and how it affects the TabControl - that it is forced to the left of the TabControl and that they have priority to not be moved into the dropdown.
`TabItem<T> CreateTabItem()` should explain that it constructs a visual tab item to be displayed in the TabControl header.

All abstract members must explain what they're expecting from deriving classes/what their purpose is.
All non-private classes must explain what their purpose is.

**Comment by SirCmpwn** [comment]
Meh. I disagree with a blanket "everything must have this" rule. In many cases it's pretty clear.

**Comment by peppy** [comment]
Closing as this stuff has changed heavily since this issue was opened.
