### ISSUE TITLE
Setting `VeldridUniformBuffer.Data` may call `renderer.FlushCurrentBatch` when not suppose to

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-framework#5770]
Let's use `CircularBlob` as an example (but same happens with other drawables).
When populating `parametersBuffer.Data` comparison should occur, so if the same data already exists we are not calling `renderer.FlushCurrentBatch`. However data to compare is provided by the `storages[currentStorageIndex]`. At this point there are 2 storages: [0] with default data and [1] with the data from the previous frame. But `currentStorageIndex` is 0, so we are always comparing with the default data, thus making comparison fail.

_(Here's the point when I'm not sure what I'm talking about)_
**Potential point of failure:** [0] storage is **never** being populated with data. We are always increasing `currentStorageIndex` before that.

**Comment by smoogipoo** [comment]
> At this point there are 2 storages: [0] with default data and [1] with the data from the previous frame. But `currentStorageIndex` is 0, so we are always comparing with the default data, thus making comparison fail.

This is covered by the second condition at the time of upload here:
