### ISSUE TITLE
Add a flip property to Drawables?

### ISSUE THREAD

**Issue by nobbele** [ppy/osu-framework#5775]
It's already been implemented at https://github.com/ppy/osu/blob/0fa32fed51c46dfba8415004393e0dc0f033c11c/osu.Game/Storyboards/Drawables/DrawableStoryboardAnimation.cs#L73, can it be made available to everyone without dealing with `Scale` manually?

**Comment by peppy** [comment]
What's your use case for this?

We haven't seen this used often, so for the time being I'd probably recommend you copy the implementation from that class you found. You could make a `FlippableDrawable:Drawable` if it's a common usage in your project.
