### ISSUE TITLE
(Veldrid) `DrawNode` changes in drawables with bound uniform block are causing draw performance loss

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-framework#5779]
[Here's the test scene showing the issue](https://github.com/EVAST9919/osu-framework/blob/uniform-colour/osu.Framework.Tests/Visual/UserInterface/TestSceneUniformColour.cs)

On my machine (win10) In this scene when colour is static my frame times are around 1.9ms. Howewer with colour changing it becomes 5.4, which is kinda a big hit.
**What uniform blocks have to do with anything**: the issue is no longer present when changing `CircularProgress` to a simple `Box` for example and performance loss is insignificant.
**Why Veldrid:** with LegacyGL frametimes go from 1.5 (static) to 1.7 (changing), so the issue is no longer present in this case as well.

**Comment by smoogipoo** [comment]
I can't seem to repro this :(

**Comment by EVAST9919** [comment]
Here are my results:
| | Veldrid | LegacyGL |
|-----|-----|-----|
| Idle | ![veldrid-idle](https://github.com/ppy/osu-framework/assets/22874522/814ceb16-3c32-4548-b1ca-270f09fb92a3) | ![gl-idle](https://github.com/ppy/osu-framework/assets/22874522/8efe7864-5de4-484b-972f-f6db291c943c) |
| Animated | ![veldrid-anim](https://github.com/ppy/osu-framework/assets/22874522/b056e4d0-6317-4353-bbaf-5cd5c2b8a7ec) | ![gl-anim](https://github.com/ppy/osu-framework/assets/22874522/8ecab08a-f19f-4f3e-9c8f-423706a75542) |

**Comment by EVAST9919** [comment]
Okay, turned out it's not only about colour, it's about any `DrawNode` change. Movement, scale, etc

**Comment by smoogipoo** [comment]
Are you able to profile this and show the list of expensive methods? It sounds like you're hitting a case several others are, but that I haven't been able to repro.

**Comment by EVAST9919** [comment]
@smoogipoo so I was using [your pr](https://github.com/ppy/osu-framework/pull/5778) as a reference and moticed that there are too many flushes still. However removing `FlushCurrentBatch` from `VeldridRenderer.BindUniformBuffer()` literally fixes everything. No sure if this is a correct fix though, but it does magic: my fps went from 500 in idle to 1k and ~950 when animated

https://github.com/ppy/osu-framework/assets/22874522/598630b7-bbc2-4c24-84b0-ecf5fd611660

**Comment by EVAST9919** [comment]
Okay, unfortunately this is not a correct fix, osu with local framework runs super bad.

**Comment by smoogipoo** [comment]
> In the expensive methods there's nothing really useful (or expensive really), only invalidations which take like 2%

You should only be looking at the draw thread. Can you screenshot the top list of methods, or take a trace and upload it so we can investigate? If you feel unsafe uploading it here, you can email them to peppy.

Also, are you running this fullscreen, or windowed/borderless? If you're running windowed/borderless then you should test in fullscreen.

**Comment by EVAST9919** [comment]
>Also, are you running this fullscreen, or windowed/borderless? If you're running windowed/borderless then you should test in fullscreen.

This is the issue for both windowed anf fullscreen
> You should only be looking at the draw thread.

Is this what you are looking for?

![Снимок экрана 2023-05-11 182856](https://github.com/ppy/osu-framework/assets/22874522/fc766544-902b-487b-94e2-30794e5f37c3)

**Comment by smoogipoo** [comment]
Give this branch a shot: https://github.com/smoogipoo/osu-framework/tree/vbo-staging-buffer

**Comment by EVAST9919** [comment]
It's way better, yes. Went form 180fps to 360
