### ISSUE TITLE
IsActive is not correct if game started while window not active.

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#578]

**Comment by ekrctb** [comment]
The situation happening:
1. GameHost get Window.Focused and false is returned.
2. GameWindow.Run starts.
3. WinGLNative HandleActivate and Focused is set to true. OnFocusedChanged is invoked. Window.Focused is now true.
  But this is before NativeWindow.Events is set to true and event listeners are not registered. The event is not reaching to NativeWindow and osu.Framework.
4. GameWindow.Run calls ProcessEvents and NativeWindow.Events is set to true. Now GameWindow can receive window events but it is too late.

I'm not sure what is the best way to fix this. I'm thinking of either:
1. Delay first get of Window.Focused (how late?).
2. Register event handlers (set Events to true) earlier. I'm not sure about the impact of doing this.

**Comment by Marcel1202** [comment]
Still having this problem with the newest release using Ubuntu 18.10.
