### ISSUE TITLE
GitHub workflows should not build projects with unfamiliar .NET versions

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#5799]
See https://discord.com/channels/188630481301012481/188630652340404224/1108268055840182342 / https://github.com/ppy/osu/pull/23570#issuecomment-1550777620.

As we're using the .NET 6 SDKs in our local toolchains, CI builds projects using .NET 7 instead, allowing new features that are not present in .NET 6 to pass CI and end up breaking the project.

This is due to the fact that GitHub workflows come with preinstalled .NET versions, and `dotnet` commands selecting the highest .NET version available due to no `global.json` file being present.

One way we could solve this is add back `global.json` configuration and set it to always pick the highest minor version available of the .NET version that we're targeting currently, i.e.
```json
{
  "sdk": {
    "version": "6.0.100",
    "rollForward": "latestMinor"
  }
}
```
(note I haven't checked whether this does as I expect it to, my thought is that it'll pick any SDK in the .NET 6 range).

We can also specifically locate the `dotnet` binary of the .NET 6 SDK that's installed in the workflow, but that would probably be too ugly to achieve.

Opening this issue thread for tracking, not suggesting any immediate action.

**Comment by bdach** [comment]
Game was pinned by https://github.com/ppy/osu/pull/23595
