### ISSUE TITLE
Tablet initialization on aarch64 Linux throws NullReferenceException

### ISSUE THREAD

**Issue by gBasil** [ppy/osu-framework#5816]
When attempting to run osu!lazer on aarch64 NixOS through `NIXPKGS_ALLOW_UNFREE=1 NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nix shell --impure nixpkgs#osu-lazer-bin` (which builds version 2023.511.0) followed by running the `osu!` binary, the following error is thrown and the game crashes:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at osu.Framework.Input.Handlers.Tablet.OpenTabletDriverHandler.Initialize(GameHost host)
   at osu.Framework.Platform.GameHost.initialiseInputHandlers()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /build/source/osu.Desktop/Program.cs:line 120
```

It seems to potentially be related to #5423.

It would of course be best to fix the underlying issue for aarch64 Linux systems (works on the same machine on aarch64 Darwin/macOS), but it could temporarily be worked around by disabling only the built-in tablet drivers if they fail to initialize instead of preventing osu! from launching.

**Comment by peppy** [comment]
It's the same issue, please make a post in that issue thread with your added details.
