### ISSUE TITLE
Stencil isn't working within `BufferedContainer`s

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-framework#5861]
How to reproduce: in the `StencilTestScene` make `StencilDrawable` a child of a `BufferedContainer`. Result will look like Stencil was not applied at all.
Tested with LegacyGL and D3D, so it probably just isn't handled by the `BufferedContainer` implementation.

**Comment by smoogipoo** [comment]
It's not handled by default, but it should work if you give it a stencil format:

`new BufferedContainer(new[] { RenderBufferFormat.D32S8 })`

**Comment by EVAST9919** [comment]
It *kinda* does. Main buffer works fine, but effect buffers become empty.
![Снимок экрана (377)](https://github.com/ppy/osu-framework/assets/22874522/1d9bce5f-bb7e-4344-b83e-beece70d5c64)
That's because effect buffers are being created with the same format as the main buffer.
![Снимок экрана 2023-06-22 172858](https://github.com/ppy/osu-framework/assets/22874522/a8d8d63e-b69c-4ab1-8f31-6cd6b9d2936f)
Making formats null for them fixes the issue.
![Снимок экрана (376)](https://github.com/ppy/osu-framework/assets/22874522/6a1b4acb-4a91-4c44-9aa4-38e0e19c44ab)
So what's the way forward? Adding a separate array to use for effect buffers or always leaving them as null?

**Comment by smoogipoo** [comment]
Stencil should not be applied to the effect buffers. I don't think there's ever a valid use for that since you're drawing an entire quad.

If you'd want to, for example, blur and _then_ apply the grid stencil from that test scene to create crisp gutters, then the way of doing that should be to invert the process - blur first in a sub-container, and then stencil in the parenting container.

**Comment by EVAST9919** [comment]
I'm not applying stencil to the effect buffers. What I'm saying is that with your proposal Main and Effect buffers are being created with stencil format, which is probably incorrect (because applying stencil format *only* to the main buffer fixes my issues). Instead I'm proposing to split format specification for main and effect buffers to have more control.

**Comment by smoogipoo** [comment]
Is there ever a use for applying stencil to the effect buffers? Even separately from the main buffer? Because it's drawing an entire quad.
So my proposal is that effect buffers shouldn't get any stencil (_or depth_) formats at all.

**Comment by EVAST9919** [comment]
Looks like I wasn't clear enough: I'm not applying stencil to the buffered container. It's the drawable within the buffered container which contains stencil isn't being rendered.

[Screenshot 1](https://user-images.githubusercontent.com/22874522/247962012-1d9bce5f-bb7e-4344-b83e-beece70d5c64.png): using [your proposal](https://github.com/ppy/osu-framework/issues/5861#issuecomment-1602112820) Main buffer works as expected, but effect buffers are empty. That's because they are now have this format too due to how `BufferedDrawNodeSharedData` is implemented (it's using provided format for Main end Effect buffers).

[Screenshot 2](https://user-images.githubusercontent.com/22874522/247962562-6a1b4acb-4a91-4c44-9aa4-38e0e19c44ab.png): changing `BufferedDrawNodeSharedData` implementation so Effect buffers don't use provided format fixes the issue.

**My proposals:**
1. Changing `BufferedDrawNodeSharedData` so that provided `RenderBufferFormat` isn't applied to the Effect buffers.
2. Adding additional `RenderBufferFormat[]` parameter which will be used only by effect buffers

**Comment by smoogipoo** [comment]
I don't know why you're restating what I'm saying. Please read over again because I'm not questioning you, I'm making a declaration and/or agreeing with your proposal (1).
