### ISSUE TITLE
Veldrid renderer should not fetch pipeline instances & resource sets when issuing a draw call where possible

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#5891]
There's about 1-2ms CPU overhead coming just from that in a 500 draw calls scenario.

**Comment by smoogipoo** [comment]
Is the solution here to create the pipeline from the current state at draw time then? Because we can't progressively create or mutate pipelines - we need to create a `GraphicsPipelineDescription` that contains the full state before the immutable `Pipeline` is created from it.

**Comment by frenzibyte** [comment]
More like, adding flags that prevent from fetching the pipeline state and re-using the previous one. This is because the overhead of fetching the pipeline from the dictionary as well as fetching the resources add up to about 1-2ms CPU overhead.

**Comment by peppy** [comment]
Have you profiles this in an isolated means yet? It sounds like the same phantom overhead you were seeing with veldrid validation that may only be appearing on iOS...

**Comment by frenzibyte** [comment]
Indeed, after re-confirming using the same draw calls I profiled with before, there appears to be no overhead from the `DrawVertices` method after all.
