### ISSUE TITLE
Investigate using `Managed`/`Shared` texture storage mode in Metal for direct uploads

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-framework#5912]
Already got it to work veldrid-side with the following diff:
```diff
diff --git a/src/Veldrid/MTL/MTLGraphicsDevice.cs b/src/Veldrid/MTL/MTLGraphicsDevice.cs
index c864c81..7369954 100644
--- a/src/Veldrid/MTL/MTLGraphicsDevice.cs
+++ b/src/Veldrid/MTL/MTLGraphicsDevice.cs
@@ -394,26 +394,21 @@ private protected override void UpdateBufferCore(DeviceBuffer buffer, uint buffe
             uint arrayLayer)
         {
             MTLTexture mtlTex = Util.AssertSubtype<Texture, MTLTexture>(texture);
-            if (mtlTex.StagingBuffer.IsNull)
-            {
-                Texture stagingTex = ResourceFactory.CreateTexture(new TextureDescription(
-                    width, height, depth, 1, 1, texture.Format, TextureUsage.Staging, texture.Type));
-                UpdateTexture(stagingTex, source, sizeInBytes, 0, 0, 0, width, height, depth, 0, 0);
-                CommandList cl = ResourceFactory.CreateCommandList();
-                cl.Begin();
-                cl.CopyTexture(
-                    stagingTex, 0, 0, 0, 0, 0,
-                    texture, x, y, z, mipLevel, arrayLayer,
-                    width, height, depth, 1);
-                cl.End();
-                SubmitCommands(cl);
-
-                cl.Dispose();
-                stagingTex.Dispose();
+
+            mtlTex.GetSubresourceLayout(mipLevel, arrayLayer, out uint dstRowPitch, out uint dstDepthPitch);
+
+            if (!mtlTex.DeviceTexture.IsNull)
+            {
+                var origin = new MTLOrigin(x, y, z);
+                var size = new MTLSize(width, height, depth);
+
+                if (texture.Type != TextureType.Texture2D)
+                    throw new NotSupportedException("This operation is only supported on 2D textures for now.");
+
+                mtlTex.DeviceTexture.replaceRegion(new MTLRegion(origin, size), (UIntPtr)mipLevel, (UIntPtr)arrayLayer, source.ToPointer(), (UIntPtr)(width * 4), UIntPtr.Zero);
             }
             else
             {
-                mtlTex.GetSubresourceLayout(mipLevel, arrayLayer, out uint dstRowPitch, out uint dstDepthPitch);
                 ulong dstOffset = Util.ComputeSubresourceOffset(mtlTex, mipLevel, arrayLayer);
                 uint srcRowPitch = FormatHelpers.GetRowPitch(width, texture.Format);
                 uint srcDepthPitch = FormatHelpers.GetDepthPitch(srcRowPitch, height, texture.Format);
diff --git a/src/Veldrid/MTL/MTLTexture.cs b/src/Veldrid/MTL/MTLTexture.cs
index e01620e..5da47d6 100644
--- a/src/Veldrid/MTL/MTLTexture.cs
+++ b/src/Veldrid/MTL/MTLTexture.cs
@@ -63,7 +63,7 @@ public MTLTexture(ref TextureDescription description, MTLGraphicsDevice _gd)
 
             if (Usage != TextureUsage.Staging)
             {
-                MTLStorageMode = isDepth && _gd.PreferMemorylessDepthTargets ? MTLStorageMode.Memoryless : MTLStorageMode.Private;
+                MTLStorageMode = isDepth && _gd.PreferMemorylessDepthTargets ? MTLStorageMode.Memoryless : MTLStorageMode.Shared;
 
                 MTLTextureDescriptor texDescriptor = MTLTextureDescriptor.New();
                 texDescriptor.width = (UIntPtr)Width;

```

But quick profiling sessions with [this test case](https://github.com/ppy/osu-framework/pull/5904/commits/bcadb6564fb2124bf14f9a9d11e2979a5c5d77e4) show pretty interesting results.

upload staging texture + copy command:

![](https://media.discordapp.net/attachments/1116207304681992212/1127222624280399942/CleanShot_2023-07-08_at_15.58.58.png?width=2562&height=305)

`Managed`/`Staging` texture & direct write using `replaceRegion`:

![](https://media.discordapp.net/attachments/1116207304681992212/1127222785903706163/CleanShot_2023-07-08_at_16.00.27.png?width=2562&height=305)

As can be seen above, keeping texture as `Private` and using copy command performs 2x faster than making it `Managed`/`Shared` and updating it directly. This might have a relation with the fact that I'm testing this on an Apple GPU.

**Comment by frenzibyte** [comment]
@peppy interested to see results of this on non-apple GPUs (see diff above).

**Comment by smoogipoo** [comment]
> keeping texture as `Private` and using copy command performs 2x faster than making it `Managed`/`Shared` and updating it directly

`private` is documented as performing better than shared buffers due coherency not being required: https://developer.apple.com/documentation/metal/mtlstoragemode/private . It's also the reason I asked you to test it for VBOs back a while ago, but at the time you mentioned there was no discernible change iirc.

**Comment by frenzibyte** [comment]
I've been reconsidering that since shared/managed storage is the default for `MTLTexture`s, but I think this boils down to how much we upload to the texture from CPU as opposed to drawing with it in the GPU.

I've noticed a couple of flags that have an effect on this, both negatively and positively, so I've went ahead and made screenshots of the frame graphs with each one of these flags (note all of them use managed/shared storage mode).

|  | untracked resource | no gpu optimisation |
|---|---------------------------------|--------------------------------------------------|
| untracked resource | ![managed + untracked](https://github.com/ppy/osu-framework/assets/22781491/edaa34fc-3888-4fd6-befe-88c4a3be2eb4) | ![managed + nogpuopt + untracked](https://github.com/ppy/osu-framework/assets/22781491/783930d7-ebc5-4008-9f39-f2a35ee81436) |
| write-combined cache   | ![managed + untracked   writecache](https://github.com/ppy/osu-framework/assets/22781491/d003f164-282f-49b2-b5de-6ec452e620af) | ![managed + nogpuopt + writecache](https://github.com/ppy/osu-framework/assets/22781491/c64be5ec-f958-4e3b-acc8-7b98489a0d88) |
| no gpu optimisation   | ![managed + nogpuopt + untracked](https://github.com/ppy/osu-framework/assets/22781491/783930d7-ebc5-4008-9f39-f2a35ee81436) | ![managed + nogpuopt](https://github.com/ppy/osu-framework/assets/22781491/b326541b-9828-4d47-8aed-82373c84111e) |

According to the above screenshots and furthermore checking, marking managed/shared texture resource as untracked helps with the upload overhead, but still doesn't reach the performance of https://github.com/ppy/osu-framework/pull/5911. Those flags seem pretty interesting to play with elsewhere, but initial attempt don't show anything immediately good from them, so I will leave it at that.

Going to close this since managed/shared textures aren't beneficial for us compared to private.
