### ISSUE TITLE
iOS password is visible on correction bar on keyboard

### ISSUE THREAD

**Issue by gadielisawesome** [ppy/osu-framework#6010]
Not sure if the title makes sense, so let me expand.

Entering text in the password field where you sign in, on any iOS device, the password appears on the keyboard correction thing. Not sure how to describe it, but it's used for word correction. Sometimes, it will correct the password to a word. This gets really frustrating sometimes when trying to sign in. It is also a bad security vulnerability. I don't know if there is any way to tell iOS that this is a password field. I tried myself but I couldn't figure it out for the life of me.

**Comment by Susko3** [comment]
Duplicate of https://github.com/ppy/osu/issues/24041.
