### ISSUE TITLE
Masking sub-tree creation can be avoided with relative ease

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-framework#6224]
Also adresses https://github.com/ppy/osu-framework/issues/1432

While `ComputeIsMaskedAway` isn't *that* expensive, iterating over children in complex scenes adds up. And we do that many times per composite. I tried to move all the masking computations into `UpdateSubTree` and it works fine (or I was lucky and didn't encounter any issues so far) and we get performance benefits.
I understand though that this is not as easy as it sounds since it affects the whole update system and benefits are not that big, but may be for the future it's something to consider. Or not.

[framework diff](https://github.com/ppy/osu-framework/compare/master...EVAST9919:masking-subtree?expand=1)
[osu-side diff](https://github.com/ppy/osu/compare/master...EVAST9919:masking-subtree?expand=1)
(I'll pr if that's a direction we want to go in)

||master|proposal|
|---|---|---|
|direct (600 items loaded)|![direct-master](https://github.com/ppy/osu-framework/assets/22874522/96721066-3e3f-4687-be92-8c2e3fabf63d)|![direct-pr](https://github.com/ppy/osu-framework/assets/22874522/5f666905-b209-46c9-93ff-63f33fa2db6a)|
|mods-overlay|![mods-master](https://github.com/ppy/osu-framework/assets/22874522/3c17961c-fbe7-471b-9a0c-d229cc7c2eb4)|![mods-pr](https://github.com/ppy/osu-framework/assets/22874522/9b8fb691-9739-4e61-b5d7-e9d1456a1e12)|
|song-select + direct + beatmap overlay|![overlays-master](https://github.com/ppy/osu-framework/assets/22874522/aef30d61-fe1f-4cfd-9217-889a314927b7)|![overlays-pr](https://github.com/ppy/osu-framework/assets/22874522/60633bd7-3004-48b7-afd9-fe508737aea5)|
|song-select|![ss-master](https://github.com/ppy/osu-framework/assets/22874522/21425c4d-ff64-4423-9e54-7ff1c0acc7f9)|![ss-pr](https://github.com/ppy/osu-framework/assets/22874522/c2606e8a-0420-4412-8aac-7abcdcea0f1f)|

**Comment by smoogipoo** [comment]
I don't remember/think there's a particular reason why it's a separate pass.

**Comment by EVAST9919** [comment]
Okay, there's a reason for that: that's to ensure all the updates/invalidations/whatever have taken place.
With my approach there are cases in which, for example, `ScreenSpaceDrawQuad` is one frame outdated (content in `ScrollContainer`) and as such `IsMaskedAway` isn't "realtime". This has something to do with invalidation/validation timings and I'm not going into that rabbit hole.

Closing as not as simple to implement as initially thought.

**Comment by EVAST9919** [comment]
Hmm, it seems like it's possible to put masking calculations into `GenerateDrawNodeSubTree` with similar benefits, still investigating.
I'll probably just open a pr when it's ready.
