### ISSUE TITLE
Platforms other than Windows crash when last windowed mode is borderless in latest master

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-framework#6262]
Using macOS, but looking at the method, Windows is only implemented.

If you were using borderless before the SDL3 merge, it crashes after updating to latest master and you would have to manually set to `Windowed` / `Fullscreen`.

```
[runtime] 2024-04-22 17:42:58 [error]: An unhandled error has occurred.
[runtime] 2024-04-22 17:42:58 [error]: System.PlatformNotSupportedException: Operation is not supported on this platform.
[runtime] 2024-04-22 17:42:58 [error]: at osu.Framework.Platform.SDL3Window.SetBorderless(Display display)
[runtime] 2024-04-22 17:42:58 [error]: at osu.Framework.Platform.SDL3Window.UpdateWindowStateAndSize(WindowState state, Display display, DisplayMode displayMode)
[runtime] 2024-04-22 17:42:58 [error]: at osu.Framework.Platform.SDL3DesktopWindow.UpdateWindowStateAndSize(Wi
```

The following osu!-side lines can probably be removed if borderless is not a thing anymore for macOS:
https://github.com/ppy/osu/blob/308744348f8d7919d38b5508bb904a27b9909fad/osu.Game/OsuGame.cs#L855-L863
https://github.com/ppy/osu/blob/308744348f8d7919d38b5508bb904a27b9909fad/osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs#L271-L279

Fullscreen on macOS somewhat doesn't take full control on SDL3 anymore, but cmd-tab has a horrible delay as opposed to borderless.

**Comment by bdach** [comment]
@Susko3
