### ISSUE TITLE
AddFont() Method can't find my font.

### ISSUE THREAD

**Issue by kenter7317** [ppy/osu-framework#6273]
it has correctly converted by fnt and png, to binary, i think it must be wrong path problem, here is my repo 
: https://github.com/kenter7317/DreamofSomeone

and the error is 

```
[runtime] 2024-04-30 18:33:09 [error]: Couldn't load font asset from Resources/Fonts/210omnigulim010/210omnigulim010.
[runtime] 2024-04-30 18:33:09 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
[runtime] 2024-04-30 18:33:09 [error]: at osu.Framework.Extensions.ExtensionMethods.ComputeMD5Hash(Stream stream)
[runtime] 2024-04-30 18:33:09 [error]: at osu.Framework.IO.Stores.GlyphStore.<LoadFontAsync>b__14_0()
[runtime] 2024-04-30 18:33:09 [verbose]: ?? ScreenStack#116(depth:1) entered StartScreen#341
```

**Comment by Susko3** [comment]
https://github.com/kenter7317/DreamofSomeone/blob/a05ca34e2da9211f5081b7f792b2f2f542125c53/DreamofSomeone.Game/DreamofSomeoneGame.cs#L19

You'll probably want to remove `Resources/` from the font asset name, as that is implied.
```diff
-AddFont(Resources, @"Resources/Fonts/210omnigulim010/210omnigulim010");
+AddFont(Resources, @"Fonts/210omnigulim010/210omnigulim010");
```

See how osu! does it:
https://github.com/ppy/osu/blob/e0e790fa9412368ff7b414791348476f05e28f2f/osu.Game/OsuGameBase.cs#L448

**Comment by kenter7317** [comment]
this error happend because dll resources has different name or path to real path. please add this solution to wiki
1.  find<Your Game Name>.Resources/bin/<Your Game Name>.Game.dll
2. open that dll file using assembly viewer
3. check the real font file path inside the dll, and correct code.

**Comment by bdach** [comment]
@kenter7317 i'm confused. did the removal of the `Resources` prefix fix it? or did you do something else entirely?

i'm not sure why the wiki has the prefixes to be fair, neither framework or game has them.

**Comment by kenter7317** [comment]
I remove that prefix `resources `and corrected path. that prefix may be implied 
```
AddFont(*Resources*, path)
```

but still the Framework couldn't find my font, then I try some other steps, finally I find that Framework find path's Resources in the dll file. then check assembly. and fix them, in my case. the right path is Fonts/210omnigulim/_210omnigulim

I'll commit this changes and comment my code, I'm sorry about availabilities of misunderstanding your comment, cuz I'm foreigners

**Comment by bdach** [comment]
Okay sure that checks out, but that is because you've accidentally hit a stupid implementation detail of embedded resources. If the name of an embedded resource starts with a digit it will apparently get automatically an underscore prepended to it. See https://stackoverflow.com/questions/14705211/how-is-net-renaming-my-embedded-resources.

I'll remove the error from the wiki and also add a note to not start the name of the resource with a digit I guess.

**Comment by sk-zk** [comment]
> https://github.com/kenter7317/DreamofSomeone/blob/a05ca34e2da9211f5081b7f792b2f2f542125c53/DreamofSomeone.Game/DreamofSomeoneGame.cs#L19
> 
> You'll probably want to remove `Resources/` from the font asset name, as that is implied.
> 
> ```diff
> -AddFont(Resources, @"Resources/Fonts/210omnigulim010/210omnigulim010");
> +AddFont(Resources, @"Fonts/210omnigulim010/210omnigulim010");
> ```
> 
> See how osu! does it: https://github.com/ppy/osu/blob/e0e790fa9412368ff7b414791348476f05e28f2f/osu.Game/OsuGameBase.cs#L448

Could someone change this on the wiki page? Took me a while to find it

**Comment by peppy** [comment]
@sk-zk thanks for pointing this out. i've updated https://github.com/ppy/osu-framework/wiki/Setting-Up-Fonts.
