### ISSUE TITLE
Vulkan renderer causes the game to crash after getting to results screen

### ISSUE THREAD

**Issue by huuishuu** [ppy/osu-framework#6285]
# PC Specs:

CPU: AMD Ryzen 5 5600X
RAM: 32GB DDR4 3200mhz
GPU: Nvidia GeForce RTX 3060 (driver version 552.44)
OS: Windows 11 Pro 23H2 (OS Build 22631.3447)

# Game client version:
2024.412.1-lazer

# Description:

@shavitush helped me debug this locally using x64dbg and dnSpy.

I've started encountering an issue where my osu!lazer would just crash every time, without fail, when either:
- Entering the results screen after a map
- Starting a new map after exiting out of one

What tends to happen usually is that my game would completely freeze over, begin flickering, while the audio in the background would continue. Sometimes I'm able to interact with UI elements while the game is frozen but this isn't consistent. The game crashes silently without an error message. This is only an issue when the game is in full screen mode, Windowed & Borderless don't seem to be affected.

While debugging, we encountered anomalies where the game silently crashed without an error when entering song select. We did, however, manage to catch the crash regarding the results screen once but couldn't replicate it again. We forgot to take a screenshot of it but the top of the call stack threw an exception saying that memory is trying to be written to a non-accessible page and the module was ppy.Veldrid or something among those lines, with function calls starting with `vk`, indicating Vulkan APIs are triggering it.

Under Direct3D11, it works fine.

Seeing that most issues relating to Veldrid are posted to this repo, I'm posting the issue here.

I recorded what I could regarding this with OBS here:
https://www.youtube.com/watch?v=FWUt_4L-jy4

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/28039
https://github.com/ppy/osu/issues/28072
https://github.com/ppy/osu/issues/28132
https://github.com/ppy/osu/discussions/27659
etc.
