### ISSUE TITLE
Double clicking dropdowns with `AlwaysShowSearchBar` set to false gets absorbed by transparent textbox

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-framework#6342]
I'd expect the dropdown to hide.

https://github.com/user-attachments/assets/e39bffea-f945-4f9a-967e-a3da66fb788a

**Comment by smoogipoo** [comment]
This one is quite annoying to handle, because the textbox has handled the click so only it can receive the double click.

**Comment by frenzibyte** [comment]
One way I can imagine to have this work is disabling positional input from reaching the textbox when text is empty, should do the job in theory.
