### ISSUE TITLE
High output latency on GPUs with triple buffering VSync forced

### ISSUE THREAD

**Issue by Sarisan** [ppy/osu-framework#6358]
This affects Intel Iris Xe Graphics

Those values should be equal to `refreshRate` variable
https://github.com/ppy/osu-framework/blob/7bb0e9e9ad285ffb0fa67db458fb43c81a17656f/osu.Framework/Platform/GameHost.cs#L1345-L1346

**Comment by bdach** [comment]
> Those values should be equal to refreshRate variable

How are you even claiming this? What's your methodology here? What evidence do you have that that's correct?

**Comment by Sarisan** [comment]
> > Those values should be equal to refreshRate variable
> 
> How are you even claiming this? What's your methodology here? What evidence do you have that that's correct?

In the other games where VSync option is separated from refresh rate I noticed that setting it to my display's refresh rate value fixes high output latency, while setting it to higher values makes latency get worse and worse step by step. Later then I wanted to check it out what refresh rate is set with VSync in osu!lazer and found those 2 lines in the code. I changed both of the values to match my display refresh rate and built it from source to test changes. The result was as expected, the game was finally playable with VSync turned on.

**Comment by smoogipoo** [comment]
Changing that variable is not the correct fix. It sounds like this is related to GPU queueing, and potentially a configuration issue.

That said, nothing can be actioned on without some missing items:
1. Logs (options -> export logs).
2. A video of the game running with the graphs by pressing Ctrl+F11 twice.

**Comment by peppy** [comment]
VSync *should* have higher latency. If it doesn't it's not working correctly. The code you cite is a correct implementation of vsync. It is up to the GPU driver to handle vsync flipping.

**Comment by smoogipoo** [comment]
Nah let's keep this open. This is not true vsync - it's a pseudo-vsync enabled by triple buffering. Please read my comment.

**Comment by Sarisan** [comment]
> Changing that variable is not the correct fix. It sounds like this is related to GPU queueing, and potentially a configuration issue.
> 
> That said, nothing can be actioned on without some missing items:
> 
> 1. Logs (options -> export logs).
> 2. A video of the game running with the graphs by pressing Ctrl+F11 twice.

GitHub won't let me upload video larger than 20 MiB, so I uploaded them to my [GDrive](https://drive.google.com/drive/folders/1lFW3wRqEgTXT2fmFLf68HxImB9CAh7Xt?usp=sharing)

**Comment by smoogipoo** [comment]
Cool, you already did the next step I was going to ask - it like OpenGL is working as expected for you, though it's using true vsync and you should expect higher latency as a result.

It looks like it's probably a configuration issue our side but I don't think we're going to fix this until swapping out the graphics abstraction (veldrid) with something better.

I'm currently looking into SDL_gpu which afaik supports mailbox/fast-sync/this thing.

I suggest using OGL in any case. Will close for now.

**Comment by Sarisan** [comment]
> OpenGL is working as expected for you

With the "fix" it is, without it it's unplayable

**Comment by smoogipoo** [comment]
Yes, well, that is how VSync is supposed to work - it's supposed to be unplayable. If you don't want latency, then don't use VSync.

There's more that can and will be done on this in the future, but your fix is not the way.

**Comment by Sarisan** [comment]
> it's supposed to be unplayable

It was totally playable on other Intel GPUs I tested where triple buffered VSync wasn't forced, HD Graphics 3000/400/500/505

**Comment by peppy** [comment]
@Sarisan can you try setting the refresh rate in the game 1 hz underneath your monitor refresh rate and run the same tests (with the same videos)? Curious to see how this looks for you.

**Comment by Sarisan** [comment]
> @Sarisan can you try setting the refresh rate in the game 1 hz underneath your monitor refresh rate and run the same tests (with the same videos)? Curious to see how this looks for you.

If you mean
```
drawLimiter = refreshRate - 1; 
updateLimiter = refreshRate - 1; 
```
Then it's the exact result as without `- 1`.
