### ISSUE TITLE
[LICENSING] The ppy.osu.Framework.NativeLibs nuget package has wrong license on Nuget Gallery

### ISSUE THREAD

**Issue by xgqt** [ppy/osu-framework#6388]
https://www.nuget.org/packages/ppy.osu.Framework.NativeLibs/2024.912.0-nativelibs has MIT license on Nuget gallery but ships binary files with questionable licenses (BASS).

In case of Nuget Gallery I think you can just point to a txt file explaining what is vendorded.

**Comment by peppy** [comment]
It's only really intended for our consumption. I don't know what you'd want to see for something like this, would "N/A" work?
