### ISSUE TITLE
[linux-arm] can't seem to run o!f project on arm 32-bit

### ISSUE THREAD

**Issue by approachcircle** [ppy/osu-framework#6446]
I'm not sure if o!f supports arm 32-bit, but I'm pretty sure it should. When publishing my project using `dotnet publish --runtime linux-arm --self-contained` the executable runs, sits for a little while, then exits without error or any output for that matter, as seen [here](https://streamable.com/f3su60). I thought this could be to do with the fact that I am running the project over VNC and it is failing to create a window and so bailing early, but the exact same behaviour is observed on the actual hardware. The hardware in question is a windows surface RT running raspbian. 

The project itself just pushes a screen with one child being a `SpriteText` object which updates every frame with the time, like a clock. I wanted to keep it simple just to test if o!f would run on the hardware to begin with.

**Comment by frenzibyte** [comment]
Running on release configuration does not log anything happening during the execution to console. Either way, o!f does not yet have all library assets for `linux-arm`/`linux-arm64` runtime. Related: https://github.com/ppy/osu-framework/pull/6288

**Comment by peppy** [comment]
Not supporting 32 bit platforms.
