### ISSUE TITLE
Touchpad scrolling

### ISSUE THREAD

**Issue by paparony03** [ppy/osu-framework#670]
I'm not sure whether this framework even requires touchpad support because osu! probably won't be played using the laptop touchpads. I'm also sure this is an OpenTK problem not this framework, but I figured I should still address this.
I found out when running osu!lazer on my laptop, the song selection carousel won't scroll when I use the scroll gesture (two fingers). The current client receives the touchpad scroll events and is able to scroll the carousel and adjust the volume.

Any idea how to fix this? (or whether to even fix this?)

**Comment by VPeruS** [comment]
Hmm. Scroll works fine for me. What platform you running on?

**Comment by paparony03** [comment]
I am running Windows 10 x64 on a Lenovo laptop.
The thing is, scrolling for me works everywhere properly including the current osu!, only on lazer it doesn't seem to work.
Maybe it's an OpenTK problem after all.

**Comment by peppy** [comment]
I see now reason this would happen unless your touchpad drivers are selectively not sending wheel events.

Are you capable of debugging this yourself? If not, I don't believe we have anyone else able to fix this as we cannot reproduce it in the first place.

**Comment by paparony03** [comment]
Closing because I cannot debug these myself and doesn't seem to be reproducible.
