### ISSUE TITLE
Android targeting support

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#681]
We need to add full android support for the framework.

This should not be too difficult as everything has been designed with cross-platform support in mind. Will require hooking up Xamarin, adding the android version of bass (any probably other) native libraries.

I welcome anyone who has an interest in cross-platform targeting support, especially if you have experience with xamarin.

**Comment by Tauntawn** [comment]
In it's current state Android support won't be possible, System.Drawing is not available on Xamarin Android. The main Framework assembly will need to be reworked to remove that dependency. Once that's done it should then be simple to complete the rest as you say.

**Comment by peppy** [comment]
system.drawing is hardly used anywhere in our code base (we have purposefully avoided using it for such reasons). you should have no trouble removing the dependency if you are intending on taking on this task.

**Comment by Tauntawn** [comment]
I intend too, it'll be great fun I think. I'll start by removing that dependency then look at targeting support.

**Comment by Tauntawn** [comment]
2>  No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.

I've managed to get the build down to this warning, which from my understanding is because of the framework targeting .net 4.5, but I have managed to get it to build..... sadly it's gonna take me awhile to actually make a sample to begin testing anything cause to be honest I've never used OpenGL on Android.... all my apps have been built with Android views. So this is all new to me! Any suggestions on something I may have missed that would cause this issue though?

**Comment by VPeruS** [comment]
You can try recompile Xamarin.Android with proper target version.

**Comment by ticotaco72** [comment]
@Tauntawn Can you publish result of your work?

**Comment by ticotaco72** [comment]
@peppy should comppatibility changes for android be mergable to master or as new branch?

**Comment by ticotaco72** [comment]
@peppy i need to use some code from Android namespace. So i need to make multitarget project. And i found two ways for it, and i wanted to ask what fits better to you.
1. Change SDK to https://github.com/onovotny/MSBuildSdkExtras to allow multitargetting for xamarin and netstandard simultaneously.
2. Create shared project and next 2 for every target

**Comment by peppy** [comment]
xamarin should support netstandard, no?

**Comment by ticotaco72** [comment]
Yeah, but i need to use android.content.context.GetExternalFilesDir() to access path to external storage

**Comment by peppy** [comment]
Have you checked the iOS PR for reference? https://github.com/ppy/osu-framework/pull/1409/files

**Comment by swoolcock** [comment]
You can check out the solution structure I'm using for iOS if you look at my latest branch.  It's not the same branch as the one in that PR, which is dependent on an old version of OpenTK and will no longer run with the latest framework.  The new branch is currently using a (temporarily) renamed fork of OpenTK to prevent namespace clashes.  I'm still looking for a way around that.

https://github.com/swoolcock/osu-framework/tree/osutk-ios

**Comment by ticotaco72** [comment]
Thanks, I'll take a look

**Comment by ticotaco72** [comment]
can i use just dll not nuget package for now for OpenTK?

**Comment by ticotaco72** [comment]
Or maybe better question
I should use ppy's version of OpenTK, yeah?
Or can i use this included in xamarin?
Cause i cannot find a way to use ppy's version directly. Maybe using DLL and extern alias, if it will work.

**Comment by ticotaco72** [comment]
for now i get this error while running samplegame:
```
Unhandled Exception:

System.TypeLoadException: Could not set up parent class, due to: Could not set up parent class, due to: Could not set up parent class, due to: Generic Type Definition failed to init, due to: Could not set up parent class, due to: Invalid type osu.Framework.Graphics.Colour.SRGBColour for instance field osu.Framework.Graphics.Containers.CompositeDrawable:borderColour assembly:/storage/emulated/0/Android/data/SampleGame.Android1.SampleGame.Android1/files/.__override__/osu.Framework.dll type:CompositeDrawable member:(null) signature:<none> assembly:/storage/emulated/0/Android/data/SampleGame.Android1.SampleGame.Android1/files/.__override__/osu.Framework.dll type:Container`1 member:(null) signature:<none> assembly:/storage/emulated/0/Android/data/SampleGame.Android1.SampleGame.Android1/files/.__override__/osu.Framework.dll type:Container`1 member:(null) signature:<none> assembly:/storage/emulated/0/Android/data/SampleGame.Android1.SampleGame.Android1/files/.__override__/osu.Framework.dll type:Container member:(null) signature:<none> assembly:/storage/emulated/0/Android/data/SampleGame.Android1.SampleGame.Android1/files/.__override__/osu.Framework.dll type:Game member:(null) signature:<none>: wystąpił wyjątek 
```
are these problems with opentk or is this bigger problem?
and my branch is https://github.com/ticotaco72/osu-framework/tree/target-android

**Comment by miterosan** [comment]
Rename the opengl dll.

**Comment by swoolcock** [comment]
You might want to ping @FreezyLemon about Android support, as he’s spent some time researching it.

**Comment by FreezyLemon** [comment]
Hm.. it's been a while since I tried it, but you'd probably be best off trying to get OpenTK to work first...
There've been a lot of issues with it (mostly due to Xamarin.Android being uncooperative with their namespace usage), and I couldn't find a workaround yet.

Some more info on this:
opentk/opentk#494 (almost the exact issue I had)
opentk/opentk#810 (this issue has some links in it that give detailed descriptions, also the post itself is useful)

**Comment by ticotaco72** [comment]
Thanks. I'll look for some solution for this problem, but for now I'll use osutk fork for development time as @swoolcock in osutk branch

**Comment by ticotaco72** [comment]
@FreezyLemon Can OpenTK's GameWindow be initialised in standard way on Android? cause in my implementation it can't initialise DisplayDevice and throws an error. I'm debugging on vs' emulator

**Comment by ticotaco72** [comment]
```
System.TypeInitializationException: The type initializer for 'osuTK.DisplayDevice' threw an exception.

09-28 21:50:54.504 D/Mono    ( 6220): DllImport attempting to load: '/system/lib/liblog.so'.
09-28 21:50:54.505 D/Mono    ( 6220): DllImport loaded library '/system/lib/liblog.so'.
09-28 21:50:54.505 D/Mono    ( 6220): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
09-28 21:50:54.505 D/Mono    ( 6220): Searching for '__android_log_print'.
09-28 21:50:54.505 D/Mono    ( 6220): Probing '__android_log_print'.
09-28 21:50:54.505 D/Mono    ( 6220): Found as '__android_log_print'.
09-28 21:50:54.510 I/MonoDroid( 6220): UNHANDLED EXCEPTION:
09-28 21:50:54.819 I/MonoDroid( 6220): System.TypeInitializationException: The type initializer for 'osuTK.DisplayDevice' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/dev/dri'.
09-28 21:50:54.819 I/MonoDroid( 6220):   at System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) [0x000f7] in <43dbbdc147f2482093d8409abb04c233>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):   at System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) [0x00006] in <43dbbdc147f2482093d8409abb04c233>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):   at System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () [0x00054] in <43dbbdc147f2482093d8409abb04c233>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):   at System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) [0x000d6] in <43dbbdc147f2482093d8409abb04c233>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):   at System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) [0x00009] in <43dbbdc147f2482093d8409abb04c233>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):   at System.IO.Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) [0x00000] in <43dbbdc147f2482093d8409abb04c233>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):   at System.IO.Directory.InternalGetFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) [0x00000] in <43dbbdc147f2482093d8409abb04c233>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):   at System.IO.Directory.GetFiles (System.String path) [0x0000e] in <43dbbdc147f2482093d8409abb04c233>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):   at osuTK.Platform.Linux.LinuxFactory.CreateDisplay (System.IntPtr& gbm_device, System.IntPtr& egl_display) [0x00011] in <a54ff0cec5aa4de9af1726aec139577d>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):   at osuTK.Platform.Linux.LinuxFactory.get_gpu_fd () [0x0001d] in <a54ff0cec5aa4de9af1726aec139577d>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):   at osuTK.Platform.Linux.LinuxFactory.CreateDisplayDeviceDriver () [0x00001] in <a54ff0cec5aa4de9af1726aec139577d>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):   at osuTK.DisplayDevice..cctor () [0x00010] in <a54ff0cec5aa4de9af1726aec139577d>:0 
09-28 21:50:54.819 I/MonoDroid( 6220):    --- End of inner exception stack trace ---
09-28 21:50:54.820 I/MonoDroid( 6220):   at osu.Framework.Platform.Android.myAndroidGameWindow..ctor () [0x00008] in C:\Users\ppast\OneDrive\Pulpit\osu-developing\osu-framework\osu.Framework.Platform.Android\myAndroidGameWindow.cs:20 
09-28 21:50:54.820 I/MonoDroid( 6220):   at osu.Framework.Platform.Android.AndroidGameHost..ctor (System.String gameName, System.Boolean bindIPC) [0x0000a] in C:\Users\ppast\OneDrive\Pulpit\osu-developing\osu-framework\osu.Framework.Platform.Android\AndroidGameHost.cs:27 
09-28 21:50:54.820 I/MonoDroid( 6220):   at osu.Framework.AndroidHost.GetSuitableHost (System.String gameName, System.Boolean bindIPC) [0x00001] in C:\Users\ppast\OneDrive\Pulpit\osu-developing\osu-framework\osu.Framework.Platform.Android\AndroidHost.cs:10 
09-28 21:50:54.820 I/MonoDroid( 6220):   at SampleGame.MainActivity.OnStart () [0x0000e] in C:\Users\ppast\OneDrive\Pulpit\osu-developing\osu-framework\SampleGame.Android1\MainActivity.cs:23 
09-28 21:50:54.820 I/MonoDroid( 6220):   at Android.App.Activity.n_OnStart (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <a10f61e70eeb434e952fef884856c199>:0 
09-28 21:50:54.820 I/MonoDroid( 6220):   at (wrapper dynamic-method) System.Object.4(intptr,intptr)
09-28 21:50:55.533 W/zygote  ( 6220): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
09-28 21:50:55.541 D/Mono    ( 6220): DllImport searching in: '__Internal' ('(null)').
An unhandled exception occured.
```

Do i understand it well, that it tries to get something from x11, but it isn't supported in android?

**Comment by neico** [comment]
Well at core android is a linux based OS, so finding things like `/dev/*` is more or less normal.
What is strange tough is that it seems to call something in `osuTK.Platform.Linux`, I don't think that's supposed to happen, you sure you're using the correct library?
openTK can be quite wonky when it comes to mobile support, it didn't even compile properly on android for quite a while.

You might want to compare [opentk/opentk/develop/src/OpenTK/Platform/Factory.cs](https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Factory.cs) with [ppy/opentk/develop/src/OpenTK/Platform/Factory.cs](https://github.com/ppy/opentk/blob/develop/src/OpenTK/Platform/Factory.cs)

**Comment by swoolcock** [comment]
@neico `osuTK` is my fork of ppy's OpenTK that just has the top-level namespace and assemblies renamed.  It's to prevent namespace clashes with Xamarin's outdated OpenTK fork.

**Comment by ticotaco72** [comment]
After some code reading i think loading using Linux factory seems reasonable, and not like a bug. But i don't know maybe this is incorrect. 
AndroidFactory is used only as embedded factory and i haven't seen how it's used

**Comment by swoolcock** [comment]
TBH I would take most of the OpenTK Android/iOS code with a grain of salt, as the maintainers have no interest in supporting it.  There will likely be significant changes required to OpenTK to get it to a usable stage for osu!framework on mobile platforms.

**Comment by ticotaco72** [comment]
without building androidfactory/iosfactory and neccesasry clases from scratch, i think using sdl2 could solve part of problems (only CreateGLContext isn't implemented sdl2factory), but building this is some mess too

**Comment by tangalbert919** [comment]
I have an Android device, so I'm going to help out with this as well.

Perhaps I'll learn a lot about C# and Xamarin and many other things in the process.

**Comment by swoolcock** [comment]
Please follow the discussion in the OpenTK Discord server to keep up to date on the Xamarin situation. 👍
