### ISSUE TITLE
Screen resolution is being modified when minimised

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#729]
reproduction:

1. set screen mode to windowed.
2. minimise
3. restore
4. observe that restored window resolution is completely wrong

also visible in osu HUD overlay when restoring from minimised.

**Comment by VPeruS** [comment]
Still happens? Cannot reproduce with linux/SDL.

**Comment by Poliwrath** [comment]
Might be a Windows 8/10 issue. I'm using Windows 7 and I can't get anything either (with and without aero/dwm)

**Comment by PsYcHo96** [comment]
On Windows 10, can't reproduce.

**Comment by peppy** [comment]
I believe this has been resolved by https://github.com/ppy/osu-framework/pull/1146
