### ISSUE TITLE
Input handling on Linux

### ISSUE THREAD

**Issue by paparony03** [ppy/osu-framework#739]
When window is minimized or hidden under other windows, it still receives input.
I don't know about other distros but I have this issue on Ubuntu 16.04

It seems like IsActive is _true all the time_ and Activated event is continuously being invoked.
https://streamable.com/xwzdq

The osu! logo not showing is another issue.

**Comment by VPeruS** [comment]
Arch linux, awesome-wm 4.0. 
UI elements receive mouse moving events(if another window cover it), but doesn't respont to clicks.
Mouse on logo:
![2017-05-22-173700_1366x768_scrot](https://cloud.githubusercontent.com/assets/7927055/26313828/c08190b4-3f14-11e7-88ba-f92d6b71f741.png)

Mouse not in logo circle:
![2017-05-22-173842_1366x768_scrot](https://cloud.githubusercontent.com/assets/7927055/26313900/fc814cc6-3f14-11e7-9cb6-f46ae03a925b.png)

**Comment by VPeruS** [comment]
If window was maximized and then minimized, it would start receive clicks events.

**Comment by huoyaoyuan** [comment]
It seems an issue of `GameHost.setActive`.

**Comment by VPeruS** [comment]
This changes may solve problem when window isn't focused but still handle mouse clicks.

https://github.com/VPeruS/osu-framework/commit/59766d01e0521c1d054f12ca1148a78e0d60be6e

**Comment by paparony03** [comment]
@VPeruS seems to work really well for me
Make a PR

**Comment by peppy** [comment]
This should be fixed 👍 .
