### ISSUE TITLE
Autopilot issue (or timeline)

### ISSUE THREAD

**Issue by rayriffy** [ppy/osu-framework#744]
I randomly try auto mods and i accidentally found out that i can move timeline for fast forward stuff and then this happen.
https://youtu.be/T2ZLttXqTJg

**Comment by huoyaoyuan** [comment]
It's an timeline issue, I mentioned this in auto too.
Seems the jumped hitobjects are still loaded and expired.

**Comment by peppy** [comment]
this is a work in progress, yes.

also wrong project.
