### ISSUE TITLE
Mouse input is broken on macOS

### ISSUE THREAD

**Issue by lqf96** [ppy/osu-framework#768]
Currently the mouse input is broken on macOS (at least for touchpad).
When moving the cursor into the game window it disappears and doesn't function.
When I maximize the game window and make it occupying the whole screen I can see the mouse cursor on the top left of the window. The game can respond to click events now but the cursor still cannot be moved.

<img width="1280" alt="2017-05-30 11 14 49" src="https://cloud.githubusercontent.com/assets/11476527/26566923/98de013a-4529-11e7-9b90-63c557c2b57d.png">
<img width="1280" alt="2017-05-30 11 14 59" src="https://cloud.githubusercontent.com/assets/11476527/26566932/a4c6d31e-4529-11e7-8274-8d4ec09153bd.png">
<img width="1280" alt="2017-05-30 11 15 09" src="https://cloud.githubusercontent.com/assets/11476527/26566935/a8437a38-4529-11e7-8238-7f7405611aa8.png">

**Comment by peppy** [comment]
Are you on the developer builds of sierra?

**Comment by lqf96** [comment]
No. I'm on macOS 10.12.5

**Comment by peppy** [comment]
So it's safe to say it's broken for touchpads but not for mice.

This is already a known issue. In fact, keyboard input is also broken to some extent due to changes at macOS's end.

**Comment by lqf96** [comment]
So strange... The mouse pointer of latest osu! works on my classmate's Macbook Pro 2016, but not on my Macbook Pro 2015. We both are using Mighty Mouse this time.

**Comment by peppy** [comment]
We've narrowed this down to a 64bit mono bug. Try 32 bit mono or 64bit 5.0.1.1 specifically; both work as expected

**Comment by VPeruS** [comment]
Installing SDL2 lib will resolve this too.

**Comment by VPeruS** [comment]
https://github.com/VPeruS/opentk/commit/8a83dd1016b6456d17c710481468df53be9b90f0

Cannot test in real game. But test window start firing mouse move events.

**Comment by VPeruS** [comment]
I suppose it can be closed #820
