### ISSUE TITLE
Improve performance of image loading

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#77]
![image](https://cloud.githubusercontent.com/assets/191335/18767646/6df6c980-815b-11e6-93b1-3065fdfbc23b.png)

Check whether there are ways that we can improve MagickImage performance or find a leaner alternative.

**Comment by dlemstra** [comment]
I don't know how to read the data of this image. Do you know which part of the loading should be improved? I might be able to help you with that.

**Comment by peppy** [comment]
This is still a valid concern with the MonoGame PNG libraries (which also at some point need to be removed from our codebase).

**Comment by Tom94** [comment]
We switched back to `System.Drawing`, so performance is good again. Still need to fix loading of transparent pixels in libgdiplus for linux (see https://github.com/mono/libgdiplus/pull/43).
