### ISSUE TITLE
Is it possible to "mainline" changes to the OpenTK fork?

### ISSUE THREAD

**Issue by lqf96** [ppy/osu-framework#812]
Currently osu!lazer is maintaining a custom OpenTK fork for bug fixes and some new features. I'm wondering if there is any possibility to contribute our changes to the upstream?

**Comment by peppy** [comment]
Our fork has almost no differences compared to upstream. We do plan on submitting changes as time permits (you're welcome to help with that!)

**Comment by peppy** [comment]
We are now vanilla OpenTK (at least for now).
