### ISSUE TITLE
Seeking to a track's very end does not set its HasCompleted state correctly

### ISSUE THREAD

**Issue by MrTheMake** [ppy/osu-framework#824]
Steps to reproduce:

1. Replace the action of one of the music controller's buttons with `Action = () => current?.Track?.Seek(current.Track.Length),`
2. Press the button. The music controller should now skip to the next track. However, it does not as the track's HasCompleted state is incorrectly false.

**Comment by MrTheMake** [comment]
The error is caused by the seek function itself. `Bass.ChannelSetPosition(activeStream, pos)` (TrackBass, Around line 190) returns `false` when pos is the converted length of the track indicating that an error occurred. The error is `position` and it is mentioned that it occurs when 
> 	The requested position is invalid, eg. beyond the end.

However, I am unsure why this happens. I checked the length via `Bass.ChannelGetLength(activeStream)` and when seeking to a track's end, `pos` is equal to `Bass.ChannelGetLength(activeStream)` thus the position is **not** beyond the end.

**Comment by MrTheMake** [comment]
if `pos` is clamped between `0` and `Bass.ChannelGetLength(activeStream) - 1`, `Bass.ChannelSetPosition(activeStream, pos)` does not throw an exception. However, `currentTime` will then not be `Bass.ChannelGetLength(activeStream) - 1` (converted) but `Bass.ChannelGetLength(activeStream) - 4` and it will stay at this value as its `Bass.ChannelIsActive(activeStream)` value is `stopped`.

**Comment by nyquillerium** [comment]
We recently discovered that bass does not support seeking to the end of the track. Not sure if we should still account for this issue.
