### ISSUE TITLE
RelativeMouseDrag should not be at a framework level

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#897]
If another project wants to implement this non-standard behaviour, they should just rewrite said code in my opinion. @Tom94 has already made it clear he thinks this should exist in the framework, but I still disagree.

I am going to go ahead and remove all usage of it in the framework (currently in very few places) because it is non-standard. Pending further discussion, I believe it should be moved to the osu! project where it is only enabled on a user explicitly enabling it from a disabled default.

**Comment by Tom94** [comment]
Never had a strong opinion; see https://github.com/ppy/osu-framework/pull/857 . I just personally like how scrolling with it feels like.
