### ISSUE TITLE
IsLoaded can become true before LoadComplete

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#913]
If a parent is loaded asynchronously, its children will become `IsLoaded` before they are rooted.

**Comment by peppy** [comment]
is this still a thing?

**Comment by smoogipooo** [comment]
Depends what's rooted means in this context. Afaik we don't have the concept of root as we once had, but previously rooted meant we had a game instance. This will never be the case with async load.
If rooted in this context means that it will have a parent, then no, this isn't possible. In general if no test case is provided and no case of this being an issue is documented then this thread has no use.

**Comment by peppy** [comment]
as in i think we fixed this a few weeks ago, just wanted to confirm :P

**Comment by peppy** [comment]
This is resolved
