### ISSUE TITLE
Make HandleInput automatic; move input events to interfaces

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#952]
- Remove `OnKeyDown` / `OnMouseDown` etc. from `Drawable`
- Move to interfaces `IHandleMouseEvents` `IHandleKeyboardEvents`
- Populate `HandleInput` on construction by doing checks for self implementing these interfaces.

Make sure we only cast to the interfaces on firing events, not when building queues (we can still use `HandleInput` to build the queue).

After this is done, we can likely make `HandleInput` `protected` or `private`.

**Comment by peppy** [comment]
See https://github.com/ppy/osu-framework/issues/952 for relevant discussion.

**Comment by UselessToucan** [comment]
Since you did not close the issue after [this discussion](https://github.com/ppy/osu-framework/pull/1135) the situation is unclear for me.
What do you plan to do with input events?

**Comment by peppy** [comment]
Seems like people have differing opinions this one. For now let's leave it open for discussion until we get a chance to come to a conclusion.

**Comment by smoogipoo** [comment]
Closing this as a majority of people liken usability of using the framework over cleanliness achieved by moving input methods to events. We can look back on the last two PRs and re-use them in the future if needed (they are in working order).
